swagger: "2.0"
info:
  title: MHRSD_AddChamberIbanValidation
  description: This service adds a chamber's iban for validation.
  x-ibm-name: addchamberibanvalidation
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /addchamberibanvalidation:
    parameters:
    - $ref: '#/parameters/X-IBM-Client-Id'
    - $ref: '#/parameters/X-IBM-Client-Secret'
    post:
      tags:
      - Add Gov Iban Validation
      description: AddChamberIbanValidation
      operationId: AddChamberIbanValidation
      parameters:
      - name: request
        in: body
        schema:
          $ref: '#/definitions/RequestModel'
        description: Add Chamber Iban Validation
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
definitions:
  RequestModel:
    type: object
    description: This response object returned by the get operation
    properties:
      consumerReferenceNumber:
        type: string
        example: CA761232-ED42-11CE-BACD-00AA0057B223
      iban:
        type: string
        example: SA7580000204036012139042
      name:
        type: string
        example: Zafart Khann Alih Abbasu
      entityId:
        type: string
        example: "10203040560"
      idType:
        type: string
        example: ID_COCL
      secondaryId:
        type: string
        example: "1045038373"
      secondaryIdType:
        type: string
        example: NID
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      referenceNumber:
        type: string
        example: "1276756"
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  IntegerNumberModel:
    type: object
    description: This object use for integer numbers
    additionalProperties:
      type: integer
      example: 1
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
      Location:
        type: string
        description: Id url encoded
  Response204:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\nvar cfg={\n    \"serviceCode\" : \"AIIV0001\",\n
          \   \"channelId\" : \"Qiwa\",\n    \"requestName\" : \"AddChamberIbanValidationRq\",\n
          \   \"responseName\": \"AddChamberIbanValidationRs\",\n    \"errorMap\"
          :{\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid Request\"}\n
          \   }\n    \n};\n\napim.setvariable('cfg',cfg);\n"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\n\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode,\r\n\t\t\t\"DebugFlag\":
          1            \r\n\r\n        },\r\n        \"Body\" : apim.getvariable('message.body')\r\n
          \           \r\n        \r\n    }\r\n};\r\n\r\nif (typeof OperatorId !==
          'undefined')\r\n    appcReq[cfg.requestName].Header.UserInfo = {\r\n        \"IDNumber\"
          : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        version: 2.0.0
        title: invoke
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: POST
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        target-url: $(ace-tip-mhrsd-post)/external/addchamberibanvalidation
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "\tvar apim = require('apim');\r\n\t\r\n\tapim.output('application/json');\r\n\r\n
          \   \r\n    \r\n    var cfg = apim.getvariable('cfg');\r\n    \r\n\tvar
          TransactionId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.TransactionId\");\r\n\tvar
          ChannelId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ChannelId\");\r\n\tvar
          RequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.RequestTime\");\r\n\tvar
          SessionId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.SessionId\");\r\n\tvar
          MWRequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWRequestTime\");\r\n\tvar
          MWResponseTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWResponseTime\");\r\n\tvar
          status = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ResponseStatus.Status\");\r\n\t\r\n\r\n
          \   apim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\r\n
          \   apim.setvariable('message.headers.Channel-Id',ChannelId,'add');\r\n
          \   if (RequestTime !== 'undefined')\r\n\t    apim.setvariable('message.headers.RequestTime',RequestTime,'add');\r\n\tif
          (SessionId !== 'undefined')\r\n        apim.setvariable('message.headers.X-Request-Id',SessionId,'add');\r\n
          \    if (MWRequestTime !== 'undefined')\r\n        apim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\r\n
          \   if (MWResponseTime !== 'undefined')\r\n        apim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\r\n\r\n
          \   \r\n    apim.setvariable('message.headers.Response-Status',status,'add');"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar body = message[cfg.responseName].Body;\n\n\nsession.output.write(body);\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\r\n\r\nvar message = apim.getvariable('message.body');\r\nvar
                cfg = apim.getvariable('cfg');  \r\n\r\nif (message[cfg.responseName].Header.BackendError)\r\n{\r\nvar
                error = {\r\n  \"errorCode\": message[cfg.responseName].Header.ResponseStatus.Code,\r\n
                \ \"errorMessage\": {\r\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\r\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\r\n
                \ },\r\n  \"BackendError\": {\r\n                \"ErrorCode\": message[cfg.responseName].Header.BackendError.ErrorCode,\r\n
                \               \"ErrorDescription\": message[cfg.responseName].Header.BackendError.ErrorDescription
                ,\r\n                \"HRSD_BackEndError_GUID\": message[cfg.responseName].Header.BackendError.HRSD_BackEndError_GUID\r\n
                \           }\r\n  \r\n};\r\n\r\n}\r\n\r\nelse {\r\n    var error
                = {\r\n  \"errorCode\": message[cfg.responseName].Header.ResponseStatus.Code,\r\n
                \ \"errorMessage\": {\r\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\r\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\r\n
                \ }\r\n  \r\n};\r\n}\r\nvar httperror=0;\r\nif(cfg.errorMap){\r\n
                \   if(cfg.errorMap[error.errorCode]){\r\n       httperror = cfg.errorMap[error.errorCode].code;\r\n
                \      \r\n       //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\r\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\r\n
                \      //apim.error('ERROR',httperror,errmgs,details);\r\n    }\r\n}\r\nif(httperror
                == 0){\r\n   httperror = 409;\r\n   // apim.error('ERROR',400,'Bad
                Request','Invalid request');\r\n}\r\napim.setvariable('message.status.code',httperror,'set');\r\n\r\nsession.output.write(error);\r\napim.output('application/json');"
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
