swagger: "2.0"
info:
  title: AddEstablishmentUserSubscription
  x-ibm-name: addestablishmentusersubscription
  version: 1.0.0
  description: This service is used to add several subscriptions and their users .
schemes:
- https
basePath: /usermanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-usrm-addorterminate)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  AddEstablishmentUserSubscriptionRq_MessageType:
    type: object
    properties:
      AddEstablishmentUserSubscriptionRq:
        $ref: '#/definitions/AddEstablishmentUserSubscriptionRq_Type'
  AddEstablishmentUserSubscriptionRs_MessageType:
    type: object
    properties:
      AddEstablishmentUserSubscriptionRs:
        $ref: '#/definitions/AddEstablishmentUserSubscriptionRs_Type'
  AddEstablishmentUserSubscriptionRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/AddEstablishmentUserSubscriptionRq_BodyType'
  AddEstablishmentUserSubscriptionRq_BodyType:
    type: object
    properties:
      SubscriptionsList:
        $ref: '#/definitions/SubscriptionsList_Type'
      PaymentReference:
        type: string
        default: "123124423"
  SubscriptionsList_Type:
    type: object
    properties:
      SubscriptionItem:
        type: array
        items:
          $ref: '#/definitions/SubscriptionItem_Type'
  SubscriptionItem_Type:
    type: object
    properties:
      SubscriptionId:
        type: string
        default: "0"
      IdNo:
        type: string
        default: "5"
      Duration:
        type: string
        default: "0"
      LaborOfficeId:
        type: string
        default: "0"
      SequenceNumber:
        type: string
        default: "1053655"
      EstablishmentId:
        type: string
        default: "432"
  AddEstablishmentUserSubscriptionRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/AddEstablishmentUserSubscriptionRs_BodyType'
  AddEstablishmentUserSubscriptionRs_BodyType:
    type: object
    properties:
      ErrorsList:
        $ref: '#/definitions/ErrorsList_Type'
  ErrorsList_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: AEUS0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: AEUS0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /addestablishmentusersubscription:
    post:
      operationId: AddEstablishmentUserSubscription
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/AddEstablishmentUserSubscriptionRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Establishment Info
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/AddEstablishmentUserSubscriptionRq_MessageType'
        description: AddEstablishmentUserSubscriptionRq
        required: true
