swagger: "2.0"
info:
  title: AddNewLaborOfficeUser
  x-ibm-name: addnewlaborofficeuser
  version: 1.0.0
  description: AddNewLaborOfficeUser
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-user)/qiwalo/addnewlouser
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  AddNewLaborOfficeUserRq_MessageType:
    type: object
    properties:
      AddNewLaborOfficeUserRq:
        $ref: '#/definitions/AddNewLaborOfficeUserRq_Type'
  AddNewLaborOfficeUserRs_MessageType:
    type: object
    properties:
      AddNewLaborOfficeUserRs:
        $ref: '#/definitions/AddNewLaborOfficeUserRs_Type'
  AddNewLaborOfficeUserRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/AddNewLaborOfficeUserRq_BodyType'
  AddNewLaborOfficeUserRq_BodyType:
    type: object
    properties:
      IdNo:
        type: string
      UserId:
        type: integer
      Name:
        type: string
      Email:
        type: string
      MobileNumber:
        type: string
      UserStatusId:
        type: integer
      UserTypeId:
        type: integer
      IdExpiryDate:
        type: string
      OfficeID:
        type: integer
    required:
    - IdNo
    - UserTypeId
  AddNewLaborOfficeUserRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/AddNewLaborOfficeUserRs_BodyType'
  AddNewLaborOfficeUserRs_BodyType:
    type: object
    properties: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /addnewlouser:
    post:
      operationId: AddNewLaborOfficeUser
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/AddNewLaborOfficeUserRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Add New Labor Office User
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/AddNewLaborOfficeUserRq_MessageType'
        description: AddNewLaborOfficeUserRq
        required: true
