swagger: "2.0"
info:
  title: AddUpdateOccupationGroup
  x-ibm-name: addupdateoccupationgroup
  version: 1.0.0
  description: This service is used to add a new occupation group to the occupation
    matrix or update exist one
schemes:
- https
basePath: /occmng
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-ocpm-occmgmtpost)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  AddUpdateOccupationGroupRq_MessageType:
    type: object
    properties:
      AddUpdateOccupationGroupRq:
        $ref: '#/definitions/AddUpdateOccupationGroupRq_Type'
  AddUpdateOccupationGroupRs_MessageType:
    type: object
    properties:
      AddUpdateOccupationGroupRs:
        $ref: '#/definitions/AddUpdateOccupationGroupRs_Type'
  AddUpdateOccupationGroupRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/AddUpdateOccupationGroupRq_BodyType'
  AddUpdateOccupationGroupRq_BodyType:
    type: object
    properties:
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      OccupationGroupDetails:
        $ref: '#/definitions/OccupationGroupDetails_Type'
      SaudizationPercentage:
        type: integer
        default: "12"
      OccupationsList:
        $ref: '#/definitions/OccupationsList_Type'
      AddUpDelete:
        type: integer
        default: "1"
    required:
    - AddUpDelete
  RequesterDetails_Type:
    type: object
    properties:
      RequesterIdNo:
        type: string
        default: "1"
      RequesterUserId:
        type: integer
        default: "11"
      RequesterName:
        type: string
        default: ee
    required:
    - RequesterIdNo
    - RequesterUserId
    - RequesterName
  OccupationGroupDetails_Type:
    type: object
    properties:
      OccupationGroupId:
        type: integer
        default: "13"
      OccupationGroupNameAr:
        type: string
        default: test2
      OccupationGroupNameEn:
        type: string
        default: test1
    required:
    - OccupationGroupId
  OccupationsList_Type:
    type: object
    properties:
      Occupations:
        type: array
        items:
          $ref: '#/definitions/Occupations_Type'
    required:
    - Occupations
  Occupations_Type:
    type: object
    properties:
      OccupationId:
        type: integer
        default: "1"
    required:
    - OccupationId
  AddUpdateOccupationGroupRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/AddUpdateOccupationGroupRs_BodyType'
  AddUpdateOccupationGroupRs_BodyType: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: AUOG0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: AUOG0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /addupdeoccgroup:
    post:
      operationId: AddUpdateOccupationGroup
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/AddUpdateOccupationGroupRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Validate SC Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/AddUpdateOccupationGroupRq_MessageType'
        description: AddUpdateOccupationGroupRq
        required: true
