swagger: "2.0"
info:
  title: Ajeer_GetEstablishmentQuota
  x-ibm-name: ajeer-getestablishmentquota
  version: 1.0.2
  description: This service is used to get case details through Takamol Internal/External
    Integration.
schemes:
- https
basePath: /ajeer/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - map:
        version: 2.0.0
        title: map
        inputs:
          laborOfficeId:
            schema:
              type: string
            variable: request.parameters.laborOfficeId
          sequenceNumber:
            schema:
              type: string
            variable: request.parameters.sequenceNumber
        outputs:
          "":
            schema:
              description: ""
              type: object
              properties:
                LaborOfficeId:
                  type: string
                  name: LaborOfficeId
                EstablishmentSequence:
                  type: string
                  name: EstablishmentSequence
              example: "{\r\n            \"LaborOfficeId\": \"25\",\r\n            \"EstablishmentSequence\":
                \"1493367\"\r\n           \r\n        }"
            variable: message.body
            content: application/json
        actions:
        - set: .LaborOfficeId
          from: laborOfficeId
        - set: .EstablishmentSequence
          from: sequenceNumber
        options:
          mapEnablePostProcessingJSON: true
          mapEmulateV4EmptyJSONObject: false
          mapEmulateV4DefaultRequiredProps: false
          mapReferenceLimit: 1
          includeEmptyXMLElements: false
          namespaceInheritance: false
          inlineNamespaces: false
          mapResolveApicVariables: false
          mapOptimizeSchemaDefinition: true
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"CCSB0001\",\n
          \   \"channelId\" : \"Ajeer\",\n    \"requestName\" : \"CalculateChangeSponsorBalanceRq\",\n
          \   \"responseName\": \"CalculateChangeSponsorBalanceRs\",\n    \"errorMap\"
          :{\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid Request\"}\n
          \   }\n    \n};\n\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode,\r\n\t\t\t\"DebugFlag\":
          1\r\n\r\n        },\r\n        \"Body\" : apim.getvariable('message.body')\r\n
          \   }\r\n};\r\n\r\nif (typeof OperatorId !== 'undefined')\r\n    appcReq[cfg.requestName].Header.UserInfo
          = {\r\n        \"IDNumber\" : OperatorId\r\n    };\r\napim.setvariable('payload',appcReq);
          \   \r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        version: 2.0.0
        title: MainBE
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        target-url: $(ace-emtf-calcchsp)/changesponsor/calculatechangesponsorbalance
    - gatewayscript:
        version: 2.0.0
        title: PrepareReqForLogging
        source: "var apim=require('apim');\r\nvar appconnectrequest = apim.getvariable('payload');\r\nvar
          APIRes = apim.getvariable('message.body');\r\nvar appname = apim.getvariable('client.app.name');\r\nvar
          UDFPayload = {\r\n                \"KeyValueArr\": [\r\n                    {\r\n
          \                       \"key\": \"Product\",\r\n                        \"value\":
          \"Ajeer\"\r\n                    },\r\n                    {\r\n                        \"key\":
          \"Client\",\r\n                        \"value\": appname\r\n                    }\r\n
          \               ]\r\n            };\t \r\n\r\nappconnectrequest.CalculateChangeSponsorBalanceRq.Header.UDF
          = UDFPayload;\r\nvar jsonData= {\r\n\t\"LogAPIData\": {\r\n\t\t\"CalculateChangeSponsorBalanceRq\":
          appconnectrequest.CalculateChangeSponsorBalanceRq,\r\n\t\t\"CalculateChangeSponsorBalanceRs\":
          APIRes.CalculateChangeSponsorBalanceRs\r\n\t}\r\n}\r\nsession.output.write(jsonData);\r\napim.output('application/json');\r\n"
    - invoke:
        version: 2.3.0
        title: LoggingBE
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        websocket-upgrade: false
        graphql-send-type: detect
        target-url: $(ace-tip-internal)/external/logwrapperapidata
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "var apim = require('apim');\napim.output('application/json');\n \nvar
          message = apim.getvariable('message.body');\nvar cfg = apim.getvariable('cfg');\nvar
          Header = message[cfg.responseName].Header;\nvar TransactionId = Header.TransactionId;\nvar
          ChannelId = Header.ChannelId;\nvar RequestTime = Header.RequestTime;\nvar
          SessionId = Header.SessionId; \nvar MWRequestTime = Header.MWRequestTime;\nvar
          MWResponseTime = Header.MWResponseTime;\nvar status = Header.ResponseStatus.Status;\nvar
          code = Header.ResponseStatus.Code;\napim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\napim.setvariable('message.headers.Channel-Id',ChannelId,'add');\nif
          (RequestTime !== 'undefined')\napim.setvariable('message.headers.RequestTime',RequestTime,'add');\nif
          (SessionId !== 'undefined')\napim.setvariable('message.headers.X-Request-Id',SessionId,'add');\nif
          (MWRequestTime !== 'undefined')\napim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\nif
          (MWResponseTime !== 'undefined')\napim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\n
          \n \napim.setvariable('message.headers.Response-Status',status,'add');\napim.setvariable('message.headers.Response-Code',code,'add');"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Code") = '00000000' or $header("Response-Code")
            = 'E0000067' or $header("Response-Code") = ' E0000066' or $header("Response-Code")
            = 'E0000066'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar body = message[cfg.responseName].Body;\n\n\nsession.output.write(body);\napim.output('application/json');"
          - map:
              inputs:
                "":
                  schema:
                    description: ""
                    type: object
                    properties:
                      Balance:
                        type: object
                        properties:
                          AvailableBalance:
                            type: string
                            name: AvailableBalance
                          BalanceType:
                            type: string
                            name: BalanceType
                        name: Balance
                      EstablishmentConditionsType:
                        type: string
                        name: EstablishmentConditionsType
                      ExpiredEstablishmentId:
                        type: string
                        name: ExpiredEstablishmentId
                      EstablishmentStatusId:
                        type: string
                        name: EstablishmentStatusId
                      CREndDate:
                        type: string
                        name: CREndDate
                      EconomicActivityId:
                        type: string
                        name: EconomicActivityId
                      ColorId:
                        type: string
                        name: ColorId
                      EntityId:
                        type: string
                        name: EntityId
                      EstablishmentId:
                        type: string
                        name: EstablishmentId
                    example: "{\r\n    \"Balance\": {\r\n        \"AvailableBalance\":
                      \"1\",\r\n        \"BalanceType\": \"2\"\r\n    },\r\n    \"EstablishmentConditionsType\":
                      \"2\",\r\n    \"ExpiredEstablishmentId\": \"0\",\r\n    \"EstablishmentStatusId\":
                      \"1\",\r\n    \"CREndDate\": \"2022-01-22\",\r\n    \"EconomicActivityId\":
                      \"38\",\r\n    \"ColorId\": \"310\",\r\n    \"EntityId\": \"25-10743-38\",\r\n
                      \   \"EstablishmentId\": \"3166592\"\r\n}"
                  variable: message.body
                  content: application/json
              outputs:
                "":
                  schema:
                    $ref: '#/definitions/ResponseModel'
                  variable: message.body
                  content: application/json
              actions:
              - set: .quota
                from: .Balance.AvailableBalance
              version: 2.0.0
              title: map
              options:
                mapEnablePostProcessingJSON: true
                mapEmulateV4EmptyJSONObject: false
                mapEmulateV4DefaultRequiredProps: false
                mapReferenceLimit: 1
                includeEmptyXMLElements: false
                namespaceInheritance: false
                inlineNamespaces: false
                mapResolveApicVariables: false
                mapOptimizeSchemaDefinition: true
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar error = {\n  \"errorCode\":
                message[cfg.responseName].Header.ResponseStatus.Code,\n  \"errorMessage\":
                {\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\n
                \ }\n};\n\nvar httperror=0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 400;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);\napim.output('application/json');"
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
  laborOfficeId:
    in: path
    name: laborOfficeId
    description: laborOfficeId
    required: true
    type: string
  sequenceNumber:
    in: path
    name: sequenceNumber
    description: sequenceNumber
    required: true
    type: string
definitions:
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      quota:
        type: integer
        example: 1200
      quotaType:
        $ref: '#/definitions/EstablishmentTypeEnum'
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  EstablishmentTypeEnum:
    type: string
    enum:
    - EXPANSION
    - ESTABLISHING
paths:
  /establishment/laborOffice/{laborOfficeId}/sequence/{sequenceNumber}/quota:
    parameters:
    - $ref: '#/parameters/X-IBM-Client-Id'
    - $ref: '#/parameters/X-IBM-Client-Secret'
    - $ref: '#/parameters/laborOfficeId'
    - $ref: '#/parameters/sequenceNumber'
    - in: header
      name: X-Request-Id
      description: X-Request-Id returned in the response header
      required: false
      type: string
    get:
      tags:
      - Establishment Quota
      description: Service to get Establishment Quota
      operationId: getEstablishmentQuota
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
  Response404:
    description: The server has not found anything matching the Request-URI.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
