swagger: "2.0"
info:
  title: SC ApproveRejectRequest
  x-ibm-name: approverejectscrequest
  version: 1.0.0
  description: This service is used to approve or reject SC request by employer.
schemes:
- https
basePath: /sc
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-salc-salary-certificate)/sc/apprejscreq
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        stop-on-error:
        - ConnectionError
        - SOAPError
        - OperationError
    - gatewayscript:
        version: 2.0.0
        title: Set Headers
        source: "var apim = require('apim');\r\nvar Response = apim.getvariable('message.body');\r\nvar
          statusCode = Response.ApproveRejectSCRequestRs.Header.ResponseStatus.Code
          ;\r\n\r\n\r\nif(statusCode == 'ESBSCHEMA' || statusCode == 'E0000004'){\r\n
          \   var code = 400\r\n    apim.setvariable('message.status.code',code,'set');\r\n}\r\nelse
          if(statusCode == '99999999'){\r\n    var code = 500\r\n    apim.setvariable('message.status.code',code,'set');\r\n}\r\nelse
          if(statusCode == 'E0000046'|| statusCode == 'E0000034' || statusCode ==
          'E0000047'|| statusCode == 'E0000048'|| statusCode == 'E0000200'|| statusCode
          == 'E0000486'){\r\n    var code = 401\r\n    apim.setvariable('message.status.code',code,'set');\r\n}\r\nelse
          if(statusCode == '00000000'){\r\n    var code = 200\r\n    apim.setvariable('message.status.code',code,'set');\r\n}else{\r\n
          \     var code = 409\r\n    apim.setvariable('message.status.code',code,'set');\r\n}"
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "500"
            type: string
          - set: message.headers.content-type
            value: application/json
            type: string
          - set: message.body
            value: '{"errorCode": "E00500", "errorMessage": "Internal Server Error"}'
            type: string
    finally: []
  properties:
    target-url:
      value: http://salc-salary-certificate-http-ace.apps.stg.qiwa-nonprod.local/sc/apprejscreq
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  catalogs: {}
  buffering: true
definitions:
  ApproveRejectSCRequestRq_MessageType:
    type: object
    properties:
      ApproveRejectSCRequestRq:
        $ref: '#/definitions/ApproveRejectSCRequestRq_Type'
  ApproveRejectSCRequestRs_MessageType:
    type: object
    properties:
      ApproveRejectSCRequestRs:
        $ref: '#/definitions/ApproveRejectSCRequestRs_Type'
  ApproveRejectSCRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ApproveRejectSCRequestRq_BodyType'
  ApproveRejectSCRequestRq_BodyType:
    type: object
    properties:
      RequestId:
        type: string
        default: "654"
      IsApproved:
        type: integer
        default: "7657"
      RejectionReason:
        type: string
        default: Invalid
    required:
    - RequestId
    - IsApproved
  ApproveRejectSCRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ApproveRejectSCRequestRs_BodyType'
  ApproveRejectSCRequestRs_BodyType:
    type: object
    properties: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: ARSCR001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: ARSCR001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /apprejscreq:
    post:
      operationId: ApproveRejectSCRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ApproveRejectSCRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Approve Reject SC Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ApproveRejectSCRequestRq_MessageType'
        description: ApproveRejectSCRequestRq
        required: true
