swagger: "2.0"
info:
  title: Async Data History
  x-ibm-name: async-data-history
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
produces: []
consumes: []
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
  clientSecret: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - operation-switch:
        version: 2.0.0
        title: operation-switch
        case:
        - operations:
          - verb: post
            path: /gethistorydata
          execute:
          - invoke:
              version: 2.3.0
              title: invoke
              backend-type: detect
              header-control:
                type: blocklist
                values: []
              parameter-control:
                type: allowlist
                values: []
              http-version: HTTP/1.1
              timeout: 60
              verb: keep
              chunked-uploads: true
              persistent-connection: true
              cache-response: protocol
              cache-ttl: 900
              websocket-upgrade: false
              graphql-send-type: detect
              target-url: $(ace-rept-history-async)/gethistorydata
        - operations:
          - verb: post
            path: /gethistorydata/UpdateSoftDeleteHistory
          execute:
          - invoke:
              version: 2.3.0
              title: invoke
              backend-type: detect
              header-control:
                type: blocklist
                values: []
              parameter-control:
                type: allowlist
                values: []
              http-version: HTTP/1.1
              timeout: 60
              verb: keep
              chunked-uploads: true
              persistent-connection: true
              cache-response: protocol
              cache-ttl: 900
              websocket-upgrade: false
              graphql-send-type: detect
              target-url: $(ace-rept-history-async)/gethistorydata/UpdateSoftDeleteHistory
        otherwise: []
    catch: []
    finally: []
  properties: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  application-authentication:
    certificate: false
  catalogs: {}
  buffering: true
paths:
  /gethistorydata:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
  /gethistorydata/UpdateSoftDeleteHistory:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
