swagger: "2.0"
info:
  title: Qiwa_SC_CancelRequest
  x-ibm-name: cancelscrequest
  version: 1.0.1
  description: This service is used to cancel the SC request by the laborer before
    the current employer being approved or rejected.
schemes:
- https
basePath: /sc
security:
- ClientSecret: []
  OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  ClientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientIdHeader:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://gw-apic.qiwa.info/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: $(ace-salc-salary-certificate)/sc/cancelscreq
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        stop-on-error:
        - OperationError
        - SOAPError
        - ConnectionError
    - gatewayscript:
        version: 2.0.0
        title: Set Headers
        source: "var apim = require('apim');\r\nvar Response = apim.getvariable('message.body');\r\nvar
          statusCode = Response.CancelSCRequestRs.Header.ResponseStatus.Code ;\r\n\r\n\r\nif(statusCode
          == 'ESBSCHEMA' || statusCode == 'E0000059' || statusCode == 'E0000119'){\r\n
          \   var code = 400\r\n    apim.setvariable('message.status.code',code,'set');\r\n}\r\nelse
          if(statusCode == '99999999'){\r\n    var code = 500\r\n    apim.setvariable('message.status.code',code,'set');\r\n}\r\nelse
          if(statusCode == 'E9999998'){\r\n    var code = 408\r\n    apim.setvariable('message.status.code',code,'set');\r\n}\r\nelse
          if(statusCode == '00000000'){\r\n    var code = 200\r\n    apim.setvariable('message.status.code',code,'set');\r\n}else{\r\n
          \     var code = 409\r\n    apim.setvariable('message.status.code',code,'set');\r\n}\r\n"
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "500"
            type: string
          - set: message.headers.content-type
            value: application/json
            type: string
          - set: message.body
            value: '{"errorCode": "E00500", "errorMessage": "Internal Server Error"}'
            type: string
    finally: []
  properties:
    target-url:
      value: $(ace-salc-salary-certificate)/sc/cancelscreq
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  application-authentication:
    certificate: false
  catalogs: {}
  buffering: true
definitions:
  CancelSCRequestRq_MessageType:
    type: object
    properties:
      CancelSCRequestRq:
        $ref: '#/definitions/CancelSCRequestRq_Type'
  CancelSCRequestRs_MessageType:
    type: object
    properties:
      CancelSCRequestRs:
        $ref: '#/definitions/CancelSCRequestRs_Type'
  CancelSCRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CancelSCRequestRq_BodyType'
  CancelSCRequestRq_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
        default: "23423"
    required:
    - RequestId
  CancelSCRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CancelSCRequestRs_BodyType'
  CancelSCRequestRs_BodyType: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CSCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CSCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /cancelscreq:
    post:
      operationId: CancelSCRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CancelSCRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Cancel SC Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CancelSCRequestRq_MessageType'
        description: CancelSCRequestRq
        required: true
