swagger: "2.0"
info:
  title: CancelRunawayStatusForEmployee
  version: 1.0.0
  description: cancelRunawayStatusForEmployee
  x-ibm-name: cancelrunawaystatusforemployee
paths:
  /CancelRunawayStatusForEmployee:
    post:
      operationId: CancelRunawayStatusForEmployee
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CancelAbsentRunawayStatusRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Cancel Absent Runaway Status
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CancelAbsentRunawayStatusRq_MessageType'
        description: CancelAbsentRunawayStatusRq
        required: true
basePath: /qiwa/v2
definitions:
  CancelAbsentRunawayStatusRq_MessageType:
    type: object
    properties:
      CancelAbsentRunawayStatusRq:
        $ref: '#/definitions/CancelAbsentRunawayStatusRq_Type'
  CancelAbsentRunawayStatusRs_MessageType:
    type: object
    properties:
      CancelAbsentRunawayStatusRs:
        $ref: '#/definitions/CancelAbsentRunawayStatusRs_Type'
  CancelAbsentRunawayStatusRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CancelAbsentRunawayStatusRq_BodyType'
  CancelAbsentRunawayStatusRq_BodyType:
    type: object
    properties:
      laborOfficeId:
        type: integer
      sequenceNumber:
        type: integer
      laborerId:
        type: string
      reason:
        type: string
      requestId:
        type: integer
      cancelledBy:
        type: string
    required:
    - laborOfficeId
    - sequenceNumber
    - laborerId
    - reason
    - requestId
    - cancelledBy
  CancelAbsentRunawayStatusRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CancelAbsentRunawayStatusRs_BodyType'
  CancelAbsentRunawayStatusRs_BodyType:
    type: object
    properties:
      responseMessage:
        type: string
      responseMessageAr:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  cors:
    enabled: true
  properties:
    target-url:
      value: http://example.com
      description: The URL of the target service
      encoded: false
  phase: realized
  enforced: true
  gateway: datapower-api-gateway
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-ctfl-absentservices)/cancelabsentrunawaystatus
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: response
        source: |
          var apim = require('apim');


          apim.output('application/json');

          var cfg = {
              "responseName": "CancelAbsentRunawayStatusRs"
          };

          var status = apim.getvariable("message.body."+cfg.responseName+".Header.ResponseStatus.Status");

          apim.setvariable('message.headers.Response-Status',status,'add');
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: ($header("Response-Status") = 'Error' or $header("Response-Status")
            = 'ERROR')
          execute:
          - gatewayscript:
              version: 2.0.0
              title: error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\n\nvar
                cfg={\n    \"responseName\": \"CancelAbsentRunawayStatusRs\",\n    \"errorMap\"
                :{\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid Request\"},\n
                \       \"E0001472\"  : {\"code\" :409, \"msg\":\"Cancellation Not
                allowed for this laborer\t\"},\n        \"E0001474\"  : {\"code\"
                :409, \"msg\":\"NIC failure\"},\n        \"E0001478\"  : {\"code\"
                :400, \"msg\":\"Laborer ID is mandatory, please enter a valid one.\"},\n
                \       \"E0001484\"  : {\"code\" :400, \"msg\":\"Reason is mandatory,
                please share the reason for cancellation\"},\n        \"E0000024\"
                \ : {\"code\" :409, \"msg\":\"No Data Found\"},\n        \"NIC00253\"
                \ : {\"code\" :409, \"msg\":\"Unexpected exception\"},\n        \"E0001490\"
                \ : {\"code\" :400, \"msg\":\"CancelledBy is mandatory, please enter
                a valid one.\"},\n        \"E0001499\"  : {\"code\" :400, \"msg\":\"Request
                ID is mandatory, please enter a valid one\"},\n        \"E0001500\"
                \ : {\"code\" :400, \"msg\":\"Labor Office ID is mandatory, please
                enter a valid one\"},\n        \"E0001501\"  : {\"code\" :400, \"msg\":\"Sequence
                Number is mandatory, please enter a valid one\"},\n        \"REST:Gateway\"
                \ : {\"code\" :500, \"msg\":\"internal server\"}\n\n    }\n    \n};\n\nvar
                error = {\n  \"errorCode\": message[cfg.responseName].Header.ResponseStatus.Code\n};\n\n\nvar
                httperror = 0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \   }\n}\n\nif (httperror == 0){\n    httperror = 400;\n}\n\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(message);\napim.output('application/json');\n\n\n\n"
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute: []
    finally: []
  type: rest
  testable: true
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
host: $(catalog.host)
schemes:
- https
