swagger: "2.0"
info:
  title: CheckETReqStatus
  x-ibm-name: checketreqstatus
  version: 1.0.0
  description: This service is used to check Employee Transfer Status.
schemes:
- https
basePath: /changesponsor
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-emtf-etchecks)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |
          var apim = require('apim');
          var Response = apim.getvariable('message.body');
          var statusCode = Response.CheckETReqStatusRs.Header.ResponseStatus.Code ;


          if(statusCode == 'E9999998'){
              var code = 408
              apim.setvariable('message.status.code',code,'set');
          }
          else if(statusCode == '00000000'){
              var code = 200
              apim.setvariable('message.status.code',code,'set');
          }else{
                var code = 409
              apim.setvariable('message.status.code',code,'set');
          }
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CheckETReqStatusRq_MessageType:
    type: object
    properties:
      CheckETReqStatusRq:
        $ref: '#/definitions/CheckETReqStatusRq_Type'
  CheckETReqStatusRs_MessageType:
    type: object
    properties:
      CheckETReqStatusRs:
        $ref: '#/definitions/CheckETReqStatusRs_Type'
  CheckETReqStatusRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckETReqStatusRq_BodyType'
  CheckETReqStatusRq_BodyType:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
        default: "8"
      DestinationSequenceNumber:
        type: integer
        default: "254"
      LaborerIdNo:
        type: integer
        default: "76574"
    required:
    - DestinationLaborOfficeId
    - DestinationSequenceNumber
    - LaborerIdNo
  CheckETReqStatusRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckETReqStatusRs_BodyType'
  CheckETReqStatusRs_BodyType:
    type: object
    properties:
      ETRequestStatus:
        $ref: '#/definitions/CodeName_Type'
      ReasonsList:
        $ref: '#/definitions/ReasonsList_Type'
      Details:
        $ref: '#/definitions/Details_Type'
    required:
    - ETRequestStatus
    - ReasonsList
    - Details
  ReasonsList_Type:
    type: object
    properties:
      Reasons:
        type: array
        items:
          $ref: '#/definitions/Reasons_Type'
    required:
    - Reasons
  Reasons_Type:
    type: object
    properties:
      ReasonId:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - ReasonId
    - ArDescription
    - EnDescription
  Details_Type:
    type: object
    properties:
      WPExpired:
        type: integer
      IqamaExpired:
        type: integer
      HasAmicableSettlementCase:
        type: integer
      HasMaliciousReport:
        type: integer
      EntryDate90DaysWithNoWP:
        type: integer
      HasFinalExitVisaWithStatus1:
        type: integer
      EntryDateLess1Year:
        type: integer
      HasActivePolicy:
        type: integer
      ContractAuthentication100:
        type: integer
      IMS80:
        type: integer
    required:
    - WPExpired
    - IqamaExpired
    - HasAmicableSettlementCase
    - HasMaliciousReport
    - EntryDate90DaysWithNoWP
    - HasFinalExitVisaWithStatus1
    - EntryDateLess1Year
    - HasActivePolicy
    - ContractAuthentication100
    - IMS80
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CETRS001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CETRS001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "543"
      IDNumber:
        type: integer
        default: "2345"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /checketreqstatus:
    post:
      operationId: CheckETReqStatus
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckETReqStatusRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search the employee transfer requests for establishment depending
        on several data
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckETReqStatusRq_MessageType'
        description: CheckETReqStatusRq
        required: true
