swagger: "2.0"
info:
  title: CheckMedicalLicenseValiditySCFHS
  x-ibm-name: checkmedicallicensevalidityscfhs
  version: 1.0.0
  description: This service is used to check the validity of medical licenses in SCFHS.
schemes:
- https
basePath: /scfhs
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-ei-externals)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  CheckMedicalLicenseValidityRq_MessageType:
    type: object
    properties:
      CheckMedicalLicenseValidityRq:
        $ref: '#/definitions/CheckMedicalLicenseValidityRq_Type'
  CheckMedicalLicenseValidityRs_MessageType:
    type: object
    properties:
      CheckMedicalLicenseValidityRs:
        $ref: '#/definitions/CheckMedicalLicenseValidityRs_Type'
  CheckMedicalLicenseValidityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckMedicalLicenseValidityRq_BodyType'
  CheckMedicalLicenseValidityRq_BodyType:
    type: object
    properties:
      LaborerIdNo:
        type: string
        default: "1257475"
    required:
    - LaborerIdNo
  CheckMedicalLicenseValidityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckMedicalLicenseValidityRs_BodyType'
  CheckMedicalLicenseValidityRs_BodyType:
    type: object
    properties:
      RegistrationNumber:
        type: string
      Name:
        $ref: '#/definitions/Name_Type'
      Gender:
        $ref: '#/definitions/CodeName_Type'
      Category:
        $ref: '#/definitions/CodeName_Type'
      Specialty:
        $ref: '#/definitions/CodeName_Type'
      Constraint:
        $ref: '#/definitions/CodeName_Type'
      PractitionerStatus:
        $ref: '#/definitions/CodeDesc_Type'
      Reason:
        $ref: '#/definitions/CodeDesc_Type'
      IssuedDate:
        type: string
      ExpiryDate:
        type: string
      LicenseValidityStatus:
        $ref: '#/definitions/CodeDesc_Type'
      Transaction:
        $ref: '#/definitions/Transaction_Type'
      Error:
        $ref: '#/definitions/Error_Type'
      ExecutedOn:
        type: string
      Message:
        $ref: '#/definitions/CodeDesc_Type'
    required:
    - RegistrationNumber
    - IssuedDate
    - ExpiryDate
    - ExecutedOn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SCMLV001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SCMLV001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  Name_Type:
    type: object
    properties:
      FirstName:
        type: string
      SecondName:
        type: string
      LastName:
        type: string
      FirstNameT:
        type: string
      SecondNameT:
        type: string
      LastNameT:
        type: string
    required:
    - FirstName
    - SecondName
    - LastName
    - FirstNameT
    - SecondNameT
    - LastNameT
  CodeName_Type:
    type: object
    properties:
      Code:
        type: string
      DescAr:
        type: string
      DescEn:
        type: string
    required:
    - Code
    - DescAr
    - DescEn
  CodeDesc_Type:
    type: object
    properties:
      Code:
        type: string
      DescAr:
        type: string
      DescEn:
        type: string
    required:
    - Code
    - DescAr
    - DescEn
  Transaction_Type:
    type: object
    properties:
      StatusCode:
        type: string
      StatusDescEn:
        type: string
    required:
    - StatusCode
    - StatusDescEn
  Error_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorText:
        type: string
      ErrorType:
        type: string
    required:
    - ErrorCode
    - ErrorText
    - ErrorType
paths:
  /chkmedicallicval:
    post:
      operationId: CheckMedicalLicenseValiditySCFHS
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckMedicalLicenseValidityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Check Medical License Validity SCFHS
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckMedicalLicenseValidityRq_MessageType'
        description: CheckMedicalLicenseValidityRq
        required: true
