swagger: "2.0"
info:
  title: CheckEstablishmentUnifiedOwnerAge
  version: 1.0.0
  description: CheckEstablishmentUnifiedOwnerAge
  x-ibm-name: checkestablishmentunifiedownerage
paths:
  /checkestunifiedownerage:
    post:
      operationId: CheckEstablishmentUnifiedOwnerAge
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckEstablishmentUnifiedOwnerAgeRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Calculate Establishment Quota
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckEstablishmentUnifiedOwnerAgeRq_MessageType'
        description: CheckEstablishmentUnifiedOwnerAgeRq
        required: true
basePath: /qiwa/common
definitions:
  CheckEstablishmentUnifiedOwnerAgeRq_MessageType:
    type: object
    properties:
      CheckEstablishmentUnifiedOwnerAgeRq:
        $ref: '#/definitions/CheckEstablishmentUnifiedOwnerAgeRq_Type'
  CheckEstablishmentUnifiedOwnerAgeRs_MessageType:
    type: object
    properties:
      CheckEstablishmentUnifiedOwnerAgeRs:
        $ref: '#/definitions/CheckEstablishmentUnifiedOwnerAgeRs_Type'
  CheckEstablishmentUnifiedOwnerAgeRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckEstablishmentUnifiedOwnerAgeRq_BodyType'
  CheckEstablishmentUnifiedOwnerAgeRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      SubEconomicActivityId:
        type: integer
      EstablishmentTypeId:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
  CheckEstablishmentUnifiedOwnerAgeRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckEstablishmentUnifiedOwnerAgeRs_BodyType'
  CheckEstablishmentUnifiedOwnerAgeRs_BodyType:
    type: object
    properties: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-utl-commonapps3)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
