swagger: "2.0"
info:
  title: CheckNatGenOccEligibility
  x-ibm-name: checknatgenocceligibility
  version: 1.0.0
  description: This service is used to check the eligibility of the nationalities
    ,gender and occupations
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-utl-commonapps)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CheckNatGenOccEligibilityRq_MessageType:
    type: object
    properties:
      CheckNatGenOccEligibilityRq:
        $ref: '#/definitions/CheckNatGenOccEligibilityRq_Type'
  CheckNatGenOccEligibilityRs_MessageType:
    type: object
    properties:
      CheckNatGenOccEligibilityRs:
        $ref: '#/definitions/CheckNatGenOccEligibilityRs_Type'
  CheckNatGenOccEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckNatGenOccEligibilityRq_BodyType'
  CheckNatGenOccEligibilityRq_BodyType:
    type: object
    properties:
      ServiceCode:
        type: string
        default: QS0000001
      Nationalities:
        $ref: '#/definitions/Nationalities_Type'
      Occupations:
        $ref: '#/definitions/Occupations_Type'
      Origins:
        $ref: '#/definitions/Origins_Type'
      Gender:
        $ref: '#/definitions/Gender_Type'
      EconomicActivityId:
        type: integer
        default: "23"
    required:
    - ServiceCode
  Nationalities_Type:
    type: object
    properties:
      NationalityId:
        type: array
        items:
          type: integer
          default: "2"
  Occupations_Type:
    type: object
    properties:
      OccupationId:
        type: array
        items:
          type: integer
          default: "12"
  Origins_Type:
    type: object
    properties:
      OriginId:
        type: array
        items:
          type: integer
          default: "16"
  Gender_Type:
    type: object
    properties:
      GenderId:
        type: array
        items:
          type: integer
          default: "2"
  CheckNatGenOccEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckNatGenOccEligibilityRs_BodyType'
  CheckNatGenOccEligibilityRs_BodyType:
    type: object
    properties:
      ErrorsList:
        $ref: '#/definitions/ErrorsList_Type'
  ErrorsList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: integer
      EnDescription:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CNGOE001
      DebugFlag:
        type: integer
        default: "1"
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CNGOE001
      DebugFlag:
        type: integer
        default: "1"
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
paths:
  /checknatgenocceligibility:
    post:
      operationId: CheckNatGenOccEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckNatGenOccEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Entity Information
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckNatGenOccEligibilityRq_MessageType'
        description: CheckNatGenOccEligibilityRq
        required: true
