swagger: "2.0"
info:
  title: CheckChangeOccupationEligibility
  x-ibm-name: checkchangeoccupationeligibility
  version: 1.0.0
  description: This service is used to check the eligibility of establishment requesting
    occupation change.
schemes:
- https
basePath: /chgoccupation
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-chgo-choccvalidates)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CheckChangeOccupationEligibilityRq_MessageType:
    type: object
    properties:
      CheckChangeOccupationEligibilityRq:
        $ref: '#/definitions/CheckChangeOccupationEligibilityRq_Type'
  CheckChangeOccupationEligibilityRs_MessageType:
    type: object
    properties:
      CheckChangeOccupationEligibilityRs:
        $ref: '#/definitions/CheckChangeOccupationEligibilityRs_Type'
  CheckChangeOccupationEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckChangeOccupationEligibilityRq_BodyType'
  CheckChangeOccupationEligibilityRq_BodyType:
    type: object
    properties:
      HasExpiredWP:
        type: boolean
        default: "True"
      EntityNotes:
        $ref: '#/definitions/EntityNotes_Type'
      ColorId:
        type: integer
        default: "1"
      CREndDate:
        type: string
        default: "2020-10-12"
      EstablishmentStatusId:
        type: integer
        default: "23"
    required:
    - HasExpiredWP
    - EntityNotes
    - ColorId
    - CREndDate
    - EstablishmentStatusId
  EntityNotes_Type:
    type: object
    properties:
      EntityNote:
        type: array
        items:
          $ref: '#/definitions/EntityNote_Type'
  EntityNote_Type:
    type: object
    properties:
      NoteSourceId:
        type: integer
        default: "15"
  CheckChangeOccupationEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckChangeOccupationEligibilityRs_BodyType'
  CheckChangeOccupationEligibilityRs_BodyType:
    type: object
    properties:
      'ErrorsList ':
        $ref: '#/definitions/ErrorList_Type'
  ErrorList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: integer
      ArDescription:
        type: string
      EngDescription:
        type: string
    required:
    - ErrorCode
    - ArDescription
    - EngDescription
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CCOE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CCOE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /checkchangeoccupationeligibility:
    post:
      operationId: CheckChangeOccupationEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckChangeOccupationEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Check Change Occupation Eligibility
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckChangeOccupationEligibilityRq_MessageType'
        description: CheckChangeOccupationEligibilityRq
        required: true
