swagger: "2.0"
info:
  title: CreateNewContract V2
  x-ibm-name: createnewcontract-v2
  version: 1.0.0
  description: 'This service is used to create a contract with its details. '
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-contractcreates)/contractmanagement/createnewcontract
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CreateNewContractRq_MessageType:
    type: object
    properties:
      CreateNewContractRq:
        $ref: '#/definitions/CreateNewContractRq_Type'
  CreateNewContractRs_MessageType:
    type: object
    properties:
      CreateNewContractRs:
        $ref: '#/definitions/CreateNewContractRs_Type'
  CreateNewContractRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CreateNewContractRq_BodyType'
  CreateNewContractRq_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/Establishment_Type'
      RequesterDetails:
        $ref: '#/definitions/Requester_Type'
      LaborerDetails:
        $ref: '#/definitions/Laborer_Type'
      ContractDetails:
        $ref: '#/definitions/Contract_Type'
      RelatedToId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
    required:
    - EstablishmentDetails
    - RequesterDetails
    - LaborerDetails
    - ContractDetails
    - RelatedToId
  Establishment_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      NationalAddress:
        type: string
      EstablishmentEmail:
        type: string
      PhoneNumber:
        type: string
      MobileNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - NationalAddress
    - EstablishmentEmail
    - PhoneNumber
    - MobileNumber
  Requester_Type:
    type: object
    properties:
      RequesterName:
        type: string
      RequesterIdNo:
        type: integer
      RequesterType:
        type: integer
        enum:
        - 1
        - 2
        - 3
      RequesterRoleEn:
        type: string
      RequesterRoleAr:
        type: string
    required:
    - RequesterName
    - RequesterIdNo
    - RequesterType
    - RequesterRoleEn
    - RequesterRoleAr
  Laborer_Type:
    type: object
    properties:
      LaborerTypeId:
        type: integer
        enum:
        - 1
        - 2
      LaborerIdNo:
        type: integer
      BorderNumber:
        type: integer
      PassportNumber:
        type: string
      LaborerName:
        type: string
      NationalAddress:
        type: string
      LaborerEmail:
        type: string
      LaborerMobileNumber:
        type: string
        pattern: ^05\d{8}$
      LaborerDOB:
        $ref: '#/definitions/HGDate_Type'
      DOBType:
        type: integer
        enum:
        - 1
        - 2
      Nationality:
        type: integer
      Gender:
        type: integer
        enum:
        - 1
        - 2
      Religion:
        type: integer
      MaritalStatus:
        type: integer
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      EducationId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      SpecialtyId:
        type: integer
      WorkLocationId:
        type: integer
      IBAN:
        type: string
        pattern: ^SA\d{22}$
    required:
    - LaborerTypeId
    - LaborerIdNo
    - LaborerName
    - NationalAddress
    - LaborerEmail
    - LaborerMobileNumber
    - LaborerDOB
    - DOBType
    - Nationality
    - Gender
    - Religion
    - MaritalStatus
    - EducationId
    - SpecialtyId
    - WorkLocationId
    - IBAN
  HGDate_Type:
    type: object
    properties:
      HijriDate:
        type: integer
        format: int64
        example: 14451201
      GregDate:
        type: string
        format: date-time
  Contract_Type:
    type: object
    properties:
      ContractTemplateId:
        type: integer
      OccupationId:
        type: integer
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      ContractTypeId:
        type: integer
        enum:
        - 1
        - 2
        description: 1- Full time, 2- Part time
      ExecutionLocation:
        type: integer
      ContractDurationId:
        type: integer
        enum:
        - 1
        - 2
        description: 1- Fixed-term Contract, 2- Open-ended
      ContractPeriod:
        type: integer
      CurrentStartDate:
        type: string
        format: date-time
      CurrentExpiryDate:
        type: string
        format: date-time
      WorkingHoursTypeId:
        type: integer
        enum:
        - 1
        - 2
        description: 1- Weekly Hours, 2- Daily Hours
      DaysPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      HoursPerWeek:
        type: integer
      RestingDays:
        type: integer
      Salary:
        type: number
        format: decimal
      SalaryDueDay:
        type: integer
      ProbationPeriod:
        type: integer
      VacationPeriod:
        type: integer
      NoticePeriod:
        type: integer
      RenewalStatusId:
        type: integer
        enum:
        - 2
        - 3
        - 4
        - 5
        description: 2- Auto Termination, 3- One time with same period, 4- One time
          with different period, 5- Multiple times with same period
      RenewalTimes:
        type: integer
      RenewalPeriod:
        type: integer
      CategoryId:
        type: integer
      IsUploadFilesSkiped:
        type: integer
      UploadedFiles:
        $ref: '#/definitions/UploadedFiles_Type'
      Allowances:
        $ref: '#/definitions/Allowances_Type'
      InKindBenefits:
        $ref: '#/definitions/InKindBenefits_Type'
      Commission:
        $ref: '#/definitions/Commission_Type'
      OptionalClauses:
        $ref: '#/definitions/OptionalClauses_Type'
      Terms:
        $ref: '#/definitions/Terms_Type'
      AdditionalTerms:
        $ref: '#/definitions/AdditionalTerms_Type'
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
  UploadedFiles_Type:
    type: object
    properties:
      UploadedFilesItem:
        type: array
        items:
          $ref: '#/definitions/UploadedFilesItem_Type'
  UploadedFilesItem_Type:
    type: object
    properties:
      FileId:
        type: string
      FileTypeId:
        type: integer
  Allowances_Type:
    type: object
    properties:
      AllowancesItem:
        type: array
        items:
          $ref: '#/definitions/AllowancesItem_Type'
  AllowancesItem_Type:
    type: object
    properties:
      AllowanceType:
        type: integer
        enum:
        - 1
        - 2
        - 3
        description: 1- Housing, 2- Transportation, 3- Other
      NameAr:
        type: string
      NameEn:
        type: string
      Amount:
        type: number
        format: decimal
  InKindBenefits_Type:
    type: object
    properties:
      InKindBenefitsItem:
        type: array
        items:
          $ref: '#/definitions/InKindBenefitsItem_Type'
  InKindBenefitsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
      DescriptionEn:
        type: string
      DescriptionAr:
        type: string
      Frequency:
        type: integer
        enum:
        - 1
        - 2
        description: 1- Monthly, 2- Annually
      DueDate:
        type: string
        format: date-time
  Commission_Type:
    type: object
    properties:
      CommissionItem:
        type: array
        items:
          $ref: '#/definitions/CommissionItem_Type'
  CommissionItem_Type:
    type: object
    properties:
      CommissionBaseEn:
        type: string
      CommissionBaseAr:
        type: string
      Percentage:
        type: integer
      Frequency:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        description: 1- Monthly, 2- Weekly, 3- Quarterly, 4- Annually
  OptionalClauses_Type:
    type: object
    properties:
      OptionalClausesItem:
        type: array
        items:
          $ref: '#/definitions/OptionalClausesItem_Type'
  OptionalClausesItem_Type:
    type: object
    properties:
      OptionalClausesType:
        type: integer
        enum:
        - 1
        - 2
        - 3
        description: 1- Non Compete Agreement, 2- On Disclosure Clause, 3- Compensation
          Amount
      Period:
        type: integer
      Field:
        type: string
      Location:
        type: string
      FirstParty:
        type: string
      SecondParty:
        type: string
  Terms_Type:
    type: object
    properties:
      TermsItem:
        type: array
        items:
          $ref: '#/definitions/TermsItem_Type'
  TermsItem_Type:
    type: object
    properties:
      TermId:
        type: integer
  AdditionalTerms_Type:
    type: object
    properties:
      AdditionalTermsItem:
        type: array
        items:
          $ref: '#/definitions/AdditionalTermsItem_Type'
  AdditionalTermsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
  CreateNewContractRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CreateNewContractRs_BodyType'
  CreateNewContractRs_BodyType:
    type: object
    properties:
      ContractId:
        type: integer
      Status:
        $ref: '#/definitions/CodeName_Type'
    required:
    - ContractId
    - Status
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /createnewcontract:
    post:
      operationId: CreateNewContract
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CreateNewContractRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Create New Contract
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CreateNewContractRq_MessageType'
        description: CreateNewContractRq
        required: true
