swagger: "2.0"
info:
  title: CreateTrnCntr
  version: 1.0.0
  description: CreateTrnCntr
  x-ibm-name: createtrncntr
paths:
  /createtrncntr:
    post:
      operationId: CreateTrnCntr
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CreateTrnCntrRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Create Training Contract
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CreateTrnCntrRq_MessageType'
        description: CreateTrnCntrRq
        required: true
basePath: /trncntr
definitions:
  CreateTrnCntrRq_MessageType:
    type: object
    properties:
      CreateTrnCntrRq:
        $ref: '#/definitions/CreateTrnCntrRq_Type'
  CreateTrnCntrRs_MessageType:
    type: object
    properties:
      CreateTrnCntrRs:
        $ref: '#/definitions/CreateTrnCntrRs_Type'
  CreateTrnCntrRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CreateTrnCntrRq_BodyType'
  CreateTrnCntrRq_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/Establishment_Type'
      RequesterDetails:
        $ref: '#/definitions/Requester_Type'
      TraineeDetails:
        $ref: '#/definitions/Trainee_Type'
      ContractDetails:
        $ref: '#/definitions/Contract_Type'
    required:
    - EstablishmentDetails
    - RequesterDetails
    - TraineeDetails
    - ContractDetails
  Establishment_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      NationalAddress:
        type: string
      EstablishmentEmail:
        type: string
      PhoneNumber:
        type: string
      MobileNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - NationalAddress
    - EstablishmentEmail
    - PhoneNumber
    - MobileNumber
  Requester_Type:
    type: object
    properties:
      RequesterName:
        type: string
      RequesterIdNo:
        type: integer
      RequesterType:
        type: integer
      RequesterRoleEn:
        type: string
      RequesterRoleAr:
        type: string
    required:
    - RequesterIdNo
    - RequesterName
    - RequesterType
    - RequesterRoleEn
    - RequesterRoleAr
  Trainee_Type:
    type: object
    properties:
      TraineeIdNo:
        type: integer
      TraineeName:
        type: string
      TraineeDOB:
        type: integer
      TraineeEmail:
        type: string
      TraineeMobileNumber:
        type: string
      NationalAddress:
        type: string
      EducationId:
        type: integer
      EducationalInstitutionId:
        type: integer
      SpecialtyId:
        type: integer
      BankName:
        type: string
      IBAN:
        type: string
    required:
    - TraineeIdNo
    - TraineeName
    - TraineeDOB
    - TraineeEmail
    - TraineeMobileNumber
    - NationalAddress
    - EducationId
    - EducationalInstitutionId
    - SpecialtyId
  Contract_Type:
    type: object
    properties:
      TrainingOccupationId:
        type: integer
      JobDescription:
        $ref: '#/definitions/JobDescription_Type'
      TargetedSkillsList:
        $ref: '#/definitions/SkillsList_Type'
      ContractTypeId:
        type: integer
      TrainingTypeId:
        type: integer
      TrainingLocationTypeId:
        type: integer
      TrainingLocationId:
        type: integer
      ExecutionLocationId:
        type: integer
      ContractPeriod:
        type: integer
      ContractStartDate:
        type: string
      ContractExpiryDate:
        type: string
      WorkingHoursTypeId:
        type: integer
      DaysPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      HoursPerWeek:
        type: integer
      RestingDays:
        type: integer
      TrainingReward:
        type: number
      TrainingRewardDay:
        type: integer
      NoticePeriod:
        type: integer
      Allowances:
        $ref: '#/definitions/Allowances_Type'
      InKindBenefits:
        $ref: '#/definitions/InKindBenefits_Type'
      TermsList:
        $ref: '#/definitions/Terms_Type'
      AdditionalTermsList:
        $ref: '#/definitions/AdditionalTerms_Type'
    required:
    - TrainingOccupationId
    - TargetedSkillsList
    - ContractTypeId
    - TrainingTypeId
    - TrainingLocationTypeId
    - TrainingLocationId
    - ExecutionLocationId
    - ContractPeriod
    - ContractStartDate
    - ContractExpiryDate
    - WorkingHoursTypeId
    - DaysPerWeek
    - RestingDays
    - NoticePeriod
    - TermsList
  HGDate_Type:
    type: object
    properties:
      HijriDate:
        type: integer
      GregDate:
        type: string
  JobDescription_Type:
    type: object
    properties:
      JobDescriptionAr:
        type: string
      JobDescriptionEng:
        type: string
    required:
    - JobDescriptionAr
    - JobDescriptionEng
  Allowances_Type:
    type: object
    properties:
      AllowancesItem:
        type: array
        items:
          $ref: '#/definitions/AllowancesItem_Type'
  AllowancesItem_Type:
    type: object
    properties:
      AllowancNameAr:
        type: string
      AllowanceNameEn:
        type: string
      Amount:
        type: number
    required:
    - AllowancNameAr
    - AllowanceNameEn
    - Amount
  InKindBenefits_Type:
    type: object
    properties:
      InKindBenefitsItem:
        type: array
        items:
          $ref: '#/definitions/InKindBenefitsItem_Type'
  InKindBenefitsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
      DescriptionEn:
        type: string
      DescriptionAr:
        type: string
      Frequency:
        type: integer
        enum:
        - 1
        - 2
        description: 1- Monthly, 2- Annually
      DueDate:
        type: string
        format: date-time
  Terms_Type:
    type: object
    properties:
      TermsItem:
        type: array
        items:
          $ref: '#/definitions/TermsItem_Type'
  TermsItem_Type:
    type: object
    properties:
      TermId:
        type: integer
  AdditionalTerms_Type:
    type: object
    properties:
      AdditionalTermsItem:
        type: array
        items:
          $ref: '#/definitions/AdditionalTermsItem_Type'
  AdditionalTermsItem_Type:
    type: object
    properties:
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - NameAr
    - NameEn
  SkillsList_Type:
    type: object
    properties:
      SkillItem:
        type: array
        items:
          $ref: '#/definitions/SkilItem_Type'
  SkilItem_Type:
    type: object
    properties:
      SkillId:
        type: integer
    required:
    - SkillId
  CreateTrnCntrRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CreateTrnCntrRs_BodyType'
  CreateTrnCntrRs_BodyType:
    type: object
    properties:
      TrainingContractId:
        type: integer
      TrainingContractStatus:
        $ref: '#/definitions/CodeName_Type'
    required:
    - TrainingContractId
    - TrainingContractStatus
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-trncntr-creates)$(request.path)
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
