swagger: "2.0"
info:
  title: CreateNewLaborOffice
  x-ibm-name: createnewlaboroffice
  version: 1.0.0
  description: CreateNewLaborOffice
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-labor-office)/qiwalo/createnewloffice
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  CreateNewLaborOfficeRq_MessageType:
    type: object
    properties:
      CreateNewLaborOfficeRq:
        $ref: '#/definitions/CreateNewLaborOfficeRq_Type'
  CreateNewLaborOfficeRs_MessageType:
    type: object
    properties:
      CreateNewLaborOfficeRs:
        $ref: '#/definitions/CreateNewLaborOfficeRs_Type'
  CreateNewLaborOfficeRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CreateNewLaborOfficeRq_BodyType'
  CreateNewLaborOfficeRq_BodyType:
    type: object
    properties:
      LODetails:
        $ref: '#/definitions/LODetails_Type'
      LOServicesList:
        $ref: '#/definitions/LOServicesList_Type'
    required:
    - LODetails
    - LOServicesList
  LODetails_Type:
    type: object
    properties:
      Address:
        $ref: '#/definitions/Address_Type'
      Location:
        type: string
      OfficeName:
        type: string
      OfficeDescription:
        type: string
      OfficePhoneNumber:
        type: string
      OfficeEmail:
        type: string
      OfficeCode:
        type: string
      WorkingHourFrom:
        type: string
      WorkingHourTo:
        type: string
      HourlyCapacity:
        type: integer
      LOContactPerson:
        type: string
      InActive:
        type: string
      OfficeID:
        type: integer
      IsElectronicOffice:
        type: string
      IsKioskMachine:
        type: string
      IsQiwa:
        type: string
    required:
    - OfficeName
    - WorkingHourFrom
    - WorkingHourTo
    - HourlyCapacity
    - IsElectronicOffice
  Address_Type:
    type: object
    properties:
      CityId:
        type: integer
      RegionId:
        type: integer
      District:
        type: string
      Street:
        type: string
      BuildingNumber:
        type: string
      AddressDescription:
        type: string
      POBox:
        type: string
      ZIPCode:
        type: string
      Latitude:
        type: number
      Longitude:
        type: number
  LOServicesList_Type:
    type: object
    properties:
      LOServicesItem:
        type: array
        items:
          $ref: '#/definitions/LOServicesItem_Type'
  LOServicesItem_Type:
    type: object
    properties:
      LOServiceID:
        type: integer
      ServiceStatus:
        type: integer
    required:
    - LOServiceID
    - ServiceStatus
  CreateNewLaborOfficeRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CreateNewLaborOfficeRs_BodyType'
  CreateNewLaborOfficeRs_BodyType:
    type: object
    properties:
      OfficeID:
        type: integer
      CreationDate:
        type: string
    required:
    - OfficeID
    - CreationDate
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /createnewloffice:
    post:
      operationId: CreateNewLaborOffice
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CreateNewLaborOfficeRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Create New Labor Office
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CreateNewLaborOfficeRq_MessageType'
        description: CreateNewLaborOfficeRq
        required: true
