swagger: "2.0"
info:
  title: Donation Widget
  x-ibm-name: donation-widget
  version: 1.0.0
  description: This API is provided for getting info for FE services
  contact:
    name: HRSD Team
host: $(catalog.host)
schemes:
- https
basePath: /api/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties: {}
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
        parameter-control:
          type: blocklist
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(donation-platform-api)$(api.operation.path)
        follow-redirects: false
    catch: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  authRequest:
    type: object
    description: ""
    additionalProperties: false
    properties:
      app_id:
        type: string
        example: a1257cdf1dad3797fba43499b9778676
      app_key:
        type: string
        example: a1bbee413a950c486498c1145244b515
paths:
  /refresh_token:
    post:
      summary: Refresh Token
      tags:
      - Donation Widget::Refresh Token
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "404":
          description: Not Found
      parameters:
      - name: RefreshToken
        in: header
        required: false
        type: string
      consumes: []
  /auth:
    post:
      summary: Auth
      tags:
      - Donation Widget::Auth
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "404":
          description: Not Found
      parameters:
      - name: auth request
        in: body
        required: false
        schema:
          $ref: '#/definitions/authRequest'
      consumes: []
  /auth/auth_vendor:
    get:
      summary: Auth Vendor
      tags:
      - Donation Widget::Auth Vendor
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "404":
          description: Not Found
