swagger: "2.0"
info:
  title: Download-Files
  x-ibm-name: download-files
  version: 1.0.0
  description: Download-Files
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-files)/qiwalo/downloadfiles
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  DownloadFilesRq_MessageType:
    type: object
    properties:
      DownloadFilesRq:
        $ref: '#/definitions/DownloadFilesRq_Type'
  DownloadFilesRs_MessageType:
    type: object
    properties:
      DownloadFilesRs:
        $ref: '#/definitions/DownloadFilesRs_Type'
  DownloadFilesRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/DownloadFilesRq_BodyType'
  DownloadFilesRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/DownloadFilesRs_BodyType'
  DownloadFilesRq_BodyType:
    type: object
    properties:
      File_ID:
        type: string
    required:
    - File_ID
  DownloadFilesRs_BodyType:
    type: object
    properties:
      File_ID:
        type: string
      FileData:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
paths:
  /downloadfiles:
    post:
      operationId: post Download-Files
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/DownloadFilesRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Insert a Download-Files
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/DownloadFilesRq_MessageType'
        description: The request body for the operation
        required: true
