swagger: "2.0"
info:
  title: DataPortalTurnOver
  x-ibm-name: dpturnoverindicator
  version: 1.0.0
  description: TurnOver Indicator
host: $(catalog.host)
schemes:
- https
basePath: /dpturnoverindicator
security:
- OAuth2.0:
  - IntegrationScope
securityDefinitions:
  OAuth2.0:
    type: oauth2
    description: ""
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://icp-proxy.qiwa.info:31558/getdpturnoverindicatorrate
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  DataPortalRequest:
    type: object
    properties:
      DataPortalTOIReq:
        type: object
        properties:
          Header:
            $ref: '#/definitions/DataPortalReq_HeaderType'
          Body:
            $ref: '#/definitions/DataPortalReq_BodyType'
  HeaderType:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      ResponseStatus:
        $ref: '#/definitions/ResponseStatusType'
      BackendError:
        $ref: '#/definitions/BackendErrorType'
  DataPortalReq_HeaderType:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
  DataPortalReq_BodyType:
    type: object
    properties:
      dim:
        type: object
        properties:
          id:
            type: integer
          key:
            type: string
            enum:
            - TI
          params:
            type: object
            properties:
              selections:
                $ref: '#/definitions/SelectionsType'
              filters:
                $ref: '#/definitions/FiltersType'
        required:
        - id
        - key
        - params
    required:
    - dim
  SelectionsType:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            seq:
              type: integer
            grouped:
              type: boolean
            func:
              type: string
  FiltersType:
    type: object
    properties:
      filter:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            gt:
              type: string
            lt:
              type: string
            eq:
              type: string
            neq:
              type: string
            in:
              type: object
              properties:
                value:
                  type: array
                  items:
                    type: string
          required:
          - name
  DataPortalRes_BodyType:
    type: object
    properties:
      fact:
        type: object
        properties:
          id:
            type: integer
          item:
            type: array
            items:
              $ref: '#/definitions/NameValuePair'
  ResponseStatusType:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendErrorType:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  NameValuePair:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
      item:
        $ref: '#/definitions/NameValuePairType'
  NameValuePairType:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
      item:
        $ref: '#/definitions/NameValuePair'
  DataPortalResponse:
    type: object
    properties:
      DataPortalTOIRes:
        type: object
        properties:
          Header:
            $ref: '#/definitions/HeaderType'
          Body:
            $ref: '#/definitions/DataPortalRes_BodyType'
paths:
  /getdpturnoverindicatorrate:
    post:
      operationId: postGetReport
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/DataPortalResponse'
      consumes:
      - application/json
      produces:
      - application/json
      description: Insert a GetReport
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/DataPortalRequest'
        description: The request body for the operation
        required: true
