swagger: "2.0"
info:
  title: Encryption
  x-ibm-name: encryption
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: http://icp-proxy.qiwa.info:32578/alrajhiverification/v1/encryptData
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  application-authentication:
    certificate: false
paths:
  /Encryption:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
