swagger: "2.0"
info:
  title: GetContractTermsConditions V2
  x-ibm-name: getcontracttermsconditions-v2
  version: 1.0.0
  description: GetContractTermsConditions
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-getscontract)/contractmanagement/getcontracttermcond
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetContractTermsConditionsRq_MessageType:
    type: object
    properties:
      GetContractTermsConditionsRq:
        $ref: '#/definitions/GetContractTermsConditionsRq_Type'
  GetContractTermsConditionsRs_MessageType:
    type: object
    properties:
      GetContractTermsConditionsRs:
        $ref: '#/definitions/GetContractTermsConditionsRs_Type'
  GetContractTermsConditionsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetContractTermsConditionsRq_BodyType'
  GetContractTermsConditionsRq_BodyType:
    type: object
    properties:
      ContractId:
        type: integer
    required:
    - ContractId
  GetContractTermsConditionsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetContractTermsConditionsRs_BodyType'
  GetContractTermsConditionsRs_BodyType:
    type: object
    properties:
      Item:
        $ref: '#/definitions/Item_Type'
      TotalRecordsCount:
        type: integer
  Item_Type:
    type: object
    properties:
      Sequance:
        type: string
      ArticleId:
        type: string
      SectionName:
        type: string
      VersionId:
        type: string
      DescriptionAr:
        type: string
      DescriptionEn:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
paths:
  /getcontracttermcond:
    post:
      operationId: GetContractTermsConditions
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetContractTermsConditionsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Update User Information
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetContractTermsConditionsRq_MessageType'
        description: GetContractTermsConditionsRq
        required: true
