swagger: "2.0"
info:
  title: MCI_GetCrDetails
  x-ibm-name: getcrdetails
  version: 1.0.0
schemes:
- https
basePath: /mci/v1
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - map:
        version: 2.0.0
        title: map
        inputs:
          "":
            schema:
              type: object
              properties:
                crNumber:
                  type: string
                  name: crNumber
            variable: request.body
            content: application/json
        outputs:
          "":
            schema:
              type: object
              properties:
                CRNumber:
                  type: string
                  name: CRNumber
            variable: message.body
            content: application/json
        actions:
        - set: .CRNumber
          from: .crNumber
        options:
          mapEnablePostProcessingJSON: true
          mapEmulateV4EmptyJSONObject: false
          mapEmulateV4DefaultRequiredProps: false
          mapReferenceLimit: 1
          includeEmptyXMLElements: false
          namespaceInheritance: false
          inlineNamespaces: false
          mapResolveApicVariables: false
          mapOptimizeSchemaDefinition: true
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"EXGCRD0001\",\n
          \   \"channelId\" : \"Integration\",\n    \"requestName\" : \"CrDetailsRq\",\n
          \   \"responseName\": \"CrDetailsRs\",\n    \"errorMap\" :{\n        \"ESBSCHEMA\"
          : {\"code\" :400, \"msg\":\"Invalid Request\"}\n    }\n    \n};\n\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\n\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\n\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.Operator-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode\r\n        },\r\n
          \       \"Body\" : apim.getvariable('message.body')\r\n            \r\n
          \       \r\n    }\r\n};\r\n\r\nif (typeof OperatorId !== 'undefined')\r\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\r\n        \"IDNumber\"
          : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-tip-mci)/external/getcrdetails
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "var apim = require('apim');\r\napim.output('application/json');\r\nvar
          message = apim.getvariable('message.body');\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          Header = message[cfg.responseName].Header;\r\nvar TransactionId = Header.TransactionId;\r\nvar
          ChannelId = Header.ChannelId;\r\nvar RequestTime = Header.RequestTime;\r\nvar
          SessionId = Header.SessionId; \r\nvar MWRequestTime = Header.MWRequestTime;\r\nvar
          MWResponseTime = Header.MWResponseTime;\r\nvar status = Header.ResponseStatus.Status;\r\nvar
          code = Header.ResponseStatus.Code;\r\napim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\r\napim.setvariable('message.headers.Channel-Id',ChannelId,'add');\r\nif
          (RequestTime !== 'undefined')\r\napim.setvariable('message.headers.RequestTime',RequestTime,'add');\r\nif
          (SessionId !== 'undefined')\r\napim.setvariable('message.headers.X-Request-Id',SessionId,'add');\r\nif
          (MWRequestTime !== 'undefined')\r\napim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\r\nif
          (MWResponseTime !== 'undefined')\r\napim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\r\napim.setvariable('message.headers.Response-Status',status,'add');\r\napim.setvariable('message.headers.Response-Code',code,'add');"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar body = message[cfg.responseName].Body;\n\n\nsession.output.write(body);\napim.output('application/json');"
          - map:
              version: 2.0.0
              title: map
              inputs:
                "":
                  schema:
                    $ref: '#/definitions/StrCrDetailsRs_BodyType'
                  variable: message.body
                  content: application/json
              outputs:
                "":
                  schema:
                    $ref: '#/definitions/CrDetailsRs_BodyType'
                  variable: message.body
                  content: application/json
              actions:
              - set: .nationalNumber
                from: .NationalNumber
              - set: .mainCRNumber
                from: .MainCRNumber
              - set: .crType
                from: .CRType
              - set: .crIssueDate.gregorianDate
                from: .CRIssueDate.GregorianDate
              - set: .crIssueDate.hijriDate
                from: .CRIssueDate.HijriDate
              - set: .crExpiryDate.gregorianDate
                from: .CRExpiryDate.GregorianDate
              - set: .crExpiryDate.hijriDate
                from: .CRExpiryDate.HijriDate
              - set: .crCityAR
                from: .CRCityAR
              - set: .crCityEN
                from: .CRCityEN
              - set: .crNameAR
                from: .CRNameAR
              - set: .crCapital
                from: .CRCapital
              - set: .crLegalTypeEN
                from: .CRLegalTypeEN
              - set: .crLegalTypeAR
                from: .CRLegalTypeAR
              - set: .crStatus.status
                from: .CRStatus.Status
              - set: .crStatus.crStatusDate
                from: .CRStatus.CRStatusDate
              - set: .crStatus.crStatusReason
                from: .CRStatus.CRStatusReason
              - set: .crPhoneNo
                from: .CRPhoneNo
              - set: .crFaxNo
                from: .CRFaxNo
              - set: .crAddress
                from: .CRAddress
              - set: .crActivities.crActivities
                from: .CRActivities.CRActivities
              - create: .crActivities.listOfISICActivities
                foreach: .CRActivities.ListOfISICActivities.ISICActivity
                from: .CRActivities.ListOfISICActivities.ISICActivity
                actions:
                - set: isICCode
                  from: ISICCode
                - set: isICName
                  from: ISICName
              options:
                mapEnablePostProcessingJSON: true
                mapEmulateV4EmptyJSONObject: false
                mapEmulateV4DefaultRequiredProps: false
                mapReferenceLimit: 1
                includeEmptyXMLElements: false
                namespaceInheritance: false
                inlineNamespaces: false
                mapResolveApicVariables: false
                mapOptimizeSchemaDefinition: true
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar error = {\n    \"ErrorResponse\":
                message[cfg.responseName].Header.ResponseStatus\n}\n\n\nvar httperror=0;\nif(cfg.errorMap){\n
                \   if(cfg.errorMap[error.ErrorResponse.Code]){\n       httperror
                = cfg.errorMap[error.ErrorResponse.Code].code;\n       \n       //var
                errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n       //var
                details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 400;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);\napim.output('application/json');"
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
paths:
  /get-cr-details:
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
definitions:
  StrCrDetailsRs_BodyType:
    type: object
    properties:
      NationalNumber:
        type: string
      CRType:
        type: string
      MainCRNumber:
        type: string
      CRIssueDate:
        $ref: '#/definitions/StrCRDate_Type'
      CRExpiryDate:
        $ref: '#/definitions/StrCRDate_Type'
      CRCityAR:
        type: string
      CRCityEN:
        type: string
      CRNameAR:
        type: string
      CRCapital:
        type: string
      CRLegalTypeEN:
        type: string
      CRLegalTypeAR:
        type: string
      CRStatus:
        $ref: '#/definitions/StrCRStatus_Type'
      CRPhoneNo:
        type: string
      CRFaxNo:
        type: string
      CRAddress:
        type: string
      CRActivities:
        $ref: '#/definitions/StrCRActivities_Type'
  StrCRDate_Type:
    type: object
    properties:
      GregorianDate:
        type: string
      HijriDate:
        type: string
  StrCRStatus_Type:
    type: object
    properties:
      Status:
        type: string
      CRStatusDate:
        type: string
      CRStatusReason:
        type: string
  StrCRActivities_Type:
    type: object
    properties:
      CRActivities:
        type: string
      ListOfISICActivities:
        $ref: '#/definitions/StrListOfISICActivities_Type'
  StrListOfISICActivities_Type:
    type: object
    properties:
      ISICActivity:
        type: array
        items:
          $ref: '#/definitions/StrISICActivity_Type'
  StrISICActivity_Type:
    type: object
    properties:
      ISICCode:
        type: string
      ISICName:
        type: string
  CrDetailsRs_BodyType:
    type: object
    properties:
      nationalNumber:
        type: string
      crType:
        type: string
      mainCRNumber:
        type: string
      crIssueDate:
        $ref: '#/definitions/CRDate_Type'
      crExpiryDate:
        $ref: '#/definitions/CRDate_Type'
      crCityAR:
        type: string
      crCityEN:
        type: string
      crNameAR:
        type: string
      crCapital:
        type: string
      crLegalTypeEN:
        type: string
      crLegalTypeAR:
        type: string
      crStatus:
        $ref: '#/definitions/CRStatus_Type'
      crPhoneNo:
        type: string
      crFaxNo:
        type: string
      crAddress:
        type: string
      crActivities:
        $ref: '#/definitions/CRActivities_Type'
  CRDate_Type:
    type: object
    properties:
      gregorianDate:
        type: string
      hijriDate:
        type: string
  CRStatus_Type:
    type: object
    properties:
      status:
        type: string
      crStatusDate:
        type: string
      crStatusReason:
        type: string
  CRActivities_Type:
    type: object
    properties:
      crActivities:
        type: string
      listOfISICActivities:
        type: array
        items:
          $ref: '#/definitions/ISICActivity_Type'
  ISICActivity_Type:
    type: object
    properties:
      isICCode:
        type: string
      isICName:
        type: string
