swagger: "2.0"
info:
  title: GetEstablishmentWPStatusTotalsMLSD
  x-ibm-name: getestablishmentwpstatustotalsmlsd
  version: 1.0.0
  description: GetEstablishmentWPStatusTotalsMLSD
schemes:
- https
basePath: /qiwa/esb
security:
- ClientID: []
  ClientSecret: []
securityDefinitions:
  ClientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
  ClientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdwp)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  GetEstablishmentWPStatusTotalsMLSDRq_MessageType:
    type: object
    properties:
      GetEstablishmentWPStatusTotalsMLSDRq:
        $ref: '#/definitions/GetEstablishmentWPStatusTotalsMLSDRq_Type'
  GetEstablishmentWPStatusTotalsMLSDRs_MessageType:
    type: object
    properties:
      GetEstablishmentWPStatusTotalsMLSDRs:
        $ref: '#/definitions/GetEstablishmentWPStatusTotalsMLSDRs_Type'
  GetEstablishmentWPStatusTotalsMLSDRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentWPStatusTotalsMLSDRq_BodyType'
  GetEstablishmentWPStatusTotalsMLSDRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
  GetEstablishmentWPStatusTotalsMLSDRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentWPStatusTotalsMLSDRs_BodyType'
  GetEstablishmentWPStatusTotalsMLSDRs_BodyType:
    type: object
    properties:
      AvailableVisas:
        type: integer
      CurrentLaborers:
        type: integer
      PendingEstablishingVisaRequests:
        type: integer
      PendingSponsorTransferRequests:
        type: integer
    required:
    - AvailableVisas
    - CurrentLaborers
    - PendingEstablishingVisaRequests
    - PendingSponsorTransferRequests
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      DebugFlag:
        $ref: '#/definitions/DebugFlag_Type'
      TransactionId:
        $ref: '#/definitions/TransactionId_Type'
      ChannelId:
        $ref: '#/definitions/ChannelId_Type'
      SessionId:
        $ref: '#/definitions/SessionId_Type'
      RequestTime:
        $ref: '#/definitions/RequestTime_Type'
      MWRequestTime:
        $ref: '#/definitions/MWRequestTime_Type'
      ServiceCode:
        $ref: '#/definitions/ServiceCode_Type'
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      DebugFlag:
        $ref: '#/definitions/DebugFlag_Type'
      TransactionId:
        $ref: '#/definitions/TransactionId_Type'
      ChannelId:
        $ref: '#/definitions/ChannelId_Type'
      SessionId:
        $ref: '#/definitions/SessionId_Type'
      RequestTime:
        $ref: '#/definitions/RequestTime_Type'
      MWRequestTime:
        $ref: '#/definitions/MWRequestTime_Type'
      MWResponseime:
        $ref: '#/definitions/MWResponseTime_Type'
      ServiceCode:
        $ref: '#/definitions/ServiceCode_Type'
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  DebugFlag_Type:
    type: integer
    default: "1"
  ServiceCode_Type:
    type: string
    default: MGEWT001
  TransactionId_Type:
    type: string
    default: "6222121543"
  ChannelId_Type:
    type: string
    default: Qiwa
  SessionId_Type:
    type: string
    default: "212"
  RequestTime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  MWRequestTime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  MWResponseTime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /mlsdgetestablishmentwpstatustotals:
    post:
      operationId: GetEstablishmentWPStatusTotalsMLSD
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentWPStatusTotalsMLSDRs_MessageType'
      description: Get Establishment WP Status Totals MLSD
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEstablishmentWPStatusTotalsMLSDRq_MessageType'
        description: GetEstablishmentWPStatusTotalsMLSDRq
        required: true
