swagger: "2.0"
info:
  title: GetEmploymentContractDetails V2
  version: 1.0.0
  description: GetEmploymentContractDetails
  x-ibm-name: getemploymentcontractdetails-v2
paths:
  /getempcontdetails:
    post:
      operationId: GetEmploymentContractDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEmploymentContractDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: ' get contract details.'
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEmploymentContractDetailsRq_MessageType'
        description: GetEmploymentContractDetailsRq
        required: true
basePath: /contractmanagement/v2
definitions:
  GetEmploymentContractDetailsRq_MessageType:
    type: object
    properties:
      GetEmploymentContractDetailsRq:
        $ref: '#/definitions/GetEmploymentContractDetailsRq_Type'
  GetEmploymentContractDetailsRs_MessageType:
    type: object
    properties:
      GetEmploymentContractDetailsRs:
        $ref: '#/definitions/GetEmploymentContractDetailsRs_Type'
  GetEmploymentContractDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEmploymentContractDetailsRq_BodyType'
  GetEmploymentContractDetailsRq_BodyType:
    type: object
    properties:
      NationalUnifiedNumber:
        type: integer
      ContractId:
        type: integer
    required:
    - ContractId
    - NationalUnifiedNumber
  GetEmploymentContractDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEmploymentContractDetailsRs_BodyType'
  GetEmploymentContractDetailsRs_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        type: array
        items:
          $ref: '#/definitions/Establishment_type'
      RequesterDetails:
        type: array
        items:
          $ref: '#/definitions/Requester_Type'
      UpdateRequesterDetails:
        type: array
        items:
          $ref: '#/definitions/UpdateRequester_Type'
      LaborerDetails:
        type: array
        items:
          $ref: '#/definitions/Laborer_Type'
      ContractDetails:
        type: array
        items:
          $ref: '#/definitions/Contract_Type'
    required:
    - EstablishmentDetails
    - RequesterDetails
    - UpdateRequesterDetails
    - LaborerDetails
    - ContractDetails
  Establishment_type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      UnifiedNationalNumber:
        type: integer
      EstablishmentType:
        $ref: '#/definitions/CodeName_Type'
      EstablishmentNameAr:
        type: string
      EstablishmentNameEn:
        type: string
      EstablishmentEmail:
        type: string
      NationalAddress:
        type: string
      PhoneNumber:
        type: string
      MobileNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - UnifiedNationalNumber
    - EstablishmentType
    - EstablishmentNameAr
    - EstablishmentNameEn
    - EstablishmentEmail
    - NationalAddress
    - PhoneNumber
    - MobileNumber
  Requester_Type:
    type: object
    properties:
      RequesterName:
        type: string
      RequesterIdNo:
        type: string
      RequesterRoleEn:
        type: string
      RequesterRoleAr:
        type: string
      RequesterType:
        $ref: '#/definitions/CodeName_Type'
    required:
    - RequesterName
    - RequesterIdNo
    - RequesterRoleEn
    - RequesterRoleAr
    - RequesterType
  UpdateRequester_Type:
    type: object
    properties:
      UpdateRequesterName:
        type: string
      UpdateRequesterIdNo:
        type: string
      UpdateRequesterRoleEn:
        type: string
      UpdateRequesterRoleAr:
        type: string
      UpdateRequesterType:
        $ref: '#/definitions/CodeName_Type'
    required:
    - UpdateRequesterName
    - UpdateRequesterIdNo
    - UpdateRequesterRoleEn
    - UpdateRequesterRoleAr
    - UpdateRequesterType
  Laborer_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      LaborerIdType:
        $ref: '#/definitions/CodeName_Type'
      PassportNumber:
        type: string
      BorderNumber:
        type: integer
      LaborerName:
        type: string
      LaborerEmail:
        type: string
      LaborerMobileNumber:
        type: string
      'NationalAddress ':
        type: string
      DOBType:
        type: integer
      LaborerDOB:
        $ref: '#/definitions/HGDate_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      Gender:
        $ref: '#/definitions/CodeName_Type'
      MaritalStatus:
        $ref: '#/definitions/CodeName_Type'
      Education:
        $ref: '#/definitions/CodeName_Type'
      Specialty:
        $ref: '#/definitions/CodeName_Type'
      WorkLocation:
        $ref: '#/definitions/CodeName_Type'
      IBAN:
        type: string
    required:
    - LaborerIdNo
    - LaborerIdType
    - PassportNumber
    - BorderNumber
    - LaborerName
    - LaborerEmail
    - LaborerMobileNumber
    - 'NationalAddress '
    - DOBType
    - LaborerDOB
    - Nationality
    - Gender
    - MaritalStatus
    - Education
    - Specialty
    - WorkLocation
    - IBAN
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
    required:
    - Code
    - NameEn
    - NameAr
  HGDate_Type:
    type: object
    properties:
      Hijri:
        type: integer
      Greogrian:
        $ref: '#/definitions/Contract_Type'
    required:
    - Hijri
    - Greogrian
  Contract_Type:
    type: object
    properties:
      ContractId:
        type: integer
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      OccupationDetails:
        $ref: '#/definitions/OccupationDetails_Type'
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      ContractDuration:
        $ref: '#/definitions/CodeName_Type'
      ExecutionLocation:
        $ref: '#/definitions/CodeName_Type'
      ContractPeriod:
        type: integer
      ProbationPeriod:
        type: integer
      NoticePeriod:
        type: integer
      VacationPeriod:
        type: integer
      WorkingHoursType:
        $ref: '#/definitions/CodeName_Type'
      HoursPerWeek:
        type: integer
      DaysPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      RestingDays:
        type: integer
      Salary:
        type: string
      TotalSalary:
        type: string
      SalaryDueDay:
        type: integer
      CurrentStartDate:
        type: string
      CurrentExpiryDate:
        type: string
      JoiningDate:
        type: string
      RenewalStatus:
        $ref: '#/definitions/CodeName_Type'
      RenewalTimes:
        type: integer
      RenewalPeriod:
        type: integer
      CreationDate:
        type: string
      LastModifiedDate:
        type: string
      LaborerAppRejDate:
        type: string
      RejectionDescription:
        type: string
      RejectionReason:
        $ref: '#/definitions/CodeName_Type'
      UpdateReason:
        $ref: '#/definitions/CodeName_Type'
      UpdateDate:
        type: integer
      ModificationReason:
        $ref: '#/definitions/CodeName_Type'
      Status:
        $ref: '#/definitions/CodeName_Type'
      LastWorkingDay:
        type: string
      Version:
        type: integer
      RelatedTo:
        $ref: '#/definitions/CodeName_Type'
      Allowances:
        $ref: '#/definitions/Allowances_Type'
      OptionalClauses:
        $ref: '#/definitions/OptionalClauses_Type'
      AdditionalTerms:
        $ref: '#/definitions/AdditionalTerms_Type'
      InKindBenefits:
        $ref: '#/definitions/InKindBenefits_Type'
      Commission:
        $ref: '#/definitions/Commission_Type'
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
  OccupationDetails_Type:
    type: object
    properties:
      OccupationId:
        type: integer
      OccupationAr:
        type: string
      OccupationEn:
        type: string
  Allowances_Type:
    type: object
    properties:
      AllowancesItem:
        type: array
        items:
          $ref: '#/definitions/AllowancesItem_Type'
  AllowancesItem_Type:
    type: object
    properties:
      AllowanceType:
        $ref: '#/definitions/CodeName_Type'
      NameAr:
        type: string
      NameEn:
        type: string
      Amount:
        type: number
  OptionalClauses_Type:
    type: object
    properties:
      OptionalClausesItem:
        type: array
        items:
          $ref: '#/definitions/OptionalClausesItem_Type'
  OptionalClausesItem_Type:
    type: object
    properties:
      OptionalClausesType:
        $ref: '#/definitions/CodeName_Type'
      Period:
        type: integer
      Field:
        type: string
      Location:
        type: string
      FirstParty:
        type: string
      SecondParty:
        type: string
  AdditionalTerms_Type:
    type: object
    properties:
      AdditionalTermsItem:
        $ref: '#/definitions/AdditionalTermsItem_Type'
  AdditionalTermsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: number
  InKindBenefits_Type:
    type: object
    properties:
      InKindBenefitsItem:
        $ref: '#/definitions/InKindBenefitsItem_Type'
  InKindBenefitsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
      DescriptionEn:
        type: string
      DescriptionAr:
        type: string
      Frequency:
        $ref: '#/definitions/CodeName_Type'
      DueDate:
        type: string
  Commission_Type:
    type: object
    properties:
      CommissionItem:
        $ref: '#/definitions/CommissionItem_Type'
  CommissionItem_Type:
    type: object
    properties:
      CommissionBaseEn:
        type: string
      CommissionBaseAr:
        type: string
      Percentage:
        type: integer
      Frequency:
        $ref: '#/definitions/CodeName_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      TotalRecordsCount:
        type: integer
      FilesList:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-cntmv2-getcon-details)/contractmanagement/getempcontdetails
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
