swagger: "2.0"
info:
  title: GetEstablishmentCurrentDataByDate
  x-ibm-name: getestablishmentcurrentdatabydate
  version: 1.0.0
  description: Integration with Get Establishment Current Data By Date Service
schemes:
- https
basePath: /common
security:
- OAuth2.0:
  - IntegrationScope
  clientId: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
    flow: application
  clientId:
    type: apiKey
    in: header
    x-key-type: client_id
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-hrsd-hrsdutility)$(request.path)
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetEstablishmentCurrentDataByDateRq_MessageType:
    type: object
    properties:
      GetEstablishmentCurrentDataByDateRq:
        $ref: '#/definitions/GetEstablishmentCurrentDataByDateRq_Type'
  GetEstablishmentCurrentDataByDateRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentCurrentDataByDateRq_BodyType'
  GetEstablishmentCurrentDataByDateRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        description: (O) LaborOfficeId
      SequenceNumber:
        type: integer
        description: (C) SequenceNumber
      FromDate:
        type: string
        description: (C) FromDate
      ToDate:
        type: string
        description: (C) ToDate
    required:
    - LaborOfficeId
    - SequenceNumber
    - FromDate
  GetEstablishmentCurrentDataByDateRs_MessageType:
    type: object
    properties:
      GetEstablishmentCurrentDataByDateRs:
        $ref: '#/definitions/GetEstablishmentCurrentDataByDateRs_Type'
  GetEstablishmentCurrentDataByDateRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentCurrentDataByDateRs_BodyType'
  GetEstablishmentCurrentDataByDateRs_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        format: int32
      SequenceNumber:
        type: integer
        format: int32
      EconomicActivityId:
        type: integer
        format: int32
      ColorId:
        type: integer
        format: int32
      GosiDisplacedTribes:
        type: integer
        format: int32
      CurrentLaborersCount:
        type: integer
        format: int32
      CurrentSaudisCount:
        type: integer
        format: int32
      CurrentForeignersCount:
        type: integer
        format: int32
    required:
    - LaborOfficeId
    - SequenceNumber
    - EconomicActivityId
    - ColorId
    - GosiDisplacedTribes
    - CurrentLaborersCount
    - CurrentSaudisCount
    - CurrentForeignersCount
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getestcurrentdatabydate:
    post:
      operationId: GetEstablishmentCurrentDataByDate
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentCurrentDataByDateRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetEstablishmentCurrentDataByDate
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEstablishmentCurrentDataByDateRq_MessageType'
        description: GetEstablishmentCurrentDataByDateRq
        required: true
