swagger: "2.0"
info:
  title: GetEstablishmentSubscription
  x-ibm-name: getestablishmentsubscription
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: ParsingParameter
        source: "var apim = require('apim');\r\nvar laborOfficeId = apim.getvariable('request.headers.laborOfficeId');\r\nvar
          sequenceNumber = apim.getvariable('request.headers.sequenceNumber');\r\nvar
          validation = true;\r\nfunction checkForNums (input) {\r\n  let result =
          /^\\d+$/.test(input);\r\n  return result\r\n}\r\nif(!(checkForNums(laborOfficeId)
          && checkForNums(sequenceNumber))){\r\napim.setvariable('api.validate',validation);\r\n}"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (api.validate=true)
          execute:
          - throw:
              version: 2.0.0
              title: throw
              name: ValidationErrors
    - map:
        version: 2.0.0
        title: map
        inputs:
          laborOfficeId:
            schema:
              type: integer
            variable: request.headers.laborOfficeId
          sequenceNumber:
            schema:
              type: integer
            variable: request.headers.sequenceNumber
        outputs:
          "":
            schema:
              description: ""
              type: object
              properties:
                UsersSubscriptionList:
                  type: object
                  properties:
                    UserSubscription:
                      type: object
                      properties:
                        LaborOfficeId:
                          type: string
                          name: LaborOfficeId
                        SequenceNumber:
                          type: string
                          name: SequenceNumber
                      xml:
                        namespace: ""
                      name: UserSubscription
                  xml:
                    namespace: ""
                  name: UsersSubscriptionList
              xml:
                namespace: ""
              example: "<UsersSubscriptionList>\r\n    <UserSubscription>\r\n        <LaborOfficeId>1</LaborOfficeId>\r\n
                \       <SequenceNumber>1664412</SequenceNumber>\r\n    </UserSubscription>\r\n</UsersSubscriptionList>"
            variable: message.body
            content: application/xml
        actions:
        - set: .UsersSubscriptionList.UserSubscription.LaborOfficeId
          from: laborOfficeId
        - set: .UsersSubscriptionList.UserSubscription.SequenceNumber
          from: sequenceNumber
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: $(dp-qiwadp-replica-sp)/EstablishmentSubscriptions_Check
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - xslt:
        version: 2.0.0
        title: xslt
        input: false
        source: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<xsl:stylesheet version=\"1.0\"\r\n
          \ xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"\r\n  xmlns:dp=\"http://www.datapower.com/extensions\"\r\n
          \ xmlns:func=\"http://exslt.org/functions\"\r\n  xmlns:apim=\"http://www.ibm.com/apimanagement\"
          extension-element-prefixes=\"dp func apim\">\r\n\r\n  <!-- Contains the
          APIM functions -->\r\n<xsl:include href=\"store:///dp/apim.custom.xsl\"
          />\r\n\r\n  <xsl:template match=\"/\">\r\n    <xsl:variable name=\"input\"
          select=\"apim:payloadRead()\" />\r\n       <xsl:variable name = \"HasActiveSubscriptions\"
          select=\"$input/sql/resultSet/row/column[3]/value\"/> \r\n\t   <xsl:variable
          name = \"Subscription_ID\" select=\"$input/sql/resultSet/row/column[4]/value\"/>
          \r\n <xsl:element name=\"Response\">\t   \r\n <xsl:element name=\"HasActiveSubscriptions\"><xsl:value-of
          select=\"$HasActiveSubscriptions\"/></xsl:element>\r\n <xsl:element name=\"Subscription_ID\"><xsl:value-of
          select=\"$Subscription_ID\"/></xsl:element>\r\n </xsl:element>\r\n  </xsl:template>\r\n</xsl:stylesheet>"
    - map:
        version: 2.0.0
        title: map
        inputs:
          "":
            schema:
              description: ""
              type: object
              properties:
                Response:
                  type: object
                  properties:
                    HasActiveSubscriptions:
                      type: string
                      name: HasActiveSubscriptions
                    Subscription_ID:
                      type: string
                      name: Subscription_ID
                  xml:
                    namespace: ""
                  name: Response
              xml:
                namespace: ""
              example: "<Response>\r\n<HasActiveSubscriptions>1</HasActiveSubscriptions>\r\n<Subscription_ID>1</Subscription_ID>\r\n</Response>"
            variable: message.body
            content: application/xml
        outputs:
          "":
            schema:
              description: ""
              type: object
              properties:
                HasActiveSubscriptions:
                  type: number
                  name: HasActiveSubscriptions
                Subscription_ID:
                  type: number
                  name: Subscription_ID
              example: |-
                {
                    "HasActiveSubscriptions": 1,
                    "Subscription_ID": 1
                  }
            variable: message.body
            content: application/json
        actions:
        - set: .Subscription_ID
          from: .Response.Subscription_ID
        - set: .HasActiveSubscriptions
          from: .Response.HasActiveSubscriptions
    - gatewayscript:
        version: 2.0.0
        title: BooleanParsing
        source: "var apim = require('apim');\r\nvar response = apim.getvariable('message.body');\r\nvar
          SubscriptionId = response.SubscriptionId;\r\nvar IsSubscribed = response.HasActiveSubscriptions;\r\nif
          (IsSubscribed == \"1\"){\r\n  if (SubscriptionId == '')\r\n    {\r\n\tvar
          response = {\r\n\t\"Error\" : \"No DataFound\"\r\n\t}}\r\n    else\r\n\t{\r\n\tvar
          response = {\r\n\t\"IsSubscribed\" : true\r\n\t}\r\n\t\r\n}\r\n}\r\nelse{\r\n\tvar
          response = {\r\n\t\"IsSubscribed\" : false\r\n\t}\r\n}\r\nsession.output.write(response);\r\napim.output('application/json');"
    catch:
    - errors:
      - ValidationErrors
      execute:
      - gatewayscript:
          version: 2.0.0
          title: SchemaError
          source: "var apim = require('apim');\r\nvar body = {\r\n    \"errorCode\":
            \"ESBSCHEMA\",\r\n    \"errorMessage\": {\r\n        \"en-US\": \"Schema
            Validation Error : Node Name  :com.ext.esb.GetEstablishmentSubscription.HTTP_GetEstablishmentSubscriptionFlow.HTTPRequestAdapter.HTTP
            Input;  Errror Text  :Node throwing exception. XML Writing Errors have
            occurred. A schema validation error has occurred while validating the
            message tree. 6000. 1. 1. 280. cvc-datatype-valid.1.2: The value \\\"test\\\"
            is not a valid value for the \\\"integer\\\" datatype.. /Root/XMLNSC/GetEstablishmentSubscription/Body/\",\r\n
            \       \"ar-SA\": \"حدث خطأ بالنظام\"\r\n    }\r\n}\r\nsession.output.write(body);\r\napim.output('application/json');"
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
parameters:
  X-IBM-Client-Id:
    name: X-IBM-Client-Id
    required: true
    in: header
    type: string
  X-IBM-Client-Secret:
    name: X-IBM-Client-Secret
    required: true
    in: header
    type: string
  X-Request-Id:
    name: X-Request-Id
    in: header
    type: string
  laborOfficeId:
    name: laborOfficeId
    type: integer
    required: true
    in: header
    description: laborOfficeId
    format: int32
  sequenceNumber:
    name: sequenceNumber
    required: true
    in: header
    type: integer
    description: sequenceNumber
    format: int32
paths:
  /getestablishmentsubscription:
    parameters:
    - name: X-IBM-Client-Id
      in: header
      required: true
      type: string
    - name: X-IBM-Client-Secret
      in: header
      required: true
      type: string
    - name: X-Request-Id
      in: header
      required: false
      type: string
    - name: laborOfficeId
      in: header
      required: true
      description: laborOfficeId
      type: integer
      format: int32
    - name: sequenceNumber
      in: header
      required: true
      description: sequenceNumber
      type: integer
      format: int32
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
