swagger: "2.0"
info:
  title: GetEstablishmentInformation
  x-ibm-name: getestablishmentinformation
  version: 1.0.0
  description: This service is used to get establishment information, which retrieves
    all details and notes related to the establishment.
schemes:
- https
basePath: /qiwa/esb
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-utl-getestabinfo)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetEstablishmentInformationRq_MessageType:
    type: object
    properties:
      GetEstablishmentInformationRq:
        $ref: '#/definitions/GetEstablishmentInformationRq_Type'
  GetEstablishmentInformationRs_MessageType:
    type: object
    properties:
      GetEstablishmentInformationRs:
        $ref: '#/definitions/GetEstablishmentInformationRs_Type'
  GetEstablishmentInformationRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentInformationRq_BodyType'
  GetEstablishmentInformationRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: string
        default: "1"
      EstablishmentSequanceNumber:
        type: string
        default: "24"
      EstablishmentId:
        type: string
        default: "1"
      NoteStatusId:
        type: string
        default: "1"
    required:
    - LaborOfficeId
    - EstablishmentSequanceNumber
    - EstablishmentId
    - NoteStatusId
  GetEstablishmentInformationRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentInformationRs_BodyType'
  GetEstablishmentInformationRs_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      NotesInformationList:
        $ref: '#/definitions/NotesInformationList_Type'
  NotesInformationList_Type:
    type: object
    properties:
      NoteInformation:
        type: array
        items:
          $ref: '#/definitions/NoteInformation_Type'
  NoteInformation_Type:
    type: object
    properties:
      NoteId:
        type: string
      EstablishmentId:
        type: string
      NoteText:
        type: string
      NoteStatusId:
        type: string
      NoteStatusName:
        type: string
      NoteTypeId:
        type: string
      StartDate:
        type: string
      EndDate:
        type: string
      NoteSourceId:
        type: string
      NoteSourceName:
        type: string
  EstablishmentDetails_Type:
    type: object
    properties:
      EstablishmentId:
        type: string
      PKEstablishmentId:
        $ref: '#/definitions/PKEstablishmentId'
      EstablishmentName:
        type: string
      LaborOfficeId:
        type: string
      SequanceNumber:
        type: string
      EstablishmentStatusId:
        type: string
      EstablishmentStatus:
        type: string
      MainEconomicActivityId:
        type: string
      SubEconomicActivityId:
        type: string
      MainEconomicActivity:
        type: string
      SubEconomicActivity:
        type: string
      CRNumber:
        type: string
      CRReleaseDate:
        type: string
      CREndDate:
        type: string
      MunicipalLicenseSource:
        $ref: '#/definitions/MunicipalLicenseSource'
      MunicipalLicenseNumber:
        type: string
      MunicipalLicenseReleaseDate:
        type: string
      MunicipalLicenseEndDate:
        type: string
      Notes:
        type: string
      SevenHundredNumber:
        type: string
      UnifiedNumberId:
        type: string
      OwnerId:
        $ref: '#/definitions/OwnerId'
      InsertDate:
        type: string
      IsMainBranch:
        type: string
      District:
        type: string
      Street:
        type: string
      EstablishmentEmail:
        $ref: '#/definitions/EstablishmentEmail'
      PostalCode:
        type: string
      ZIPCode:
        type: string
      PKOwnerId:
        type: string
      UnifiedNationalNumber:
        type: string
      UseUnifiedNationalNumberFlag:
        type: string
      CityId:
        type: string
      CityName:
        type: string
      EstablishmentTypeId:
        $ref: '#/definitions/EstablishmentTypeId'
      EstablishmentTypeName:
        $ref: '#/definitions/EstablishmentTypeName'
      WaselZipCode:
        $ref: '#/definitions/WaselZipCode'
      WaselPrimary:
        $ref: '#/definitions/WaselPrimary'
      WaselSecondary:
        $ref: '#/definitions/WaselSecondary'
      WaselUnitNo:
        $ref: '#/definitions/WaselUnitNo'
      WaselCity:
        $ref: '#/definitions/WaselCity'
      WaselArea:
        $ref: '#/definitions/WaselArea'
      WaselStreet:
        $ref: '#/definitions/WaselStreet'
      WaselExpiryDate:
        $ref: '#/definitions/WaselExpiryDate'
      WaselStatus:
        $ref: '#/definitions/WaselStatus'
      EconomicActivityId:
        type: string
      EconomicActivityName:
        type: string
      ColorId:
        type: string
      NitaqatColor:
        type: string
      SizeId:
        type: string
      SizeName:
        type: string
      ColorCode:
        type: string
      Saudis:
        type: string
      Foreigners:
        type: string
      TotalLaborerCount:
        type: string
      EntitySaudiPercentage:
        type: string
      EntityId:
        type: string
      EntityForeignersCount:
        type: string
      EntitySaudisCount:
        type: string
      EntityTotalCount:
        type: string
      EntitySaudisTotalFactorized:
        type: string
      EntityForeignersTotalFactorized:
        type: string
      NICAccountNumber:
        type: string
  PKEstablishmentId:
    type: object
    properties: {}
  MunicipalLicenseSource:
    type: object
    properties: {}
  OwnerId:
    type: object
    properties: {}
  EstablishmentEmail:
    type: object
    properties: {}
  EstablishmentTypeId:
    type: object
    properties: {}
  EstablishmentTypeName:
    type: object
    properties: {}
  WaselZipCode:
    type: object
    properties: {}
  WaselPrimary:
    type: object
    properties: {}
  WaselSecondary:
    type: object
    properties: {}
  WaselUnitNo:
    type: object
    properties: {}
  WaselCity:
    type: object
    properties: {}
  WaselArea:
    type: object
    properties: {}
  WaselStreet:
    type: object
    properties: {}
  WaselExpiryDate:
    type: object
    properties: {}
  WaselStatus:
    type: object
    properties: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GEI00001
      DebugFlag:
        type: integer
        default: "1"
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GEI00001
      DebugFlag:
        type: integer
        default: "1"
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
paths:
  /getestablishmentinformation:
    post:
      operationId: GetEstablishmentInformation
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentInformationRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Establishment Information
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEstablishmentInformationRq_MessageType'
        description: GetEstablishmentInformationRq
        required: true
