swagger: "2.0"
info:
  title: GetFinalExitReEntryVisasList
  x-ibm-name: getfinalexitreentryvisaslist
  version: 1.0.0
  description: This service is used to get  a list of final exit / re-entry visas
    requests that were requested within 10 days and no objection was requested at
    it.
schemes:
- https
basePath: /fereentryobj
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-fxo-objections)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  GetFinalExitReEntryVisasListRq_MessageType:
    type: object
    properties:
      GetFinalExitReEntryVisasListRq:
        $ref: '#/definitions/GetFinalExitReEntryVisasListRq_Type'
  GetFinalExitReEntryVisasListRs_MessageType:
    type: object
    properties:
      GetFinalExitReEntryVisasListRs:
        $ref: '#/definitions/GetFinalExitReEntryVisasListRs_Type'
  GetFinalExitReEntryVisasListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetFinalExitReEntryVisasListRq_BodyType'
  GetFinalExitReEntryVisasListRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "1"
      SequenceNumber:
        type: integer
        default: "1359"
      LaborerIdNo:
        type: integer
        default: "20002144"
      NICAccountNumber:
        type: number
        default: "11"
      LaborerFirstName:
        type: string
        default: "11"
      PageSize:
        type: integer
        default: "1"
      PageIndex:
        type: integer
        default: "100"
    required:
    - PageSize
    - PageIndex
  GetFinalExitReEntryVisasListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetFinalExitReEntryVisasListRs_BodyType'
  GetFinalExitReEntryVisasListRs_BodyType:
    type: object
    properties:
      FEReEntryVisas:
        $ref: '#/definitions/FEReEntryVisas_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GFERVL01
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GFERVL01
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  FEReEntryVisas_Type:
    type: object
    properties:
      Visa:
        type: array
        items:
          $ref: '#/definitions/Visa_Type'
  Visa_Type:
    type: object
    properties:
      RequestId:
        type: integer
      LaborerIdNo:
        type: integer
      LaborerFullName:
        type: string
      RequestType:
        $ref: '#/definitions/CodeName_Type'
      RequestDate:
        type: string
      RequestNumber:
        type: integer
      RequestStaus:
        $ref: '#/definitions/CodeName_Type'
      NICAccountNumber:
        type: number
    required:
    - RequestId
    - LaborerIdNo
    - LaborerFullName
    - RequestDate
    - RequestNumber
    - NICAccountNumber
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
paths:
  /getferevisaslist:
    post:
      operationId: GetFinalExitReEntryVisasList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetFinalExitReEntryVisasListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Final Exit Re Entry Visas List
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetFinalExitReEntryVisasListRq_MessageType'
        description: GetFinalExitReEntryVisasListRq
        required: true
