swagger: "2.0"
info:
  title: GetFinalExitDebts
  x-ibm-name: getfinalexitdebts
  version: 1.0.0
  description: GetFinalExitDebts
schemes:
- https
basePath: /workpermit
security:
- OAuth2.0:
  - IntegrationScope
  clientId: []
securityDefinitions:
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wp-wpget)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetFinalExitDebtsRq_MessageType:
    type: object
    properties:
      GetFinalExitDebtsRq:
        $ref: '#/definitions/GetFinalExitDebtsRq_Type'
  GetFinalExitDebtsRs_MessageType:
    type: object
    properties:
      GetFinalExitDebtsRs:
        $ref: '#/definitions/GetFinalExitDebtsRs_Type'
  GetFinalExitDebtsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetFinalExitDebtsRq_BodyType'
  GetFinalExitDebtsRq_BodyType:
    type: object
    properties:
      RequestNumber:
        type: string
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      SourceDetails:
        $ref: '#/definitions/SourceDetails_Type'
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      StatusIds:
        $ref: '#/definitions/StatusIds_Type'
      SponsorIdNo:
        type: number
      ExceptionRequestId:
        type: string
      SortingReleaseDate:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - PageSize
    - PageIndex
  DestinationDetails_Type:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
      DestinationSequenceNumber:
        type: integer
      DestinationEstablishmentName:
        type: string
  SourceDetails_Type:
    type: object
    properties:
      SourceLaborOfficeId:
        type: integer
      SourceSequenceNumber:
        type: integer
      SourceEstablishmentName:
        type: string
  LaborerDeta_Type:
    type: object
    properties:
      LaborerIdNo:
        type: string
      LaborerName:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      NewOccupation:
        $ref: '#/definitions/CodeName_Type'
      IqamaExpirationDate:
        type: string
      WPExpirationDate:
        type: string
  LaborerDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: string
      LaborerName:
        type: string
  StatusIds_Type:
    type: object
    properties:
      Status:
        type: array
        items:
          $ref: '#/definitions/Status_Type'
  Status_Type:
    type: object
    properties:
      Id:
        type: integer
    required:
    - Id
  GetFinalExitDebtsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetFinalExitDebtsRs_BodyType'
  GetFinalExitDebtsRs_BodyType:
    type: object
    properties:
      ETList:
        $ref: '#/definitions/ETList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  ETList_Type:
    type: object
    properties:
      ETReq:
        type: array
        items:
          $ref: '#/definitions/ETReq_Type'
    required:
    - ETReq
  ETReq_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      SourceDetails:
        $ref: '#/definitions/SourceDetails_Type'
      LaborerDetails:
        $ref: '#/definitions/LaborerDeta_Type'
      RequestDate:
        $ref: '#/definitions/Tmstmp_Type'
      TransferType:
        $ref: '#/definitions/CodeName_Type'
      Status:
        $ref: '#/definitions/CodeName_Type'
      ReleaseDate:
        $ref: '#/definitions/Tmstmp_Type'
      RejectionReasons:
        type: string
      LaborerAppRejDate:
        type: string
      CurrEmpAppRejDate:
        type: string
      NICAppRejDate:
        type: string
      RemainingDays:
        type: integer
    required:
    - RequestNumber
    - DestinationDetails
    - SourceDetails
    - LaborerDetails
    - RequestDate
    - TransferType
    - Status
    - ReleaseDate
    - LaborerAppRejDate
    - CurrEmpAppRejDate
    - NICAppRejDate
    - RemainingDays
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getfinalexitdebts:
    post:
      operationId: GetFinalExitDebts
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetFinalExitDebtsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service is used to get laborers who have debts related to
        their final exit.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetFinalExitDebtsRq_MessageType'
        description: GetFinalExitDebtsRq
        required: true
