swagger: "2.0"
info:
  title: GetGovernmentSectorsList
  x-ibm-name: getgovernmentsectorslist
  version: 1.0.0
  description: This service is used to get list of governmental sectors .
schemes:
- https
basePath: /visa/seasonalvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-sese-govsectors)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetGovernmentSectorsListRq_MessageType:
    type: object
    properties:
      GetGovernmentSectorsListRq:
        $ref: '#/definitions/GetGovernmentSectorsListRq_Type'
  GetGovernmentSectorsListRs_MessageType:
    type: object
    properties:
      GetGovernmentSectorsListRs:
        $ref: '#/definitions/GetGovernmentSectorsListRs_Type'
  GetGovernmentSectorsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetGovernmentSectorsListRq_BodyType'
  GetGovernmentSectorsListRq_BodyType:
    type: object
    properties:
      GovernmentalSectorId:
        type: string
      GovermentSectorNumber:
        type: integer
      GovermentSectorName:
        type: string
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - PageSize
    - PageIndex
  GetGovernmentSectorsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetGovernmentSectorsListRs_BodyType'
  GetGovernmentSectorsListRs_BodyType:
    type: object
    properties:
      GovernmentSectorList:
        $ref: '#/definitions/GovernmentSectorList_Type'
      TotalRecordsCount:
        type: integer
  GovernmentSectorList_Type:
    type: object
    properties:
      GovernmentalSectorDetails:
        type: array
        items:
          $ref: '#/definitions/GovernmentalSectorDetail_Type'
  GovernmentalSectorDetail_Type:
    type: object
    properties:
      GovermentSectorId:
        type: string
      GovermentSectorNumber:
        type: integer
      GovermentSectorName:
        type: string
      IsExempted:
        type: boolean
    required:
    - IsExempted
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getgoversectorslist:
    post:
      operationId: GetGovernmentSectorsList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetGovernmentSectorsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Update Refunded
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetGovernmentSectorsListRq_MessageType'
        description: GetGovernmentSectorsListRq
        required: true
