swagger: "2.0"
info:
  title: GetLaborerInformationMLSD
  x-ibm-name: getlaborerinformationmlsd
  version: 1.0.0
  description: This service is used to get all the laborer information, including
    the related Establishment to the laborer.
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdget2)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetLaborerInformationMLSDRq_MessageType:
    type: object
    properties:
      GetLaborerInformationMLSDRq:
        $ref: '#/definitions/GetLaborerInformationMLSDRq_Type'
  GetLaborerInformationMLSDRs_MessageType:
    type: object
    properties:
      GetLaborerInformationMLSDRs:
        $ref: '#/definitions/GetLaborerInformationMLSDRs_Type'
  GetLaborerInformationMLSDRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetLaborerInformationMLSDRq_BodyType'
  GetLaborerInformationMLSDRq_BodyType:
    type: object
    properties:
      IdNo:
        type: string
        default: "2048256909"
      IqamaExpiryDate:
        type: string
        default: "2019-01-31"
    required:
    - IdNo
  GetLaborerInformationMLSDRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetLaborerInformationMLSDRs_BodyType'
  GetLaborerInformationMLSDRs_BodyType:
    type: object
    properties:
      EstablishmentInfo:
        $ref: '#/definitions/EstablishmentInfo_Type'
      LaborerInformation:
        $ref: '#/definitions/LaborerInformation_Type'
      TotalRecordCount:
        type: integer
  LaborerInformation_Type:
    type: object
    properties:
      PKLaborerId:
        type: string
      LaborerIdNo:
        type: string
      FirstName:
        type: string
      SecondName:
        type: string
      ThirdName:
        type: string
      FourthName:
        type: string
      Gender:
        type: string
      BirthOfDate:
        type: string
      Nationality:
        $ref: '#/definitions/Nationality_Type'
      EducationalStatus:
        $ref: '#/definitions/EducationalStatus_Type'
      Qualification:
        $ref: '#/definitions/Qualification_Type'
      Job:
        $ref: '#/definitions/Job_Type'
      LaborerStatus:
        $ref: '#/definitions/LaborerStatus_Type'
      AccomodationStatus:
        $ref: '#/definitions/AccomodationStatus_Type'
      EntryDate:
        type: string
      ReligionId:
        type: integer
      IdReleaseDate:
        type: string
      IqamaExpirationDate:
        type: string
      ServiceStartDate:
        type: string
      ServiceEndDate:
        type: string
      PassportNo:
        type: string
      PassportSource:
        type: string
      PassportReleaseDate:
        type: string
      BorderNo:
        type: string
      WorkPermitTypeId:
        type: integer
      WorkPermitStartDate:
        type: integer
      WorkPermitEndDate:
        type: integer
      ServiceEndReasonId:
        type: integer
      ImmunizationStatus:
        $ref: '#/definitions/ImmunizationStatus_Type'
  EstablishmentInfo_Type:
    type: object
    properties:
      EstablishmentId:
        type: string
      EstablishmentName:
        type: string
      LaborOfficeId:
        type: string
      SequanceNumber:
        type: integer
      UnifiedNumberId:
        type: integer
  Nationality_Type:
    type: object
    properties:
      NationalityCode:
        type: string
      NationalityName:
        type: string
  EducationalStatus_Type:
    type: object
    properties:
      EducationalStatusCode:
        type: string
      EducationalStatusName:
        type: string
  Qualification_Type:
    type: object
    properties:
      QualificationCode:
        type: string
      QualificationName:
        type: string
  Job_Type:
    type: object
    properties:
      JobCode:
        type: string
      JobName:
        type: string
  LaborerStatus_Type:
    type: object
    properties:
      LaborerStatusCode:
        type: string
      LaborerStatusName:
        type: string
  AccomodationStatus_Type:
    type: object
    properties:
      AccomodationStatusCode:
        type: string
      AccomodationStatusName:
        type: string
  ImmunizationStatus_Type:
    type: object
    properties:
      Code:
        type: string
      NameAr:
        type: string
      NameEn:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGLI0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGLI0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getlaborerinformationmlsd:
    post:
      operationId: GetLaborerInformationMLSD
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetLaborerInformationMLSDRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetLaborerInformationMLSD
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetLaborerInformationMLSDRq_MessageType'
        description: GetLaborerInformationMLSD
        required: true
