swagger: "2.0"
info:
  title: GetLicenseRequestComments
  x-ibm-name: getlicenserequestcomments
  version: 1.0.0
  description: Get Centers Details
host: $(catalog.host)
schemes:
- https
basePath: /dashboard
security:
- OAuth2:
  - IntegrationScope
  clientID: []
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://example.com
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-taheel)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  type: rest
  phase: realized
  enforced: true
  testable: true
  application-authentication:
    certificate: false
definitions:
  GetLicenseRequestCommentsRq_MessageType:
    type: object
    properties:
      GetLicenseRequestCommentsRq:
        $ref: '#/definitions/GetLicenseRequestCommentsRq_Type'
  GetLicenseRequestCommentsRs_MessageType:
    type: object
    properties:
      GetLicenseRequestCommentsRs:
        $ref: '#/definitions/GetLicenseRequestCommentsRs_Type'
  GetLicenseRequestCommentsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetLicenseRequestCommentsRq_BodyType'
  GetLicenseRequestCommentsRq_BodyType:
    type: object
    properties:
      UserRole:
        type: integer
      RequestId:
        type: integer
  GetLicenseRequestCommentsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetLicenseRequestCommentsRs_BodyType'
  GetLicenseRequestCommentsRs_BodyType:
    type: object
    properties:
      RequestComments:
        type: array
        items:
          $ref: '#/definitions/RequestComments_Type'
  RequestComments_Type:
    type: object
    properties:
      UserId:
        type: integer
      UserRole:
        type: integer
      Comment:
        type: string
      CreationDate:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /license/comments:
    post:
      operationId: GetLicenseRequestComments
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetLicenseRequestCommentsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Centers Details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetLicenseRequestCommentsRq_MessageType'
        description: GetLicenseRequestCommentsRq
        required: true
