swagger: "2.0"
info:
  title: GetLaborOfficeUserDetails
  x-ibm-name: getlaborofficeuserdetails
  version: 2.0.0
  description: This service is used to get all the labor office users information,
    including the related office to the user.
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-user)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetLaborOfficeUserDetailsRq_MessageType:
    type: object
    properties:
      GetLaborOfficeUserDetailsRq:
        $ref: '#/definitions/GetLaborOfficeUserDetailsRq_Type'
  GetLaborOfficeUserDetailsRs_MessageType:
    type: object
    properties:
      GetLaborOfficeUserDetailsRs:
        $ref: '#/definitions/GetLaborOfficeUserDetailsRs_Type'
  GetLaborOfficeUserDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetLaborOfficeUserDetailsRq_BodyType'
  GetLaborOfficeUserDetailsRq_BodyType:
    type: object
    properties:
      IdNo:
        type: string
        default: "12345"
    required:
    - IdNo
  GetLaborOfficeUserDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetLaborOfficeUserDetailsRs_BodyType'
  GetLaborOfficeUserDetailsRs_BodyType:
    type: object
    properties:
      'LOInformation ':
        $ref: '#/definitions/LOInformation_Type'
      LOUserInformation:
        $ref: '#/definitions/LOUserInformation_Type'
    required:
    - LOUserInformation
  LOInformation_Type:
    type: object
    properties:
      'OfficeID ':
        type: integer
      OfficeName:
        type: string
      OfficeCode:
        type: string
      DailyCapacity:
        type: string
      OfficeStatus:
        $ref: '#/definitions/OfficeStatus_Type'
    required:
    - OfficeName
    - OfficeCode
    - DailyCapacity
    - OfficeStatus
  LOUserInformation_Type:
    type: object
    properties:
      IdNo:
        type: string
      Name:
        type: string
      UserStatus:
        $ref: '#/definitions/UserStatus_Type'
      UserType:
        $ref: '#/definitions/UserType_Type'
      UserServiceList:
        $ref: '#/definitions/UserServiceList_Type'
      Email:
        type: string
      MobileNumber:
        type: string
      UserId:
        type: integer
      IdExpiryDate:
        type: string
    required:
    - IdNo
    - Name
    - UserStatus
    - UserType
    - UserServiceList
    - Email
    - MobileNumber
    - UserId
    - IdExpiryDate
  UserStatus_Type:
    type: object
    properties:
      'UserStatusId ':
        type: integer
      UserStatusNameAr:
        type: string
      UserStatusNameEn:
        type: string
    required:
    - UserStatusNameAr
    - UserStatusNameEn
  UserType_Type:
    type: object
    properties:
      'UserTypeId ':
        type: integer
      UserTypeNameAr:
        type: string
      UserTypeNameEn:
        type: string
    required:
    - UserTypeNameAr
    - UserTypeNameEn
  UserServiceList_Type:
    type: object
    properties:
      UserServiceItem:
        type: array
        items:
          $ref: '#/definitions/UserServiceItem_Type'
  UserServiceItem_Type:
    type: object
    properties:
      UserServiceId:
        type: integer
      ServiceNameAr:
        type: string
      ServiceNameEn:
        type: string
      ServiceStatus:
        type: string
    required:
    - UserServiceId
    - ServiceNameAr
    - ServiceNameEn
    - ServiceStatus
  OfficeStatus_Type:
    type: object
    properties:
      OfficeStatusId:
        type: integer
      OfficeStatusAr:
        type: string
      OfficeStatusEn:
        type: string
    required:
    - OfficeStatusId
    - OfficeStatusAr
    - OfficeStatusEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GLOUD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GLOUD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getlousersdetails:
    post:
      operationId: GetLaborOfficeUserDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetLaborOfficeUserDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Create New Labor Office
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetLaborOfficeUserDetailsRq_MessageType'
        description: GetLaborOfficeUserDetailsRq
        required: true
