swagger: "2.0"
info:
  title: GetNICVisasDetails
  x-ibm-name: getnicvisasdetails
  version: 1.0.0
  description: This service is used to handle the missing visa details  from NIC based
    on saved timed-out requests into Qiwa DB also submit establishing and expansion
    visa in HRSD .
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmnv-commonvisautilites)/common/getnicvisasdetails
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetNICVisasDetailsRq_MessageType:
    type: object
    properties:
      GetNICVisasDetailsRq:
        $ref: '#/definitions/GetNICVisasDetailsRq_Type'
  GetNICVisasDetailsRs_MessageType:
    type: object
    properties:
      GetNICVisasDetailsRs:
        $ref: '#/definitions/GetNICVisasDetailsRs_Type'
  GetNICVisasDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetNICVisasDetailsRq_BodyType'
  GetNICVisasDetailsRq_BodyType:
    type: object
    properties:
      VisaRequestTypeId:
        type: integer
      RequestNumber:
        type: string
      VisaOutGoingNumber:
        type: integer
      MOLRefernceNo:
        type: string
    required:
    - VisaRequestTypeId
    - RequestNumber
  GetNICVisasDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetNICVisasDetailsRs_BodyType'
  GetNICVisasDetailsRs_BodyType:
    type: object
    properties: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getnicvisasdetails:
    post:
      operationId: GetNICVisasDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetNICVisasDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get NIC Visas Details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetNICVisasDetailsRq_MessageType'
        description: GetNICVisasDetailsRq
        required: true
