swagger: "2.0"
info:
  title: 'GetOccupationsList '
  x-ibm-name: getoccupationslist
  version: 1.0.0
  description: 'This service is used to get occupations list '
schemes:
- https
basePath: /occupationmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-ocpm-occmgmtget)/occmng/getoccupationslist
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetOccupationsListRq_MessageType:
    type: object
    properties:
      GetOccupationsListRq:
        $ref: '#/definitions/GetOccupationsListRq_Type'
  GetOccupationsListRs_MessageType:
    type: object
    properties:
      GetOccupationsListRs:
        $ref: '#/definitions/GetOccupationsListRs_Type'
  GetOccupationsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetOccupationsListRq_BodyType'
  GetOccupationsListRq_BodyType:
    type: object
    properties:
      OccupationId:
        type: integer
        default: "1"
      GroupId:
        type: integer
        default: "1"
      IsForSaudiOnly:
        type: integer
        default: "1"
      IsValidForIstiqdam:
        type: integer
        default: "1"
      IsValidForVisa:
        type: integer
        default: "1"
      IsValidForChgOccTo:
        type: integer
        default: "1"
      CanChangeOnline:
        type: integer
        default: "1"
      IsWPRequired:
        type: integer
        default: "1"
      IsGovSupportEWV:
        type: integer
        default: "1"
      IsEngineeringJob:
        type: integer
        default: "1"
      IsHomeJob:
        type: integer
        default: "1"
      IsMedicalJob:
        type: integer
        default: "1"
      IsAccountantJob:
        type: integer
        default: "1"
      IsValidForIstiqdam1_5:
        type: integer
        default: "1"
      IsAllowedForMonshaatVISA:
        type: integer
        default: "1"
      IsBlockedForSeasonalVisas:
        type: integer
        default: "1"
      ShowAll:
        type: integer
        default: "1"
      PageSize:
        type: integer
        default: "1"
      PageIndex:
        type: integer
        default: "1"
    required:
    - PageSize
    - PageIndex
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
  GetOccupationsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetOccupationsListRs_BodyType'
  GetOccupationsListRs_BodyType:
    type: object
    properties:
      OccupationsList:
        $ref: '#/definitions/OccupationsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - OccupationsList
    - TotalRecordsCount
  OccupationsList_Type:
    type: object
    properties:
      OccupationsListDetails:
        type: array
        items:
          $ref: '#/definitions/OccupationsListDetails_Type'
  OccupationsListDetails_Type:
    type: object
    properties:
      OccupationDetails:
        $ref: '#/definitions/CodeName_Type'
      IsForSaudiOnly:
        type: boolean
      IsValidForIstiqdam:
        type: boolean
      IsWPRequired:
        type: boolean
      'QsimCode ':
        type: integer
      JzaCode:
        type: integer
      BabCode:
        type: integer
      FslCode:
        type: integer
      MhnCode:
        type: integer
      MstCode:
        type: integer
      'CanChangeOnline ':
        type: boolean
      IsGovSupportEWV:
        type: boolean
      IsEngineeringJob:
        type: boolean
      IsHomeJob:
        type: boolean
      IsMedicalJob:
        type: boolean
      IsAccountantJob:
        type: boolean
      IsValidForIstiqdam1_5:
        type: boolean
      NICCode:
        type: integer
      NICOldCode:
        type: integer
      IsAllowedForMonshaatVISA:
        type: boolean
      IsBlockedForSeasonalVisas:
        type: boolean
      JobGroupId:
        type: integer
      IsGenderRequired:
        type: boolean
      SaudizationManagement:
        type: boolean
      SaudizationActionType:
        type: integer
      SaudizationPercentage:
        type: integer
      MinimumWage:
        type: integer
      CreatedOn:
        type: string
      ModifiedOn:
        type: string
      GroupList:
        $ref: '#/definitions/GroupList_Type'
      Category:
        $ref: '#/definitions/CodeName_Type'
      ChangeOccupation:
        $ref: '#/definitions/CodeName_Type'
  GroupList_Type:
    type: object
    properties:
      Group:
        type: array
        items:
          $ref: '#/definitions/CodeName_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GOL00001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GCD00001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getoccupationslist:
    post:
      operationId: 'GetOccupationsList '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetOccupationsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'GetOccupationsList '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetOccupationsListRq_MessageType'
        description: 'GetOccupationsList '
        required: true
