swagger: "2.0"
info:
  title: GetPaymentswithoutUserSubscriptions
  x-ibm-name: getpaymentswithoutusersubscriptions
  version: 1.0.0
  description: This service is used to get all the payments that does not have successful
    subscription.
schemes:
- https
basePath: /usermanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-usrm-calcandgetwithoutsub)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetPaymentswithoutUserSubscriptionsRq_MessageType:
    type: object
    properties:
      GetPaymentswithoutUserSubscriptionsRq:
        $ref: '#/definitions/GetPaymentswithoutUserSubscriptionsRq_Type'
  GetPaymentswithoutUserSubscriptionsRs_MessageType:
    type: object
    properties:
      GetPaymentswithoutUserSubscriptionsRs:
        $ref: '#/definitions/GetPaymentswithoutUserSubscriptionsRs_Type'
  GetPaymentswithoutUserSubscriptionsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetPaymentswithoutUserSubscriptionsRq_BodyType'
  GetPaymentswithoutUserSubscriptionsRq_BodyType:
    type: object
    properties:
      StartDate:
        type: string
        default: "2020-06-10"
      EndDate:
        type: string
        default: "2020-07-10"
      PageSize:
        type: integer
        default: "10"
      PageIndex:
        type: integer
        default: "100"
    required:
    - StartDate
    - EndDate
    - PageSize
    - PageIndex
  GetPaymentswithoutUserSubscriptionsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetPaymentswithoutUserSubscriptionsRs_BodyType'
  GetPaymentswithoutUserSubscriptionsRs_BodyType:
    type: object
    properties:
      List:
        $ref: '#/definitions/List_Type'
    required:
    - List
  List_Type:
    type: object
    properties:
      ListItem:
        type: array
        items:
          $ref: '#/definitions/ListItem'
    required:
    - ListItem
  ListItem:
    type: object
    properties:
      PaymentReference:
        type: string
      PaymentId:
        type: string
      IdNumber:
        type: string
      InsertDate:
        type: string
    required:
    - PaymentReference
    - IdNumber
    - InsertDate
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GPWUS001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GPWUS001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23432"
      IDNumber:
        type: integer
        default: "324324"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getpaymentswithoutusersubscriptions:
    post:
      operationId: GetPaymentswithoutUserSubscriptions
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetPaymentswithoutUserSubscriptionsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Payments without User Subscriptions
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetPaymentswithoutUserSubscriptionsRq_MessageType'
        description: GetPaymentswithoutUserSubscriptionsRq
        required: true
