swagger: "2.0"
info:
  title: 'GetQWalletTransactionsList '
  x-ibm-name: getqwallettransactionslist
  version: 1.0.0
  description: 'GetQWalletTransactionsList '
schemes:
- https
basePath: /qwallet/rb
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-qw-q-walletutilities)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  GetQWalletTransactionsListRq_MessageType:
    type: object
    properties:
      GetQWalletTransactionsListRq:
        $ref: '#/definitions/GetQWalletTransactionsListRq_Type'
  GetQWalletTransactionsListRs_MessageType:
    type: object
    properties:
      GetQWalletTransactionsListRs:
        $ref: '#/definitions/GetQWalletTransactionsListRs_Type'
  GetQWalletTransactionsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetQWalletTransactionsListRq_BodyType'
  GetQWalletTransactionsListRq_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      QWalletId:
        type: string
      TransactionID:
        type: integer
      CreationDate_From:
        type: string
        pattern: ^(20)\d{2}[-]\d{2}[-]\d{2}\s\d{2}[:]\d{2}[:]\d{2}(AM|PM)?$
      CreationDate_To:
        type: string
        pattern: ^(20)\d{2}[-]\d{2}[-]\d{2}\s\d{2}[:]\d{2}[:]\d{2}(AM|PM)?$
      TransactionAmount_From:
        type: number
      TransactionAmount_To:
        type: number
      TransactionTypeCode:
        type: integer
      OperationTypeCode:
        type: integer
      TransactionDescription:
        type: string
      PageIndex:
        type: integer
      PageSize:
        type: integer
    required:
    - EstablishmentDetails
    - QWalletId
    - PageIndex
    - PageSize
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
  GetQWalletTransactionsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetQWalletTransactionsListRs_BodyType'
  GetQWalletTransactionsListRs_BodyType:
    type: object
    properties:
      QWalletTransactionsList:
        $ref: '#/definitions/QWalletTransactionsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  QWalletTransactionsList_Type:
    type: object
    properties:
      QWalletTransactionsItem:
        type: array
        items:
          $ref: '#/definitions/QWalletTransactionsItem_Type'
    required:
    - QWalletTransactionsItem
  QWalletTransactionsItem_Type:
    type: object
    properties:
      TransactionID:
        type: string
        example: "6"
      QWalletId:
        type: string
        example: "1"
      SourceAccountNumber:
        type: string
        example: "123456789"
      DestinationAccountNumber:
        type: string
        example: "123456789"
      VIBAN:
        type: string
        example: ""
      TransactionAmount:
        type: number
        example: "4500.00"
      TransactionStatus:
        type: object
        properties:
          Code:
            type: integer
            example: 1
          DescriptionEN:
            type: string
            example: Pending Approval
          DescriptionAR:
            type: string
            example: بانتظار الموافقة
      TransactionType:
        type: object
        properties:
          Code:
            type: integer
            example: 1
          DescriptionEN:
            type: string
            example: Debit
          DescriptionAR:
            type: string
            example: سحب
      OperationType:
        type: object
        properties:
          Code:
            type: integer
            example: 1
          DescriptionEN:
            type: string
            example: Wallet Charge Out
          DescriptionAR:
            type: string
            example: سحب رصيد
      TransactionDescription:
        type: string
        example: Description
      CreationDate:
        type: string
        example: 11/10/2022 4:07:15 PM
        pattern: ^^(20)\d{2}[-]\d{2}[-]\d{2}\s\d{2}[:]\d{2}[:]\d{2}(AM|PM)?$
      CreatedBy:
        type: string
        example: "1"
      BalanceAfterTransaction:
        type: number
        example: "4500.00"
    required:
    - TransactionID
    - QWalletId
    - VIBAN
    - TransactionAmount
    - TransactionStatus
    - TransactionType
    - OperationType
    - TransactionDescription
    - CreationDate
    - CreatedBy
    - BalanceAfterTransaction
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getqwallettransactionslist:
    post:
      operationId: 'GetQWalletTransactionsList '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetQWalletTransactionsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get the details and balance of an establishment e-wallet
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetQWalletTransactionsListRq_MessageType'
        description: 'GetQWalletTransactionsList '
        required: true
