swagger: "2.0"
info:
  title: GetResendContractsList
  x-ibm-name: getresendcontractslist
  version: 1.0.0
  description: GetResendContractsList
schemes:
- https
basePath: /contractmanagement
security:
- Oauth2.0:
  - IntegrationScope
  clientId: []
securityDefinitions:
  Oauth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntm-getscontract)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  GetResendContractsListRq_MessageType:
    type: object
    properties:
      GetResendContractsListRq:
        $ref: '#/definitions/GetResendContractsListRq_Type'
  GetResendContractsListRs_MessageType:
    type: object
    properties:
      GetResendContractsListRs:
        $ref: '#/definitions/GetResendContractsListRs_Type'
  GetResendContractsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetResendContractsListRq_BodyType'
  GetResendContractsListRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      LaborerIdNo:
        type: integer
      SortByCreationDate:
        type: integer
        enum:
        - 0
        - 1
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - PageSize
    - PageIndex
  GetResendContractsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetResendContractsListRs_BodyType'
  GetResendContractsListRs_BodyType:
    type: object
    properties:
      ContractsList:
        $ref: '#/definitions/ContractsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - ContractsList
    - TotalRecordsCount
  ContractsList_Type:
    type: object
    properties:
      Contract:
        type: array
        items:
          $ref: '#/definitions/Contract_Type'
    required:
    - Contract
  Contract_Type:
    type: object
    properties:
      ContractId:
        type: integer
      LaborerId:
        type: integer
      LaborerName:
        type: string
      ContractStartDate:
        $ref: '#/definitions/Tmstmp_Type'
      ContractPeriod:
        type: integer
      OccupationEn:
        type: string
      OccupationAr:
        type: string
      JobTitleEn:
        type: string
      JobTitleAr:
        type: string
      Salary:
        type: number
      SalaryFrequencyEn:
        type: string
      SalaryFrequencyAr:
        type: string
      CreationDate:
        $ref: '#/definitions/Tmstmp_Type'
    required:
    - ContractId
    - LaborerId
    - LaborerName
    - ContractStartDate
    - ContractPeriod
    - OccupationEn
    - OccupationAr
    - JobTitleEn
    - JobTitleAr
    - Salary
    - SalaryFrequencyEn
    - SalaryFrequencyAr
    - CreationDate
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  HGDate_Type:
    type: object
    properties:
      Hijri:
        type: integer
      Greogrian:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getresendcontlist:
    post:
      operationId: 'GetResendContractsList '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetResendContractsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'GetResendContractsList '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetResendContractsListRq_MessageType'
        description: GetResendContractsList
        required: true
