swagger: "2.0"
info:
  title: GetSadadNumbers
  x-ibm-name: getsadadnumbers
  version: 1.0.0
  description: This service is used to get Sadad numbers.
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdwp)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetSadadNumbersRq_MessageType:
    type: object
    properties:
      GetSadadNumbersRq:
        $ref: '#/definitions/GetSadadNumbersRq_Type'
  GetSadadNumbersRs_MessageType:
    type: object
    properties:
      GetSadadNumbersRs:
        $ref: '#/definitions/GetSadadNumbersRs_Type'
  GetSadadNumbersRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetSadadNumbersRq_BodyType'
  GetSadadNumbersRq_BodyType:
    type: object
    properties:
      ListOfIds:
        $ref: '#/definitions/ListOfIds_Type'
    required:
    - ListOfIds
  ListOfIds_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/Item_Type'
    required:
    - Item
  Item_Type:
    type: object
    properties:
      IdNo:
        type: integer
        default: "2344778655"
    required:
    - IdNo
  GetSadadNumbersRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetSadadNumbersRs_BodyType'
  GetSadadNumbersRs_BodyType:
    type: object
    properties:
      SadadList:
        $ref: '#/definitions/SadadList_Type'
  SadadList_Type:
    type: object
    properties:
      SadadItem:
        type: array
        items:
          $ref: '#/definitions/SadadItem_Type'
    required:
    - SadadItem
  SadadItem_Type:
    type: object
    properties:
      IdNo:
        type: integer
      SadadNo:
        type: integer
    required:
    - IdNo
    - SadadNo
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GSN00001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GSN00001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getsadadnumbers:
    post:
      operationId: GetSadadNumbers
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetSadadNumbersRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service is used to check the validity of a specific service
        at a specific location (area) , with the ability of check nationality, occupation,
        and economic activity.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetSadadNumbersRq_MessageType'
        description: GetSadadNumbersRq
        required: true
