swagger: "2.0"
info:
  title: 'GetTierInvoiceDetails '
  x-ibm-name: gettierinvoicedetails
  version: 1.0.0
  description: This service is used to get tier invoice details after successful payment
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-uim-unifiedinvoices)/invoicesmanagement/gettierinvoicedetails
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetTierInvoiceDetailsRq_MessageType:
    type: object
    properties:
      GetTierInvoiceDetailsRq:
        $ref: '#/definitions/GetTierInvoiceDetailsRq_Type'
  GetTierInvoiceDetailsRs_MessageType:
    type: object
    properties:
      GetTierInvoiceDetailsRs:
        $ref: '#/definitions/GetTierInvoiceDetailsRs_Type'
  GetTierInvoiceDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetTierInvoiceDetailsRq_BodyType'
  GetTierInvoiceDetailsRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      InvoiceId:
        type: string
      InvoiceType:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - InvoiceId
    - InvoiceType
  GetTierInvoiceDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetTierInvoiceDetailsRs_BodyType'
  GetTierInvoiceDetailsRs_BodyType:
    type: object
    properties:
      InvoiceId:
        type: integer
      BuyerDetails:
        $ref: '#/definitions/BuyerDetails_Type'
      SellerDetails:
        $ref: '#/definitions/SellerDetails_Type'
      DateOfSupply:
        type: string
      InvoiceIssueDate:
        type: string
      PaymentDetails:
        $ref: '#/definitions/PaymentDetails_Type'
    required:
    - InvoiceId
    - BuyerDetails
    - SellerDetails
    - DateOfSupply
    - InvoiceIssueDate
    - PaymentDetails
  BuyerDetails_Type:
    type: object
    properties:
      EstablishmentName:
        type: string
      BuildingNo:
        type: integer
      StreetName:
        type: integer
      District:
        type: string
      City:
        type: string
      Country:
        type: string
      AdditionalNo:
        type: integer
      VATRegistrationNumber:
        type: string
      OtheBuyerId:
        type: integer
    required:
    - EstablishmentName
    - BuildingNo
    - StreetName
    - District
    - City
    - Country
    - AdditionalNo
    - VATRegistrationNumber
    - OtheBuyerId
  SellerDetails_Type:
    type: object
    properties:
      EstablishmentName:
        type: string
      BuildingNo:
        type: integer
      StreetName:
        type: integer
      District:
        type: string
      City:
        type: string
      Country:
        type: string
      AdditionalNo:
        type: integer
      VATRegistrationNumber:
        type: string
      OtherSellerId:
        type: integer
    required:
    - EstablishmentName
    - BuildingNo
    - StreetName
    - District
    - City
    - Country
    - AdditionalNo
    - VATRegistrationNumber
    - OtherSellerId
  PaymentDetails_Type:
    type: object
    properties:
      PaymentType:
        type: string
      PaidBy:
        type: integer
      PaymentAmount:
        type: number
      TaxAmount:
        type: number
      TaxRate:
        type: number
      Discount:
        type: number
      TaxableAmount:
        type: number
      ProductQuantity:
        type: integer
      UnitPrice:
        type: number
      NatureOfGoodsOrServices:
        type: string
      TotalAmoutDue:
        type: number
    required:
    - PaymentType
    - PaidBy
    - PaymentAmount
    - TaxAmount
    - TaxRate
    - Discount
    - TaxableAmount
    - ProductQuantity
    - UnitPrice
    - NatureOfGoodsOrServices
    - TotalAmoutDue
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /gettierinvoicedetails:
    post:
      operationId: 'GetTierInvoiceDetails '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetTierInvoiceDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Tier Invoice Details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetTierInvoiceDetailsRq_MessageType'
        description: GetTierInvoiceDetailsRq
        required: true
