swagger: "2.0"
info:
  title: GetUserInfoNIC
  x-ibm-name: getuserinfonic
  version: 1.0.0
host: $(catalog.host)
schemes:
- https
basePath: /common
security:
- clientID: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-common2)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
paths:
  /getuserinfonic:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    options:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
