swagger: "2.0"
info:
  title: 'GetUnifiedInvoiceDetails '
  x-ibm-name: getunifiedinvoicedetails
  version: 1.0.0
  description: 'GetUnifiedInvoiceDetails '
schemes:
- https
basePath: /invoicesmanagement
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://gw-apic.qiwa.info/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(java-invoices-qiwa-info)/api/v1/unified-invoices/details
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetUnifiedInvoiceDetailsRq_MessageType:
    type: object
    properties:
      GetUnifiedInvoiceDetailsRq:
        $ref: '#/definitions/GetUnifiedInvoiceDetailsRq_Type'
  GetUnifiedInvoiceDetailsRs_MessageType:
    type: object
    properties:
      GetNitaqComplianceWeightRs:
        $ref: '#/definitions/GetUnifiedInvoiceDetailsRs_Type'
  GetUnifiedInvoiceDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetUnifiedInvoiceDetailsRq_BodyType'
  GetUnifiedInvoiceDetailsRq_BodyType:
    type: object
    properties:
      UnifiedNumber:
        type: integer
      InvoiceId:
        type: string
      OwnerIdNumber:
        type: integer
      Lang:
        type: string
    required:
    - InvoiceId
  GetUnifiedInvoiceDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetUnifiedInvoiceDetailsRs_BodyType'
  GetUnifiedInvoiceDetailsRs_BodyType:
    type: object
    properties:
      TemplateKey:
        type: string
      TemplateName:
        type: string
      TemplateContent:
        type: string
      TemplateContentName:
        type: string
      MessageSubject:
        type: string
      MessageFromEmail:
        type: string
      MessageFromName:
        type: string
      MessageToEmail:
        type: string
      OwnerIdNo:
        type: string
      MessageCC:
        type: string
      MessageBcc:
        type: string
      merge:
        type: boolean
      merge_language:
        type: string
      MessageDetails:
        type: string
      PdfContent:
        type: string
    required:
    - TemplateKey
    - TemplateName
    - TemplateContent
    - TemplateContentName
    - MessageSubject
    - MessageFromEmail
    - MessageFromName
    - MessageToEmail
    - OwnerIdNo
    - MessageCC
    - MessageBcc
    - merge
    - merge_language
    - MessageDetails
    - PdfContent
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /GetUnifiedInvoiceDetails:
    post:
      operationId: 'GetUnifiedInvoiceDetails '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetUnifiedInvoiceDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'GetUnifiedInvoiceDetails '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetUnifiedInvoiceDetailsRq_MessageType'
        description: 'GetUnifiedInvoiceDetails '
        required: true
