swagger: "2.0"
info:
  title: GetUnassignedAgentRequests
  x-ibm-name: getunassignedagentrequests
  version: 1.0.0
  description: GetUnassignedAgentRequests
schemes:
- https
basePath: /qiwalo
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-lbro-lo-change-activity)/qiwalo/getunassignedagentrequests
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetUnassignedAgentRequestsRq_MessageType:
    type: object
    properties:
      GetUnassignedAgentRequestsRq:
        $ref: '#/definitions/GetUnassignedAgentRequestsRq_Type'
  GetUnassignedAgentRequestsRs_MessageType:
    type: object
    properties:
      GetUnassignedAgentRequestsRs:
        $ref: '#/definitions/GetUnassignedAgentRequestsRs_Type'
  GetUnassignedAgentRequestsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetUnassignedAgentRequestsRq_BodyType'
  GetUnassignedAgentRequestsRq_BodyType:
    type: object
    properties:
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - PageSize
    - PageIndex
  GetUnassignedAgentRequestsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetUnassignedAgentRequestsRs_BodyType'
  GetUnassignedAgentRequestsRs_BodyType:
    type: object
    properties:
      AgentsList:
        $ref: '#/definitions/AgentsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  AgentsItem_Type:
    type: object
    properties:
      LOAgentId:
        type: string
      LOAgentName:
        type: string
  AgentsList_Type:
    type: object
    properties:
      AgentsList:
        $ref: '#/definitions/AgentsItem_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getunassignedagentrequests:
    post:
      operationId: GetUnassignedAgentRequests
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetUnassignedAgentRequestsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetUnassignedAgentRequests
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetUnassignedAgentRequestsRq_MessageType'
        description: GetUnassignedAgentRequestsRq
        required: true
