swagger: "2.0"
info:
  title: GetWorkPermitRequestDetails
  x-ibm-name: getworkpermitrequestdetails
  version: 1.0.0
  description: This service will retreive WP details
schemes:
- https
basePath: /workpermit
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wp-workpermit)/workpermit/getworkpermitrequestdetails
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  GetWorkPermitRequestDetailsRq_MessageType:
    type: object
    properties:
      GetWorkPermitRequestDetailsRq:
        $ref: '#/definitions/GetWorkPermitRequestDetailsRq_Type'
  GetWorkPermitRequestDetailsRs_MessageType:
    type: object
    properties:
      GetWorkPermitRequestDetailsRs:
        $ref: '#/definitions/GetWorkPermitRequestDetailsRs_Type'
  GetWorkPermitRequestDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitRequestDetailsRq_BodyType'
  GetWorkPermitRequestDetailsRq_BodyType:
    type: object
    properties:
      BillNumber:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
    required:
    - BillNumber
    - LaborOfficeId
    - SequenceNumber
  GetWorkPermitRequestDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitRequestDetailsRs_BodyType'
  GetWorkPermitRequestDetailsRs_BodyType:
    type: object
    properties:
      GetWorkPermitRequestsDetails:
        $ref: '#/definitions/GetWorkPermitRequestsDetails_Type'
      TotalCount:
        type: integer
    required:
    - GetWorkPermitRequestsDetails
    - TotalCount
  GetWorkPermitRequestsDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      IqamaBorderId:
        type: integer
      FullName:
        type: string
      WpPeriod:
        type: integer
      WpNumber:
        type: integer
      Status:
        type: string
      StatusId:
        type: integer
      EstablishmentName:
        type: string
      BillNumber:
        type: integer
      BillStatus:
        type: string
      SubmissionDate:
        type: string
      TransactionFees:
        type: integer
      RemainingDays:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - IqamaBorderId
    - FullName
    - WpPeriod
    - WpNumber
    - Status
    - StatusId
    - EstablishmentName
    - BillNumber
    - BillStatus
    - SubmissionDate
    - TransactionFees
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getworkpermitrequestdetails:
    post:
      operationId: getworkpermitrequestdetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetWorkPermitRequestDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Change Sponsor Establishments List
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetWorkPermitRequestDetailsRq_MessageType'
        description: GetWorkPermitRequestDetailsRq
        required: true
