swagger: "2.0"
info:
  title: GetWPInvoiceData
  x-ibm-name: getwpinvoicedata
  version: 1.0.0
  description: GetWPInvoiceData
schemes:
- https
basePath: /workpermit
security:
- Oauth2.0:
  - IntegrationScope
  clientId: []
securityDefinitions:
  Oauth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wp-wpcommon2)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetWPInvoiceDataRq_MessageType:
    type: object
    properties:
      GetWPInvoiceDataRq:
        $ref: '#/definitions/GetWPInvoiceDataRq_Type'
  GetWPInvoiceDataRs_MessageType:
    type: object
    properties:
      GetWPInvoiceDataRs:
        $ref: '#/definitions/GetWPInvoiceDataRs_Type'
  GetWPInvoiceDataRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetWPInvoiceDataRq_BodyType'
  GetWPInvoiceDataRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      SadadNumber:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - SadadNumber
  GetWPInvoiceDataRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetWPInvoiceDataRs_BodyType'
  GetWPInvoiceDataRs_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/Establishment_Type'
      InvoiceDetails:
        $ref: '#/definitions/Invoice_Type'
    required:
    - EstablishmentDetails
    - InvoiceDetails
  Establishment_Type:
    type: object
    properties:
      EstablishmentName:
        type: string
      City:
        $ref: '#/definitions/Name_Type'
      DistrictArea:
        $ref: '#/definitions/Name_Type'
      StreetName:
        $ref: '#/definitions/Name_Type'
      PostalCode:
        type: integer
    required:
    - EstablishmentName
    - City
    - DistrictArea
    - StreetName
    - PostalCode
  Invoice_Type:
    type: object
    properties:
      InvoiceNumber:
        type: integer
      SadadNumber:
        type: integer
      IssueDate:
        type: string
      TotalFees:
        type: integer
      PaymentStatus:
        $ref: '#/definitions/Name_Type'
      PaymentDate:
        type: string
      PaymentMethod:
        type: string
        enum:
        - CreditCard
        - SADAD
        - Qwallet
      LaborersList:
        $ref: '#/definitions/LaborersList_Type'
    required:
    - InvoiceNumber
    - SadadNumber
    - IssueDate
    - TotalFees
    - PaymentStatus
    - PaymentDate
    - PaymentMethod
    - LaborersList
  LaborersList_Type:
    type: object
    properties:
      Laborers:
        $ref: '#/definitions/Laborers_Type'
    required:
    - Laborers
  Laborers_Type:
    type: object
    properties:
      EmployeeId:
        type: integer
      EmployeeName:
        type: string
      WorkPermitExpiryDate:
        type: string
      WorkPermitValidityPeriod:
        type: integer
      WorkPermitTotalFees:
        type: integer
    required:
    - EmployeeId
    - EmployeeName
    - WorkPermitExpiryDate
    - WorkPermitValidityPeriod
    - WorkPermitTotalFees
  Name_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
    required:
    - NameEn
    - NameAr
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getwpinvoicedata:
    post:
      operationId: GetWPInvoiceData
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetWPInvoiceDataRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Work Permit Invoice Data
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetWPInvoiceDataRq_MessageType'
        description: GetWPInvoiceDataRq
        required: true
