swagger: "2.0"
info:
  title: GOSI Contributor History
  x-ibm-name: gosi-contributor-history
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
produces:
- application/json
consumes:
- application/json
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  ClientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |-
          var apim = require('apim');

          apim.setvariable('message.headers.Authorization','Basic bW9sX3VzcjpNMGxAZzBzaQ==');
          apim.setvariable('message.headers.Content-Type','application/json');
          apim.setvariable('message.headers.Accept','*/*');
          apim.setvariable('message.headers.Accept-Encoding','gzip, deflate, br');


          //apim.setvariable('message.body',apim.getvariable('message.body'));

          apim.output('application/json');
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: $(dp-gosi-contract)/denodo-graphql-service/graphql/GOSI_MOL
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values: []
        inject-proxy-headers: true
        username: mol_usr
        password: M0l@g0si
    catch: []
  properties: {}
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
paths:
  /GOSI_MOL:
    post:
      responses:
        "200":
          description: success
          schema:
            type: object
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        schema:
          type: object
