swagger: "2.0"
info:
  title: HyperpayWebHookCallBack
  x-ibm-name: hyperpaywebhookcallback
  version: 1.0.0
  description: HyperpayWebHookCallBack
schemes:
- https
basePath: /hyperpay
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.3.0
        title: ACE-Invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        websocket-upgrade: false
        graphql-send-type: detect
        target-url: $(dp-qiwadp-qiwahrsdrouter)/takamol/prod/hyperpay/webhooks
    - invoke:
        version: 2.3.0
        title: Java-Invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        websocket-upgrade: false
        graphql-send-type: detect
        target-url: $(dp-qiwadp-saudipayments)/api/v1/callback/hyperpay/webhook
    finally: []
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  application-authentication:
    certificate: false
  buffering: true
definitions:
  HyperpayWebHookCallBackRq_MessageType:
    type: object
    properties:
      HyperpayWebHookCallBackRq:
        $ref: '#/definitions/HyperpayWebHookCallBackRq_Type'
  HyperpayWebHookCallBackRs_MessageType:
    type: object
    properties:
      HyperpayWebHookCallBackRs:
        $ref: '#/definitions/HyperpayWebHookCallBackRs_Type'
  HyperpayWebHookCallBackRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/HyperpayWebHookCallBackRq_BodyType'
  HyperpayWebHookCallBackRq_BodyType:
    type: object
    properties:
      InitializationVector:
        type: string
      AuthenticationTag:
        type: string
      Payload:
        type: string
    required:
    - Payload
    - AuthenticationTag
  HyperpayWebHookCallBackRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/HyperpayWebHookCallBackRs_BodyType'
  HyperpayWebHookCallBackRs_BodyType:
    type: object
    properties:
      Status: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /webhooks:
    post:
      operationId: HyperpayWebHookCallBack
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/HyperpayWebHookCallBackRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: HyperpayWebHookCallBack
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/HyperpayWebHookCallBackRq_MessageType'
        description: HyperpayWebHookCallBackRq
        required: true
