swagger: "2.0"
info:
  title: InsertIndividualUnifiedInvoices
  version: 1.0.0
  description: InsertIndividualUnifiedInvoices
  x-ibm-name: insertindividualunifiedinvoices
schemes:
- https
basePath: /qiwa/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /invoicesmanagement/insertindividualunifiedinvoices:
    post:
      operationId: InsertIndividualUnifiedInvoices
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get the details and balance of an establishment e-wallet
      parameters:
      - $ref: '#/parameters/X-IBM-Client-Id'
      - $ref: '#/parameters/X-IBM-Client-Secret'
      - name: body
        in: body
        schema:
          $ref: '#/definitions/InsertIndividualUnifiedInvoicesRq_MessageType'
        description: InsertIndividualUnifiedInvoices
        required: true
definitions:
  InsertIndividualUnifiedInvoicesRq_MessageType:
    type: object
    properties:
      InsertIndividualUnifiedInvoicesRq:
        $ref: '#/definitions/InsertIndividualUnifiedInvoicesRq_Type'
  InsertIndividualUnifiedInvoicesRs_MessageType:
    type: object
    properties:
      InsertIndividualUnifiedInvoicesRs:
        $ref: '#/definitions/InsertIndividualUnifiedInvoicesRs_Type'
  InsertIndividualUnifiedInvoicesRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/InsertIndividualUnifiedInvoicesRq_BodyType'
  InsertIndividualUnifiedInvoicesRq_BodyType:
    type: object
    properties:
      IdType:
        type: string
      IdNumber:
        type: integer
      BuyerName:
        type: string
      PaymentReference:
        type: string
      PaymentBrand:
        type: string
      IsNotificationNeeded:
        type: integer
      EmailSubject:
        type: string
      Email:
        type: string
      OwnerIdNo:
        type: integer
      DatePaid:
        type: string
      InvoiceTypeId:
        type: integer
      TotalExcludingVat:
        type: number
      TotalTaxable:
        type: number
      TotalVat:
        type: number
      Total:
        type: number
      Discount:
        type: number
      InvoiceAddress:
        $ref: '#/definitions/InvoiceAddressModel'
      InvoiceDetailsList:
        $ref: '#/definitions/InvoiceDetailsListModel'
    required:
    - IdType
    - IdNumber
    - BuyerName
    - PaymentReference
    - PaymentBrand
    - IsNotificationNeeded
    - OwnerIdNo
    - DatePaid
    - InvoiceTypeId
    - TotalExcludingVat
    - TotalTaxable
    - TotalVat
    - Total
    - Discount
    - InvoiceDetailsList
  InvoiceAddressModel:
    type: object
    properties:
      City:
        type: string
      District:
        type: string
      StreetName:
        type: string
      BuildingNumber:
        type: string
      AdditionalNumber:
        type: string
      Country:
        type: string
  InvoiceDetailsListModel:
    type: object
    properties:
      InvoiceDetailsItem:
        type: array
        items:
          $ref: '#/definitions/InvoiceDetailsItemModel'
    required:
    - InvoiceDetailsItem
  InvoiceDetailsItemModel:
    type: object
    properties:
      Quantity:
        type: integer
      UnitPrice:
        type: number
      TaxableAmount:
        type: number
      Discount:
        type: number
      TaxRate:
        type: number
      TaxAmount:
        type: number
      ItemSubtotal:
        type: number
      ServiceDetails:
        type: string
    required:
    - Quantity
    - UnitPrice
    - TaxableAmount
    - Discount
    - TaxRate
    - TaxAmount
    - ItemSubtotal
    - ServiceDetails
  InsertIndividualUnifiedInvoicesRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/InsertIndividualUnifiedInvoicesRs_MessageType'
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
      Location:
        type: string
        description: Id url encoded
  Response204:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ESBXMLResponseHeader_Type'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ESBXMLResponseHeader_Type'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ESBXMLResponseHeader_Type'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ESBXMLResponseHeader_Type'
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-uim-insunifiedinv)/invoicesmanagement/insertindividualunifiedinvoices
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
