swagger: "2.0"
info:
  title: InsertPostgresAutoReport
  x-ibm-name: insertpostgresautoreport
  version: 1.0.0
schemes:
- https
basePath: /reporting
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  properties:
    target-url:
      value: http://icp-proxy.qiwa.info:30230/reporting/insertpostgresautoreport
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  application-authentication:
    certificate: false
paths:
  /insertpostgresautoreport:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
