swagger: "2.0"
info:
  title: IssueEstablishingVisas
  x-ibm-name: issueestablishingvisas
  version: 1.0.0
  description: IssueEstablishingVisas
host: $(catalog.host)
schemes:
- https
basePath: /qiwa/esb
produces:
- application/json
consumes:
- application/json
security:
- ClientID: []
  ClientSecret: []
securityDefinitions:
  ClientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  ClientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://192.168.80.4:30090
      description: The internal IP of 'icp-cluster.qiwa.info'
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-estv-issueandrefund)$(request.path)
        follow-redirects: false
        timeout: 150
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
definitions:
  DebugFlag_Type:
    type: integer
    default: "1"
  ServiceCode_Type:
    type: string
    default: IEV00001
  TransactionId_Type:
    type: string
    default: "6222121543"
  ChannelId_Type:
    type: string
    default: Qiwa
  SessionId_Type:
    type: string
    default: "212"
  RequestTime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  MWRequestTime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  MWResponseime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  IssueEstablishingVisasRq_MessageType:
    type: object
    properties:
      IssueEstablishingVisasRq:
        $ref: '#/definitions/IssueEstablishingVisasRq_Type'
  IssueEstablishingVisasRs_MessageType:
    type: object
    properties:
      IssueEstablishingVisasRs:
        $ref: '#/definitions/IssueEstablishingVisasRs_Type'
  IssueEstablishingVisasRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/IssueEstablishingVisasRq_BodyType'
  IssueEstablishingVisasRq_BodyType:
    type: object
    properties:
      VisaRequestDetailsList:
        $ref: '#/definitions/VisaReqDtlsList_Type'
      LaborOfficeId:
        type: integer
        default: 1234
      EstablishmentSequenceNumber:
        type: integer
        default: 1234
      EstablishmentId:
        type: integer
        default: 1234
    required:
    - LaborOfficeId
    - EstablishmentSequenceNumber
  VisaReqDtlsList_Type:
    type: object
    properties:
      VisaRequestDetails:
        type: array
        items:
          $ref: '#/definitions/VisaReqDtls_Type'
  VisaReqDtls_Type:
    type: object
    properties:
      JobId:
        type: integer
      EmbassyId:
        type: integer
      NationalityId:
        type: integer
      GenderId:
        type: integer
      religionId:
        type: integer
      NumberOfVisas:
        type: integer
  Address_Type:
    type: object
    properties:
      City:
        type: string
      District:
        type: string
      Street:
        type: string
      BuildingNumber:
        type: string
      POBox:
        type: string
      ZIPCode:
        type: string
      Latitude:
        type: integer
      Longitude:
        type: integer
      AddressDescription:
        type: string
  IssueEstablishingVisasRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/IssueEstablishingVisasRs_BodyType'
  IssueEstablishingVisasRs_BodyType:
    type: object
    properties:
      RequestNumber:
        type: string
      RequestID:
        type: string
      IssueVisaBordersDetailsList:
        $ref: '#/definitions/IssueVisaBordersDetailsList_Type'
  IssueVisaBordersDetailsList_Type:
    type: object
    properties:
      IssueVisaBordersDetails:
        type: array
        items:
          $ref: '#/definitions/IssueVisaBordersDetails_Type'
  IssueVisaBordersDetails_Type:
    type: object
    properties:
      JobId:
        type: integer
      EmbassyId:
        type: integer
      NationalityId:
        type: integer
      GenderId:
        type: integer
      ReligionId:
        type: integer
      BorderNumber:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        $ref: '#/definitions/TransactionId_Type'
      ChannelId:
        $ref: '#/definitions/ChannelId_Type'
      SessionId:
        $ref: '#/definitions/SessionId_Type'
      RequestTime:
        $ref: '#/definitions/RequestTime_Type'
      MWRequestTime:
        $ref: '#/definitions/MWRequestTime_Type'
      ServiceCode:
        $ref: '#/definitions/ServiceCode_Type'
      DebugFlag:
        $ref: '#/definitions/DebugFlag_Type'
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        $ref: '#/definitions/TransactionId_Type'
      ChannelId:
        $ref: '#/definitions/ChannelId_Type'
      SessionId:
        $ref: '#/definitions/SessionId_Type'
      RequestTime:
        $ref: '#/definitions/RequestTime_Type'
      MWRequestTime:
        $ref: '#/definitions/MWRequestTime_Type'
      MWResponseime:
        $ref: '#/definitions/MWResponseime_Type'
      ServiceCode:
        $ref: '#/definitions/ServiceCode_Type'
      DebugFlag:
        $ref: '#/definitions/DebugFlag_Type'
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /issueestablishingvisas:
    post:
      operationId: IssueEstablishingVisas
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/IssueEstablishingVisasRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Issue Establishing Visas
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/IssueEstablishingVisasRq_MessageType'
        description: IssueEstablishingVisasRq
        required: true
