swagger: "2.0"
info:
  title: IstiqdamGetPackages
  x-ibm-name: istiqdamgetpackages
  version: 1.0.0
  description: This is a wrapper API used to get  the packages.
x-ibm-configuration:
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: SetHttpHeaders
        source: "var apim = require('apim');\r\nvar clientId = apim.getvariable('client.app.name');\r\nvar
          apiKey = apim.getvariable('message.headers.API-KEY');\r\n\r\napim.setvariable('message.headers.API-KEY',apiKey);\r\napim.setvariable('message.headers.client-id',clientId);"
    - invoke:
        version: 2.2.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        http-version: HTTP/1.1
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        graphql-send-type: detect
        websocket-upgrade: false
        target-url: $(dp-qiwadp-qiwahrsdrouter)/api/protected/istiqdam/packages?size=$(request.parameters.size)&page=$(request.parameters.page)&sort=$(request.parameters.sort)&filter=$(request.parameters.filter)
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\r\nvar cfg={\r\n    \"serviceCode\" :
          \"GPSMI001\",\r\n    \"channelId\" : \"Qiwa\",\r\n    \"requestName\" :
          \"IsteqdamGetPackagesRq\",\r\n    \"responseName\": \"IsteqdamGetPackagesRs\",\r\n
          \   \"errorMap\" :{\r\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid
          Request\"}\r\n    }\r\n    \r\n};\r\nvar DPResponse = apim.getvariable('message.body');\r\napim.setvariable('DPResponse',DPResponse);\r\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare-Request
        source: "var apim = require('apim');\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\nvar appname
          = apim.getvariable('client.app.name');\r\napim.setvariable('TransactionID1',millisecondsvalue);\r\nvar
          appcReq = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode,\r\n            \"DebugFlag\":
          \"1\",\r\n            \"UserInfo\": {\r\n                \"UserId\": apim.getvariable('message.headers.UserId'),\r\n
          \               \"IDNumber\": apim.getvariable('message.headers.IDNumber')\t\t\t\t\r\n
          \           },\r\n            \"UDF\": {\r\n                \"KeyValueArr\":
          [\r\n                    {\r\n                        \"key\": \"Product\",\r\n
          \                       \"value\": \"TIP-Wrapper\"\r\n                    },\r\n
          \                   {\r\n                        \"key\": \"Client\",\r\n
          \                       \"value\": appname\r\n                    }\r\n
          \               ]\r\n            }\t\t\t\r\n        },\r\n        \"Body\"
          : apim.getvariable('request.body')\r\n            \r\n    }\r\n};\r\n\r\nif
          (typeof OperatorId !== 'undefined')\r\n    appcReq[cfg.requestName].Header.UserInfo
          = {\r\n        \"IDNumber\" : OperatorId\r\n    };\r\napim.setvariable('payload',appcReq);
          \    \r\n//session.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - gatewayscript:
        version: 2.0.0
        title: ReqForLogging
        source: "var apim=require('apim');\r\nvar appconnectrequest = apim.getvariable('payload');\r\nvar
          Body = apim.getvariable('DPResponse');\r\nvar Headers = appconnectrequest.IsteqdamGetPackagesRq.Header;\r\nvar
          transactionId1 = Math.floor(1000000000 + Math.random() * 9000000000);\r\napim.setvariable('message.headers.TransactionID',transactionId1);\r\napim.setvariable('TransactionID',transactionId1);\r\nvar
          SuccessCall =\r\n{\r\n                \"Status\": \"SUCCESS\",\r\n                \"Code\":
          \"00000000\",\r\n                \"ArabicMsg\": \"تمت العملية بنجاح\",\r\n
          \               \"EnglishMsg\": \"Success Call\"\r\n            }\r\n\r\nvar
          APIRes = {\r\n    \"Header\": Headers,\r\n     Body\r\n};\r\nAPIRes.Header.ResponseStatus
          = SuccessCall;\r\nvar jsonData= {\r\n\t\"LogAPIData\": {\r\n\t\t\"IsteqdamGetPackagesRq\":
          appconnectrequest.IsteqdamGetPackagesRq,\r\n\t\t\"IsteqdamGetPackagesRs\":
          APIRes,\r\n\t}\r\n}\r\nsession.output.write(jsonData);\r\napim.output('application/json');"
    - invoke:
        version: 2.2.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        graphql-send-type: detect
        websocket-upgrade: false
        target-url: $(ace-tip-internal)/external/logwrapperapidata
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: "var apim = require('apim');\r\nvar FinalRes = apim.getvariable('DPResponse');\r\nvar
          TransId = apim.getvariable('TransactionID1');\r\n//apim.setvariable('TransactionID1',millisecondsvalue);\r\napim.setvariable('message.headers.TransactionID',TransId);\r\nsession.output.write(FinalRes);\r\napim.output('application/json');"
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /api/v1/external
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /packages:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    parameters:
    - name: size
      required: true
      in: query
      type: integer
    - name: page
      required: true
      in: query
      type: integer
    - name: sort
      required: true
      in: query
      type: string
    - name: filter
      required: false
      in: query
      type: string
schemes:
- https
definitions:
  ResponseModel:
    type: object
    properties:
      total:
        type: number
      pages:
        type: number
      size:
        type: number
      content:
        type: array
        items:
          type: object
          properties:
            id:
              type: number
            duration:
              type: object
              properties:
                value:
                  type: number
                type:
                  type: string
            gender:
              type: object
              properties:
                name:
                  type: object
                  properties:
                    en:
                      type: string
                    ar:
                      type: string
                code:
                  type: number
            nationality:
              type: object
              properties:
                name:
                  type: object
                  properties:
                    en:
                      type: string
                    ar:
                      type: string
                code:
                  type: number
            occupation:
              type: object
              properties:
                name:
                  type: object
                  properties:
                    en:
                      type: string
                    ar:
                      type: string
                code:
                  type: number
            price:
              type: object
              properties:
                gross:
                  type: number
                net:
                  type: number
                vat:
                  type: number
            downPayment:
              type: number
            activationDate:
              type: string
            expiryDate:
              type: string
            link:
              type: string
            creatorType:
              type: string
            createdAt:
              type: string
            updatedAt:
              type: string
    example: '{"total":14,"pages":2,"size":10,"content":[{"id":5798,"duration":{"value":1,"type":"MONTHLY"},"gender":{"name":{"en":"Female","ar":"انثى"},"code":2},"nationality":{"name":{"en":"Ghana","ar":"غانا"},"code":402},"occupation":{"name":{"en":"Special
      Speaking and Hearing Specialist","ar":"اخصائي نطق و سمع خاص"},"code":6411221},"price":{"gross":1.15,"net":1,"vat":0.15},"downPayment":0,"activationDate":"2025-02-10T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-02-10T14:29:50"},{"id":5799,"duration":{"value":1,"type":"MONTHLY"},"gender":{"name":{"en":"Male","ar":"ذكر"},"code":1},"nationality":{"name":{"en":"Kenya","ar":"كيني"},"code":406},"occupation":{"name":{"en":"Special
      Speaking and Hearing Specialist","ar":"اخصائي نطق و سمع خاص"},"code":6411221},"price":{"gross":1,"net":1,"vat":0},"downPayment":0,"activationDate":"2025-02-10T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-02-10T14:32:19"},{"id":5800,"duration":{"value":2,"type":"MONTHLY"},"gender":{"name":{"en":"Female","ar":"انثى"},"code":2},"nationality":{"name":{"en":"Philippines","ar":"فلبيني"},"code":368},"occupation":{"name":{"en":"Cooker","ar":"طباخ
      منزلي"},"code":6411115},"price":{"gross":2.3,"net":2,"vat":0.3},"downPayment":0,"activationDate":"2025-02-10T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-02-10T14:33:34"},{"id":5801,"duration":{"value":3,"type":"MONTHLY"},"gender":{"name":{"en":"Male","ar":"ذكر"},"code":1},"nationality":{"name":{"en":"Ghana","ar":"غانا"},"code":402},"occupation":{"name":{"en":"Physiotherapist","ar":"علاج
      طبيعي خاص"},"code":6411201},"price":{"gross":3.45,"net":3,"vat":0.45},"downPayment":0,"activationDate":"2025-02-10T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-02-10T14:35:01"},{"id":5802,"duration":{"value":4,"type":"MONTHLY"},"gender":{"name":{"en":"Male","ar":"ذكر"},"code":1},"nationality":{"name":{"en":"Ethiopia","ar":"أثيوبي"},"code":414},"occupation":{"name":{"en":"Farm
      worker","ar":"مزارع منزلي"},"code":6411145},"price":{"gross":4.6,"net":4,"vat":0.6},"downPayment":0,"activationDate":"2025-02-10T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-02-10T14:37:21"},{"id":5804,"duration":{"value":6,"type":"MONTHLY"},"gender":{"name":{"en":"Female","ar":"انثى"},"code":2},"nationality":{"name":{"en":"Cambodia","ar":"كمبودي"},"code":371},"occupation":{"name":{"en":"House
      Worker","ar":"عامل منزلي"},"code":6132075},"price":{"gross":1015,"net":1000,"vat":15},"downPayment":0,"activationDate":"2025-02-25T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://c4model.com/","creatorType":"establishment","createdAt":"2025-02-25T09:32:30"},{"id":5807,"duration":{"value":24,"type":"MONTHLY"},"gender":{"name":{"en":"Male","ar":"ذكر"},"code":1},"nationality":{"name":{"en":"Cambodia","ar":"كمبودي"},"code":371},"occupation":{"name":{"en":"Special
      Speaking and Hearing Specialist","ar":"اخصائي نطق و سمع خاص"},"code":6411221},"price":{"gross":1037.5,"net":1000,"vat":37.5},"downPayment":0,"activationDate":"2025-03-03T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-03-03T15:25:13","updatedAt":"2025-04-25T08:58:26"},{"id":5825,"duration":{"value":11,"type":"MONTHLY"},"gender":{"name":{"en":"Male","ar":"ذكر"},"code":1},"nationality":{"name":{"en":"Burundi","ar":"بورندي"},"code":386},"occupation":{"name":{"en":"Farm
      worker","ar":"مزارع منزلي"},"code":6411145},"price":{"gross":10750,"net":10000,"vat":750},"downPayment":5000,"activationDate":"2025-03-26T00:00:00","expiryDate":"2025-06-30T00:00:00","link":"https://musaned.unified-portal.stage.devops.takamol.support/e-services/packages/create","creatorType":"establishment","createdAt":"2025-03-26T06:00:12"},{"id":5848,"duration":{"value":5,"type":"MONTHLY"},"gender":{"name":{"en":"Female","ar":"انثى"},"code":2},"nationality":{"name":{"en":"Ghana","ar":"غانا"},"code":402},"occupation":{"name":{"en":"Physiotherapist","ar":"علاج
      طبيعي خاص"},"code":6411201},"price":{"gross":1269.49,"net":1234.34,"vat":35.15},"downPayment":100.23,"activationDate":"2025-04-09T00:00:00","expiryDate":"2025-09-30T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-04-09T07:03:32"},{"id":5854,"duration":{"value":3,"type":"MONTHLY"},"gender":{"name":{"en":"Male","ar":"ذكر"},"code":1},"nationality":{"name":{"en":"Burundi","ar":"بورندي"},"code":386},"occupation":{"name":{"en":"Special
      Speaking and Hearing Specialist","ar":"اخصائي نطق و سمع خاص"},"code":6411221},"price":{"gross":11.27,"net":10.12,"vat":1.15},"downPayment":1,"activationDate":"2025-05-05T00:00:00","expiryDate":"2025-09-29T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2025-05-05T11:34:38"}]}'
responses: {}
parameters: {}
tags:
- name: Wrapper
