swagger: "2.0"
info:
  title: IstiqdamGetPackage
  x-ibm-name: istiqdamgetpackage
  version: 1.0.0
  description: This is a wrapper API used to get the package details.
x-ibm-configuration:
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: SetHttpHeaders
        source: "var apim = require('apim');\r\nvar clientId = apim.getvariable('client.app.name');\r\nvar
          apiKey = apim.getvariable('message.headers.API-KEY');\r\n\r\napim.setvariable('message.headers.API-KEY',apiKey);\r\napim.setvariable('message.headers.client-id',clientId);"
    - invoke:
        version: 2.2.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        graphql-send-type: detect
        websocket-upgrade: false
        target-url: $(dp-qiwadp-qiwahrsdrouter)/api/protected/istiqdam/package/$(request.parameters.Id)
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\r\nvar cfg={\r\n    \"serviceCode\" :
          \"ICC00001\",\r\n    \"channelId\" : \"Qiwa\",\r\n    \"requestName\" :
          \"IsteqdamGetPackageRq\",\r\n    \"responseName\": \"IsteqdamGetPackageRs\",\r\n
          \   \"errorMap\" :{\r\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid
          Request\"}\r\n    }\r\n    \r\n};\r\nvar DPResponse = apim.getvariable('message.body');\r\napim.setvariable('DPResponse',DPResponse);\r\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare-Request
        source: "var apim = require('apim');\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\nvar appname
          = apim.getvariable('client.app.name');\r\napim.setvariable('TransactionID1',millisecondsvalue);\r\nvar
          appcReq = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode,\r\n            \"DebugFlag\":
          \"1\",\r\n            \"UserInfo\": {\r\n                \"UserId\": apim.getvariable('message.headers.UserId'),\r\n
          \               \"IDNumber\": apim.getvariable('message.headers.IDNumber')\t\t\t\t\r\n
          \           },\r\n            \"UDF\": {\r\n                \"KeyValueArr\":
          [\r\n                    {\r\n                        \"key\": \"Product\",\r\n
          \                       \"value\": \"TIP-Wrapper\"\r\n                    },\r\n
          \                   {\r\n                        \"key\": \"Client\",\r\n
          \                       \"value\": appname\r\n                    }\r\n
          \               ]\r\n            }\t\t\t\r\n        },\r\n        \"Body\"
          : apim.getvariable('request.body')\r\n            \r\n    }\r\n};\r\n\r\nif
          (typeof OperatorId !== 'undefined')\r\n    appcReq[cfg.requestName].Header.UserInfo
          = {\r\n        \"IDNumber\" : OperatorId\r\n    };\r\napim.setvariable('payload',appcReq);
          \    \r\n//session.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - gatewayscript:
        version: 2.0.0
        title: ReqForLogging
        source: "var apim=require('apim');\r\nvar appconnectrequest = apim.getvariable('payload');\r\nvar
          Body = apim.getvariable('DPResponse');\r\nvar Headers = appconnectrequest.IsteqdamGetPackageRq.Header;\r\nvar
          transactionId1 = Math.floor(1000000000 + Math.random() * 9000000000);\r\napim.setvariable('message.headers.TransactionID',transactionId1);\r\napim.setvariable('TransactionID',transactionId1);\r\nvar
          SuccessCall =\r\n{\r\n                \"Status\": \"SUCCESS\",\r\n                \"Code\":
          \"00000000\",\r\n                \"ArabicMsg\": \"تمت العملية بنجاح\",\r\n
          \               \"EnglishMsg\": \"Success Call\"\r\n            }\r\n\r\nvar
          APIRes = {\r\n    \"Header\": Headers,\r\n     Body\r\n};\r\nAPIRes.Header.ResponseStatus
          = SuccessCall;\r\nvar jsonData= {\r\n\t\"LogAPIData\": {\r\n\t\t\"IsteqdamGetPackageRq\":
          appconnectrequest.IsteqdamGetPackageRq,\r\n\t\t\"IsteqdamGetPackageRs\":
          APIRes,\r\n\t}\r\n}\r\nsession.output.write(jsonData);\r\napim.output('application/json');"
    - invoke:
        version: 2.2.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        graphql-send-type: detect
        websocket-upgrade: false
        target-url: $(ace-tip-internal)/external/logwrapperapidata
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: "var apim = require('apim');\r\nvar FinalRes = apim.getvariable('DPResponse');\r\nvar
          TransId = apim.getvariable('TransactionID1');\r\n//apim.setvariable('TransactionID1',millisecondsvalue);\r\napim.setvariable('message.headers.TransactionID',TransId);\r\nsession.output.write(FinalRes);\r\napim.output('application/json');"
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /api/v1/external
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /package/{Id}:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    parameters:
    - name: Id
      required: true
      in: path
      type: integer
schemes:
- https
definitions:
  ResponseModel:
    type: object
    properties:
      id:
        type: number
      duration:
        type: object
        properties:
          value:
            type: number
          type:
            type: string
      gender:
        type: object
        properties:
          name:
            type: object
            properties:
              en:
                type: string
              ar:
                type: string
          code:
            type: number
      nationality:
        type: object
        properties:
          name:
            type: object
            properties:
              en:
                type: string
              ar:
                type: string
          code:
            type: number
      occupation:
        type: object
        properties:
          name:
            type: object
            properties:
              en:
                type: string
              ar:
                type: string
          code:
            type: number
      price:
        type: object
        properties:
          gross:
            type: number
          net:
            type: number
          vat:
            type: number
      downPayment:
        type: number
      activationDate:
        type: string
      expiryDate:
        type: string
      link:
        type: string
      creatorType:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
      specifications:
        type: array
        items:
          type: object
          properties:
            value:
              type: object
              properties:
                en:
                  type: string
                ar:
                  type: string
            position:
              type: number
            createdAt:
              type: string
      payments:
        type: array
        items:
          type: object
          properties:
            value:
              type: number
            position:
              type: number
            createdAt:
              type: string
      priceSpecifications:
        type: array
        items:
          type: object
          properties:
            id:
              type: number
            type:
              type: string
            name:
              type: object
              properties:
                en:
                  type: string
                ar:
                  type: string
            price:
              type: object
              properties:
                gross:
                  type: number
                net:
                  type: number
                vat:
                  type: number
            createdAt:
              type: string
    example: '{"id":5786,"duration":{"value":1,"type":"MONTHLY"},"gender":{"name":{"en":"Female","ar":"انثى"},"code":2},"nationality":{"name":{"en":"Kenya","ar":"كيني"},"code":406},"occupation":{"name":{"en":"Cooker","ar":"طباخ
      منزلي"},"code":6411115},"price":{"gross":111.25,"net":100,"vat":11.25},"downPayment":0,"activationDate":"2024-12-27T00:00:00","expiryDate":"2025-03-31T00:00:00","link":"https://google.com","creatorType":"establishment","createdAt":"2024-12-27T10:54:38","updatedAt":"2025-04-01T00:00:04","specifications":[{"value":{"en":"Special
      specification 1","ar":"مواصفات خاصة 1"},"position":1,"createdAt":"2024-12-27
      10:54:38 +0000"}],"payments":[{"value":111.25,"position":1,"createdAt":"2024-12-27
      10:54:38 +0000"}],"priceSpecifications":[{"id":12463,"type":"laborer_salary","name":{"en":"Labore
      salary","ar":"أجر العامل /العاملة"},"price":{"gross":25,"net":25,"vat":0},"createdAt":"2024-12-27
      10:54:38 +0000"},{"id":12464,"type":"laborer_benefits","name":{"en":"Additional
      benefits for the Labore","ar":"المزايا الإضافية للعامل/للعاملة"},"price":{"gross":28.75,"net":25,"vat":3.75},"createdAt":"2024-12-27
      10:54:38 +0000"},{"id":12465,"type":"paid_expenses","name":{"en":"External recruitment
      costs, government costs and paid expenses","ar":"تكاليف الاستقدام الخارجية والتكاليف
      الحكومية والمصروفات المدفوعة"},"price":{"gross":28.75,"net":25,"vat":3.75},"createdAt":"2024-12-27
      10:54:38 +0000"},{"id":12466,"type":"service_costs","name":{"en":"Service costs","ar":"قيمة
      الخدمة"},"price":{"gross":28.75,"net":25,"vat":3.75},"createdAt":"2024-12-27
      10:54:38 +0000"}]}'
responses: {}
parameters: {}
tags:
- name: Wrapper
