swagger: "2.0"
info:
  title: LORegistrationRequestService
  x-ibm-name: loregistrationrequestservice
  version: 1.0.0
  description: The purpose of this service is to register an establishment as law
    office to serve policies services.
schemes:
- https
basePath: /policies
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-policies)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  LORegistrationRequestServiceRq_MessageType:
    type: object
    properties:
      LORegistrationRequestServiceRq:
        $ref: '#/definitions/LORegistrationRequestServiceRq_Type'
  LORegistrationRequestServiceRs_MessageType:
    type: object
    properties:
      LORegistrationRequestServiceRs:
        $ref: '#/definitions/LORegistrationRequestServiceRs_Type'
  LORegistrationRequestServiceRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/LORegistrationRequestServiceRq_BodyType'
  LORegistrationRequestServiceRq_BodyType:
    type: object
    properties:
      LOSequenceNumber:
        type: integer
        default: "123147"
      LOLaborOfficeId:
        type: string
        default: "1"
      LawyerDetailsList:
        $ref: '#/definitions/LawyerDetailsList_Type'
      LOCommercialName:
        type: string
        default: test
      LOPhoneNumber:
        type: string
        default: "1775"
      LawOfficeContactDetails:
        $ref: '#/definitions/LawOfficeContactDetails_Type'
      HasValidLawFirmLicense:
        type: integer
        default: "7657571"
      GOSIValidation:
        type: integer
        default: "1876"
      IsActive:
        type: integer
        default: "1"
      LORequestId:
        type: integer
        default: "76781"
      LOCity:
        type: integer
        default: "10"
    required:
    - LOSequenceNumber
    - LOLaborOfficeId
    - HasValidLawFirmLicense
    - GOSIValidation
  LawyerDetailsList_Type:
    type: object
    properties:
      LawyerDetailsItem:
        type: array
        items:
          $ref: '#/definitions/LawyerDetailsItem_Type'
    required:
    - LawyerDetailsItem
  LawyerDetailsItem_Type:
    type: object
    properties:
      LawyerNationalId:
        type: integer
        default: "1"
      LawyerName:
        type: string
        default: Ahmed
    required:
    - LawyerNationalId
    - LawyerName
  LawOfficeContactDetails_Type:
    type: object
    properties:
      ContactName:
        type: string
        default: testcon
      ContactEmail:
        type: string
        default: abc@c.ovm
      ContactPhoneNumber:
        type: string
    required:
    - ContactName
    - ContactEmail
    - ContactPhoneNumber
  LORegistrationRequestServiceRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/LORegistrationRequestServiceRs_BodyType'
  LORegistrationRequestServiceRs_BodyType:
    type: object
    properties:
      LORequestId:
        type: integer
      IsEligible:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: LORRS001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: LORRS001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /loregreqservice:
    post:
      operationId: LORegistrationRequestService
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/LORegistrationRequestServiceRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Approve Change Occupation Laborer or Employer
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/LORegistrationRequestServiceRq_MessageType'
        description: LORegistrationRequestServiceRq
        required: true
