swagger: "2.0"
info:
  title: MakePayment V2
  x-ibm-name: makepayment-v2
  version: 1.0.0
  description: The service is used to prepare payment.
schemes:
- https
basePath: /payment/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-pay-makeandrefpay)/payment/makepaymentv2
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |
          var apim = require('apim');
          var Response = apim.getvariable('message.body');
          var statusCode = Response.MakePaymentv2Rs.Header.ResponseStatus.Code ;


          if(statusCode == 'E9999998'){
              var code = 408
              apim.setvariable('message.status.code',code,'set');
          }
          else if(statusCode == 'HYPP0031'){
              var code = 201
              apim.setvariable('message.status.code',code,'set');
          }
          else if(statusCode == '00000000'|| 'HYPP0005'){
              var code = 200
              apim.setvariable('message.status.code',code,'set');
          }
          else{
                var code = 409
              apim.setvariable('message.status.code',code,'set');
          }
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: payload
    success-content: payload
  application-authentication:
    certificate: false
  buffering: true
definitions:
  MakePaymentRq_MessageType:
    type: object
    properties:
      MakePaymentRq:
        $ref: '#/definitions/MakePaymentRq_Type'
  MakePaymentRs_MessageType:
    type: object
    properties:
      MakePaymentRs:
        $ref: '#/definitions/MakePaymentRs_Type'
  MakePaymentRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/MakePaymentRq_BodyType'
  MakePaymentRq_BodyType:
    type: object
    properties:
      ApplicationId:
        type: integer
        default: "11"
      ProductId:
        type: integer
        default: "23"
      ProviderId:
        type: integer
        default: "1"
      Description:
        type: string
        default: Pending
      Amount:
        type: string
        default: "99.99"
      Currency:
        type: string
        default: SAR
    required:
    - ApplicationId
    - ProductId
    - ProviderId
    - Description
    - Amount
    - Currency
  MakePaymentRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/MakePaymentRs_BodyType'
  MakePaymentRs_BodyType:
    type: object
    properties:
      PaymentWidgetsFunction:
        type: string
      PaymentReference:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MP000001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MP000001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /makepayment:
    post:
      operationId: MakePayment
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/MakePaymentRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Make Payment
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/MakePaymentRq_MessageType'
        description: MakePaymentRq
        required: true
