swagger: "2.0"
info:
  title: MLSD_GetEstablishmentCurrentData
  x-ibm-name: mlsd-getestablishmentcurrentdata
  version: 1.0.0
  description: This service is used to get current information for a specific establishment
    or all establishment under the same entity.
schemes:
- https
basePath: /common
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdutility)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetEstablishmentCurrentDataMLSDRq_MessageType:
    type: object
    properties:
      GetEstablishmentCurrentDataMLSDRq:
        $ref: '#/definitions/GetEstablishmentCurrentDataMLSDRq_Type'
  GetEstablishmentCurrentDataMLSDRs_MessageType:
    type: object
    properties:
      ValidateVisitVisaRequestRs:
        $ref: '#/definitions/GetEstablishmentCurrentDataMLSDRs_Type'
  GetEstablishmentCurrentDataMLSDRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentCurrentDataMLSDRq_BodyType'
  GetEstablishmentCurrentDataMLSDRq_BodyType:
    type: object
    properties:
      EntityNumber:
        type: string
        default: 9-98497-1201
      LaborOfficeID:
        type: integer
        default: "17"
      SequenceNumber:
        type: integer
        default: "423"
  GetEstablishmentCurrentDataMLSDRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentCurrentDataMLSDRs_BodyType'
  GetEstablishmentCurrentDataMLSDRs_BodyType:
    type: object
    properties:
      EstablishmentsList:
        $ref: '#/definitions/EstablishmentsList_Type'
  EstablishmentsList_Type:
    type: object
    properties:
      EstablishmentsList:
        $ref: '#/definitions/EstablishmentDetails_Type'
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeID:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentColor:
        type: integer
      CurrentLaborersCount:
        type: integer
      CurrentSaudisCount:
        type: integer
      CurrentForeignersCount:
        type: integer
      EstablishmentTribesDisplaced:
        type: integer
      EstablishmentUnusedQuota:
        type: integer
      CLBLaborers:
        type: integer
      EconomicActivityId:
        type: integer
    required:
    - LaborOfficeID
    - SequenceNumber
    - EstablishmentColor
    - CurrentLaborersCount
    - CurrentSaudisCount
    - CurrentForeignersCount
    - EstablishmentTribesDisplaced
    - EstablishmentUnusedQuota
    - CLBLaborers
    - EconomicActivityId
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGECD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGECD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getestablishmentcurrentdatamlsd:
    post:
      operationId: MLSD_GetEstablishmentCurrentData
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentCurrentDataMLSDRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'MLSD Get Establishment Current Data '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEstablishmentCurrentDataMLSDRq_MessageType'
        description: GetEstablishmentCurrentDataMLSDRq
        required: true
