swagger: "2.0"
info:
  title: Monthly Establishment Report
  x-ibm-name: monthly-establishment-report
  version: 1.0.0
  description: Swagger file for Monthly Report for Establishment
  termsOfService: ""
  contact:
    email: asim.bhatti@royalcyber.com
schemes:
- https
basePath: /EstablishmentReport
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: service_config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"EXCAV001\",\n
          \   \"channelId\" : \"Integration\",\n\t\"SessionId\" : \"212\",\n    \"requestName\"
          : \"EstablishmentReportRq\",\n    \"responseName\": \"EstablishmentReportRs\",\n
          \   \"errorMap\" :{\n                              \"ESBSCHEMA\" : {\"code\"
          :400, \"msg\":\"Invalid Request\"}\n                          }\n    \n};\n\n\n\napim.setvariable('cfg',cfg);\napim.output('application/json');"
    - gatewayscript:
        version: 2.0.0
        title: build_headers
        source: "var apim = require('apim');\n\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\nvar dt = new Date();\nvar cfg = apim.getvariable('cfg');\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\n\n\nvar appcReq
          = {\n    [cfg.requestName]:{\n        \"Header\" : {\n            \"TransactionId\"
          : millisecondsvalue,\n            \"ChannelId\": cfg.channelId,\n            \"SessionId\":
          cfg.SessionId, //apim.getvariable('message.headers.X-Request-Id'),\n            \"RequestTime\"
          : formatDate(dt),\n\t\t\t\"MWRequestTime\" : formatDate(dt),\n            \"ServiceCode\":
          cfg.serviceCode\n\t\t\n        },\n        \"Body\" : apim.getvariable('message.body')\n
          \           \n        \n    }\n};\n\nif (typeof OperatorId !== 'undefined')\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\n        \"IDNumber\" :
          OperatorId\n    };\nsession.output.write(appcReq);\napim.output('application/json');\n\n\nfunction
          formatDate(d)\n{\n    //get the month\n    var month = d.getMonth();\n    //get
          the day\n    //convert day to string\n    var day = d.getDate().toString();\n
          \   //get the year\n    var year = d.getFullYear();\n    var hour = d.getHours().toString();\n
          \   var minitue = d.getMinutes().toString();\n    var second = d.getSeconds().toString();\n
          \   var millisecond = d.getMilliseconds().toString();\n    //pull the last
          two digits of the year\n    year = year.toString();\n    \n    //increment
          month by 1 since it is 0 indexed\n    //converts month to a string\n    month
          = (month + 1).toString();\n\n    //if month is 1-9 pad right with a 0 for
          two digits\n    if (month.length === 1)\n        month = \"0\" + month;\n\n
          \   //if day is between 1-9 pad right with a 0 for two digits\n    if (day.length
          === 1)\n        day = \"0\" + day;\n\n    if (hour.length === 1)\n        hour
          = \"0\" + hour;\n\n    if (minitue.length === 1)\n        minitue = \"0\"
          + minitue;\n\n    if (second.length === 1)\n        second = \"0\" + second;\n
          \       \n    if (millisecond.length == 1)\n        millisecond = \"00\"
          + millisecond;\n        \n    if (millisecond.length == 2)\n        millisecond
          = \"0\" + millisecond;\n    \n    \n\n    //return the string \"MMddyy\"\n
          \   return year+\"-\"+month+\"-\"+day+\" \"+hour + \":\" + minitue + \":\"
          + second+\".\"+millisecond;\n}"
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: $(ace-prow-monthlyestreport)/external/GetMonthlyEstablishmentReport
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        stop-on-error:
        - OperationError
        - SOAPError
        - ConnectionError
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: set_headers
        source: |
          var apim = require('apim');

          apim.output('application/json');

          var message = apim.getvariable('message.body');
          var cfg = apim.getvariable('cfg');
          var Header = message[cfg.responseName].Header;
          var TransactionId = Header.TransactionId;
          var ChannelId = Header.ChannelId;
          var RequestTime = Header.RequestTime;
          var SessionId = Header.SessionId;
          var MWRequestTime = Header.MWRequestTime;
          var MWResponseTime = Header.MWResponseTime;
          var status = Header.ResponseStatus.Status;
          var code = Header.ResponseStatus.Code;
          apim.setvariable('message.headers.Transaction-Id',TransactionId,'add');

          apim.setvariable('message.headers.Channel-Id',ChannelId,'add');
          if (RequestTime !== 'undefined')
           apim.setvariable('message.headers.RequestTime',RequestTime,'add');
          if (SessionId !== 'undefined')
           apim.setvariable('message.headers.X-Request-Id',SessionId,'add');
          if (MWRequestTime !== 'undefined')
          apim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');
          if (MWResponseTime !== 'undefined')
          apim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');

          apim.setvariable('message.headers.Response-Status',status,'add');
          apim.setvariable('message.headers.Response-Code',code,'add');
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Code") = "00000000")) or (($header("Response-Code")
            = "00000055"))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\n//var
                cfg = apim.getvariable('cfg'); \n///var body = message[cfg.responseName].Body;\n\n\nsession.output.write(message);\napim.output('application/json');"
        - condition: ($header("Response-Status") = "ERROR") or ($header("Response-Status")
            = "Error")
          execute:
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');     \n\nvar error = {\n  \"errorCode\":
                message[cfg.responseName].Header.ResponseStatus.Code,\n  \"errorMessage\":
                {\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\n
                \ }\n};\n\nvar httperror=0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 400;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nvar
                body = message[cfg.responseName].Header;\nsession.output.write(body);\n//
                session.output.write(error); \napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');     \n\nvar error = {\n  \"errorCode\":
                message['Error'].Code,\n  \"errorMessage\": {\n    \"en-US\": message['Error'].Detail,\n
                \   \"ar-SA\": 'System Error'\n}\n    \n};\n\nvar httperror=0;\nif(cfg.errorMap){\n
                \   if(cfg.errorMap[error.errorCode]){\n       httperror = cfg.errorMap[error.errorCode].code;\n
                \      \n       //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 500;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nvar
                body = message[cfg.responseName].Header;\nsession.output.write(body);
                \n\n//session.output.write(error); \napim.output('application/json');"
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "500"
            type: string
          - set: message.headers.content-type
            value: application/json
            type: string
          - set: message.body
            value: '{     "errorCode": "E000500",     "errorMessage": "Internal server
              error"              }'
            type: string
    finally: []
  properties:
    target-url:
      value: http://prow-monthlyestreport-http-ace.apps.stg.qiwa-nonprod.local/external/GetMonthlyEstablishmentReport
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: payload
    error-content: header
    enabled: true
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
tags:
- name: EstablishmentReport
  description: To get establishment monthy info for reporting purposes
definitions:
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: NPC00001
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  EstablishmentReportRq_MessageType:
    type: object
    properties:
      EstablishmentReportRq:
        $ref: '#/definitions/EstablishmentReportRq_Type'
  EstablishmentReportRs_MessageType:
    type: object
    properties:
      EstablishmentReportRs:
        $ref: '#/definitions/EstablishmentReportRs_Type'
  EstablishmentReportRq_Type:
    type: object
    properties:
      Body:
        $ref: '#/definitions/EstablishmentReportRq_BodyType'
  EstablishmentReportRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/EstablishmentReportRs_BodyType'
  EstablishmentReportRq_BodyType:
    type: object
    required:
    - LabourOfficeId
    - SequenceNumber
    - Month
    - Year
    properties:
      LabourOfficeId:
        type: number
      SequenceNumber:
        type: number
      Month:
        type: string
        example: 1
      Year:
        type: string
        example: 12
  EstablishmentReportRs_BodyType:
    type: object
    required:
    - Company
    - Scores
    - Employees
    - AuthorizationTypes
    - Violations
    - WorkPermits
    - Notifications
    - Notes
    properties:
      Company:
        $ref: '#/definitions/CompanyDef'
      Scores:
        $ref: '#/definitions/ScoresDef'
      Employees:
        $ref: '#/definitions/EmployeesDef'
      AuthorizationTypes:
        $ref: '#/definitions/AuthTypesDef'
      Violations:
        $ref: '#/definitions/ViolationsDef'
      WorkPermits:
        $ref: '#/definitions/WorkPermistDef'
      Notifications:
        $ref: '#/definitions/NotificationsDef'
      Notes:
        $ref: '#/definitions/NotesDef'
  CompanyDef:
    type: object
    properties:
      LaborOfficeId:
        type: string
      SequenceNumber:
        type: string
      Name:
        type: string
      Status:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: active
      NitaqLevel:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Ar:
            type: string
            example: الأحمر
          En:
            type: string
            example: Green
      Size:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: '...'
      Type:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: '...'
      UnifiedNumber:
        type: string
        example: 1223
      MainAddress:
        type: object
        properties:
          Street:
            type: string
            example: Establishment Street
          District:
            type: string
            example: Establishment District
          City:
            type: object
            properties:
              Id:
                type: number
                example: 1
              Name:
                type: string
                example: Establishment City
          ZipCode:
            type: number
            example: 11564
          BuildingNumber:
            type: string
            example: Granada Oasis
  ScoresDef:
    type: object
    properties:
      Primary:
        type: object
        properties:
          Score:
            type: number
            example: 100
          Nitaqat:
            type: number
            example: 100
          WorkPermits:
            type: number
            example: 100
          NotesInWps:
            type: number
            example: 100
          ContractAuthentication:
            type: number
            example: 100
      Secondary:
        type: object
        properties:
          Score:
            type: number
            example: 100
          LaborPolicy:
            type: number
            example: 100
          Deductions:
            type: number
            example: 100
          Ims:
            type: number
            example: 100
  EmployeesDef:
    type: object
    properties:
      Saudis:
        type: number
        example: 100
      Foreigners:
        type: number
        example: 5
      Total:
        type: number
        example: 5
  AuthTypesDef:
    type: object
    properties:
      UnifiedNumberManager:
        type: number
        example: 100
      UnifiedNumberManagerName:
        type: string
        example: 5
      EstablishmentUser:
        type: number
        example: 5
  ViolationsDef:
    type: array
    items:
      type: object
      properties:
        Id:
          type: number
          example: 100
        Description:
          type: string
          example: Violation Description
        Date:
          type: string
          example: "2021-01-01 15:01:01"
        Amount:
          type: number
          example: 1000
        Status:
          type: string
          example: Paid
  WorkPermistDef:
    type: object
    properties:
      HasExpats:
        type: boolean
        example: true
      Valid:
        type: number
        example: 5
      Expired:
        type: number
        example: 1
      WaitingForPayment:
        type: number
        example: 3
  NotificationsDef:
    type: array
    items:
      type: object
      properties:
        En:
          type: string
          example: Current Nitaq is Medium Green
        Ar:
          type: string
          example: نيتاق
  NotesDef:
    type: array
    items:
      $ref: '#/definitions/NotesArrayDef'
  NotesArrayDef:
    properties:
      Text:
        type: string
        example: Note Text
      StartDate:
        type: string
        example: "2022-06-02 17:00:00"
      Type:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: Type Name
      Source:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: Source Name
paths:
  /EstablishmentReport:
    post:
      tags:
      - EstablishmentReport
      summary: Used to get monthly establishment info
      description: ""
      operationId: getEstablishmentReport
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        description: EstablishmentReportRq
        schema:
          $ref: '#/definitions/EstablishmentReportRq_MessageType'
      - name: X-IBM-Client-Id
        in: header
        required: true
        type: string
      - name: X-IBM-Client-Secret
        in: header
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/EstablishmentReportRs_MessageType'
        "405":
          description: Invalid input
