swagger: "2.0"
info:
  title: nafathcallback-v2
  x-ibm-name: nafathcallback-v2
  description: nafathcallback-v2
  version: 2.0.0
host: $(catalog.host)
schemes:
- https
basePath: /Nafath/Callback/v2
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  ClientSecret:
    type: apiKey
    in: header
    x-key-type: client_secret
    name: X-IBM-Client-Secret
  clientID:
    type: apiKey
    in: header
    x-key-type: client_id
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties: {}
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |-
          var apim = require('apim');
          var appcReq = apim.getvariable('message.body');
          apim.setvariable('message.headers.Authorization', 'Bearer eyJraWQiOiIwZjllNWU4NzQzNGVlYTUzMThjZDJhMTRmZTdkMTY5NWU5YzZmZTc2Y2M1MTc2NjMyZGRkZWE5YjlmMzdhM2YyIiwiYWxnIjoiUlMyNTYifQ.eyJleHAiOjIwNTI2MzIzNjEsIm5iZiI6MTY5MjYzMjM2MSwiaXNzIjoiUWl3YSIsImF1ZCI6Iiouc2VsZi5xaXdhIiwiaWF0IjoxNjkyNjMyMzYxLCJqdGkiOiJxaXdhLXNlbGYtMSIsImNsaWVudF9pZCI6InFpd2EiLCJzZXJ2aWNlIjp0cnVlfQ.PCBJdnLY0MvvnURqlcyZg1IJUIDi3GsZj63rFsjFKA3uM26nj7sdYK-NnCLfoErUdRw176UP-mCVQY58ocI7pN0blrsRqpwNjXaQ7-ypqp2AnyYCTCG2OnYcfrxd2DLP4JhEfmc7gOi_bEn1hPvZiXIA2hIHY0MAW93B4J89tJI90AH5SMOr0T2k2BlL0p3ldiZIm5k065J1sGOZHwdCuBCK-Gx_ehOSWaEaNejrd1S6QWUl31-OkN34IHvBiR-ZIEqDw4tNZwgromKYmLMGU1uMdWXUbSXcLh_8ZVl7FV081EVhIf51n7Ajqrs0JopqB_pp3kcnNI_tIB1K-P1uJQ','add');
          apim.output('application/json');
          session.output.write(appcReq);
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        target-url: $(nafathcallback-url)
        follow-redirects: false
        inject-proxy-headers: true
    finally: []
    catch: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    enabled: true
    error-content: payload
    success-content: payload
  buffering: true
definitions:
  CallbackRequest:
    type: object
    additionalProperties: false
    properties:
      id:
        type: integer
      key:
        type: string
  CallbackResponse:
    type: object
    properties:
      success:
        type: string
      reason:
        type: string
paths:
  /status:
    post:
      operationId: postGetReport
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CallbackResponse'
      consumes:
      - application/json
      produces:
      - application/json
      description: Insert a GetReport
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CallbackRequest'
        description: The request body for the operation
        required: true
