swagger: "2.0"
info:
  title: NIC-PersonTitleRecord
  description: This API exposes used to get Person Title Record to be used for required
    NIC services.
  x-ibm-name: nic-persontitlerecord
  version: 1.0.0
schemes:
- https
basePath: /nic/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /persontitlerecord/personID/{personID}/birthDate/{birthDate}:
    parameters:
    - $ref: '#/parameters/X-IBM-Client-Id'
    - $ref: '#/parameters/X-IBM-Client-Secret'
    - $ref: '#/parameters/UserId'
    - $ref: '#/parameters/personID'
    - $ref: '#/parameters/birthDate'
    get:
      tags:
      - Get Person Title Record
      description: Service to get person title record
      operationId: persontitlerecord
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
definitions:
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      titleDescAr:
        type: string
        example: الأمير
      titleDescEn:
        type: string
        example: PRINCE
      titleLongDescAr:
        type: string
        example: صاحب السمو الملكي الأمير
      requestTimestamp:
        type: string
        example: "2022-12-26T12:48:50.8806597+03:00"
      responseTimestamp:
        type: string
        example: "2022-12-26T12:48:51.0499848+03:00"
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  IntegerNumberModel:
    type: object
    description: This object use for integer numbers
    additionalProperties:
      type: integer
      example: 1
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
  UserId:
    in: header
    name: UserId
    description: UserI d
    required: false
    type: integer
  personID:
    in: path
    name: personID
    description: personID
    required: true
    type: integer
  birthDate:
    in: path
    name: birthDate
    description: birthDate
    required: true
    type: integer
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
      Location:
        type: string
        description: Id url encoded
  Response204:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - map:
        inputs:
          personID:
            schema:
              type: integer
            variable: request.parameters.personID
          birthDate:
            schema:
              type: integer
            variable: request.parameters.birthDate
        outputs:
          "":
            schema:
              type: object
              properties:
                personID:
                  type: string
                birthDate:
                  type: number
            variable: message.body
            content: application/json
        actions:
        - set: .personID
          from: personID
        - set: .birthDate
          from: birthDate
        version: 2.0.0
        title: map
        options:
          mapEnablePostProcessingJSON: true
          mapEmulateV4EmptyJSONObject: false
          mapEmulateV4DefaultRequiredProps: false
          mapReferenceLimit: 1
          includeEmptyXMLElements: false
          inlineNamespaces: false
          namespaceInheritance: false
          mapResolveApicVariables: false
          mapOptimizeSchemaDefinition: true
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"PTR00001\",\n
          \   \"channelId\" : \"Integration\",\n    \"requestName\" : \"PersonTitleRecordRq\",\n
          \   \"responseName\": \"PersonTitleRecordRs\",\n    \"errorMap\" :{\n        \"ESBSCHEMA\"
          : {\"code\" :400, \"msg\":\"Invalid Request\"}\n    }\n    \n};\n\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\n\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\n\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode,\r\n            \"UserInfo\":
          {\r\n                \"UserId\": apim.getvariable('message.headers.UserId'),\r\n
          \               \"IDNumber\": apim.getvariable('message.headers.operatorId')\r\n
          \           }\r\n        },\r\n        \"Body\" : apim.getvariable('message.body')\r\n
          \           \r\n        \r\n    }\r\n};\r\n\r\nif (typeof OperatorId !==
          'undefined')\r\n    appcReq[cfg.requestName].Header.UserInfo = {\r\n        \"IDNumber\"
          : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        target-url: $(ace-tip-nic-get)/external/persontitlerecord
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: |-
          var apim = require('apim');

          apim.output('application/json');

          var message = apim.getvariable('message.body');
          var cfg = apim.getvariable('cfg');
          var Header = message[cfg.responseName].Header;
          var TransactionId = Header.TransactionId;
          var ChannelId = Header.ChannelId;
          var RequestTime = Header.RequestTime;
          var SessionId = Header.SessionId;
          var MWRequestTime = Header.MWRequestTime;
          var MWResponseTime = Header.MWResponseTime;
          var status = Header.ResponseStatus.Status;
          apim.setvariable('message.headers.Transaction-Id',TransactionId,'add');
          apim.setvariable('message.headers.Channel-Id',ChannelId,'add');
          if (RequestTime !== 'undefined')
           apim.setvariable('message.headers.RequestTime',RequestTime,'add');
          if (SessionId !== 'undefined')
           apim.setvariable('message.headers.X-Request-Id',SessionId,'add');
          if (MWRequestTime !== 'undefined')
          apim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');
          if (MWResponseTime !== 'undefined')
          apim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');

          apim.setvariable('message.headers.Response-Status',status,'add');
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar body = message[cfg.responseName].Body;\n\n\nsession.output.write(body);\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar error = {\n  \"errorCode\":
                message[cfg.responseName].Header.ResponseStatus.Code,\n  \"errorMessage\":
                {\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\n
                \ }\n};\n\nvar httperror=0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 409;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);\napim.output('application/json');"
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
