swagger: "2.0"
info:
  title: NIC_AuthenticateUserByMobile
  x-ibm-name: nic-authenticateuserbymobile
  version: 1.0.0
  description: This service is used to authenticate the user by the mobile from NIC
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-tip-nic-get)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  AuthenticateUserByMobileNICRq_MessageType:
    type: object
    properties:
      AuthenticateUserByMobileNICRq:
        $ref: '#/definitions/AuthenticateUserByMobileNICRq_Type'
  AuthenticateUserByMobileNICRs_MessageType:
    type: object
    properties:
      AuthenticateUserByMobileNICRs:
        $ref: '#/definitions/AuthenticateUserByMobileNICRs_Type'
  AuthenticateUserByMobileNICRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/AuthenticateUserByMobileNICRq_BodyType'
  AuthenticateUserByMobileNICRq_BodyType:
    type: object
    properties:
      IdNo:
        type: integer
        default: "2088005042"
      SMSCode:
        type: string
        default: "23422"
    required:
    - IdNo
    - SMSCode
  AuthenticateUserByMobileNICRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: NAUBM001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: NAUBM001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /authenticateuserbymobilenic:
    post:
      operationId: AuthenticateUserByMobileNIC
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/AuthenticateUserByMobileNICRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Submit Expansion Visa Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/AuthenticateUserByMobileNICRq_MessageType'
        description: AuthenticateUserByMobileNICRq
        required: true
