swagger: "2.0"
info:
  title: NIC_GetCitizenInformation
  x-ibm-name: nic-getcitizeninformation
  version: 1.0.0
schemes:
- https
basePath: /nic/v1
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - map:
        version: 2.0.0
        title: map
        inputs:
          "":
            schema:
              type: object
              properties:
                CitizenInformationNICRq:
                  type: object
                  name: CitizenInformationNICRq
                  properties:
                    DateOfBirth:
                      type: string
                      name: DateOfBirth
                    IdNo:
                      type: string
                      name: IdNo
                    UserInfo:
                      type: object
                      name: UserInfo
                      properties:
                        UserId:
                          type: string
                          name: UserId
                        IDNumber:
                          type: string
                          name: IDNumber
            variable: request.body
            content: application/json
        outputs:
          "":
            schema:
              type: object
              properties:
                DateOfBirth:
                  type: string
                  name: DateOfBirth
                IdNo:
                  type: string
                  name: IdNo
            variable: message.body
            content: application/json
          Operator-Id:
            schema:
              type: string
            variable: message.headers.Operator-Id
        actions:
        - set: Operator-Id.DateOfBirth
          from: .CitizenInformationNICRq.DateOfBirth
        - set: Operator-Id.IdNo
          from: .CitizenInformationNICRq.IdNo
        - set: $item
          from: .CitizenInformationNICRq.UserInfo.IDNumber
        - set: .DateOfBirth
          from: .CitizenInformationNICRq.DateOfBirth
        - set: .IdNo
          from: .CitizenInformationNICRq.IdNo
        - set: Operator-Id
          from: .CitizenInformationNICRq.UserInfo.IDNumber
        options:
          mapEnablePostProcessingJSON: true
          mapEmulateV4EmptyJSONObject: false
          mapEmulateV4DefaultRequiredProps: false
          mapReferenceLimit: 1
          includeEmptyXMLElements: false
          namespaceInheritance: false
          inlineNamespaces: false
          mapResolveApicVariables: false
          mapOptimizeSchemaDefinition: true
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"NGCI0001\",\n
          \   \"channelId\" : \"Qiwa\",\n    \"requestName\" : \"GetCitizenInformationNICRq\",\n
          \   \"responseName\": \"GetCitizenInformationNICRs\",\n    \"errorMap\"
          :{\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid Request\"}\n
          \   }\n    \n};\n\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\n\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\n\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.Reference-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode\r\n        },\r\n
          \       \"Body\" : apim.getvariable('message.body')\r\n            \r\n
          \       \r\n    }\r\n};\r\n\r\nif (typeof OperatorId !== 'undefined')\r\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\r\n        \"IDNumber\"
          : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-nic-getcitizen)/common/getcitizeninformationnic
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "\tvar apim = require('apim');\n\t\n\tapim.output('application/json');\n\n
          \   \n    \n    var cfg = apim.getvariable('cfg');\n    \n\tvar TransactionId
          = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.TransactionId\");\n\tvar
          ChannelId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ChannelId\");\n\tvar
          RequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.RequestTime\");\n\tvar
          SessionId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.SessionId\");\n\tvar
          MWRequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWRequestTime\");\n\tvar
          MWResponseTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWResponseTime\");\n\tvar
          status = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ResponseStatus.Status\");\n\t\n\n
          \   apim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\n
          \   apim.setvariable('message.headers.Channel-Id',ChannelId,'add');\n    if
          (RequestTime !== 'undefined')\n\t    apim.setvariable('message.headers.RequestTime',RequestTime,'add');\n\tif
          (SessionId !== 'undefined')\n        apim.setvariable('message.headers.Reference-Id',SessionId,'add');\n
          \    if (MWRequestTime !== 'undefined')\n        apim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\n
          \   if (MWResponseTime !== 'undefined')\n        apim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\n\n
          \   \n    apim.setvariable('message.headers.Response-Status',status,'add');\n
          \   "
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar body = {\n    \"CitizenInformationNICRs\"
                : message[cfg.responseName].Body\n}; \n\n\n\n\n\nsession.output.write(body);\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar error = {\n    \"ErrorResponse\":
                message[cfg.responseName].Header.ResponseStatus\n}\n\n\nvar httperror=0;\nif(cfg.errorMap){\n
                \   if(cfg.errorMap[error.ErrorResponse.Code]){\n       httperror
                = cfg.errorMap[error.ErrorResponse.Code].code;\n       \n       //var
                errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n       //var
                details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 400;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);\napim.output('application/json');"
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
paths:
  /get-citizen-info:
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
