swagger: "2.0"
info:
  title: Nitaqat Indicator
  x-ibm-name: nitaqat-indicator-v1
  version: 1.0.0
  description: API to get the nitaqat Indicator information
schemes:
- https
basePath: /indicator
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: /external/GetNitaqatIndicators
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: json
        header-control:
          type: allowlist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-prow-indicators)$(target-url)
        follow-redirects: false
        inject-proxy-headers: true
        cache-response: no-cache
        stop-on-error:
        - ConnectionError
        - OperationError
        - SOAPError
    finally: []
    catch:
    - default: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  NitaqatIndicatorReq:
    type: object
    properties:
      Header:
        $ref: '#/definitions/RequestHeader'
      Body:
        $ref: '#/definitions/NitaqatIndicatorReqBody'
  NitaqatIndicatorRes:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ResponseHeader'
      Body:
        $ref: '#/definitions/NitaqatIndicatorResBody'
  RequestHeader:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: PANID001
      DebugFlag:
        type: string
        default: 1
  ResponseHeader:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: PANID001
      ResponseStatus:
        $ref: '#/definitions/ResponseStatus'
      BackendError:
        $ref: '#/definitions/BackendError'
  ResponseStatus:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendError:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  NitaqatIndicatorReqBody:
    type: object
    properties:
      laborOfficeId:
        type: string
      sequenceNumber:
        type: string
    required:
    - laborOfficeId
    - sequenceNumber
  NitaqatIndicatorResBody:
    type: object
    properties:
      sectorsAverageNationalizationRate:
        type: number
        example: 39.23
      leaderNationalizationRate:
        type: number
        example: 79.45
      currentNitaqatStreak:
        type: number
        example: 50.93
      yearOnYearImprovement:
        type: number
        example: 10.4
paths:
  /getNitaqatIndicator:
    post:
      tags:
      - Get Nitaqat Indicator V1
      description: to Get the nitaqat Indicator information
      operationId: NitaqatIndicator
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/NitaqatIndicatorReq'
        description: Nitaqat Indicator Req
        required: true
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/NitaqatIndicatorRes'
