swagger: "2.0"
info:
  version: 1.0.0
  title: OccupationsByActivity
  x-ibm-name: occupationsbyactivity
basePath: /api/v2/common
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
x-ibm-configuration:
  properties:
    target-url:
      value: http://example.com
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.set('message.headers.X-API-Secret', '54587485154194846354877848');
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(internal-establishment)$(request.path)?$(request.querystring)
        follow-redirects: false
        inject-proxy-headers: true
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /occupation-activity-mapping/occupations-by-activity:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
schemes:
- https
