swagger: "2.0"
info:
  title: OndemandMonthlyReport
  x-ibm-name: ondemand-monthly-report
  version: 1.0.0
  description: Swagger file for OnDemand Monthly Report for Establishment
  termsOfService: ""
  contact:
    email: S.Kolisetty-c@takamol.sa
schemes:
- https
basePath: /EstablishmentReport
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 120
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-prow-monthlyreport-ondemand)/external/ondemand/getmonthlyreport
        follow-redirects: false
        inject-proxy-headers: true
        stop-on-error:
        - OperationError
        - SOAPError
        - ConnectionError
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "500"
            type: string
          - set: message.headers.content-type
            value: application/json
            type: string
          - set: message.body
            value: '{     "errorCode": "E000500",     "errorMessage": "Internal server
              error"              }'
            type: string
    finally: []
  properties:
    target-url:
      value: http://prow-monthlyreport-ondemand-http-ace.apps.stg.qiwa-nonprod.local/external/ondemand/getmonthlyreport
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
tags:
- name: EstablishmentReport
  description: To get establishment monthy info for reporting purposes
definitions:
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: NPC00001
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
  EstablishmentReportRq_MessageType:
    type: object
    properties:
      EstablishmentReportRq:
        $ref: '#/definitions/EstablishmentReportRq_Type'
  EstablishmentReportRs_MessageType:
    type: object
    properties:
      EstablishmentReportRs:
        $ref: '#/definitions/EstablishmentReportRs_Type'
  EstablishmentReportRq_Type:
    type: object
    properties:
      Body:
        $ref: '#/definitions/EstablishmentReportRq_BodyType'
  EstablishmentReportRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/EstablishmentReportRs_BodyType'
  EstablishmentReportRq_BodyType:
    type: object
    properties:
      LabourOfficeId:
        type: number
      SequenceNumber:
        type: number
  EstablishmentReportRs_BodyType:
    type: object
    properties:
      Company:
        $ref: '#/definitions/CompanyDef'
      Scores:
        $ref: '#/definitions/ScoresDef'
      Employees:
        $ref: '#/definitions/EmployeesDef'
      AuthorizationTypes:
        $ref: '#/definitions/AuthTypesDef'
      Violations:
        $ref: '#/definitions/ViolationsDef'
      WorkPermits:
        $ref: '#/definitions/WorkPermistDef'
      Notifications:
        $ref: '#/definitions/NotificationsDef'
      Notes:
        $ref: '#/definitions/NotesDef'
  CompanyDef:
    type: object
    properties:
      LaborOfficeId:
        type: string
      SequenceNumber:
        type: string
      Name:
        type: string
      Status:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: active
      NitaqLevel:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Ar:
            type: string
            example: الأحمر
          En:
            type: string
            example: Green
      Size:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: '...'
      Type:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: '...'
      UnifiedNumber:
        type: string
        example: 1223
      MainAddress:
        type: object
        properties:
          Street:
            type: string
            example: Establishment Street
          District:
            type: string
            example: Establishment District
          City:
            type: object
            properties:
              Id:
                type: number
                example: 1
              Name:
                type: string
                example: Establishment City
          ZipCode:
            type: number
            example: 11564
          BuildingNumber:
            type: string
            example: Granada Oasis
  ScoresDef:
    type: object
    properties:
      Primary:
        type: object
        properties:
          Score:
            type: number
            example: 100
          Nitaqat:
            type: number
            example: 100
          WorkPermits:
            type: number
            example: 100
          NotesInWps:
            type: number
            example: 100
          ContractAuthentication:
            type: number
            example: 100
      Secondary:
        type: object
        properties:
          Score:
            type: number
            example: 100
          LaborPolicy:
            type: number
            example: 100
          Deductions:
            type: number
            example: 100
          Ims:
            type: number
            example: 100
  EmployeesDef:
    type: object
    properties:
      Saudis:
        type: number
        example: 100
      Foreigners:
        type: number
        example: 5
      Total:
        type: number
        example: 5
  AuthTypesDef:
    type: object
    properties:
      UnifiedNumberManager:
        type: number
        example: 100
      UnifiedNumberManagerName:
        type: string
        example: 5
      EstablishmentUser:
        type: number
        example: 5
  ViolationsDef:
    type: array
    items:
      type: object
      properties:
        Id:
          type: number
          example: 100
        Description:
          type: string
          example: Violation Description
        Date:
          type: string
          example: "2021-01-01 15:01:01"
        Amount:
          type: number
          example: 1000
        Status:
          type: string
          example: Paid
  WorkPermistDef:
    type: object
    properties:
      HasExpats:
        type: boolean
        example: true
      Valid:
        type: number
        example: 5
      Expired:
        type: number
        example: 1
      WaitingForPayment:
        type: number
        example: 3
  NotificationsDef:
    type: array
    items:
      type: object
      properties:
        En:
          type: string
          example: Current Nitaq is Medium Green
        Ar:
          type: string
          example: نيتاق
  NotesDef:
    type: array
    items:
      $ref: '#/definitions/NotesArrayDef'
  NotesArrayDef:
    properties:
      Text:
        type: string
        example: Note Text
      StartDate:
        type: string
        example: "2022-06-02 17:00:00"
      Type:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: Type Name
      Source:
        type: object
        properties:
          Id:
            type: number
            example: 1
          Name:
            type: string
            example: Source Name
paths:
  /Ondemand/GetMonthlyReport:
    post:
      tags:
      - EstablishmentReport
      summary: Used to get monthly establishment info
      description: ""
      operationId: getEstablishmentReport
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        description: EstablishmentReportRq
        schema:
          $ref: '#/definitions/EstablishmentReportRq_MessageType'
      - name: X-IBM-Client-Id
        in: header
        required: true
        type: string
      - name: X-IBM-Client-Secret
        in: header
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/EstablishmentReportRs_MessageType'
        "405":
          description: Invalid input
