swagger: "2.0"
info:
  title: OSH_GetPerformanceCardRequestFiltered
  x-ibm-name: osh-getperformancecardrequestfiltered
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientIdHeader:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        target-url: $(oshv2-url)/api/v1/performanceCardRequestFiltered
        follow-redirects: false
        inject-proxy-headers: true
        stop-on-error:
        - OperationError
        - SOAPError
        - ConnectionError
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "500"
            type: string
          - set: message.headers.content-type
            value: application/json
            type: string
          - set: message.body
            value: '{ "errorCode": "500", "errorMessage": "Internal server error"
              }'
            type: string
  properties: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
paths:
  /performanceCardRequestFiltered:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
