swagger: "2.0"
info:
  title: OSH_GetSelfAssessmentTemplateQuestionsAnswersById
  x-ibm-name: osh-getselfassessmenttemplatequestionsanswersbyid
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientIdHeader:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: Set Variables
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"OHS001\",\n
          \   \"channelId\" : \"QOHS001\",\n\t\"SessionId\" : \"1\",\n    \"requestName\"
          : \"GetAllSelfAssessmentTemplateSectionQuestionAnswer\",\n    \"responseName\":
          \"GetAllSelfAssessmentTemplateSectionQuestionAnswer\",\n    \"debugFlag\"
          : \"0\",\n    \"UserInfo\" : \"OSH\",\n    \"errorMap\" :{\n                              \"ESBSCHEMA\"
          : {\"code\" :400, \"msg\":\"Invalid Request\"}\n                          }\n
          \   \n};\n\n\n\napim.setvariable('cfg',cfg);\napim.output('application/json');"
    - gatewayscript:
        version: 2.0.0
        title: Create Header
        source: "var apim = require('apim');\n\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\nvar dt = new Date();\nvar cfg = apim.getvariable('cfg');\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\n\n\nvar appcReq
          = {\n    [cfg.requestName]:{\n        \"Header\" : {\n            \"TransactionId\"
          : millisecondsvalue,\n            \"ChannelId\": cfg.channelId,\n            \"SessionId\":
          cfg.SessionId, //apim.getvariable('message.headers.X-Request-Id'),\n            \"RequestTime\"
          : formatDate(dt),\n\t\t\t\"MWRequestTime\" : formatDate(dt),\n            \"ServiceCode\":
          cfg.serviceCode,\n            \"DebugFlag\": cfg.debugFlag,\n            \"UserInfo\":
          cfg.UserInfo\n\t\t\n        },\n        \"Body\" : apim.getvariable('message.body')\n
          \           \n        \n    }\n};\n\nif (typeof OperatorId !== 'undefined')\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\n        \"IDNumber\" :
          OperatorId\n    };\nsession.output.write(appcReq);\napim.output('application/json');\n\n\nfunction
          formatDate(d)\n{\n    //get the month\n    var month = d.getMonth();\n    //get
          the day\n    //convert day to string\n    var day = d.getDate().toString();\n
          \   //get the year\n    var year = d.getFullYear();\n    var hour = d.getHours().toString();\n
          \   var minitue = d.getMinutes().toString();\n    var second = d.getSeconds().toString();\n
          \   var millisecond = d.getMilliseconds().toString();\n    //pull the last
          two digits of the year\n    year = year.toString();\n    \n    //increment
          month by 1 since it is 0 indexed\n    //converts month to a string\n    month
          = (month + 1).toString();\n\n    //if month is 1-9 pad right with a 0 for
          two digits\n    if (month.length === 1)\n        month = \"0\" + month;\n\n
          \   //if day is between 1-9 pad right with a 0 for two digits\n    if (day.length
          === 1)\n        day = \"0\" + day;\n\n    if (hour.length === 1)\n        hour
          = \"0\" + hour;\n\n    if (minitue.length === 1)\n        minitue = \"0\"
          + minitue;\n\n    if (second.length === 1)\n        second = \"0\" + second;\n
          \       \n    if (millisecond.length == 1)\n        millisecond = \"00\"
          + millisecond;\n        \n    if (millisecond.length == 2)\n        millisecond
          = \"0\" + millisecond;\n    \n    \n\n    //return the string \"MMddyy\"\n
          \   return year+\"-\"+month+\"-\"+day+\" \"+hour + \":\" + minitue + \":\"
          + second+\".\"+millisecond;\n}"
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        target-url: $(oshv2-url)/api/v1/GetSelfAssessmentTemplateQuestionsAnswersById
        follow-redirects: false
        inject-proxy-headers: true
        stop-on-error:
        - OperationError
        - SOAPError
        - ConnectionError
    - gatewayscript:
        version: 2.0.0
        title: Build Headers
        source: "\tvar apim = require('apim');\n\t\n\tapim.output('application/json');\n\n
          \   \n    \n    var cfg = apim.getvariable('cfg');\n   \n   \n    \n\tvar
          TransactionId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.TransactionId\");\n\tvar
          ChannelId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ChannelId\");\n\tvar
          RequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.RequestTime\");\n\tvar
          SessionId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.SessionId\");\n\tvar
          MWRequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWRequestTime\");\n\tvar
          MWResponseTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWResponseTime\");\n\tvar
          status = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ResponseStatus.Status\");\n\t\n\n
          \   apim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\n
          \   apim.setvariable('message.headers.Channel-Id',ChannelId,'add');\n    if
          (RequestTime !== 'undefined')\n\t    apim.setvariable('message.headers.RequestTime',RequestTime,'add');\n\tif
          (SessionId !== 'undefined')\n        apim.setvariable('message.headers.X-Request-Id',SessionId,'add');\n
          \    if (MWRequestTime !== 'undefined')\n        apim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\n
          \   if (MWResponseTime !== 'undefined')\n        apim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\n\n
          \   \n    apim.setvariable('message.headers.Response-Status',status,'add');\n
          \   "
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Success
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg'); \nvar body = message[cfg.responseName].Body;\n\n\nsession.output.write(body);\napim.output('application/json');"
        - condition: ($header("Response-Status") = 'Error' or ($header("Response-Status")
            = 'ERROR'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');     \n\nvar error = {\n  \"errorCode\":
                message[cfg.responseName].Header.ResponseStatus.Code,\n  \"errorMessage\":
                {\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\n
                \   //\"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\n
                \ }\n};\n\nvar httperror=0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \   }\n}\nif(httperror == 0){\n   httperror = 400;\n\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);
                \napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Otherwise
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');     \n\nvar error = {\n  \"errorCode\":
                message['Error'].Code,\n  \"errorMessage\": {\n    \"en-US\": message['Error'].Detail,\n
                \   \"ar-SA\": 'System Error'\n};\n\nvar httperror=0;\nif(cfg.errorMap){\n
                \   if(cfg.errorMap[error.errorCode]){\n       httperror = cfg.errorMap[error.errorCode].code;\n
                \      \n    }\n}\nif(httperror == 0){\n   httperror = 500;\n\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);
                \napim.output('application/json');"
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions: []
  properties: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
paths:
  /GetSelfAssessmentTemplateQuestionsAnswersById:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
