swagger: "2.0"
info:
  title: OTP_SessionAPI
  x-ibm-name: otp_sessionapi
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(otp-apiurl)/session
        follow-redirects: false
        inject-proxy-headers: true
    finally: []
  properties:
    target-url:
      value: https://api.qiwa.info/session
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: payload
    error-content: payload
    preserved-request-header: []
  buffering: true
  categories: []
basePath: /qiwa/v2
paths:
  /session:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    x-key-type: client_id
  ClientSecret:
    type: apiKey
    x-key-type: client_secret
    name: X-IBM-Client-Secret
    in: header
schemes:
- https
security:
- clientID: []
  ClientSecret: []
