swagger: "2.0"
info:
  version: 1.0.0
  title: p2htip_testapi_ratelimit_dynamicvalue2
  x-ibm-name: p2htip_testapi_ratelimit_dynamicvalue2
basePath: /test/ratelimit/dynamicvalue2
x-ibm-configuration:
  properties:
    target-url:
      value: https://tip-v2-auth.stage.tiptech.sa/oauth2/jwks
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: set_subscriptionid
        source: "\r\nvar metadata = context.get('client.app.metadata');\r\nvar plan
          = context.get('plan.name');\r\nvar subid = metadata[plan];\r\n\r\n\r\ncontext.set(\"subscription_id\",
          subid);\r\ncontext.message.header.set('Subscription-ID', subid);\r\n"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: $header('Subscription-ID') != null
          execute:
          - ratelimit:
              version: 2.2.0
              title: ratelimit-consume
              source: plan-named
              rate-limit:
              - name: tip-rate-limit
                operation: consume
          - gatewayscript:
              version: 2.0.0
              title: Build response
              source: "var payload = { \"client.app.id\": context.get('client.app.id'),
                \"subscription_id\": context.get('subscription_id'), \"metadata\":
                context.get('client.app.metadata'),\"plan.name\": context.get('plan.name')};\r\ncontext.message.body.write(payload);\r\ncontext.message.header.set('Content-Type',
                \"application/json\");"
        - otherwise:
          - throw:
              version: 2.1.0
              title: throw
              name: UndefinedSubscription
              error-status-reason: Undefined subscription
              error-status-code: "503"
              message: Please contact Takamol Integration Portal support.
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /:
    get:
      responses:
        "200":
          $ref: '#/responses/Response200'
        "429":
          $ref: '#/responses/Response429'
      produces:
      - application/json
definitions:
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      client.app.id:
        type: string
      subscription_id:
        type: string
responses:
  Response200:
    description: Response
    schema:
      $ref: '#/definitions/ResponseModel'
  Response429:
    description: The request was sent too many times in a given amount of time
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecret:
    type: apiKey
    in: header
    name: X-IBM-Client-Secret
security:
- clientSecret: []
  clientID: []
schemes:
- https
