swagger: "2.0"
info:
  title: Primary Compliance Score V2
  x-ibm-name: primary-compliance-score-v2
  version: 1.0.0
  description: API for retrieving Primary Compliance Score V2
schemes:
- https
basePath: /NitaqatComplianceScore
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://prow-internal-primarycompscore-http-ace.apps.stg.qiwa-nonprod.local/external/GetPrimaryComplianceScore/V2
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-prow-internal-primarycompscore)/external/GetPrimaryComplianceScore/V2
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
    catch: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  buffering: true
  application-authentication:
    certificate: false
definitions:
  NitaqatComplianceScoreRq_MessageType:
    type: object
    properties:
      NitaqatComplianceScoreRQ_V2:
        $ref: '#/definitions/ComplianceScoreRequest'
  NitaqatComplianceScoreRs_MessageType:
    type: object
    properties:
      NitaqatComplianceScoreRS_V2:
        $ref: '#/definitions/ComplianceScoreResponse'
  ComplianceScoreRequest:
    type: object
    properties:
      Header:
        $ref: '#/definitions/RequestHeader'
      Body:
        $ref: '#/definitions/ComplianceScoreRq_Body'
  ComplianceScoreResponse:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ResponseHeader'
      Body:
        $ref: '#/definitions/ComplianceScoreRs_Body'
  RequestHeader:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
  ResponseHeader:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
      ResponseStatus:
        $ref: '#/definitions/ResponseStatus'
      BackendError:
        $ref: '#/definitions/BackendError'
  ResponseStatus:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendError:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  ComplianceScoreRq_Body:
    type: object
    required:
    - LaborerId
    - LabourOfficeId
    - SequenceNumber
    - Notes
    - WorkPermits
    - ContractAuthentication
    - LaborerLocation
    properties:
      LaborerId:
        type: number
      LabourOfficeId:
        type: number
      SequenceNumber:
        type: number
      Notes:
        $ref: '#/definitions/Notes_RqType'
      WorkPermits:
        $ref: '#/definitions/WorkPermits_RqType'
      ContractAuthentication:
        $ref: '#/definitions/ContractAuth_RqType'
      LaborerLocation:
        $ref: '#/definitions/LaborerLocation_RqType'
  ComplianceScoreRs_Body:
    type: object
    properties:
      WorkPermits:
        $ref: '#/definitions/WorkPermits_Type'
      EstPhaseDetails:
        $ref: '#/definitions/EstPhase'
      ContractAuthentication:
        $ref: '#/definitions/ContractAuth'
      Nitaqat:
        $ref: '#/definitions/NitaqatType'
      Scores:
        $ref: '#/definitions/ScoresType'
      LaborerLocation:
        $ref: '#/definitions/LLType'
      ComplianceStatus:
        $ref: '#/definitions/CSType'
      MOMComplianceScoreChanges:
        $ref: '#/definitions/MOMchangeType'
      ScoreComparision:
        $ref: '#/definitions/ScoreCompType'
  WorkPermits_Type:
    type: object
    properties:
      Establishment:
        $ref: '#/definitions/WorkPermits'
      Unified:
        $ref: '#/definitions/WorkPermits'
  WorkPermits:
    type: object
    properties:
      Total:
        type: number
        example: 13
      Expired:
        type: number
        example: 13
      Valid:
        type: number
        example: 0
      PendingPayments:
        type: number
        example: 1
      EstWorkPermit:
        type: number
        example: 1
      NoWPGreaterThan90Days:
        type: number
        example: 1
      NoWPLessThan90Days:
        type: number
        example: 1
  EstPhase:
    type: object
    properties:
      EstPhaseStatus:
        type: string
        example: expansion
      EstAllowanceEndDate:
        type: string
        example: 12-05-2024
  ContractAuth:
    type: object
    properties:
      Percentage:
        type: integer
        example: 0
      TotalAuthenticatedContracts:
        type: integer
        example: 12
      TotalUnauthenticatedContracts:
        type: integer
        example: 3
  NitaqatType:
    type: object
    properties:
      Color:
        type: object
        properties:
          Id:
            type: string
            example: 300
          Ar:
            type: string
            example: اخضر منخفض
          En:
            type: string
            example: Low Green
      Evaluations:
        type: array
        items:
          type: object
          properties:
            Id:
              type: string
              example: 300
            Ar:
              type: string
              example: اخضر منخفض
            En:
              type: string
              example: Low Green
            From:
              type: integer
              example: Low Green
            To:
              type: integer
              example: Low Green
      NextColor:
        type: object
        properties:
          Id:
            type: string
            example: 300
          Ar:
            type: string
            example: اخضر منخفض
          En:
            type: string
            example: Low Green
      Notification:
        type: object
        properties:
          Ar:
            type: string
            example: اخضر
          EN:
            type: string
            example: Low Green
      SaudisToBeHired:
        type: string
        example: اخضر
      GracePeriod:
        type: object
        properties:
          StartDate:
            type: string
            example: 12-05-2024
          EndDate:
            type: string
            example: 12-05-2024
      EntityNumber:
        type: string
        example: 28-23313-100
      Activity:
        type: string
        example: السلع النسائية، بيع الهواتف المحمولة وصيانتها
      NumberOfSaudis:
        type: integer
        example: 0
      NumberOfExpats:
        type: integer
        example: 0
      NationalizationRate:
        type: integer
        example: 0
      NumberOfFactorizedSaudis:
        type: integer
        example: 0
      NumberOfFactorizedExpats:
        type: integer
        example: 0
      Run_ID:
        type: string
        example: 123
      Run_Date:
        type: string
        example: "2024-05-30T00:00:00.000Z"
      CalculationMethod:
        type: string
        example: Direct
      SizeId:
        type: integer
        example: 1
  ScoresType:
    type: object
    properties:
      Nitaqat:
        type: integer
        example: 0
      WorkPermits:
        type: integer
        example: 12
      NotesInWps:
        type: integer
        example: 3
      ContractAuthentication:
        type: integer
        example: 3
      LaborerLocation:
        type: integer
        example: 3
      Compliance:
        type: integer
        example: 3
  LLType:
    type: object
    properties:
      Assigned:
        type: integer
        example: 0
      NotAssigned:
        type: integer
        example: 12
  CSType:
    type: object
    properties:
      Nitaqat:
        type: boolean
        example: false
      Notes:
        type: boolean
        example: false
      WorkPermits:
        type: boolean
        example: false
      ContractAuth:
        type: boolean
        example: false
      LaborerLocation:
        type: boolean
        example: false
      Compliance:
        type: boolean
        example: false
  MOMchangeType:
    type: object
    properties:
      Nitaqat:
        type: integer
        example: 0
      WorkPermits:
        type: integer
        example: 0
      NotesInWps:
        type: integer
        example: 0
      ContractAuthentication:
        type: integer
        example: 0
      LaborerLocation:
        type: integer
        example: 0
      Compliance:
        type: integer
        example: 0
  ScoreCompType:
    type: object
    properties:
      EntityAvgCompScore:
        type: integer
        example: 0
  WorkPermits_RqType:
    type: object
    properties:
      Establishment:
        $ref: '#/definitions/WorkPermits_Rq'
      Unified:
        $ref: '#/definitions/WorkPermits_Rq'
  WorkPermits_Rq:
    type: object
    properties:
      Valid:
        type: string
        example: 0
      Expired:
        type: string
        example: 42
      ExpiringIn30Days:
        type: string
        example: 0
      Pending:
        type: string
        example: 7
      NoWPGreaterThan90Days:
        type: string
        example: 0
      NoWPLessThan90Days:
        type: string
        example: 0
  ContractAuth_RqType:
    type: object
    properties:
      TotalLaborersCount:
        type: integer
        example: 62
      TotalAuthenticatedContracts:
        type: integer
        example: 4
      TotalAuthenticationPercentage:
        type: string
        example: 6.45
  LaborerLocation_RqType:
    type: object
    properties:
      TotalAssignedLaborers:
        type: integer
        example: 9
      TotalUnassignedLaborers:
        type: integer
        example: 3
      AssignedPercentage:
        type: string
        example: 6
  Notes_RqType:
    type: object
    properties:
      WPSNotesCount:
        type: integer
        example: 9
paths:
  /ComplianceScoreV2:
    post:
      tags:
      - Compliance Score V2
      description: Used to get Nitaq Compliance Score V2
      operationId: getComplianceScorev2
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/NitaqatComplianceScoreRq_MessageType'
        description: NitaqatComplianceScoreRQ_V2
        required: true
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/NitaqatComplianceScoreRs_MessageType'
host: $(catalog.host)
