swagger: "2.0"
info:
  title: PushReqOccUpd
  version: 1.0.0
  description: This service is used to push the occupation and update it from PACC
    team
  x-ibm-name: pushreqoccupd
basePath: /external/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /pushreqoccupd:
    post:
      operationId: pushReqOccUpd
      description: This service is used to push the occupation and update it from
        PACC team
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/pushReqOccUpdRq_BodyType'
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
definitions:
  pushReqOccUpdRq_BodyType:
    type: object
    required:
    - programType
    - activeInactive
    properties:
      occupationCode:
        type: integer
      countryId:
        type: integer
      programType:
        type: integer
        enum:
        - 1
        - 2
      activeInactive:
        type: integer
        enum:
        - 1
        - 0
  pushReqOccUpdRs_BodyType:
    type: object
    required:
    - message
    properties:
      message:
        type: string
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/pushReqOccUpdRs_BodyType'
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
      Location:
        type: string
        description: Id url encoded
  Response204:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
    policy:
    - allow-origin:
      - $(cors-allowed-origin)
      allow-credentials: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: |-
          var apim = require('apim');

          var cfg={
              "serviceCode" : "PROUP0001",
              "channelId" : "Qiwa",
              "requestName" : "pushReqOccUpdRq",
              "responseName": "pushReqOccUpdRs",
              "errorMap" :{
                  "ESBSCHEMA" : {"code" :400, "msg":"Invalid Request"}
              }
          };

          apim.setvariable('cfg',cfg);
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: |-
          var apim = require('apim');
          var millisecondsvalue = ""+(new Date()).getTime();
          var dt = new Date();
          var cfg = apim.getvariable('cfg');
          var OperatorId=apim.getvariable('message.headers.Operator-Id');
          var appname = apim.getvariable('client.app.name');

          var appcReq = {
              [cfg.requestName]:{
                  "Header" : {
                      "TransactionId" : millisecondsvalue,
                      "ChannelId": cfg.channelId,
                      "SessionId": apim.getvariable('message.headers.X-Request-Id'),
                      "RequestTime" : formatDate(dt),
                      "ServiceCode": cfg.serviceCode,
                      "DebugFlag": "1",
                      "UserInfo": {
                          "UserId": apim.getvariable('message.headers.UserId'),
                          "IDNumber": apim.getvariable('message.headers.IDNumber')
                      },
                      "UDF": {
                          "KeyValueArr": [
                              {
                                  "key": "Product",
                                  "value": "pushReqOccUpd"
                              },
                              {
                                  "key": "Client",
                                  "value": appname
                              }
                          ]
                      }
                  },
                  "Body" : apim.getvariable('message.body')
              }
          };

          if (typeof OperatorId !== 'undefined')
              appcReq[cfg.requestName].Header.UserInfo = {
                  "IDNumber" : OperatorId
              };

          session.output.write(appcReq);
          apim.output('application/json');

          function formatDate(d)
          {
              var month = d.getMonth();
              var day = d.getDate().toString();
              var year = d.getFullYear();
              var hour = d.getHours().toString();
              var minitue = d.getMinutes().toString();
              var second = d.getSeconds().toString();
              var millisecond = d.getMilliseconds().toString();

              year = year.toString();

              month = (month + 1).toString();

              if (month.length === 1)
                  month = "0" + month;

              if (day.length === 1)
                  day = "0" + day;

              if (hour.length === 1)
                  hour = "0" + hour;

              if (minitue.length === 1)
                  minitue = "0" + minitue;

              if (second.length === 1)
                  second = "0" + second;

              if (millisecond.length == 1)
                  millisecond = "00" + millisecond;

              if (millisecond.length == 2)
                  millisecond = "0" + millisecond;

              return year+"-"+month+"-"+day+" "+hour + ":" + minitue + ":" + second+"."+millisecond;
          }
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        target-url: $(ace-tip-musaned)/external/pushreqoccupd
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: |-
          var apim = require('apim');
          apim.output('application/json');
          var message = apim.getvariable('message.body');
          var cfg = apim.getvariable('cfg');
          var Header = message[cfg.responseName].Header;
          var TransactionId = Header.TransactionId;
          var ChannelId = Header.ChannelId;
          var RequestTime = Header.RequestTime;
          var SessionId = Header.SessionId;
          var MWRequestTime = Header.MWRequestTime;
          var MWResponseTime = Header.MWResponseTime;
          var status = Header.ResponseStatus.Status;
          var code = Header.ResponseStatus.Code;
          apim.setvariable('message.headers.Transaction-Id',TransactionId,'add');
          apim.setvariable('message.headers.Channel-Id',ChannelId,'add');
          if (RequestTime !== 'undefined')
            apim.setvariable('message.headers.RequestTime',RequestTime,'add');

          if (SessionId !== 'undefined')
            apim.setvariable('message.headers.X-Request-Id',SessionId,'add');

          if (MWRequestTime !== 'undefined')
            apim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');

          if (MWResponseTime !== 'undefined')
            apim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');

          apim.setvariable('message.headers.Response-Status',status,'add');
          apim.setvariable('message.headers.Response-Code',code,'add');
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: |-
                var apim = require('apim');
                var message = apim.getvariable('message.body');
                var cfg = apim.getvariable('cfg');
                var body = message[cfg.responseName].Body;

                session.output.write(body);
                apim.output('application/json');
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: |-
                var apim = require('apim');
                var message = apim.getvariable('message.body');
                var cfg = apim.getvariable('cfg');
                var responseStatus = message[cfg.responseName].Header.ResponseStatus;
                var errorCode = responseStatus.Code;
                var error = {
                    "errorCode": errorCode,
                    "errorMessage": {
                        "en-US": responseStatus.EnglishMsg,
                        "ar-SA": responseStatus.ArabicMsg
                    }
                };
                var httperror = 0;
                if (cfg.errorMap && cfg.errorMap[errorCode]) {

                    httperror = cfg.errorMap[errorCode].code;

                    if (errorCode === "ESBSCHEMA") {

                        error = {
                            "errorCode": "ESBSCHEMA",
                            "errorMessage": {
                                "en-US": "Schema Validation Error",
                                "ar-SA": "حدث خطأ بالنظام"
                            }
                        };
                    }
                }
                if (httperror === 0) {
                    httperror = 409;
                }
                apim.setvariable('message.status.code', httperror, 'set');
                session.output.write(error);
                apim.output('application/json');
  properties:
    target-url:
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
