swagger: "2.0"
info:
  title: Qiwa_ValidEligAdminJrney
  version: 1.0.0
  description: ValidEligAdminJrney
  x-ibm-name: qiwa_valideligadminjrney
paths:
  /valeligadminjour:
    post:
      operationId: ValidEligAdminJrney
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidEligAdminJrneyRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: ValidEligAdminJrney
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidEligAdminJrneyRq_MessageType'
        description: ValidEligAdminJrney
        required: true
basePath: /workinsaudi
definitions:
  ValidEligAdminJrneyRq_MessageType:
    type: object
    properties:
      ValidEligAdminJrneyRq:
        $ref: '#/definitions/ValidEligAdminJrneyRq_Type'
  ValidEligAdminJrneyRs_MessageType:
    type: object
    properties:
      ValidEligAdminJrneyRs:
        $ref: '#/definitions/ValidEligAdminJrneyRs_Type'
  ValidEligAdminJrneyRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidEligAdminJrneyRq_BodyType'
  ValidEligAdminJrneyRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      EstablishmentSequanceNumber:
        type: integer
      CandidiateId:
        type: integer
      VisaRequestDetailsList:
        $ref: '#/definitions/VisaRequestDetails_Type'
      ValidationLevel:
        type: integer
    required:
    - ValidationLevel
  VisaRequestDetails_Type:
    type: object
    properties:
      visaRequestDetails:
        type: array
        items:
          $ref: '#/definitions/visaRequestDetails_Type'
  visaRequestDetails_Type:
    type: object
    properties:
      JobId:
        type: integer
      EmbassyId:
        type: integer
      NationalityId:
        type: integer
      Gender:
        type: integer
      NumberOfVisas:
        type: integer
    required:
    - JobId
    - EmbassyId
    - NationalityId
    - Gender
    - NumberOfVisas
  ValidEligAdminJrneyRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidEligAdminJrneyRs_BodyType'
  ValidEligAdminJrneyRs_BodyType:
    type: object
    properties:
      EntityInformatin:
        $ref: '#/definitions/EntityInformations_Type'
      EstablishmentInformation:
        $ref: '#/definitions/EstablishmentInformations_Type'
      Balance:
        type: integer
      NotAllowedOccupationsNationalitiesList:
        $ref: '#/definitions/NotAllowedOccupationsNationalitiesList_Type'
      EstablishmentPunishmentSources:
        $ref: '#/definitions/EstablishmentPunishmentSources_Type'
      UnrelatedOccupations:
        $ref: '#/definitions/UnrelatedOccupations_Type'
  EstablishmentPunishmentSources_Type:
    type: object
    properties:
      PunishmentSources:
        type: array
        items:
          $ref: '#/definitions/PunishmentSources_Type'
  PunishmentSources_Type:
    type: object
    properties:
      PunishmentSourceNameEN:
        type: string
      PunishmentSourceNameAR:
        type: string
      PunishmentSourceId:
        type: integer
    required:
    - PunishmentSourceNameEN
    - PunishmentSourceNameAR
    - PunishmentSourceId
  NotAllowedOccupationsNationalitiesList_Type:
    type: object
    properties:
      NotAllowedOccupationsNationalities:
        type: array
        items:
          $ref: '#/definitions/NotAllowedOccupationsNationalities_Type'
  NotAllowedOccupationsNationalities_Type:
    type: object
    properties:
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      Occupation:
        $ref: '#/definitions/CodeName_Type'
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
  UnrelatedOccupations_Type:
    type: object
    properties:
      UnrelatedOccupationIds:
        type: integer
      UnrelatedOccupationsPercentage:
        type: number
      MaximumRemaininglaborers:
        type: integer
  EntityInformatin_Type:
    type: object
    properties: {}
  EstablishmentInformation_Type:
    type: object
    properties: {}
  EntityInformations_Type:
    type: object
    properties:
      ExpiredEstablishmentId:
        type: integer
      EstablishmentDetailsList:
        $ref: '#/definitions/EstablishmentDetailsList_Type'
      NotesList:
        $ref: '#/definitions/NotesInfoList_Type'
  EstablishmentDetailsList_Type:
    type: object
    properties:
      EstablishmentDetailsItem:
        type: array
        items:
          $ref: '#/definitions/EstablishmentDetailsItem_Type'
  EstablishmentDetailsItem_Type:
    type: object
    properties:
      UnifiedNumberId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentName:
        type: string
      InsertDate:
        type: string
      EconomicActivityId:
        type: integer
      ColorId:
        type: integer
      SizeId:
        type: integer
      OldestEstablishmentPerActivity:
        type: integer
      OrderedEstablishmentOldest:
        type: integer
  NotesInfoList_Type:
    type: object
    properties:
      NoteInformation:
        type: array
        items:
          $ref: '#/definitions/NotesInfo_Type'
  NotesInfo_Type:
    type: object
    properties:
      EstablishmentId:
        type: integer
      NoteSourceId:
        type: integer
      NoteText:
        type: string
      NoteStatusId:
        type: integer
      NoteTypeId:
        type: integer
      StartDate:
        type: string
      EndDate:
        type: string
      NoteId:
        type: integer
      NotesOrder:
        type: integer
  EstablishmentInformations_Type:
    type: object
    properties:
      EstablishmentId:
        type: integer
      PKEstablishmentId:
        type: integer
      EstablishmentName:
        type: string
      LaborOfficeId:
        type: integer
      SequanceNumber:
        type: integer
      EstablishmentStatusId:
        type: integer
      EstablishmentStatus:
        type: string
      MainEconomicActivityId:
        type: integer
      SubEconomicActivityId:
        type: integer
      MainEconomicActivity:
        type: integer
      SubEconomicActivity:
        type: string
      CRNumber:
        type: string
      CRReleaseDate:
        type: string
      CREndDate:
        type: string
      MunicipalLicenseSource:
        type: string
      MunicipalLicenseNumber:
        type: string
      MunicipalLicenseReleaseDate:
        type: string
      MunicipalLicenseEndDate:
        type: string
      Notes:
        type: string
      SevenHundredNumber:
        type: string
      UnifiedNumberId:
        type: string
      OwnerId:
        type: string
      InsertDate:
        type: string
      IsMainBranch:
        type: string
      District:
        type: string
      Street:
        type: string
      EstablishmentEmail:
        type: string
      PostalCode:
        type: string
      ZIPCode:
        type: string
      PKOwnerId:
        type: integer
      UnifiedNationalNumber:
        type: string
      UseUnifiedNationalNumberFlag:
        type: integer
      CityId:
        type: integer
      CityName:
        type: string
      EstablishmentTypeId:
        type: integer
      EstablishmentTypeName:
        type: string
      WaselZipCode:
        type: string
      WaselPrimary:
        type: string
      WaselSecondary:
        type: string
      WaselUnitNo:
        type: string
      WaselCity:
        type: string
      WaselArea:
        type: string
      WaselStreet:
        type: string
      WaselExpiryDate:
        type: string
      WaselStatus:
        type: integer
      EconomicActivityId:
        type: integer
      EconomicActivityName:
        type: string
      ColorId:
        type: string
      NitaqatColor:
        type: string
      SizeId:
        type: string
      SizeName:
        type: string
      ColorCode:
        type: string
      Saudis:
        type: string
      Foreigners:
        type: string
      TotalLaborerCount:
        type: integer
      NotesInformationList:
        $ref: '#/definitions/NotesList_Type'
  NotesList_Type:
    type: object
    properties:
      NoteInformation:
        type: array
        items:
          $ref: '#/definitions/NoteInfo_Type'
  NoteInfo_Type:
    type: object
    properties:
      NoteId:
        type: string
      EstablishmentId:
        type: string
      NoteText:
        type: string
      NoteStatusId:
        type: integer
      NoteStatusName:
        type: string
      NoteTypeId:
        type: integer
      StartDate:
        type: string
      EndDate:
        type: string
      NoteSourceId:
        type: integer
      NoteSourceName:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  EstablishmentsList_Type:
    type: object
    properties:
      EstablishmentItem:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-estv-establishingvalidates)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        chunked-uploads: true
        persistent-connection: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
