swagger: "2.0"
info:
  title: Qiwa_updateoccupation
  x-ibm-name: qiwa-updateoccupation
  version: 1.0.0
  description: add occupation
schemes:
- https
basePath: /matrixmanagement
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-mtrm-matrixmanagement)/matrixmanagement/updateoccupation
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  updateoccupationRq_MessageType:
    type: object
    properties:
      updateoccupationRq:
        $ref: '#/definitions/updateoccupationRq_Type'
  updateoccupationRs_MessageType:
    type: object
    properties:
      updateoccupationRs:
        $ref: '#/definitions/updateoccupationRs_Type'
  updateoccupationRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/updateoccupationRq_BodyType'
  updateoccupationRq_BodyType:
    type: object
    properties:
      OccupationId:
        type: integer
      OccupationNameAr:
        type: string
      OccupationNameEn:
        type: string
      OccupationGroupId:
        type: integer
      IsForSaudiOnly:
        type: integer
      IsIncludedForEWV:
        type: integer
      IsIncludedForTempVisa:
        type: integer
      IsIncludedForSeasonalVisa:
        type: integer
      IsValidWPJob:
        type: integer
      IsValid1_5ForIstiqdam:
        type: integer
      IsValidForIstiqdam:
        type: integer
      IsEngineeringJob:
        type: integer
      IsHomeJob:
        type: integer
      IsMedicalJob:
        type: integer
      IsAccountantJob:
        type: integer
      RequireProfVerif:
        type: integer
      Gender:
        type: integer
      IsForOccupationManagement:
        type: integer
      IsForContractManagement:
        type: integer
      SaudizationManagement:
        type: integer
      SaudizationActionType:
        type: integer
      SaudizationWarningStartDate:
        type: string
        format: date
      SaudizationWarningEndtDate:
        type: string
        format: date
      SaudizationPercentage:
        type: integer
      MinimumWage:
        type: integer
      IsActive:
        type: integer
      Comment:
        type: string
    required:
    - OccupationId
    - Comment
  updateoccupationRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /updateoccupation:
    post:
      operationId: updateoccupation
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/updateoccupationRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Terminate Or Transfer Subscription When Change Establishment Type
      parameters:
      - name: X-Request-Id
        in: header
        description: X-Request-Id returned in the response header
        required: false
        type: string
      - name: X-IBM-Client-Secret
        in: header
        description: Client secret issued by security server
        required: true
        type: string
      - name: X-IBM-Client-Id
        in: header
        description: Client id issued by security server
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/updateoccupationRq_MessageType'
        description: updateoccupationRq
        required: true
