swagger: "2.0"
info:
  title: Qiwa_DonationTicket
  x-ibm-name: qiwa-donationticket
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
  clientSecret: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://gw-apic.qiwa.info/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://icp-proxy.qiwa.info:31553/qiwa_donationportal/v1/GetTickets
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  catalogs: {}
definitions:
  GetDonationTicketReq:
    type: object
    additionalProperties: false
    properties:
      TransactionId:
        type: string
      EstablishmentId:
        type: string
      MobileNumber:
        type: string
  GetDonationTicketResp:
    type: object
  ErrorModel:
    type: object
    properties:
      errorCode:
        type: string
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
    required:
    - errorCode
  LocaleDataModel:
    type: object
    properties:
      en-US:
        type: string
      ar-SA:
        type: string
paths:
  /GetDonationTicket:
    post:
      responses:
        "201":
          description: success
          schema:
            $ref: '#/definitions/GetDonationTicketResp'
      consumes:
      - application/json
      produces:
      - application/json
      operationId: postGetDonationTicket
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/GetDonationTicketReq'
