swagger: "2.0"
info:
  title: Qiwa_MM_GetMatrix
  x-ibm-name: qiwa-mm-getmatrix
  version: 1.0.0
  description: This service is used by the consumer to get matrix details (The relationship
    between Services and entities).
schemes:
- https
basePath: /qiwa/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - map:
        version: 2.0.0
        title: map
        inputs:
          serviceCode:
            schema:
              type: integer
            variable: request.parameters.serviceCode
          entityCode:
            schema:
              type: integer
            variable: request.parameters.entityCode
        outputs:
          output:
            schema:
              description: ""
              type: object
              properties:
                ServiceCode:
                  type: number
                  name: ServiceCode
                EntityCode:
                  type: number
                  name: EntityCode
              example: "{\r\n            \"ServiceCode\":9,\r\n            \"EntityCode\":10\r\n
                \       }"
            variable: message.body
        actions:
        - set: output.ServiceCode
          from: serviceCode
        - set: output.EntityCode
          from: entityCode
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"GAE00001\",\n
          \   \"channelId\" : \"Integration\",\n    \"requestName\" : \"GetMatrixRq\",\n
          \   \"responseName\": \"GetMatrixRs\",\n    \"errorMap\" :{\n        \"ESBSCHEMA\"
          : {\"code\" :400, \"msg\":\"Invalid Request\"}\n    }\n    \n};\n\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\n\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode\r\n\r\n
          \       },\r\n        \"Body\" : apim.getvariable('message.body')\r\n            \r\n
          \       \r\n    }\r\n};\r\n\r\nif (typeof OperatorId !== 'undefined')\r\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\r\n        \"IDNumber\"
          : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: http://icp-proxy.qiwa.info:31863/matrixmanagement/getmatrix
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
parameters:
  serviceCode:
    in: query
    name: serviceCode
    description: Service Code
    required: false
    type: integer
    format: int32
  entityCode:
    in: query
    name: entityCode
    description: Entity Code
    required: false
    type: integer
    format: int32
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
definitions:
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      Matrix:
        $ref: '#/definitions/MatrixModel'
  MatrixModel:
    type: object
    properties:
      MatrixItem:
        type: array
        items:
          $ref: '#/definitions/MatrixItemModel'
  MatrixItemModel:
    type: object
    properties:
      ServiceCode:
        type: integer
        example: 6
      ServiceTitleAr:
        type: string
        example: تقرير أداء المنشأة
      ServiceTitleEn:
        type: string
        example: Customer Report
      EntityCode:
        type: integer
        example: 6
      EntityNameAr:
        type: string
        example: تقرير أداء المنشأة
      EntityNameArEn:
        type: string
        example: Customer Report
      IsActive:
        type: integer
        enum:
        - 0
        - 1
        example: 1
      LastModifiedDate:
        type: string
        example: "2019-10-10 00:00:00.555"
      LastModifiedUser:
        type: string
        example: "8899881"
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
paths:
  /matrixmanagement/matrix:
    parameters:
    - name: serviceCode
      in: query
      required: false
      description: Service Code
      type: integer
      format: int32
    - name: entityCode
      in: query
      required: false
      description: Entity Code
      type: integer
      format: int32
    - name: X-IBM-Client-Id
      in: header
      required: true
      description: Client id issued by security server
      type: string
    - name: X-IBM-Client-Secret
      in: header
      required: true
      description: Client secret issued by security server
      type: string
    - name: X-Request-Id
      in: header
      required: false
      description: X-Request-Id returned in the response header
      type: string
    get:
      tags:
      - Matrix List
      description: Service to Get matrix list
      operationId: getmatrix
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
