swagger: "2.0"
info:
  title: SADAD_BillCancel
  x-ibm-name: sadad-billcancel
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
security:
- ClientSecret: []
  OAuth2.0:
  - IntegrationScope
  clientID: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  ClientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - operation-switch:
        version: 2.0.0
        title: operation-switch
        case:
        - operations:
          - verb: post
            path: /BillCancel
          execute:
          - gatewayscript:
              version: 2.0.0
              title: service_config
              source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\"
                : \"SAD00001\",\n    \"channelId\" : \"Sadad\",\n\t\"sessionId\" :
                \"1\",\n    \"requestName\" : \"SadadBillCancelRq\",\n    \"responseName\":
                \"SadadBillCancelRs\",\n    \"errorMap\" :{\n        \n    }\n    \n};\n\napim.setvariable('cfg',
                cfg);\napim.output('application/json');"
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Headers
              source: "var apim = require('apim');\n\nvar millisecondsvalue = \"\"+(new
                Date()).getTime();\nvar dt = new Date();\nvar cfg = apim.getvariable('cfg');\n\n\nvar
                appcReq = {\n    [cfg.requestName]:{\n        \"Header\" : {\n            \"TransactionId\"
                :millisecondsvalue,\n            \"ChannelId\": cfg.channelId,\n            \"SessionId\":
                cfg.sessionId, \n            \"RequestTime\" : formatDate(dt),\n\t\t\t\"MWRequestTime\"
                : formatDate(dt),\n            \"ServiceCode\": cfg.serviceCode\n
                \       },\n        \"Body\" : apim.getvariable('message.body')\n
                \           \n        \n    }\n};\n\nsession.output.write(appcReq);\napim.output('application/json');\n\n\nfunction
                formatDate(d)\n{\n    //get the month\n    var month = d.getMonth();\n
                \   //get the day\n    //convert day to string\n    var day = d.getDate().toString();\n
                \   //get the year\n    var year = d.getFullYear();\n    var hour
                = d.getHours().toString();\n    var minitue = d.getMinutes().toString();\n
                \   var second = d.getSeconds().toString();\n    var millisecond =
                d.getMilliseconds().toString();\n    //pull the last two digits of
                the year\n    year = year.toString();\n    \n    //increment month
                by 1 since it is 0 indexed\n    //converts month to a string\n    month
                = (month + 1).toString();\n\n    //if month is 1-9 pad right with
                a 0 for two digits\n    if (month.length === 1)\n        month = \"0\"
                + month;\n\n    //if day is between 1-9 pad right with a 0 for two
                digits\n    if (day.length === 1)\n        day = \"0\" + day;\n\n
                \   if (hour.length === 1)\n        hour = \"0\" + hour;\n\n    if
                (minitue.length === 1)\n        minitue = \"0\" + minitue;\n\n    if
                (second.length === 1)\n        second = \"0\" + second;\n        \n
                \   if (millisecond.length == 1)\n        millisecond = \"00\" + millisecond;\n
                \       \n    if (millisecond.length == 2)\n        millisecond =
                \"0\" + millisecond;\n    \n    \n\n    //return the string \"MMddyy\"\n
                \   return year+\"-\"+month+\"-\"+day+\" \"+hour + \":\" + minitue
                + \":\" + second+\".\"+millisecond;\n}"
        - operations:
          - verb: post
            path: /visa/BillCancel
          execute:
          - gatewayscript:
              version: 2.0.0
              title: service_config
              source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\"
                : \"SAD00001\",\n    \"channelId\" : \"Visa\",\n\t\"sessionId\" :
                \"1\",\n    \"requestName\" : \"SadadBillCancelRq\",\n    \"responseName\":
                \"SadadBillCancelRs\",\n    \"errorMap\" :{\n        \n    }\n    \n};\n\napim.setvariable('cfg',
                cfg);\napim.output('application/json');"
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Headers
              source: "var apim = require('apim');\n\nvar millisecondsvalue = \"\"+(new
                Date()).getTime();\nvar dt = new Date();\nvar cfg = apim.getvariable('cfg');\n\n\nvar
                appcReq = {\n    [cfg.requestName]:{\n        \"Header\" : {\n            \"TransactionId\"
                :millisecondsvalue,\n            \"ChannelId\": cfg.channelId,\n            \"SessionId\":
                cfg.sessionId, \n            \"RequestTime\" : formatDate(dt),\n\t\t\t\"MWRequestTime\"
                : formatDate(dt),\n            \"ServiceCode\": cfg.serviceCode\n
                \       },\n        \"Body\" : apim.getvariable('message.body')\n
                \           \n        \n    }\n};\n\nsession.output.write(appcReq);\napim.output('application/json');\n\n\nfunction
                formatDate(d)\n{\n    //get the month\n    var month = d.getMonth();\n
                \   //get the day\n    //convert day to string\n    var day = d.getDate().toString();\n
                \   //get the year\n    var year = d.getFullYear();\n    var hour
                = d.getHours().toString();\n    var minitue = d.getMinutes().toString();\n
                \   var second = d.getSeconds().toString();\n    var millisecond =
                d.getMilliseconds().toString();\n    //pull the last two digits of
                the year\n    year = year.toString();\n    \n    //increment month
                by 1 since it is 0 indexed\n    //converts month to a string\n    month
                = (month + 1).toString();\n\n    //if month is 1-9 pad right with
                a 0 for two digits\n    if (month.length === 1)\n        month = \"0\"
                + month;\n\n    //if day is between 1-9 pad right with a 0 for two
                digits\n    if (day.length === 1)\n        day = \"0\" + day;\n\n
                \   if (hour.length === 1)\n        hour = \"0\" + hour;\n\n    if
                (minitue.length === 1)\n        minitue = \"0\" + minitue;\n\n    if
                (second.length === 1)\n        second = \"0\" + second;\n        \n
                \   if (millisecond.length == 1)\n        millisecond = \"00\" + millisecond;\n
                \       \n    if (millisecond.length == 2)\n        millisecond =
                \"0\" + millisecond;\n    \n    \n\n    //return the string \"MMddyy\"\n
                \   return year+\"-\"+month+\"-\"+day+\" \"+hour + \":\" + minitue
                + \":\" + second+\".\"+millisecond;\n}"
        otherwise: []
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-sad-sad-payment)/sadad/v1/billcancel
        follow-redirects: false
        inject-proxy-headers: true
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "500"
            type: string
          - set: message.headers.Content-Type
            value: application/json
            type: string
          - set: message.body
            value: '{      "errorCode": "500",      "errorMessage": "Internal server
              error"  }'
            type: string
    finally: []
  properties: {}
  application-authentication:
    certificate: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  catalogs: {}
paths:
  /BillCancel:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
  /visa/BillCancel:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
