swagger: "2.0"
info:
  title: SbcTesting
  x-ibm-name: sbctesting
  version: 2.0.0
  description: this service is used to open establishment using Saudi Business Center
schemes:
- https
basePath: /qiwa/esbv2
security:
- {}
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://gw-apic.qiwa.info/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - parse:
        version: 2.0.0
        title: parse
        parse-settings-reference:
          default: apic-default-parsesettings
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: "var apim = require('apim');\napim.setvariable('Tid',apim.getvariable('message.body.TransactionId'));\nvar
          request= apim.getvariable('message.body');\n \n \nvar LicensesLength;\nvar
          PartyLength = Object.keys(request.CRParties.Party).length;\nvar LookupStructureLength
          = Object.keys(request.CRActivities.LookupStructure).length;\nvar CRRepresentativeLength
          = Object.keys(request.CRRepresentative).length;\nif(request.CRLicenses){\nvar
          LicensesLength = Object.keys(request.CRLicenses.License).length;\n}\nif(LicensesLength
          == 1 ){\nvar OrginalLicense = request.CRLicenses.License;\nvar newLicense
          = OrginalLicense[0];\nrequest.CRLicenses.License = newLicense;\n}\nif(PartyLength
          == 1 ){\nvar OrginalParty = request.CRParties.Party;\nvar newParty = OrginalParty[0];\nrequest.CRParties.Party
          = newParty;\n}\nif(LookupStructureLength == 1 ){\nvar OrginalLookupStructure
          = request.CRActivities.LookupStructure;\nvar newLookupStructure = OrginalLookupStructure[0];\nrequest.CRActivities.LookupStructure
          = newLookupStructure;\n}\nif(CRRepresentativeLength == 1 ){\nvar OrginalCRRepresentative
          = request.CRRepresentative;\nvar newCRRepresentative = OrginalCRRepresentative[0];\nrequest.CRRepresentative
          = newCRRepresentative;\n}\n \n \nsession.output.write(request);\napim.output('application/json');"
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"OEBSBC01\",\n
          \   \"channelId\" : \"SBC\",\n    \"requestName\" : \"OpenEstablishmentBySBCRq\",\n
          \   \"responseName\": \"OpenEstablishmentBySBCRs\",\n    \"errorMap\" :{\n
          \       \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid Request\"}\n    }\n
          \   \n};\napim.setvariable('cfg',cfg);\nvar request= apim.getvariable('message.body');\n\ndelete
          request[\"TransactionId\"];\n//var Isinteger = Number.isInteger(request.MainCR)\nif(request.MainCR
          == \"\" || request.MainCR == null)\n{\n\trequest.MainCR = 0;\n}\nsession.output.write(request);\napim.output('application/json');"
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
  UserId:
    in: header
    name: UserId
    description: UserI d
    required: false
    type: integer
definitions:
  RequestModel:
    type: object
    description: This request object
    properties:
      CRNo:
        type: string
      NationalNo:
        type: integer
      IsMain:
        type: boolean
      MainCR:
        type: integer
      BusinessType:
        $ref: '#/definitions/IDName_Type'
      Location:
        $ref: '#/definitions/IDName_Type'
      CRName:
        type: string
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      Nationality:
        $ref: '#/definitions/IDName_Type'
      ZipCode:
        type: string
      POBOX1:
        type: string
      City:
        $ref: '#/definitions/IDName_Type'
      Street:
        type: string
      LaborOfficeNo:
        type: integer
      FiscalYear:
        $ref: '#/definitions/IDName_Type'
      CRParties:
        $ref: '#/definitions/CRParties_Type'
      CRRepresentative:
        $ref: '#/definitions/CRRepresentative_Type'
      CRActivities:
        $ref: '#/definitions/CRActivities_Type'
      CRLicenses:
        $ref: '#/definitions/CRLicenses_Type'
  CRParties_Type:
    type: object
    properties:
      Party:
        type: array
        items:
          $ref: '#/definitions/Party_Type'
  CRLicenses_Type:
    type: object
    properties:
      License:
        type: array
        items:
          $ref: '#/definitions/CRLicensesItem_Type'
  Party_Type:
    type: object
    properties:
      Name:
        type: string
      RelationType:
        $ref: '#/definitions/IDName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      PartyID:
        type: integer
      BirthDate:
        type: string
  CRLicensesItem_Type:
    type: object
    properties:
      LicenseType:
        type: integer
      LicenseNo:
        type: string
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      IssuingAuthorityName:
        type: string
      Description:
        type: string
  CRRepresentative_Type:
    type: object
    properties:
      Name:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      PartyID:
        type: integer
      BirthDate:
        type: string
      PartyIDType:
        type: string
      Mobile:
        type: integer
      Email:
        type: string
  CRActivities_Type:
    type: object
    properties:
      LookupStructure:
        type: array
        items:
          $ref: '#/definitions/IDName_Type'
  IDName_Type:
    type: object
    properties:
      ID:
        type: integer
      Name:
        type: string
  CodeName_Type:
    type: object
    properties:
      ID:
        type: string
      Name:
        type: string
  ResponseModel:
    type: object
    description: This response object
    properties:
      EstablishmentIds:
        type: string
      RequestNumber:
        type: string
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  IntegerNumberModel:
    type: object
    description: This object use for integer numbers
    additionalProperties:
      type: integer
      example: 1
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
paths:
  /opnestbysbc:
    parameters:
    - name: X-IBM-Client-Id
      in: header
      required: true
      description: Client id issued by security server
      type: string
    - name: X-IBM-Client-Secret
      in: header
      required: true
      description: Client secret issued by security server
      type: string
    - name: X-Request-Id
      in: header
      required: false
      description: X-Request-Id returned in the response header
      type: string
    - name: UserId
      in: header
      required: false
      description: UserI d
      type: integer
      format: int32
    post:
      tags:
      - Open Establishment By SBC
      description: Open Establishment By SBC
      operationId: openestablishmentbysbc
      parameters:
      - name: request
        in: body
        schema:
          $ref: '#/definitions/RequestModel'
        description: Open Establishment By SBC body
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
      Location:
        type: string
        description: Id url encoded
  Response204:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
