swagger: "2.0"
info:
  title: SearchObjectionsRequests
  x-ibm-name: searchobjectionsrequests
  version: 1.0.0
  description: This service is to get objections requests with its details
schemes:
- https
basePath: /fereentryobj
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-fxo-objections)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SearchObjectionsRequestsRq_MessageType:
    type: object
    properties:
      SearchObjectionsRequestsRq:
        $ref: '#/definitions/SearchObjectionsRequestsRq_Type'
  SearchObjectionsRequestsRs_MessageType:
    type: object
    properties:
      SearchObjectionsRequestsRs:
        $ref: '#/definitions/SearchObjectionsRequestsRs_Type'
  SearchObjectionsRequestsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchObjectionsRequestsRq_BodyType'
  SearchObjectionsRequestsRq_BodyType:
    type: object
    properties:
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      LaborOfficeId:
        type: integer
        default: "1"
      SequenceNumber:
        type: integer
        default: "1"
      NICAccountNumber:
        type: string
        default: "1"
      ObjectionReasonId:
        type: integer
        default: "16"
      ObjectionStatusId:
        type: integer
        default: "18"
      RequesterIdNo:
        type: integer
        default: "19"
      PageSize:
        type: integer
        default: "10"
      PageIndex:
        type: integer
        default: "100"
    required:
    - PageSize
    - PageIndex
  LaborerDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
        default: "12"
      LaborerFirstName:
        type: string
        default: test
  SearchObjectionsRequestsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchObjectionsRequestsRs_BodyType'
  SearchObjectionsRequestsRs_BodyType:
    type: object
    properties:
      ObjectionsList:
        $ref: '#/definitions/ObjectionsList_Type'
    required:
    - ObjectionsList
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SOR00001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SOR00001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  LaborerName_Type:
    type: object
    properties:
      FirstName:
        type: string
      SecondName:
        type: string
      ThirdName:
        type: string
      FourthName:
        type: string
      FullName:
        type: string
    required:
    - FirstName
    - SecondName
    - ThirdName
    - FourthName
    - FullName
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  Objection_Type:
    type: object
    properties:
      ObjectionId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      NICAccountNumber:
        type: integer
      LaborerIdNo:
        type: integer
      LaborerName:
        $ref: '#/definitions/LaborerName_Type'
      ObjectionReason:
        type: integer
      ObjectionDescription:
        type: string
      ObjectionStatus:
        $ref: '#/definitions/CodeName_Type'
      RequesterIdNo:
        type: integer
      RejectionReason:
        $ref: '#/definitions/CodeName_Type'
    required:
    - ObjectionId
    - LaborOfficeId
    - SequenceNumber
    - NICAccountNumber
    - LaborerIdNo
    - LaborerName
    - ObjectionReason
    - ObjectionDescription
    - ObjectionStatus
    - RequesterIdNo
    - RejectionReason
  ObjectionsList_Type:
    type: object
    properties:
      Objection:
        type: array
        items:
          $ref: '#/definitions/Objection_Type'
paths:
  /searchobjreq:
    post:
      operationId: SearchObjectionsRequests
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchObjectionsRequestsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get objections requests with its details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchObjectionsRequestsRq_MessageType'
        description: Approve Reject Change Sponsor By Laborer
        required: true
