swagger: "2.0"
info:
  title: SearchChangeSponsorRequests
  x-ibm-name: searchchangesponsorrequests
  version: 1.0.0
  description: This service is used to search the requested change sponsor /transfer
    laborer requests for establishment depending on several details to get specific
    requests with their details.
schemes:
- https
basePath: /changesponsor
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-emtf-searchupdateet)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |
          var apim = require('apim');
          var Response = apim.getvariable('message.body');
          var statusCode = Response.SearchChangeSponsorRequestsRs.Header.ResponseStatus.Code ;


          if(statusCode == 'E9999998'){
              var code = 408
              apim.setvariable('message.status.code',code,'set');
          }
          else if(statusCode == '00000000'){
              var code = 200
              apim.setvariable('message.status.code',code,'set');
          }else{
                var code = 409
              apim.setvariable('message.status.code',code,'set');
          }
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SearchChangeSponsorRequestsRq_MessageType:
    type: object
    properties:
      SearchChangeSponsorRequestsRq:
        $ref: '#/definitions/SearchChangeSponsorRequestsRq_Type'
  SearchChangeSponsorRequestsRs_MessageType:
    type: object
    properties:
      SearchChangeSponsorRequestsRs:
        $ref: '#/definitions/SearchChangeSponsorRequestsRs_Type'
  SearchChangeSponsorRequestsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchChangeSponsorRequestsRq_BodyType'
  SearchChangeSponsorRequestsRq_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      SourceDetails:
        $ref: '#/definitions/SourceDetails_Type'
      RequestDetails:
        $ref: '#/definitions/RequestDetails_Type'
      BalanceType:
        type: integer
        default: "1"
      TransferType:
        type: integer
        default: "1"
      StatusId:
        type: integer
        default: "1"
      ReleaseDate:
        type: string
        default: "1"
      PageSize:
        type: integer
        default: "10"
      PageIndex:
        type: integer
        default: "1"
    required:
    - PageSize
    - PageIndex
  DestinationDetails_Type:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
        default: "176"
      DestinationSequenceNumber:
        type: integer
        default: "17"
      DestinationEstablishmentId:
        type: integer
        default: "14"
      DestinationEntityId:
        type: string
        default: "61"
  DestinationDetail_Type:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
        default: "14"
      DestinationSequenceNumber:
        type: integer
        default: "231"
      DestinationEstablishmentId:
        type: integer
        default: "123"
      DestinationEntityId:
        type: string
        default: "31"
      DestinationEstablishmentName:
        type: string
        default: test
  RequesterDetails_Type:
    type: object
    properties:
      RequesterUserId:
        type: integer
        default: "1"
      RequesterIdNo:
        type: string
        default: "134"
  SourceDetails_Type:
    type: object
    properties:
      SourceLaborOfficeId:
        type: integer
        default: "1"
      SourceSequenceNumber:
        type: integer
        default: "1"
      SourceEstablishmentId:
        type: integer
        default: "1"
      SourceEntityId:
        type: string
        default: "167"
  SourceDetail_Type:
    type: object
    properties:
      SourceLaborOfficeId:
        type: integer
        default: "1"
      SourceSequenceNumber:
        type: integer
        default: "1"
      SourceEstablishmentId:
        type: integer
        default: "1"
      SourceEntityId:
        type: string
        default: "1"
      SourceEstablishmentName:
        type: string
        default: "1"
  RequestDetails_Type:
    type: object
    properties:
      RequestSequence:
        type: integer
        default: "1"
      RequestYear:
        type: integer
        default: "1999"
  SearchChangeSponsorRequestsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchChangeSponsorRequestsRs_BodyType'
  SearchChangeSponsorRequestsRs_BodyType:
    type: object
    properties:
      ChangeSponsorList:
        $ref: '#/definitions/ChangeSponsorList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  ChangeSponsorList_Type:
    type: object
    properties:
      ChangeSponsorItem:
        type: array
        items:
          $ref: '#/definitions/ChangeSponsorItem_Type'
    required:
    - ChangeSponsorItem
  ChangeSponsorItem_Type:
    type: object
    properties:
      RequestId:
        type: integer
      DestinationDetails:
        $ref: '#/definitions/DestinationDetail_Type'
      Balance:
        $ref: '#/definitions/Balance_Type'
      UserId:
        type: integer
      IdNo:
        type: string
      RequestDate:
        type: string
      LaborerTransfersTotalCount:
        type: integer
      PaymentReference:
        type: string
      RequestDetailsCount:
        type: integer
      RequestDetailsList:
        $ref: '#/definitions/RequestDetailsList_Type'
    required:
    - RequestId
    - DestinationDetails
    - Balance
    - UserId
    - IdNo
    - RequestDate
    - LaborerTransfersTotalCount
    - PaymentReference
    - RequestDetailsCount
    - RequestDetailsList
  Balance_Type:
    type: object
    properties:
      Balance:
        type: integer
      BalanceTypeId:
        type: integer
      BalanceTypeEn:
        type: string
      BalanceTypeAr:
        type: string
    required:
    - Balance
    - BalanceTypeId
    - BalanceTypeEn
    - BalanceTypeAr
  TransferType_Type:
    type: object
    properties:
      TransferTypeId:
        type: integer
      TransferTypeEn:
        type: string
      TransferTypeAr:
        type: string
    required:
    - TransferTypeId
    - TransferTypeEn
    - TransferTypeAr
  RequestDetailsList_Type:
    type: object
    properties:
      RequestDetailsItem:
        type: array
        items:
          $ref: '#/definitions/RequestDetailsItem_Type'
    required:
    - RequestDetailsItem
  RequestDetailsItem_Type:
    type: object
    properties:
      LaborerDetails:
        $ref: '#/definitions/LaborerDetail_Type'
      RequestDetails:
        $ref: '#/definitions/RequestDetails_Type'
      SponsorId:
        type: string
      SourceDetails:
        $ref: '#/definitions/SourceDetail_Type'
      TransferType:
        $ref: '#/definitions/TransferType_Type'
      Status:
        $ref: '#/definitions/Status_Type'
      NICRejectionId:
        type: integer
      RejectionDescription:
        type: string
      CSRelatedContractId:
        type: integer
      ReleaseDate:
        type: string
      ReleaseDateType:
        $ref: '#/definitions/CodeName_Type'
      RemainingDays:
        type: integer
      CurrentContractId:
        type: integer
      DestinationUnifiedNationalNo:
        type: string
      DestOwnerId:
        type: integer
      DestEstablishmentTypeId:
        type: integer
      DestSevenHundredNo:
        type: integer
      DestUseUnifiedNationalNoFlag:
        type: integer
      RequestNumber:
        type: string
    required:
    - LaborerDetails
    - RequestDetails
    - SponsorId
    - SourceDetails
    - TransferType
    - Status
    - NICRejectionId
    - RejectionDescription
    - CSRelatedContractId
    - ReleaseDate
    - ReleaseDateType
    - RemainingDays
    - CurrentContractId
  LaborerDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: string
      LaborerName:
        type: string
      LaborerNationalityId:
        type: integer
      LaborerNationalityName:
        type: string
      LaborerBorderNum:
        type: string
  LaborerDetail_Type:
    type: object
    properties:
      LaborerIdNo:
        type: string
      LaborerName:
        type: string
      LaborerNationality:
        $ref: '#/definitions/CodeName_Type'
      LaborerNewOccupation:
        $ref: '#/definitions/CodeName_Type'
      LaborerBorderNum:
        type: string
  Status_Type:
    type: object
    properties:
      StatusId:
        type: integer
      StatusEn:
        type: string
      StatusAr:
        type: string
    required:
    - StatusId
    - StatusEn
    - StatusAr
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SCSR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SCSR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchchangesponsorrequests:
    post:
      operationId: SearchChangeSponsorRequests
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchChangeSponsorRequestsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search the requested change sponsor /transfer laborer requests
        for establishment depending on several details to get specific requests with
        their details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchChangeSponsorRequestsRq_MessageType'
        description: SearchChangeSponsorRequestsRq
        required: true
