swagger: "2.0"
info:
  title: SearchVisitVisaRequests
  x-ibm-name: searchvisitvisarequests
  version: 1.0.0
  description: This service is used to search the requested visa visit requests for
    establishment depending on request number, requester ID, visa outgoing number
    to get specific visa requests with their details and issued visas.
schemes:
- https
basePath: /visa/visitvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-vstv-vvutilities2)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SearchVisitVisaRequestsRq_MessageType:
    type: object
    properties:
      SearchVisitVisaRequestsRq:
        $ref: '#/definitions/SearchVisitVisaRequestsRq_Type'
  SearchVisitVisaRequestsRs_MessageType:
    type: object
    properties:
      SearchVisitVisaRequestsRs:
        $ref: '#/definitions/SearchVisitVisaRequestsRs_Type'
  SearchVisitVisaRequestsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchVisitVisaRequestsRq_BodyType'
  SearchVisitVisaRequestsRq_BodyType:
    type: object
    properties:
      RequestNumber:
        type: string
        default: 11-1111111-1111
      EstablishmentID:
        type: integer
        default: "753"
      EstablishmentSequence:
        type: integer
        default: "2312"
      LaborOfficeID:
        type: integer
        default: "234234"
      VisaOutgoingNumber:
        type: integer
        default: "34234"
      RequestIdNo:
        type: integer
        default: "324324"
      UserId:
        type: integer
        default: "32423"
      StatusesList:
        type: array
        items:
          properties:
            StatusID:
              type: integer
              default: "234234"
      ID:
        type: integer
        default: "676565"
      EntityID:
        type: string
      ShowRequestDetails:
        type: integer
        default: "0"
      NbRows:
        type: integer
        default: "1"
      PageIndex:
        type: integer
        default: "0"
  SearchVisitVisaRequestsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchVisitVisaRequestsRs_BodyType'
  SearchVisitVisaRequestsRs_BodyType:
    type: object
    properties:
      VisitVisasList:
        $ref: '#/definitions/VisitVisasList_Type'
  VisitVisasList_Type:
    type: object
    properties:
      TotalRecordsCount:
        type: integer
      VisitVisa:
        type: array
        items:
          $ref: '#/definitions/VisitVisa_Type'
  VisitVisa_Type:
    type: object
    properties:
      ID:
        type: integer
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      RequestYear:
        type: integer
      RequestSequence:
        type: integer
      RequestStatusId:
        type: integer
      VisaOutGoingNumber:
        type: string
      VisaIssuedDate:
        type: string
      VisaTotalCount:
        type: integer
      NICRejectionId:
        type: string
      RejectionDescription:
        type: string
      RejectionDescriptionAr:
        type: string
      RequesterIdNo:
        type: integer
      RequesterType:
        type: integer
      UserId:
        type: integer
      InsertDate:
        type: string
      LastModifiedDate:
        type: string
      RequestDetails:
        $ref: '#/definitions/RequestDetailsList_Type'
      RequestDetailsCount:
        type: integer
      IssuedVisasList:
        $ref: '#/definitions/IssedVisaInfo_Type'
      IssuedVisasCount:
        type: integer
  RequestDetailsList_Type:
    type: object
    properties:
      RequestDetail:
        type: array
        items:
          $ref: '#/definitions/RequestDetail_Type'
  IssedVisaInfo_Type:
    type: object
    properties:
      IssuedVisasInfo:
        type: array
        items:
          $ref: '#/definitions/IssuedVisasInfo_Type'
  RequestDetail_Type:
    type: object
    properties:
      ID:
        type: integer
      VisitVisaRequestId:
        type: integer
      NationalityId:
        type: integer
      EmbassyId:
        type: integer
      JobId:
        type: integer
      Religionld:
        type: integer
      GenderId:
        type: integer
      Count:
        type: integer
      InsertDate:
        type: string
  IssuedVisasInfo_Type:
    type: object
    properties:
      ID:
        type: integer
      VisaRequestTypeId:
        type: integer
      BorderNumber:
        type: integer
      NationaltyId:
        type: integer
      EmbassyId:
        type: integer
      JobId:
        type: integer
      Religionld:
        type: integer
      GenderId:
        type: integer
      VisaStatusId:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SVVR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SVVR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23432"
      IDNumber:
        type: integer
        default: "324324"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchvisitvisarequests:
    post:
      operationId: SearchVisitVisaRequests
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchVisitVisaRequestsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search Visit Visa Requests
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchVisitVisaRequestsRq_MessageType'
        description: SearchVisitVisaRequestsRq
        required: true
