swagger: "2.0"
info:
  title: SearchDependentTransferRequests
  x-ibm-name: searchdependenttransferrequests
  version: 1.0.0
  description: This service is used to search the requested dependent transfer requests
    for establishment depending on several details to get specific requests with their
    details.
schemes:
- https
basePath: /deptransfer
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-det-dependentet)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SearchDependentTransferRequestsRq_MessageType:
    type: object
    properties:
      SearchDependentTransferRequestsRq:
        $ref: '#/definitions/SearchDependentTransferRequestsRq_Type'
  SearchDependentTransferRequestsRs_MessageType:
    type: object
    properties:
      SearchDependentTransferRequestsRs:
        $ref: '#/definitions/SearchDependentTransferRequestsRs_Type'
  SearchDependentTransferRequestsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchDependentTransferRequestsRq_BodyType'
  SearchDependentTransferRequestsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchDependentTransferRequestsRs_BodyType'
  SearchDependentTransferRequestsRq_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
        default: "11"
      RequestNumber:
        type: string
        default: "1"
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      DependentDetails:
        $ref: '#/definitions/DependentDetails_Type'
      BalanceTypeId:
        type: integer
        default: "1756"
      StatusId:
        type: integer
        default: "1867"
      NewOccupationId:
        type: integer
        default: "154"
      IqamaExpiryDate:
        type: string
        default: "1765"
      PageSize:
        type: integer
        default: "100"
      PageIndex:
        type: integer
        default: "1654"
    required:
    - PageSize
    - PageIndex
  DestinationDetails_Type:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
        default: "1765"
      DestinationSequenceNumber:
        type: integer
        default: "1867"
      DestinationEstablishmentId:
        type: integer
        default: "1"
      DestinationEntityId:
        type: string
        default: "1645"
  RequesterDetails_Type:
    type: object
    properties:
      RequesterUserId:
        type: integer
        default: "156"
      RequesterIdNo:
        type: string
        default: "165"
  DependentDetails_Type:
    type: object
    properties:
      DependentIdNo:
        type: string
        default: "1645"
      DependentName:
        type: string
        default: "1678"
      DependentNationalityId:
        type: integer
        default: "1"
      DependentNationalityName:
        type: string
        default: "1654"
  SearchDependentTransferRequestsRs_BodyType:
    type: object
    properties:
      DependentRequests:
        $ref: '#/definitions/DependentRequests_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  DependentRequests_Type:
    type: object
    properties:
      DependentReqDetails:
        type: array
        items:
          $ref: '#/definitions/DependentReqDetails_Type'
  DependentReqDetails_Type:
    type: object
    properties:
      RequestId:
        type: integer
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      Balance:
        $ref: '#/definitions/Balance_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      RequestDate:
        type: string
      LaborerTransfersTotalCount:
        type: integer
      PaymentReference:
        type: string
      RequestDetailsCount:
        type: integer
      DepRequestDetails:
        $ref: '#/definitions/DepRequestDetails_Type'
    required:
    - RequestId
    - DestinationDetails
    - Balance
    - RequesterDetails
    - RequestDate
    - LaborerTransfersTotalCount
    - PaymentReference
    - RequestDetailsCount
    - DepRequestDetails
  Balance_Type:
    type: object
    properties:
      Balance:
        type: integer
      BalanceTypeId:
        type: integer
      BalanceTypeEn:
        type: string
      BalanceTypeAr:
        type: string
    required:
    - Balance
    - BalanceTypeId
    - BalanceTypeEn
    - BalanceTypeAr
  DepRequestDetails_Type:
    type: object
    properties:
      Request:
        type: array
        items:
          $ref: '#/definitions/Request_Type'
  Request_Type:
    type: object
    properties:
      DependentDetails:
        $ref: '#/definitions/DependentDetails_Type'
      SponsorId:
        type: string
      Status:
        $ref: '#/definitions/CodeName_Type'
      NICRejectionId:
        type: integer
      RejectionDescription:
        type: string
      DTRelatedContractId:
        type: integer
      RequestNumber:
        type: string
      NewOccupation:
        $ref: '#/definitions/CodeName_Type'
      IqamaExpiryDate:
        type: string
      RequestSequence:
        type: integer
      RequestYear:
        type: integer
    required:
    - DependentDetails
    - SponsorId
    - Status
    - NICRejectionId
    - RejectionDescription
    - DTRelatedContractId
    - RequestNumber
    - NewOccupation
    - IqamaExpiryDate
    - RequestSequence
    - RequestYear
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SDTR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SDTR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchchangesponsorrequests:
    post:
      operationId: SearchDependentTransferRequests
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchDependentTransferRequestsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search Dependent Transfer Requests
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchDependentTransferRequestsRq_MessageType'
        description: SearchDependentTransferRequestsRq
        required: true
