swagger: "2.0"
info:
  title: 'SearchChangeOccupation '
  x-ibm-name: searchchangeoccupation
  version: 1.0.0
  description: 'This service is used to search for the change occupations laborer
    requests. '
schemes:
- https
basePath: /chgoccupation
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-chgo-choccutility)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SearchChangeOccupationRq_MessageType:
    type: object
    properties:
      SearchChangeOccupationRq:
        $ref: '#/definitions/SearchChangeOccupationRq_Type'
  SearchChangeOccupationRs_MessageType:
    type: object
    properties:
      GetNitaqComplianceWeightRs:
        $ref: '#/definitions/SearchChangeOccupationRs_Type'
  SearchChangeOccupationRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchChangeOccupationRq_BodyType'
  SearchChangeOccupationRq_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
        default: "10004"
      RequestTypeId:
        type: integer
        default: "1"
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      RequestDetails:
        $ref: '#/definitions/RequestDetails_Type'
      StatusID:
        type: integer
        default: "1"
      IncludeDraft:
        type: integer
        default: "2"
      PageSize:
        type: integer
        default: "10"
      PageIndex:
        type: integer
        default: "100"
  SearchChangeOccupationRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchChangeOccupationRs_BodyType'
  SearchChangeOccupationRs_BodyType:
    type: object
    properties:
      ChangeOccupationList:
        $ref: '#/definitions/ChangeOccupationList_Type'
      TotalRecordsCount:
        type: integer
  ChangeOccupationList_Type:
    type: object
    properties:
      ChangeOccupationItem:
        type: array
        items:
          $ref: '#/definitions/ChangeOccupationItem_Type'
  ChangeOccupationItem_Type:
    type: object
    properties:
      RequestInformation:
        $ref: '#/definitions/RequestInformation_Type'
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      LaborTransfersTotalCount:
        type: integer
      PaymentReference:
        type: integer
      RequestDetailsCount:
        type: integer
      RequestDetailsList:
        $ref: '#/definitions/RequestDetailsList_Type'
  RequestInformation_Type:
    type: object
    properties:
      RequestId:
        type: integer
      RequestTypeId:
        type: integer
      RequestTypeEn:
        type: string
      RequestTypeAr:
        type: string
      RequestDate:
        type: string
  RequestDetailsList_Type:
    type: object
    properties:
      RequestDetailsItem:
        type: array
        items:
          $ref: '#/definitions/RequestDetailsItem_Type'
  RequestDetailsItem_Type:
    type: object
    properties:
      LaborerName:
        type: string
      LaborerIdNo:
        type: string
      LaborOfficeId:
        type: integer
      RequestDetails:
        $ref: '#/definitions/RequestDetails_Type'
      CurrentOccupationDetails:
        $ref: '#/definitions/CurrentOccupationDetails_Type'
      NewOccupationDetails:
        $ref: '#/definitions/NewOccupationDetails_Type'
      Nationality:
        $ref: '#/definitions/Nationality_Type'
      StatusDetails:
        $ref: '#/definitions/StatusDetails_Type'
      RejectionDescription:
        type: string
  CurrentOccupationDetails_Type:
    type: object
    properties:
      CurrentOccupationId:
        type: integer
      CurrentOccupationEn:
        type: string
      CurrentOccupationAr:
        type: string
  NewOccupationDetails_Type:
    type: object
    properties:
      NewOccupationId:
        type: integer
      NewOccupationEn:
        type: string
      NewOccupationAr:
        type: string
  StatusDetails_Type:
    type: object
    properties:
      StatusId:
        type: integer
      StatusEn:
        type: string
      StatusAr:
        type: string
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "12"
      SequenceNumber:
        type: integer
        default: "1"
      EstablishmentId:
        type: integer
        default: "1"
  RequesterDetails_Type:
    type: object
    properties:
      RequesterUserid:
        type: integer
        default: "1"
      RequesterIdNo:
        type: string
        default: "1979"
  LaborerDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: string
        default: "187"
      LaborerName:
        type: string
        default: test
      CurrentOccupationId:
        type: integer
        default: "1990"
      NewOccupationId:
        type: integer
        default: "18"
      Nationality:
        $ref: '#/definitions/Nationality_Type'
  RequestDetails_Type:
    type: object
    properties:
      RequestSequence:
        type: integer
        default: "1"
      RequestYear:
        type: integer
        default: "1"
  Nationality_Type:
    type: object
    properties:
      Code:
        type: integer
        default: "17"
      Name:
        type: string
        default: sa
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchchangeoccupation:
    post:
      operationId: 'SearchChangeOccupation '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchChangeOccupationRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'SearchChangeOccupation '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchChangeOccupationRq_MessageType'
        description: 'SearchChangeOccupation '
        required: true
