swagger: "2.0"
info:
  title: SearchSeasonalVisaRequests V2
  x-ibm-name: searchseasonalvisarequests-v2
  version: 1.0.0
  description: SearchSeasonalVisaRequests V2
schemes:
- https
basePath: /v2/visa/seasonalvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-sese-seasutility)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SearchSeasonalVisaRequestsRq_MessageType:
    type: object
    properties:
      SearchSeasonalVisaRequestsRq:
        $ref: '#/definitions/SearchSeasonalVisaRequestsRq_Type'
  SearchSeasonalVisaRequestsRs_MessageType:
    type: object
    properties:
      SearchSeasonalVisaRequestsRs:
        $ref: '#/definitions/SearchSeasonalVisaRequestsRs_Type'
  SearchSeasonalVisaRequestsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchSeasonalVisaRequestsRq_BodyType'
  SearchSeasonalVisaRequestsRq_BodyType:
    type: object
    properties:
      SequenceNumber:
        type: integer
      LaborOfficeId:
        type: integer
      RequestNumber:
        type: string
      EstablishmentId:
        type: integer
      VisaOutgoingNumber:
        type: integer
      RequesterIdNo:
        type: integer
      RequesterUserId:
        type: integer
      RequestStatusId:
        type: integer
      RequestId:
        type: integer
      EntityId:
        type: string
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - SequenceNumber
    - LaborOfficeId
    - PageSize
    - PageIndex
  RequesterDetails_Type:
    type: object
    properties:
      RequesterIdNo:
        type: integer
      RequesteUserId:
        type: integer
    required:
    - RequesterIdNo
    - RequesteUserId
  SourceDetails_Type:
    type: object
    properties:
      SourceLaborOfficeId:
        type: integer
      SourceSequenceNumber:
        type: integer
      SourceEstablishmentId:
        type: integer
      SourceEntityId:
        type: string
  RequestDetails_Type:
    type: object
    properties:
      RequestSequence:
        type: integer
      RequestYear:
        type: integer
  SearchSeasonalVisaRequestsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchSeasonalVisaRequestsRs_BodyType'
  SearchSeasonalVisaRequestsRs_BodyType:
    type: object
    properties:
      SeasonalVisaList:
        $ref: '#/definitions/SeasonalVisaList_Type'
      TotalRecordsCount:
        type: integer
      TotalPagesCount:
        type: integer
    required:
    - TotalRecordsCount
    - TotalPagesCount
  SeasonalVisaList_Type:
    type: object
    properties:
      SeasonalVisa:
        type: array
        items:
          $ref: '#/definitions/SeasonalVisa_Type'
    required:
    - SeasonalVisa
  SeasonalVisa_Type:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      RequestId:
        type: integer
      RequestYear:
        type: string
      RequestSequence:
        type: string
      RequestStatusId:
        $ref: '#/definitions/CodeName_Type'
      VisaOutGoingNumber:
        type: string
      VisaIssuedDate:
        type: string
      TotalVisaCount:
        type: integer
      NICRejectionId:
        type: integer
      RejectionDescription:
        type: string
      InsertDate:
        type: integer
      RequestDetailsList:
        $ref: '#/definitions/RequestDetailsList_Type'
      RequestDetailsCount:
        type: integer
      EstablishmentLocation:
        $ref: '#/definitions/EstablishmentLocation_Type'
      IssuedVisasList:
        $ref: '#/definitions/IssuedVisasList_Type'
      IssuedVisasCount:
        type: integer
    required:
    - EstablishmentDetails
    - RequesterDetails
    - RequestYear
    - RequestSequence
    - RequestStatusId
    - VisaOutGoingNumber
    - VisaIssuedDate
    - TotalVisaCount
    - NICRejectionId
    - RejectionDescription
    - InsertDate
    - RequestDetailsCount
    - IssuedVisasCount
  RequestDetailsList_Type:
    type: object
    properties:
      RequestDetail:
        $ref: '#/definitions/IssuedVisasList_Type'
    required:
    - RequestDetail
  RequestDetail_Type:
    type: object
    properties:
      RequestId:
        type: integer
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      Embassy:
        $ref: '#/definitions/CodeName_Type'
      Job:
        $ref: '#/definitions/CodeName_Type'
      Religion:
        $ref: '#/definitions/CodeName_Type'
      Gender:
        $ref: '#/definitions/CodeName_Type'
      Count:
        type: string
      InsertDate:
        type: string
    required:
    - RequestId
    - Nationality
    - Embassy
    - Job
    - Religion
    - Gender
    - Count
    - InsertDate
  IssuedVisasList_Type:
    type: object
    properties:
      IssuedVisaInfo:
        type: array
        items:
          $ref: '#/definitions/IssuedVisaInfo_Type'
    required:
    - IssuedVisaInfo
  IssuedVisaInfo_Type:
    type: object
    properties:
      RequestId:
        type: string
      BorderNumber:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      Embassy:
        $ref: '#/definitions/CodeName_Type'
      Job:
        $ref: '#/definitions/CodeName_Type'
      Religion:
        $ref: '#/definitions/CodeName_Type'
      Gender:
        $ref: '#/definitions/CodeName_Type'
      VisaRequestType:
        $ref: '#/definitions/CodeName_Type'
      VisaStatus:
        $ref: '#/definitions/CodeName_Type'
      VisaExpiryDateHijri:
        type: string
      VisaExpiryDateGregorian:
        type: string
    required:
    - RequestId
    - BorderNumber
    - Nationality
    - Embassy
    - Job
    - Religion
    - Gender
    - VisaRequestType
    - VisaStatus
    - VisaExpiryDateHijri
    - VisaExpiryDateGregorian
  EstablishmentLocation_Type:
    type: object
    properties:
      Longitude:
        type: string
      Latitude:
        type: string
      City:
        type: string
      Area:
        type: string
      District:
        type: string
      Street:
        type: string
      BuildingNo:
        type: string
      Description:
        type: string
      POBox:
        type: string
      ZIPCode:
        type: string
      LocationMapUrl:
        type: string
  CodeName_Type:
    type: object
    properties:
      Id:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
    required:
    - Id
    - NameEn
    - NameAr
  EstablishmentDetails_Type:
    type: object
    properties:
      SequenceNumber:
        type: integer
      LaborOfficeId:
        type: integer
      EstablishmentId:
        type: string
    required:
    - SequenceNumber
    - LaborOfficeId
    - EstablishmentId
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchseasvisareq:
    post:
      operationId: SearchSeasonalVisaRequests
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchSeasonalVisaRequestsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search the the requested seasonal visa for establishment depending
        on  several details to get specific requests with their details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchSeasonalVisaRequestsRq_MessageType'
        description: SearchSeasonalVisaRequestsRq
        required: true
