swagger: "2.0"
info:
  title: SendSMS
  x-ibm-name: sendsms
  version: 1.0.0
  description: SendSMS
host: $(catalog.host)
schemes:
- https
basePath: /qiwa/esb
produces:
- application/json
consumes:
- application/json
security:
- clientSecret: []
  clientID: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  testable: true
  enforced: true
  type: rest
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://192.168.80.4:30604
      description: The internal IP of 'icp-cluster.qiwa.info'
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-utl-commonapps3)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  phase: realized
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  DebugFlag_Type:
    type: integer
    default: "1"
  ServiceCode_Type:
    type: string
    default: SS000001
  TransactionId_Type:
    type: string
    default: "6222121543"
  ChannelId_Type:
    type: string
    default: Qiwa
  SessionId_Type:
    type: string
    default: "212"
  RequestTime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  MWRequestTime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  MWResponseime_Type:
    type: string
    default: "2019-10-10T00:00:00.555Z"
  EconomicActivityId_Type:
    type: string
    default: "901"
  SendSMSRq_MessageType:
    type: object
    properties:
      SendSMSRq:
        $ref: '#/definitions/SendSMSRq_Type'
  SendSMSRs_MessageType:
    type: object
    properties:
      SendSMSRs:
        $ref: '#/definitions/SendSMSRs_Type'
  SendSMSRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SendSMSRq_BodyType'
  SendSMSRq_BodyType:
    type: object
    properties:
      RecipientsList:
        $ref: '#/definitions/RecipientsList_Type'
      MessageBody:
        type: string
      SenderID:
        type: string
      Priority:
        type: string
      TimeScheduled:
        type: string
    required:
    - RecipientsList
    - MessageBody
  RecipientsList_Type:
    type: object
    properties:
      Recipient:
        type: array
        items:
          type: string
  SendSMSRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SendSMSRs_BodyType'
  SendSMSRs_BodyType:
    type: object
    properties:
      Messages:
        $ref: '#/definitions/Messages_Type'
      NumberOfUnits:
        type: string
      Cost:
        type: string
      CurrencyCode:
        type: string
      Balance:
        type: string
      DateCreated:
        type: string
      TimeCreated:
        type: string
  Messages_Type:
    type: object
    properties:
      Message:
        type: array
        items:
          $ref: '#/definitions/Message_Type'
  Message_Type:
    type: object
    properties:
      MessageID:
        type: string
      Recipient:
        type: string
      Status:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        $ref: '#/definitions/TransactionId_Type'
      ChannelId:
        $ref: '#/definitions/ChannelId_Type'
      SessionId:
        $ref: '#/definitions/SessionId_Type'
      RequestTime:
        $ref: '#/definitions/RequestTime_Type'
      MWRequestTime:
        $ref: '#/definitions/MWRequestTime_Type'
      ServiceCode:
        $ref: '#/definitions/ServiceCode_Type'
      DebugFlag:
        $ref: '#/definitions/DebugFlag_Type'
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        $ref: '#/definitions/TransactionId_Type'
      ChannelId:
        $ref: '#/definitions/ChannelId_Type'
      SessionId:
        $ref: '#/definitions/SessionId_Type'
      RequestTime:
        $ref: '#/definitions/RequestTime_Type'
      MWRequestTime:
        $ref: '#/definitions/MWRequestTime_Type'
      MWResponseime:
        $ref: '#/definitions/MWResponseime_Type'
      ServiceCode:
        $ref: '#/definitions/ServiceCode_Type'
      DebugFlag:
        $ref: '#/definitions/DebugFlag_Type'
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
        default: Francis
      IDNumber:
        type: string
        default: "4487415334961152"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /sendsms:
    post:
      operationId: SendSMS
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SendSMSRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Send SMS
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SendSMSRq_MessageType'
        description: SendSMSRq
        required: true
