swagger: "2.0"
info:
  title: SendUNHEmail
  x-ibm-name: send-unh-email
  version: 1.0.0
  description: This API sends the UNH Email
host: $(catalog.host)
schemes:
- https
basePath: /NotificationHubService
security:
- OAuth2.0: []
- clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://prow-notificationservices-emaill-http-ace.apps.stg.qiwa-nonprod.local/external/NotificationHubService/EmailSend
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: http://prow-notificationservices-emaill-http-ace.apps.stg.qiwa-nonprod.local/external/NotificationHubService/EmailSend
        follow-redirects: false
        inject-proxy-headers: true
    catch: []
    finally: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
definitions:
  EmailRequest_MessageType:
    type: object
    properties:
      NotificationEmailRequest:
        $ref: '#/definitions/EmailInfoRq_Type'
  EmailResponse_MessageType:
    type: object
    properties:
      NotificationEmailResponse:
        $ref: '#/definitions/EmailInfoRs_Type'
  EmailInfoRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/RequestHeader_Type'
      Body:
        $ref: '#/definitions/EmailInfoRq_Body'
  EmailInfoRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ResponseHeader_Type'
      Body:
        $ref: '#/definitions/EmailInfoRs_Body'
  RequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
      DebugFlag:
        type: string
        default: 1
  ResponseHeader_Type:
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
      DebugFlag:
        type: string
        default: 1
      ResponseStatus:
        $ref: '#/definitions/ResponseStatus'
      BackendError:
        $ref: '#/definitions/BackendError'
  ResponseStatus:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendError:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  EmailInfoRq_Body:
    type: object
    required:
    - SystemName
    - EventName
    - EmailId
    properties:
      SystemName:
        type: number
      EventName:
        type: number
      EmailId:
        type: array
        items:
          type: object
          properties:
            email:
              type: string
              example: test@qiwa.com
            type:
              type: string
              example: to
      Variables:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              example: ENO
            value:
              type: string
              example: 1000
  EmailInfoRs_Body:
    type: object
    properties:
      status:
        type: string
        example: Success
      Details:
        type: string
        example: Email Sent successfully
      id:
        type: string
        example: 20
paths:
  /EmailSend:
    post:
      tags:
      - Send UNH Email
      description: Used to Send UNH Email
      operationId: sendunhemail
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/EmailRequest_MessageType'
        description: EmailinfoRq
        required: true
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/EmailResponse_MessageType'
