swagger: "2.0"
info:
  title: SOCP_Rest_Services
  x-ibm-name: socp-rest-services
  version: 1.0.0
  description: SOCP_Rest_Services
schemes:
- https
basePath: /socp/v1
security:
- {}
securityDefinitions:
  ClientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-external)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SocpaRegistrationValidityExternalRq_MessageType:
    type: object
    properties:
      RegistrationValidityRq:
        $ref: '#/definitions/SocpaRegistrationValidityExternalRq_Type'
  SocpaRegistrationValidityExternalRq_Type:
    type: object
    properties:
      LaborerIqamaNo:
        type: string
      LaborerBorderNo:
        type: string
  SocpaRegistrationValidityExternalRs_MessageType:
    type: object
    properties:
      RegistrationValidityRs:
        $ref: '#/definitions/SocpaRegistrationValidityExternalRs_Type'
  SocpaRegistrationValidityExternalRs_Type:
    type: object
    properties:
      ActivationStatus:
        type: string
      ActivationEndDate:
        type: string
      MessageCode:
        type: string
      MessageText:
        type: string
  ResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: object
        properties: {}
      EnglishMsg:
        type: string
  Error_MessageType:
    type: object
    properties:
      ErrorResponse:
        $ref: '#/definitions/ResponseStatus_Type'
paths:
  /check-registration-validity:
    post:
      operationId: postRegistration-validity-external
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SocpaRegistrationValidityExternalRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Insert a registration-validity-external
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SocpaRegistrationValidityExternalRq_MessageType'
        description: The request body for the operation
        required: true
