swagger: "2.0"
info:
  title: 'SubmitOccupationCorrectionRequest '
  x-ibm-name: submitoccupationcorrectionrequest
  version: 1.0.0
  description: 'This service is used to submit a request for an occupation that needs
    to be correct based on the new occupation correction matrix. '
schemes:
- https
basePath: /chgoccupation
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-chgo-choccsubmits)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SubmitOccupationCorrectionRequestRq_MessageType:
    type: object
    properties:
      SubmitOccupationCorrectionRequestRq:
        $ref: '#/definitions/SubmitOccupationCorrectionRequestRq_Type'
  SubmitOccupationCorrectionRequestRs_MessageType:
    type: object
    properties:
      GetNitaqComplianceWeightRs:
        $ref: '#/definitions/SubmitOccupationCorrectionRequestRs_Type'
  SubmitOccupationCorrectionRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitOccupationCorrectionRequestRq_BodyType'
  SubmitOccupationCorrectionRequestRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "873"
      SequenceNumber:
        type: integer
        default: "13"
      LaborerIdNo:
        type: string
        default: "6713"
      LaborerName:
        type: string
        default: "1763"
      GenderId:
        type: integer
        default: "1"
      CurrentOccupationId:
        type: integer
        default: "3"
      NewOccupationId:
        type: integer
        default: "13"
    required:
    - LaborOfficeId
    - SequenceNumber
    - LaborerName
    - GenderId
    - CurrentOccupationId
    - NewOccupationId
  SubmitOccupationCorrectionRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitOccupationCorrectionRequestRs_BodyType'
  SubmitOccupationCorrectionRequestRs_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
    required:
    - RequestId
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SOCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SOCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /submitoccupationcorrectionrequest:
    post:
      operationId: 'SubmitOccupationCorrectionRequest '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitOccupationCorrectionRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'SubmitOccupationCorrectionRequest '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitOccupationCorrectionRequestRq_MessageType'
        description: 'SubmitOccupationCorrectionRequest '
        required: true
