swagger: "2.0"
info:
  title: SubmitSeasEndorse
  x-ibm-name: submitseasendorse
  version: 1.0.1
  description: This service is used to validate and submit seasonal endorsement. PROD
    YAML
schemes:
- https
basePath: /visa/seasonalvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-sese-seassubmits)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SubmitSeasEndorseRq_MessageType:
    type: object
    properties:
      SubmitSeasEndorseRq:
        $ref: '#/definitions/SubmitSeasEndorseRq_Type'
  SubmitSeasEndorseRs_MessageType:
    type: object
    properties:
      SubmitSeasEndorseRs:
        $ref: '#/definitions/SubmitSeasEndorseRs_Type'
  SubmitSeasEndorseRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitSeasEndorseRq_BodyType'
  SubmitSeasEndorseRq_BodyType:
    type: object
    properties:
      GovermentalSectorId:
        type: integer
      EstablishmentId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EndorsementTypeId:
        type: integer
      EstablishmentLicenseNumbers:
        type: integer
      OwnersAndRepresentativesInfosList:
        $ref: '#/definitions/OwnersAndRepresentativesInfosList_Type'
      EstablishmentLocation:
        $ref: '#/definitions/EstablishmentLocation_Type'
      ContactInformation:
        $ref: '#/definitions/ContactInformation_type'
      EndorsementDetailsList:
        $ref: '#/definitions/EndorsementDetailsList_Type'
      RequiredDocuments:
        $ref: '#/definitions/RequiredDocumentsList_Type'
    required:
    - GovermentalSectorId
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentId
    - EndorsementTypeId
    - EstablishmentLicenseNumbers
    - OwnersAndRepresentativesInfosList
    - EstablishmentLocation
    - ContactInformation
    - EndorsementDetailsList
    - RequiredDocuments
  RequiredDocumentsList_Type:
    type: object
    properties:
      FinancialCapacityId:
        type: string
      BankWarantyDetails:
        $ref: '#/definitions/BankWarantyDetails_Type'
      ClearanceRecordsList:
        type: array
        items:
          type: string
    required:
    - FinancialCapacityId
    - ClearanceRecordsList
  BankWarantyDetails_Type:
    type: object
    properties:
      BankWarrantyId:
        type: string
      BankWarrantyNumber:
        type: string
      BankWarrantyTotalAmount:
        type: number
    required:
    - BankWarrantyId
    - BankWarrantyNumber
    - BankWarrantyTotalAmount
  ContactInformation_type:
    type: object
    properties:
      ContactPersonName:
        type: string
      ContactPersonNationalId:
        type: integer
      MobileNumber:
        type: integer
    required:
    - ContactPersonName
    - MobileNumber
    - ContactPersonNationalId
  OwnersAndRepresentativesInfosList_Type:
    type: object
    properties:
      OwnersAndRepresentativesInfoItem:
        type: array
        items:
          $ref: '#/definitions/OwnersAndRepresentativesInfoItem_Type'
  OwnersAndRepresentativesInfoItem_Type:
    type: object
    properties:
      FirstName:
        type: string
      LastName:
        type: string
      PhoneNumber:
        type: string
      NationalId:
        type: integer
      Role:
        $ref: '#/definitions/CodeName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
    required:
    - FirstName
    - LastName
    - PhoneNumber
    - NationalId
    - Nationality
  EstablishmentLocation_Type:
    type: object
    properties:
      City:
        type: string
      ZipCode:
        type: string
      District:
        type: string
      StreetName:
        type: string
      BuildingNumber:
        type: string
      AdditionalNumber:
        type: string
      LocationMapUrl:
        type: string
    required:
    - AdditionalNumber
    - BuildingNumber
    - StreetName
    - District
    - ZipCode
    - City
  EndorsementDetailsList_Type:
    type: object
    properties:
      EndorsementDetailsItem:
        type: array
        items:
          $ref: '#/definitions/EndorsementDetailsItem_Type'
  EndorsementDetailsItem_Type:
    type: object
    properties:
      NationalityId:
        type: integer
      OccupationId:
        type: integer
      GenderId:
        type: integer
      ReligionId:
        type: integer
      TotalVisaNo:
        type: integer
    required:
    - NationalityId
    - OccupationId
    - GenderId
    - ReligionId
    - TotalVisaNo
  SubmitSeasEndorseRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitSeasEndorseRs_BodyType'
  SubmitSeasEndorseRs_BodyType:
    type: object
    properties:
      EndorsementNumber:
        type: integer
      EndorsementId:
        type: integer
      NotAllowedOccupationsNationalitiesList:
        $ref: '#/definitions/NotAllowedOccupationsNationalitiesList_Type'
      EstablishmentPunishmentSources:
        $ref: '#/definitions/EstablishmentPunishmentSources_Type'
      ValidationErrorList:
        $ref: '#/definitions/ValidationErrorList_Type'
    required:
    - EndorsementNumber
    - EndorsementId
  EstablishmentPunishmentSources_Type:
    type: object
    properties:
      EstablishmentPunishmentSourcesItem:
        type: array
        items:
          $ref: '#/definitions/EstablishmentPunishmentSourcesItem_Type'
  EstablishmentPunishmentSourcesItem_Type:
    type: object
    properties:
      PunishmentSourceNameEN:
        type: string
      PunishmentSourceNameAR:
        type: string
      PunishmentSourceId:
        type: integer
    required:
    - PunishmentSourceNameEN
    - PunishmentSourceNameAR
    - PunishmentSourceId
  NotAllowedOccupationsNationalitiesList_Type:
    type: object
    properties:
      NotAllowedOccupationsNationalitiesListItem:
        type: array
        items:
          $ref: '#/definitions/NotAllowedOccupationsNationalitiesListItem_Type'
  NotAllowedOccupationsNationalitiesListItem_Type:
    type: object
    properties:
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      Occupation:
        $ref: '#/definitions/CodeName_Type'
    required:
    - Nationality
    - Occupation
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ValidationErrorList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: integer
      DescriptionAr:
        type: string
      DescriptionEn:
        type: string
    required:
    - ErrorCode
    - DescriptionAr
    - DescriptionEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /subseasendorse:
    post:
      operationId: SubmitSeasEndorse
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitSeasEndorseRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: validate and submit seasonal endorsement
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitSeasEndorseRq_MessageType'
        description: SubmitSeasEndorseRq
        required: true
