swagger: "2.0"
info:
  title: SubmitDependentTransferRequest
  x-ibm-name: submitdependenttransferrequest
  version: 1.0.0
  description: This service is used to create a dependent transfer request with its
    details after the validation.
schemes:
- https
basePath: /deptransfer
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-det-dependentet)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SubmitDependentTransferRequestRq_MessageType:
    type: object
    properties:
      SubmitDependentTransferRequestRq:
        $ref: '#/definitions/SubmitDependentTransferRequestRq_Type'
  SubmitDependentTransferRequestRs_MessageType:
    type: object
    properties:
      SubmitDependentTransferRequestRs:
        $ref: '#/definitions/SubmitDependentTransferRequestRs_Type'
  SubmitDependentTransferRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitDependentTransferRequestRq_BodyType'
  SubmitDependentTransferRequestRq_BodyType:
    type: object
    properties:
      PaymentReference:
        type: string
        default: "69878757"
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      DependentsList:
        $ref: '#/definitions/DependentsList_Type'
      DependentsNationalitiesList:
        $ref: '#/definitions/DependentsNationalitiesList_Type'
    required:
    - DestinationDetails
    - DependentsList
    - DependentsNationalitiesList
  DestinationDetails_Type:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
        default: "6766"
      DestinationSequenceNumber:
        type: integer
        default: "576"
  DependentsList_Type:
    type: object
    properties:
      Dependent:
        type: array
        items:
          $ref: '#/definitions/Dependent_Type'
  Dependent_Type:
    type: object
    properties:
      DependentIdNo:
        type: string
        default: "13"
    required:
    - DependentIdNo
  DependentsNationalitiesList_Type:
    type: object
    properties:
      DependentNationalitiy:
        type: array
        items:
          $ref: '#/definitions/DependentNationalitiy_Type'
  DependentNationalitiy_Type:
    type: object
    properties:
      Nationality:
        type: integer
        default: "6"
      NumberOfLaborers:
        type: integer
        default: "12"
    required:
    - Nationality
    - NumberOfLaborers
  SubmitDependentTransferRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitDependentTransferRequestRs_BodyType'
  SubmitDependentTransferRequestRs_BodyType:
    type: object
    properties:
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorsList_Type'
      DependentIdNo:
        type: integer
      IdNoContractList:
        $ref: '#/definitions/IdNoContractList_Type'
      DependentRequestNumbers:
        $ref: '#/definitions/DependentRequestNumbers_Type'
      NotRegisteredDependents:
        $ref: '#/definitions/NotRegisteredDependents_Type'
  ValidationsErrorsList_Type:
    type: object
    properties:
      ValidationError:
        type: array
        items:
          $ref: '#/definitions/ValidationError_Type'
  ValidationError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: integer
      EnDescription:
        type: integer
    required:
    - ErrorCode
    - ArDescription
    - EnDescription
  IdNoContractList_Type:
    type: object
    properties:
      IdNoContractItem:
        type: array
        items:
          $ref: '#/definitions/IdNoContractItem_Type'
  IdNoContractItem_Type:
    type: object
    properties:
      DependentIdNo:
        type: integer
      ContractId:
        type: integer
      IsValid:
        type: integer
    required:
    - DependentIdNo
    - ContractId
    - IsValid
  DependentRequestNumbers_Type:
    type: object
    properties:
      DependentRequestNumber:
        type: array
        items:
          $ref: '#/definitions/DependentRequestNumber_Type'
  DependentRequestNumber_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      DependentIdNo:
        type: string
    required:
    - RequestNumber
    - DependentIdNo
  NotRegisteredDependents_Type:
    type: object
    properties:
      NotRegisteredDependent:
        type: array
        items:
          $ref: '#/definitions/NotRegisteredDependent_Type'
  NotRegisteredDependent_Type:
    type: object
    properties:
      DepenedntIdNo:
        type: integer
    required:
    - DepenedntIdNo
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SDTR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SDTR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendErrorsList_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendErrorsList_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /submitdepreq:
    post:
      operationId: SubmitDependentTransferRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitDependentTransferRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: The scope of this service is to create a dependent transfer request
        with its details after the validation.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitDependentTransferRequestRq_MessageType'
        description: SubmitDependentTransferRequestRq
        required: true
