swagger: "2.0"
info:
  title: SubmitTransferLaborerRequest
  x-ibm-name: submittransferlaborerrequest
  version: 1.0.0
  description: This service is used to create a transfer laborer request with its
    details after the validation.
schemes:
- https
basePath: /transferlaborer
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-changesponsor)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SubmitTransferLaborerRequestRq_MessageType:
    type: object
    properties:
      SubmitTransferLaborerRequestRq:
        $ref: '#/definitions/SubmitTransferLaborerRequestRq_Type'
  SubmitTransferLaborerRequestRs_MessageType:
    type: object
    properties:
      SubmitTransferLaborerRequestRs:
        $ref: '#/definitions/SubmitTransferLaborerRequestRs_Type'
  SubmitTransferLaborerRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitTransferLaborerRequestRq_BodyType'
  SubmitTransferLaborerRequestRq_BodyType:
    type: object
    properties:
      PaymentReference:
        type: string
        default: 93039FFA33B042600000000000X10000
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      SourceLaborerList:
        $ref: '#/definitions/SourceLaborerList_Type'
      LaborersNationalitiesList:
        $ref: '#/definitions/LaborersNationalitiesList_Type'
    required:
    - PaymentReference
    - DestinationDetails
    - SourceLaborerList
    - LaborersNationalitiesList
  DestinationDetails_Type:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
        default: "9"
      DestinationSequenceNumber:
        type: integer
        default: "1399497"
    required:
    - DestinationLaborOfficeId
    - DestinationSequenceNumber
  SourceLaborerList_Type:
    type: object
    properties:
      SourceLaborerItem:
        type: array
        items:
          $ref: '#/definitions/SourceLaborerItem_Type'
  LaborersNationalitiesList_Type:
    type: object
    properties:
      LaborersNationalitiesItem:
        type: array
        items:
          $ref: '#/definitions/LaborersNationalitiesItem_Type'
  LaborersNationalitiesItem_Type:
    type: object
    properties:
      Nationality:
        type: integer
        default: "1"
      NumberOfLaborers:
        type: integer
        default: "1"
    required:
    - Nationality
    - NumberOfLaborers
  SourceLaborerItem_Type:
    type: object
    properties:
      SourceLaborOfficeId:
        type: integer
        default: "20"
      SourceSequenceNumber:
        type: integer
        default: "1945005"
      LaborerList:
        $ref: '#/definitions/LaborerList_Type'
    required:
    - SourceLaborOfficeId
    - SourceSequenceNumber
    - LaborerList
  LaborerList_Type:
    type: object
    properties:
      LaborerItem:
        type: array
        items:
          $ref: '#/definitions/LaborerItem_Type'
  LaborerItem_Type:
    type: object
    properties:
      LaborerName:
        type: string
        default: heba
      LaborerIdNo:
        type: string
        default: "1000"
    required:
    - LaborerName
    - LaborerIdNo
  SubmitTransferLaborerRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitTransferLaborerRequestRs_BodyType'
  SubmitTransferLaborerRequestRs_BodyType:
    type: object
    properties:
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorList_Type'
      LaborerRequestNumList:
        $ref: '#/definitions/LaborerRequestNumList_Type'
  ValidationsErrorList_Type:
    type: object
    properties:
      ValidationError:
        type: array
        items:
          $ref: '#/definitions/ValidationError_Type'
  ValidationError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - ErrorCode
    - ArDescription
    - EnDescription
  LaborerRequestNumList_Type:
    type: object
    properties:
      LaborerRequestNumItem:
        type: array
        items:
          $ref: '#/definitions/LaborerRequestNumItem_Type'
  LaborerRequestNumItem_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      LaborerIdNo:
        type: string
      SourceLaborOfficeId:
        type: integer
      SourceSequenceNumber:
        type: integer
    required:
    - RequestNumber
    - LaborerIdNo
    - SourceLaborOfficeId
    - SourceSequenceNumber
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: STLR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: STLR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /submittransferlaborerrequest:
    post:
      operationId: SubmitTransferLaborerRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitTransferLaborerRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Submit Change Sponsor Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitTransferLaborerRequestRq_MessageType'
        description: SubmitTransferLaborerRequestRq
        required: true
