swagger: "2.0"
info:
  title: SubmitCSRequests
  x-ibm-name: submitcsrequests
  version: 1.0.0
  description: SubmitCSRequests
schemes:
- https
basePath: /changesponsor
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-emtf-submitet)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |
          var apim = require('apim');
          var Response = apim.getvariable('message.body');
          var statusCode = Response.SubmitCSRequestRs.Header.ResponseStatus.Code ;


          if(statusCode == 'E9999998'){
              var code = 408
              apim.setvariable('message.status.code',code,'set');
          }
          else if(statusCode == '00000000'){
              var code = 200
              apim.setvariable('message.status.code',code,'set');
          }else{
                var code = 409
              apim.setvariable('message.status.code',code,'set');
          }
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SubmitCSRequestsRq_MessageType:
    type: object
    properties:
      SubmitCSRequestsRq:
        $ref: '#/definitions/SubmitCSRequestsRq_Type'
  SubmitCSRequestsRs_MessageType:
    type: object
    properties:
      SubmitCSRequestsRs:
        $ref: '#/definitions/SubmitCSRequestsRs_Type'
  SubmitCSRequestsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitCSRequestsRq_BodyType'
  SubmitCSRequestsRq_BodyType:
    type: object
    properties:
      DestinationDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      LaborersDetailsList:
        $ref: '#/definitions/LaborersDetailsList_Type'
  LaborersDetailsList_Type:
    type: object
    properties:
      LaborersDetailsItem:
        type: array
        items:
          $ref: '#/definitions/LaborersDetailsItem_Type'
  LaborersDetailsItem_Type:
    type: object
    properties:
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      SponsorDetails:
        $ref: '#/definitions/SponsorDetails_Type'
      SourceDetails:
        $ref: '#/definitions/SourceDetails_Type'
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: integer
  SourceDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentName:
        type: string
      EntityId:
        type: string
      EstablishmentId:
        type: string
  SponsorDetails_Type:
    type: object
    properties:
      SponsorIdNo:
        type: integer
      SponsorName:
        type: string
  LaborerDetails_Type:
    type: object
    properties:
      LaborerName:
        type: string
      LaborerIdNo:
        type: string
      LaboreNationality:
        $ref: '#/definitions/CodeName_Type'
      IqamaExpiryDate:
        type: string
      TransferTypeId:
        type: integer
      LaborerStatusCode:
        type: integer
      ServiceEndDate:
        type: string
      TerminationStatusId:
        type: integer
  SubmitCSRequestsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitCSRequestsRs_BodyType'
  SubmitCSRequestsRs_BodyType:
    type: object
    properties:
      LaborersWithNotValidContracts:
        $ref: '#/definitions/LaborersWithNotValidContracts_Type'
      LaborerRequestNumList:
        $ref: '#/definitions/LaborersWithNotValidContracts_Type'
      DestinationDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorsList_Type'
  ValidationsErrorsList_Type:
    type: object
    properties:
      ValidationsError:
        type: array
        items:
          $ref: '#/definitions/ValidationError_Type'
  ValidationError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
  LaborerRequestNumList_Type:
    type: object
    properties:
      LaborerRequestNumItem:
        type: array
        items:
          $ref: '#/definitions/LaborerRequestNumItem_Type'
  LaborerRequestNumItem_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      LaborerIdNo:
        type: string
      SourceLaborOfficeId:
        type: integer
      SourceSequenceNumber:
        type: integer
      SponsorId:
        type: string
      TransferTypeId:
        type: integer
  LaborersWithNotValidContracts_Type:
    type: object
    properties:
      LaborerRequestNumItem:
        type: array
        items:
          $ref: '#/definitions/LaborerRequestItem_Type'
  LaborerRequestItem_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      ContractId:
        type: integer
      IsValid:
        type: integer
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentName:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /submitcsrequests:
    post:
      operationId: SubmitCSRequests
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitCSRequestsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Service Sustainability Configuration
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitCSRequestsRq_MessageType'
        description: SubmitCSRequestsRq
        required: true
