swagger: "2.0"
info:
  title: TemplateAPI
  x-ibm-name: templateapi
  version: 1.0.0
  description: ""
schemes:
- https
basePath: /common
security:
- {}
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  properties:
    target-url:
      value: http://datapower.qiwa.info:9076/MusandService/MusanedService.svc
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: setVariables
        source: "var apim = require('apim');\n\n apim.setvariable('requestTag','GetLaborerPrisonStatusNICRq','add');\n
          \ apim.setvariable('responseTag','GetLaborerPrisonStatusNICRs','add');\n
          \   apim.setvariable('ServiceCode','NGLPS001','add');\n  \n  "
    - gatewayscript:
        version: 2.0.0
        title: dynamicTransformation
        source: "var apim = require('apim');\n\n\n//--------------------------------\n\nvar
          currentDate = new Date();\nvar millisecondsvalue = \"\"+currentDate.getTime();\n
          apim.setvariable('myTransactionId',millisecondsvalue,'add');\nvar today
          = new Date();\nvar date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();\nvar
          time = today.getHours() + \":\" + today.getMinutes() + \":\" + today.getSeconds();\nvar
          dateTime = date+' '+time;\napim.setvariable('myRequestTime',dateTime,'add');\n\n//--------------------------------\n\nvar
          obj = apim.getvariable('message.body');\n  \n\nvar TransactionId = ''+apim.getvariable('myTransactionId');\nvar
          ChannelId =\t''+apim.getvariable('message.headers.Channel-Id');\nvar SessionId
          = '212';\nvar RequestTime = ''+apim.getvariable('myRequestTime');\nvar MWRequestTime
          = ''+apim.getvariable('myRequestTime');\nvar ServiceCode = apim.getvariable('ServiceCode');\nvar
          UserId = '';\nvar IDNumber = '';\nvar Body = '';\n\n var parent;   \n\n
          \   function printValues(obj) {\n\n        for(var k in obj) {\n\n            if(obj[k]
          instanceof Object) {\n\n                parent = k;\n\n                printValues(obj[k]);\n\n
          \           } else {\n\n            \n              if(parent =='ForeignerInfoRq'){\n\n\n
          \                if(Number.isFinite(obj[k])){\n\n                   Body
          = Body+'\"'+k+'\":'+ obj[k]+',';\n\n                 }else{\n\n                   Body
          = Body+'\"'+k+'\":\"'+ obj[k]+'\",';\n\n                 }\n\n              }\n\n
          \             if(k =='UserId'){\n\n              UserId = obj[k];\n\n              }else
          if(k =='IDNumber'){\n\n               IDNumber = obj[k];\n\n              }\n\n
          \ \n\n            };\n\n        }\n\n    };\n\n    \n\n    \n\n    printValues(obj);\n\n
          \   if(Body.endsWith(\",\")){\n\n     Body = Body.substring(0 , Body.length
          - 1); \n\n \n    }\n\n    var output = JSON.stringify(obj);\n    var requestTag
          = apim.getvariable('requestTag');\n    var message = '{\"'+requestTag+'\":
          {\"Header\": {\"TransactionId\": \"'+TransactionId+'\",\"ChannelId\": \"'+ChannelId+'\",\"SessionId\":
          \"'+SessionId+'\",\"RequestTime\": \"'+RequestTime+'\",\"MWRequestTime\":
          \"'+MWRequestTime+'\",\"ServiceCode\": \"'+ServiceCode+'\",\"DebugFlag\":
          \"1\",\"UserInfo\": {\"UserId\": \"'+UserId+'\",\"IDNumber\": \"'+IDNumber+'\"}},\"Body\":
          {'+Body+'}}}';\n\n\nsession.output.write(message);\napim.output('application/json');"
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-nic-nicget)/common/getlaborerprisonstatusnic
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: setHeaders
        source: "\tvar apim = require('apim');\n    apim.output('application/json');\n\tvar
          responseTag = apim.getvariable('responseTag');\n\tvar TransactionId = \"\"+apim.getvariable(\"message.body.\"+responseTag+\".Header.TransactionId\");\n\t//var
          mystatusCode = \"\"+apim.getvariable(\"message.body.\"+responseTag+\".Header.ResponseStatus.Code\");\n\t\n\t\tvar
          mystatusCode = \"78787878\";\n\n\tvar ChannelId = \"\"+apim.getvariable(\"message.body.\"+responseTag+\".Header.ChannelId\");\n\tvar
          RequestTime = \"\"+apim.getvariable(\"message.body.\"+responseTag+\".Header.RequestTime\");\n\t\n
          \   apim.setvariable('message.headers.TransactionId',TransactionId,'add');\n\n
          \   apim.setvariable('message.headers.ChannelId',ChannelId,'add');\n\tapim.setvariable('message.headers.RequestTime',RequestTime,'add');\n
          \   \n     apim.setvariable('message.headers.respStatusCode',mystatusCode,'add');"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("respStatusCode") = '00000000'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: extractBody
              source: "\nvar apim = require('apim');\n\n\nvar obj = apim.getvariable('message.body');\n
                \ \nvar responseTag = apim.getvariable('responseTag');\n\nvar Body
                = '';\n\n var parent;   \n\n    function printValues(obj) {\n\n        for(var
                k in obj) {\n\n            if(obj[k] instanceof Object) {\n\n                parent
                = k;\n\n                printValues(obj[k]);\n\n            } else
                {\n\n            \n              if(parent =='Body'){\n\n\n                 if(Number.isFinite(obj[k])){\n\n
                \                  Body = Body+'\"'+k+'\":'+ obj[k]+',';\n\n                 }else{\n\n
                \                  Body = Body+'\"'+k+'\":\"'+ obj[k]+'\",';\n\n                 }\n\n
                \             }\n\n              \n\n  \n\n            };\n\n        }\n\n
                \   };\n\n\n    printValues(obj);\n\n    if(Body.endsWith(\",\")){\n\n
                \    Body = Body.substring(0 , Body.length - 1); \n \n    }\n\n    var
                output = JSON.stringify(obj);\n    \n    var message = '{\"'+responseTag+'\":
                {'+Body+'}}';\n\n\nsession.output.write(message);\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: errorResponse
              source: "var apim = require('apim');\n\n\nvar obj = apim.getvariable('message.body');\n
                \ \nvar responseTag = apim.getvariable('responseTag');\n\nvar Body
                = '';\n\n var parent;   \n\n    function printValues(obj) {\n\n        for(var
                k in obj) {\n\n            if(obj[k] instanceof Object) {\n\n                parent
                = k;\n\n                printValues(obj[k]);\n\n            } else
                {\n\n            \n              if(parent =='ResponseStatus'){\n\n\n
                \                if(Number.isFinite(obj[k])){\n\n                   Body
                = Body+'\"'+k+'\":'+ obj[k]+',';\n\n                 }else{\n\n                   Body
                = Body+'\"'+k+'\":\"'+ obj[k]+'\",';\n\n                 }\n\n              }\n\n
                \             \n\n  \n\n            };\n\n        }\n\n    };\n\n\n
                \   printValues(obj);\n\n    if(Body.endsWith(\",\")){\n\n     Body
                = Body.substring(0 , Body.length - 1); \n \n    }\n\n    var output
                = JSON.stringify(obj);\n    \n    var message = '{\"ErrorResponse\":
                {'+Body+'}}';\n\n\nsession.output.write(message);\napim.output('application/json');"
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
paths:
  /GetTemplateTest: {}
