swagger: "2.0"
info:
  title: test java
  x-ibm-name: test-java
  version: 1.0.0
schemes:
- https
basePath: /test-java
security:
- clientID: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: GET
        chunked-uploads: true
        persistent-connection: true
        target-url: $(reqbin-url)/echo/get/json
        follow-redirects: false
        inject-proxy-headers: true
    catch: []
  properties:
    target-url:
      value: https://reqbin.com/echo/get/json
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /result:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
      - name: X-IBM-Client-Id
        in: header
        required: true
        type: string
      - name: X-IBM-Client-Secret
        in: header
        required: true
        type: string
