swagger: "2.0"
info:
  title: test
  x-ibm-name: test
  version: 1.0.0
  description: ""
schemes:
- https
basePath: /contractmanagement
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - log:
        version: 2.0.0
        title: log
        mode: gather-and-send
    - invoke:
        version: 2.0.0
        title: invoke
        header-control:
          type: blacklist
          values: []
        parameter-control:
          type: whitelist
          values: []
        timeout: 60
        verb: keep
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        target-url: $(ace-hrsd-hrsdget1)/common/getcombranwithsameactivities
    catch: []
  properties:
    target-url:
      value: https://gw-apic.qiwa.info/takamol/staging/mhrsd/v1/getestablishmentdetailsbylicensenumber
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  Input_BodyType:
    type: object
    properties:
      estabDataList:
        $ref: '#/definitions/InEstabDataList_Type'
  InEstabDataList_Type:
    type: object
    properties:
      laborOfficeId:
        type: string
      sequenceNo:
        type: string
      name:
        type: string
      size:
        type: string
      isMain:
        type: string
      mainLaborOffice:
        type: string
      mainSequenceNum:
        type: string
      mainEstablishmentName:
        type: string
      commercialRecord:
        type: string
      municipalLicense:
        type: string
      otherLicense:
        type: string
      ownerIdNo:
        type: string
      sevenHundredNum:
        type: string
  Output_BodyType:
    type: object
    properties:
      estabDataList:
        $ref: '#/definitions/OutEstabDataList_Type'
  OutEstabDataList_Type:
    type: object
    properties:
      laboreId:
        type: integer
      sequenceNo:
        type: number
      name:
        type: string
      size:
        type: string
      isMain:
        type: boolean
      mainLaborOffice:
        type: integer
      mainSequenceNum:
        type: number
      mainEstablishmentName:
        type: string
      commercialRecord:
        type: string
      municipalLicense:
        type: string
      otherLicense:
        type: integer
      ownerIdNo:
        type: string
      sevenHundredNum:
        type: string
paths:
  /test:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      parameters:
      - name: req
        in: body
        required: false
        schema:
          type: object
      consumes: []
      produces: []
