swagger: "2.0"
info:
  title: UpdateInspectorVisitDetailsCheck
  x-ibm-name: updateinspectorvisitdetailscheck
  version: 1.0.0
  description: 'This a push service is a used to update visit dates and to mark  the
    establishment if it has a correction period by CHECK to update Qiwa database '
schemes:
- https
basePath: /check
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-chmng-updates)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  UpdateInspectorVisitDetailsCheckRq_MessageType:
    type: object
    properties:
      UpdateInspectorVisitDetailsCheckRq:
        $ref: '#/definitions/UpdateInspectorVisitDetailsCheckRq_Type'
  UpdateInspectorVisitDetailsCheckRs_MessageType:
    type: object
    properties:
      UpdateInspectorVisitDetailsCheckRs:
        $ref: '#/definitions/UpdateInspectorVisitDetailsCheckRs_Type'
  UpdateInspectorVisitDetailsCheckRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/UpdateInspectorVisitDetailsCheckRq_BodyType'
  UpdateInspectorVisitDetailsCheckRq_BodyType:
    type: object
    properties:
      InspectionVisitID:
        type: integer
      InspectorVisitDate:
        type: string
      HasCorrectionPeriod:
        type: string
    required:
    - InspectionVisitID
  UpdateInspectorVisitDetailsCheckRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/UpdateInspectorVisitDetailsCheckRs_BodyType'
  UpdateInspectorVisitDetailsCheckRs_BodyType:
    type: object
    properties:
      ErrorsList:
        $ref: '#/definitions/ErrorsList_Type'
    required:
    - ErrorsList
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - EnDescription
    - ArDescription
    - ErrorCode
  ErrorsList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
paths:
  /updateinspvisitdet:
    post:
      operationId: UpdateInspectorVisitDetailsCheck
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/UpdateInspectorVisitDetailsCheckRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Update Inspector Visit Details Check
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/UpdateInspectorVisitDetailsCheckRq_MessageType'
        description: Update Inspector Visit Details Check
        required: true
