swagger: "2.0"
info:
  title: User Management
  x-ibm-name: user-management
  version: 1.0.0
schemes:
- https
basePath: /user-management
security:
- OAuth2.0:
  - IntegrationScope
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://gw-apic.qiwa.info/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: Get JWK
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - Authorization
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: GET
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error:
        - ConnectionError
        - SOAPError
        - OperationError
        target-url: $(api-qiwa-info-jwks)
        output: resp1
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |-
          var apim = require('apim');
          var resp1 = JSON.stringify(apim.getvariable('resp1.body'));
          var cookies = String(apim.getvariable('request.headers.cookie'));
          var cookiesList = cookies.split(';');
          var searchString = 'qiwa.authorization';
          var tokenindex = cookiesList.indexOf(cookiesList.find(
              function(str) {
                  return str.includes(searchString);
              }
          ));
          if (tokenindex !== -1) {
              var jwttoken = cookiesList[tokenindex].split('=')[1]
              apim.setvariable('message.headers.authorization','Bearer '+jwttoken);
          }

          apim.setvariable('jwk-key',resp1);
    - jwt-validate:
        version: 2.0.0
        title: jwt-validate
        jwt: message.headers.authorization
        output-claims: decoded.claims
        iss-claim: ""
        aud-claim: ""
        jws-jwk: jwk-key
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |-
          var apim = require('apim');
          var claims = JSON.stringify(apim.getvariable('decoded.claims'));
          var encodedClaims = new Buffer(claims).toString('base64');
          apim.setvariable('message.headers.payload',encodedClaims);
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
          - Authorization
        parameter-control:
          type: blocklist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        cache-response: no-cache
        cache-ttl: 900
        target-url: $(internal-um-subscription-managment-api)/api/bff/{uri}/{uri2}/{uri3}/{uri4}/{uri5}/{uri6}
        inject-proxy-headers: true
  properties:
    target-url:
      value: https://internal-um-subscription-managment-api.qiwa.info/api/bff
      description: The URL of the target service
      encoded: false
    target-url-jwk:
      value: https://api.qiwa.info/.well-known/jwks.json
      description: to get qiwa jwk to decode the jwt token
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
paths:
  /{uri}/{uri2}/{uri3}:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
    put:
      responses:
        "200":
          schema:
            type: string
          description: success
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
    patch:
      responses:
        "200":
          schema:
            type: string
          description: success
    parameters:
    - name: uri
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri2
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri3
      in: path
      required: true
      description: target backend system uri path
      type: string
  /{uri}:
    parameters:
    - name: uri
      in: path
      required: true
      description: target backend system uri path
      type: string
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
    put:
      responses:
        "200":
          schema:
            type: string
          description: success
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
    patch:
      responses:
        "200":
          schema:
            type: string
          description: success
  /{uri}/{uri2}:
    parameters:
    - name: uri
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri2
      in: path
      required: true
      description: target backend system uri path
      type: string
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
    put:
      responses:
        "200":
          schema:
            type: string
          description: success
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
    patch:
      responses:
        "200":
          schema:
            type: string
          description: success
  /{uri}/{uri2}/{uri3}/{uri4}:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
    put:
      responses:
        "200":
          schema:
            type: string
          description: success
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
    patch:
      responses:
        "200":
          schema:
            type: string
          description: success
    parameters:
    - name: uri
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri2
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri3
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri4
      in: path
      required: true
      description: target backend system uri path
      type: string
  /{uri}/{uri2}/{uri3}/{uri4}/{uri5}:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
    put:
      responses:
        "200":
          schema:
            type: string
          description: success
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
    patch:
      responses:
        "200":
          schema:
            type: string
          description: success
    parameters:
    - name: uri
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri2
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri3
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri4
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri5
      in: path
      required: true
      description: target backend system uri path
      type: string
  /{uri}/{uri2}/{uri3}/{uri4}/{uri5}/{uri6}:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
    put:
      responses:
        "200":
          schema:
            type: string
          description: success
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
    patch:
      responses:
        "200":
          schema:
            type: string
          description: success
    parameters:
    - name: uri
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri2
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri3
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri4
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri5
      in: path
      required: true
      description: target backend system uri path
      type: string
    - name: uri6
      in: path
      required: true
      description: target backend system uri path
      type: string
