swagger: "2.0"
info:
  title: ValidateLaborerInTC
  x-ibm-name: validatelaborerintc
  version: 1.0.1
  description: This service is used to check if the laborer is eligible to request
    a terminate contract or to be requested in terminate contract request.
schemes:
- https
basePath: /tc
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-tc-tcvalidates)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  ValidateLaborerInTCRq_MessageType:
    type: object
    properties:
      ValidateLaborerInTCRq:
        $ref: '#/definitions/ValidateLaborerInTCRq_Type'
  ValidateLaborerInTCRs_MessageType:
    type: object
    properties:
      ValidateLaborerInTCRs:
        $ref: '#/definitions/ValidateLaborerInTCRs_Type'
  ValidateLaborerInTCRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateLaborerInTCRq_BodyType'
  ValidateLaborerInTCRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      LaborerIdNo:
        type: integer
      LaborerTypeId:
        type: integer
      RequesterTypeId:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - LaborerIdNo
    - LaborerTypeId
    - RequesterTypeId
  ValidateLaborerInTCRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateLaborerInTCRs_BodyType'
  ValidateLaborerInTCRs_BodyType:
    type: object
    properties:
      EstablishmentName:
        type: string
      LaborerName:
        type: string
      JobCode:
        type: string
      ContractId:
        type: integer
      ContractStartDate:
        type: string
      ContractExpiryDate:
        type: string
      NoticePeriod:
        type: integer
      ProbationPeriod:
        type: integer
      ProbationTerminationRight:
        type: integer
      RelatedToId:
        type: string
      HasNoContract:
        type: boolean
      HasQiwaActiveContract:
        type: boolean
    required:
    - EstablishmentName
    - LaborerName
    - JobCode
    - ContractId
    - ContractStartDate
    - ContractExpiryDate
    - NoticePeriod
    - ProbationPeriod
    - ProbationTerminationRight
    - HasNoContract
    - HasQiwaActiveContract
    - RelatedToId
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /vallaborerintc:
    post:
      operationId: ValidateLaborerInTC
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateLaborerInTCRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Validate Laborer In Terminate Contract
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateLaborerInTCRq_MessageType'
        description: ValidateLaborerInTCRq
        required: true
