swagger: "2.0"
info:
  title: VerifyLaborerMeccaLocation
  version: 1.0.0
  description: This service is used to verify whether the laborer is assigned on a
    specified location city.
  x-ibm-name: verifylaborermeccalocation
paths:
  /VerifyLaborerMeccaLocation:
    post:
      operationId: VerifyLaborerMeccaLocation
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/VerifyLaborerMeccaLocationRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: VerifyLaborerMeccaLocation
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/VerifyLaborerMeccaLocationRq_MessageType'
        description: This service is used to verify whether the laborer is assigned
          on a specified location city.
        required: true
basePath: /estabmanagement
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
definitions:
  VerifyLaborerMeccaLocationRq_MessageType:
    type: object
    properties:
      VerifyLaborerMeccaLocationRq:
        $ref: '#/definitions/VerifyLaborerMeccaLocationRq_Type'
  VerifyLaborerMeccaLocationRs_MessageType:
    type: object
    properties:
      VerifyLaborerMeccaLocationRs:
        $ref: '#/definitions/VerifyLaborerMeccaLocationRs_Type'
  VerifyLaborerMeccaLocationRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/VerifyLaborerMeccaLocationRq_BodyType'
  VerifyLaborerMeccaLocationRq_BodyType:
    type: object
    properties:
      LaborerId:
        type: integer
    required:
    - LaborerId
  Name_Type:
    type: object
    properties:
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - NameAr
    - NameEn
  Coordinates_Type:
    type: object
    properties:
      Longitude:
        type: string
      Latitude:
        type: string
    required:
    - Longitude
    - Latitude
  VerifyLaborerMeccaLocationRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/VerifyLaborerMeccaLocationRs_BodyType'
  VerifyLaborerMeccaLocationRs_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: string
      SequenceNumber:
        type: string
      UnifiedNationalNumber:
        type: string
      LocationDetails:
        $ref: '#/definitions/Location_Type'
      LaborerDetails:
        $ref: '#/definitions/Laborer_Type'
    required:
    - LaborOfficeId
    - SequenceNumber
    - UnifiedNationalNumber
  Location_Type:
    type: object
    properties:
      LocationName:
        type: string
      LocationDescription:
        type: string
      LocationCity:
        type: string
      LocationCoordinates:
        $ref: '#/definitions/Coordinates_Type'
      LocationAddress:
        type: string
      LocationBuildingNo:
        type: integer
      LocationZipCode:
        type: string
      LocationUnitNo:
        type: integer
      LocationAddtionalNo:
        type: integer
      LocationDistrictArea:
        $ref: '#/definitions/Name_Type'
      LocationStreetName:
        $ref: '#/definitions/Name_Type'
      BaladiaName:
        type: string
      AmanahName:
        type: string
      ShortAddress:
        type: string
    required:
    - LocationName
    - LocationDescription
    - LocationCity
  Laborer_Type:
    type: object
    properties:
      LaborerId:
        type: integer
      IsRotated:
        type: integer
    required:
    - LaborerId
    - IsRotated
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-cmpm-mecca-location)$(request.path)
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
