swagger: "2.0"
info:
  title: ZendeskDisabilityStatus
  x-ibm-name: zendesk-disabilitystatus
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-zen-zendesk)/zendesk/Webhookevent/getdisabledemplinfor
        follow-redirects: false
        inject-proxy-headers: true
    catch: []
    finally: []
  properties: {}
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
paths:
  /getDisabilityStatus:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
security:
- {}
