swagger: "2.0"
info:
  title: AAA
  x-ibm-name: aaa
  version: 1.0.0
schemes:
- https
basePath: /qwallet/rb
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://gw-apic.qiwa.info/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-qw-q-walletcashout)/qwallet/rb/qwalletcashoutrequest
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
paths:
  /qwalletcashoutrequest:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    options:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
