swagger: "2.0"
info:
  title: AjeerSearchChangeSponsor
  description: This API exposes AJEER search change sponsor from Qiwa platform
  x-ibm-name: ajeer-searchchangesponsor
  version: 2.0.0
schemes:
- https
basePath: /ajeer/v2
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /ajeer-search-change-sponsor:
    parameters:
    - $ref: '#/parameters/X-IBM-Client-Id'
    - $ref: '#/parameters/X-IBM-Client-Secret'
    post:
      tags:
      - ajeer search change sponsor request
      description: Service to get search change sponsor
      operationId: ajeersearchchangesponsor
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/RequestModel'
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/Response201'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
definitions:
  RequestModel:
    type: object
    description: This request object used by the post operation
    properties:
      requestId:
        type: integer
      destinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      requesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      laborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      sourceDetails:
        $ref: '#/definitions/SourceDetails_Type'
      requestDetails:
        $ref: '#/definitions/RequestDetails_Type'
      balanceType:
        type: integer
      transferType:
        type: integer
      statusId:
        type: integer
      releaseDate:
        type: string
      pageSize:
        type: integer
      pageIndex:
        type: integer
  DestinationDetails_Type:
    type: object
    properties:
      destinationLaborOfficeId:
        type: integer
      destinationSequenceNumber:
        type: integer
      destinationEstablishmentId:
        type: integer
      destinationEntityId:
        type: string
  RequesterDetails_Type:
    type: object
    properties:
      requesterUserId:
        type: integer
      requesterIdNo:
        type: string
  SourceDetails_Type:
    type: object
    properties:
      sourceLaborOfficeId:
        type: integer
      sourceSequenceNumber:
        type: integer
      sourceEstablishmentId:
        type: integer
      sourceEntityId:
        type: string
  RequestDetails_Type:
    type: object
    properties:
      requestSequence:
        type: integer
      requestYear:
        type: integer
  LaborerDetails_Type:
    type: object
    properties:
      laborerIdNo:
        type: string
      laborerName:
        type: string
      laborerNationalityId:
        type: integer
      laborerNationalityName:
        type: string
      laborerBorderNum:
        type: string
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      ChangeSponsorList:
        $ref: '#/definitions/ChangeSponsorList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  ChangeSponsorList_Type:
    type: object
    properties:
      ChangeSponsorItem:
        type: array
        items:
          $ref: '#/definitions/ChangeSponsorItem_Type'
    required:
    - ChangeSponsorItem
  ChangeSponsorItem_Type:
    type: object
    properties:
      RequestId:
        type: integer
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      Balance:
        $ref: '#/definitions/Balance_Type'
      UserId:
        type: integer
      IdNo:
        type: string
      RequestDate:
        type: string
      LaborerTransfersTotalCount:
        type: integer
      PaymentReference:
        type: string
      RequestDetailsCount:
        type: integer
      RequestDetailsList:
        $ref: '#/definitions/RequestDetailsList_Type'
    required:
    - RequestId
    - DestinationDetails
    - Balance
    - UserId
    - IdNo
    - RequestDate
    - LaborerTransfersTotalCount
    - PaymentReference
    - RequestDetailsCount
    - RequestDetailsList
  Balance_Type:
    type: object
    properties:
      Balance:
        type: integer
      BalanceTypeId:
        type: integer
      BalanceTypeEn:
        type: string
      BalanceTypeAr:
        type: string
    required:
    - Balance
    - BalanceTypeId
    - BalanceTypeEn
    - BalanceTypeAr
  TransferType_Type:
    type: object
    properties:
      TransferTypeId:
        type: integer
      TransferTypeEn:
        type: string
      TransferTypeAr:
        type: string
    required:
    - TransferTypeId
    - TransferTypeEn
    - TransferTypeAr
  RequestDetailsList_Type:
    type: object
    properties:
      RequestDetailsItem:
        type: array
        items:
          $ref: '#/definitions/RequestDetailsItem_Type'
    required:
    - RequestDetailsItem
  RequestDetailsItem_Type:
    type: object
    properties:
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      RequestDetails:
        $ref: '#/definitions/RequestDetails_Type'
      SponsorId:
        type: string
      SourceDetails:
        $ref: '#/definitions/SourceDetails_Type'
      TransferType:
        $ref: '#/definitions/TransferType_Type'
      Status:
        $ref: '#/definitions/Status_Type'
      NICRejectionId:
        type: integer
      RejectionDescription:
        type: string
      CSRelatedContractId:
        type: integer
      ReleaseDate:
        type: string
      ReleaseDateType:
        $ref: '#/definitions/CodeName_Type'
      RemainingDays:
        type: integer
      CurrentContractId:
        type: integer
      DestinationUnifiedNationalNo:
        type: string
      DestOwnerId:
        type: integer
      DestEstablishmentTypeId:
        type: integer
      DestSevenHundredNo:
        type: integer
      DestUseUnifiedNationalNoFlag:
        type: integer
      RequestNumber:
        type: string
    required:
    - LaborerDetails
    - RequestDetails
    - SponsorId
    - SourceDetails
    - TransferType
    - Status
    - NICRejectionId
    - RejectionDescription
    - CSRelatedContractId
    - ReleaseDate
    - ReleaseDateType
    - RemainingDays
    - CurrentContractId
    - RequestNumber
  Status_Type:
    type: object
    properties:
      StatusId:
        type: integer
      StatusEn:
        type: string
      StatusAr:
        type: string
    required:
    - StatusId
    - StatusEn
    - StatusAr
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
responses:
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-emtf-etutilities)/changesponsor/ajeersearchchangesponsorrequests
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
