swagger: "2.0"
info:
  title: Anil_Test
  x-ibm-name: anil-test
  version: 1.0.0
schemes:
- https
basePath: /anil-test
produces:
- application/xml
consumes:
- application/json
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - json-to-xml:
        version: 2.0.0
        title: json-to-xml
        root-element-name: json
        always-output-root-element: false
        unnamed-element-name: element
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
paths:
  /test:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    options:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
