swagger: "2.0"
info:
  title: ApproveRejectSeasEndorse
  x-ibm-name: approverejectseasendorse
  version: 1.0.1
  description: This service is used to approve or reject seasonal endorsement
schemes:
- https
basePath: /visa/seasonalvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-sese-seassubmits)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  ApproveRejectSeasEndorseRq_MessageType:
    type: object
    properties:
      ApproveRejectSeasEndorseRq:
        $ref: '#/definitions/ApproveRejectSeasEndorseRq_Type'
  ApproveRejectSeasEndorseRs_MessageType:
    type: object
    properties:
      ApproveRejectSeasEndorseRs:
        $ref: '#/definitions/ApproveRejectSeasEndorseRs_Type'
  ApproveRejectSeasEndorseRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ApproveRejectSeasEndorseRq_BodyType'
  ApproveRejectSeasEndorseRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      IsApproved:
        type: integer
      EndorsementId:
        type: integer
      EndorsementDetalisList:
        $ref: '#/definitions/EndorsementDetalisList_Type'
      RejectReason:
        type: string
      ResubmissionReason:
        type: string
      ChangeVisaCountReason:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - IsApproved
    - EndorsementId
  EndorsementDetalisList_Type:
    type: object
    properties:
      EndorsementDetailsItem:
        type: array
        items:
          $ref: '#/definitions/EndorsementDetailsItem_Type'
  EndorsementDetailsItem_Type:
    type: object
    properties:
      NationalityId:
        type: integer
      OccupationId:
        type: integer
      ReligionId:
        type: integer
      GenderId:
        type: integer
      TotalVisaNo:
        type: integer
      NbOfVisasGrantedMLSD:
        type: integer
  ApproveRejectSeasEndorseRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ApproveRejectSeasEndorseRs_BodyType'
  ApproveRejectSeasEndorseRs_BodyType:
    type: object
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /apprejcseasendorse:
    post:
      operationId: ApproveRejectSeasEndorse
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ApproveRejectSeasEndorseRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: ApproveRejectSeasEndorse
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ApproveRejectSeasEndorseRq_MessageType'
        description: ApproveRejectSeasEndorseRq
        required: true
