swagger: "2.0"
info:
  title: AssignUnassignAppointments
  x-ibm-name: assignunassignappointments
  version: 1.0.0
  description: AssignUnassignAppointments - PROD Yaml
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-appointment)/qiwalo/assignunassignappointments
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  AssignUnassignAppointmentsRq_MessageType:
    type: object
    properties:
      AssignUnassignAppointmentsRq:
        $ref: '#/definitions/AssignUnassignAppointmentsRq_Type'
  AssignUnassignAppointmentsRs_MessageType:
    type: object
    properties:
      AssignUnassignAppointmentsRs:
        $ref: '#/definitions/AssignUnassignAppointmentsRs_Type'
  AssignUnassignAppointmentsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/AssignUnassignAppointmentsRq_BodyType'
  AssignUnassignAppointmentsRq_BodyType:
    type: object
    properties:
      AppointmentId:
        type: integer
      OfficeID:
        type: integer
      AgentIdNo:
        type: integer
      AssignFlag:
        type: integer
    required:
    - AppointmentId
    - OfficeID
    - AgentIdNo
    - AssignFlag
  AssignUnassignAppointmentsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /assignunassignappointments:
    post:
      operationId: AssignUnassignAppointments
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/AssignUnassignAppointmentsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Assign Unassign Appointments
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/AssignUnassignAppointmentsRq_MessageType'
        description: AssignUnassignAppointmentsRq
        required: true
