swagger: "2.0"
info:
  title: Async Data History Revised
  x-ibm-name: async-data-history-revised
  version: 3.0.4
schemes:
- https
basePath: /qiwa/v2
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: ""
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |-
          var apim = require('apim');

          apim.setvariable('message.headers.Authorization','Basic bW9sX3VzcjpNMGxAZzBzaQ==');
          apim.setvariable('message.headers.Content-Type','application/json');
          apim.setvariable('message.headers.Accept','*/*');
          apim.setvariable('message.headers.Accept-Encoding','gzip, deflate, br');


          var message = apim.getvariable('message.body');
          var vID = message.GetLbrHistDataRq.LaborId;

          var body = '{"query":"{ContributorHistoryEngagement(ID:'+ vID + ') {SOCIALINSURANCENUMBER,    SPECIALIZATIONCODE,   CONTRACTLASTMODIFIE,   ENGAGEMENTLASTMODIFIE,   MOBILENUMBER,    EMAILID,    EDUCATION,    OCCUPATIONCODE,    WORKTYPE,  NATIONALUNIFIEDNO,   ENGAGEMENTSTATUS,    JOININGDATE,    LEAVINGDATE,    REASONFORLEAVING,    REGISTRATIONNUMBER,    COMMERCIALREGISTRATIONNUMBER,    ESTABLISHMENTNAMEARB,    ESTABLISHMENTNAMEENG,    MOLESTID,    MOLESTOFFICEID,    MOLOFFICEID,    MOLUNIID,  ID,   BASICWAGE,    HOUSINGBENEFIT,    COMMISSION,    OTHERALLOWANCE,    STATUS,    CONTRACTTYPE,    STARTDATE,    ENDDATE,    NOTICEPERIOD,    JOBTITLEARB,    JOBTITLEENG,    WORKCITY,    WORKCOUNTRY  }}","variables":{}}';
          //var body = '{ ContributorHistoryEngagement(ID:'+ vID '+){BASICWAGE,COMMERCIALREGISTRATIONNUMBER,COMMISSION,CONTRACTLASTMODIFIE,CONTRACTTYPE,EDUCATION,EMAILID,ENDDATE,ENGAGEMENTLASTMODIFIE,ENGAGEMENTSTATUS,ESTABLISHMENTNAMEARB,ESTABLISHMENTNAMEENG,HOUSINGBENEFIT,ID,JOBTITLEARB,JOBTITLEENG,JOININGDATE,LEAVINGDATE,MOBILENUMBER,MOLESTID,MOLESTOFFICEID,MOLOFFICEID,MOLUNIID,NATIONALUNIFIEDNO,NOTICEPERIOD,OCCUPATIONCODE,OTHERALLOWANCE,REASONFORLEAVING,REGISTRATIONNUMBER,SOCIALINSURANCENUMBER,SPECIALIZATIONCODE,STARTDATE,STATUS,WORKCITY,WORKCOUNTRY,WORKTYPE    }}';


          //apim.setvariable('message.body',body);
          session.output.write(body);
          //apim.setvariable('message.body',apim.getvariable('message.body'));

          apim.output('application/json');
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        target-url: $(dp-gosi-contract)/denodo-graphql-service/graphql/GOSI_MOL
        username: mol_usr
        password: M0l@g0si
    catch: []
  properties: {}
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
paths:
  /getasynchistorydatarevised:
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
