swagger: "2.0"
info:
  title: CalculateChangeSponsorBalance
  x-ibm-name: calculatechangesponsorbalance
  version: 1.0.0
  description: This service is used to calculate available laborers to be transferred.
schemes:
- https
basePath: /changesponsor
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-emtf-calcchsp)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |
          var apim = require('apim');
          var Response = apim.getvariable('message.body');
          var statusCode = Response.CalculateChangeSponsorBalanceRs.Header.ResponseStatus.Code ;


          if(statusCode == 'E9999998'){
              var code = 408
              apim.setvariable('message.status.code',code,'set');
          }
          else if(statusCode == '00000000'){
              var code = 200
              apim.setvariable('message.status.code',code,'set');
          }else{
                var code = 409
              apim.setvariable('message.status.code',code,'set');
          }
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CalculateChangeSponsorBalanceRq_MessageType:
    type: object
    properties:
      CalculateChangeSponsorBalanceRq:
        $ref: '#/definitions/CalculateChangeSponsorBalanceRq_Type'
  CalculateChangeSponsorBalanceRs_MessageType:
    type: object
    properties:
      CalculateChangeSponsorBalanceRs:
        $ref: '#/definitions/CalculateChangeSponsorBalanceRs_Type'
  CalculateChangeSponsorBalanceRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CalculateChangeSponsorBalanceRq_BodyType'
  CalculateChangeSponsorBalanceRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      ValidationLevel:
        type: integer
      EstablishmentConditionsType:
        type: integer
      SizeId:
        type: integer
      TierId:
        type: integer
      SubEconomicActivityId:
        type: integer
    required:
    - LaborOfficeId
    - EstablishmentSequence
  CalculateChangeSponsorBalanceRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CalculateChangeSponsorBalanceRs_BodyType'
  CalculateChangeSponsorBalanceRs_BodyType:
    type: object
    properties:
      Balance:
        $ref: '#/definitions/Balance'
      EstablishmentConditionsType:
        type: integer
      ProfSkillsExempted:
        type: integer
      QuotaMaxHigh:
        type: integer
      QuotaMaxMedLow:
        type: integer
      QuotaMaxLow:
        type: integer
      CurrentHigh:
        type: integer
      CurrentMed:
        type: integer
      CurrentLow:
        type: integer
      MediumLowOccPercentage:
        type: number
      LowOccPercentage:
        type: number
      UnUsedIssuedVisaCount:
        type: integer
      TierId:
        type: integer
      SizeId:
        type: integer
      ExpiredEstablishmentId:
        type: integer
      EntityNoteSourceList:
        $ref: '#/definitions/EntityNoteSourceList_Type'
      EstablishmentStatusId:
        type: integer
      CREndDate:
        type: string
      AllowanceStartDate:
        type: string
      AllowanceEndDate:
        type: string
      EconomicActivityId:
        type: integer
      ColorId:
        type: integer
      EntityId:
        type: integer
      EstablishmentId:
        type: integer
      Expansion:
        $ref: '#/definitions/Expansion_Type'
      ProfSkillsDetails:
        $ref: '#/definitions/ProfSkillsDetails_Type'
      Establishing:
        $ref: '#/definitions/Establishing_Type'
      RealEntitiesForeignersCount:
        type: integer
  Expansion_Type:
    type: object
    properties:
      EntityAjeerPendingLaborers:
        type: integer
      EntityCLBLaborers:
        type: integer
      issuedVisas:
        type: integer
      PendingValue:
        type: integer
      NotUsedVisas:
        type: integer
      CurrentLaborers:
        type: number
      EntityForeignersTotalFactorized:
        type: number
      EntitySaudisTotalFactorized:
        type: number
      EntitySaudiPercentage:
        type: number
      EconomicActivityId:
        type: integer
      ColorId:
        type: integer
      SizeId:
        type: integer
      Quota:
        type: integer
  Establishing_Type:
    type: object
    properties:
      AvailableVisas:
        type: integer
      CurrentLaborers:
        type: integer
      PendingEstablishingVisaRequests:
        type: integer
      PendingSponsorTransferRequests:
        type: integer
      NotUsedVisas:
        type: integer
      EntityAjeerPendingLaborers:
        type: integer
  ProfSkillsDetails_Type:
    type: object
    properties:
      ProfSkillsExempted:
        type: integer
      QuotaMaxHigh:
        type: integer
      QuotaMaxMedLow:
        type: integer
      QuotaMaxLow:
        type: integer
      QuotaRealMaxHigh:
        type: integer
      QuotaRealMaxMedLow:
        type: integer
      QuotaRealMaxLow:
        type: integer
      CurrentHigh:
        type: integer
      CurrentMed:
        type: integer
      CurrentLow:
        type: integer
      CurrentMedLow:
        type: integer
      ETHighSkillOccupations:
        type: integer
      ETMediumSkillOccupations:
        type: integer
      ETLowSkillOccupations:
        type: integer
      CurrentProffSkillsUsedBalance:
        type: integer
      TotalQuota:
        type: integer
      HighSalarythreshold:
        type: integer
      MediumSalarythreshold:
        type: integer
      MediumLowOccPercentage:
        type: integer
      LowOccPercentage:
        type: integer
      HighHiringCapacity:
        type: integer
      MedLowHiringCapacity:
        type: integer
      LowHiringCapacity:
        type: integer
      PotentialHighRemaining:
        type: integer
      PotentialMedLowRemaining:
        type: integer
      PotentialLowRemaining:
        type: integer
  Balance:
    type: object
    properties:
      AvailableBalance:
        type: integer
      BalanceType:
        type: integer
  EntityNoteSourceList_Type:
    type: object
    properties:
      EntityNoteSourceItem:
        type: array
        items:
          $ref: '#/definitions/EntityNoteSourceItem_Type'
  EntityNoteSourceItem_Type:
    type: object
    properties:
      NoteSourceId:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /calculatechangesponsorbalance:
    post:
      operationId: CalculateChangeSponsorBalance
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CalculateChangeSponsorBalanceRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: CalculateChangeSponsorBalance
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CalculateChangeSponsorBalanceRq_MessageType'
        description: CalculateChangeSponsorBalanceRq
        required: true
