swagger: "2.0"
info:
  title: ChangeEstabActivity
  x-ibm-name: changeestabactivity
  version: 1.0.0
  description: Change Establishment Activity
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-change-estab-activity)/estabmanagement/changeestabact
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  ChangeEstabActivityRq_MessageType:
    type: object
    properties:
      ChangeEstabActivityRq:
        $ref: '#/definitions/ChangeEstabActivityRq_Type'
  ChangeEstabActivityRs_MessageType:
    type: object
    properties:
      ChangeEstabActivityRs:
        $ref: '#/definitions/ChangeEstabActivityRs_Type'
  ChangeEstabActivityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ChangeEstabActivityRq_BodyType'
  ChangeEstabActivityRq_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      NewIsic4ActivityId:
        type: integer
      NewRequiredSaudLevel:
        type: string
      CurrentRequiredSaudLevel:
        type: string
      ChangeActivityReasonId:
        type: integer
      OtherChangeActivityReasonText:
        type: string
      ChangeActivityNote:
        type: string
      LicenseNumber:
        type: string
      LicenseIssueDate:
        type: string
      LicenseExpiryDate:
        type: string
      Attachment:
        $ref: '#/definitions/Attachment_Type'
  ChangeEstabActivityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ChangeEstabActivityRs_BodyType'
  Attachment_Type:
    type: object
    properties:
      AttachmentDetails:
        type: array
        items:
          $ref: '#/definitions/AttachmentDetails_Type'
  AttachmentDetails_Type:
    type: object
    properties:
      AttachmentId:
        type: string
      AttachmentName:
        type: string
  ChangeEstabActivityRs_BodyType:
    type: object
    properties:
      Message:
        type: string
      RequestId:
        type: integer
      RequestNumber:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /changeestabact:
    post:
      operationId: ChangeEstabActivity
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ChangeEstabActivityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Change Establishment Activity
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ChangeEstabActivityRq_MessageType'
        description: ChangeEstabActivityRq
        required: true
