swagger: "2.0"
info:
  title: Chatbot_Init
  x-ibm-name: chatbot_init
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(dp-qiwadp-qiwahrsdrouter)/api/chat/init
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /api/chat
paths:
  /init:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecret:
    type: apiKey
    x-key-type: client_secret
    name: X-IBM-Client-Secret
    in: header
schemes:
- https
security:
- clientID: []
  clientSecret: []
