swagger: "2.0"
info:
  title: CheckVisasNICStatus
  version: 1.0.0
  description: Check Visas NIC Status
  x-ibm-name: checkvisasnicstatus
paths:
  /CheckvisasNICstatus:
    post:
      operationId: CheckVisasNICStatus
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckVisasNICStatusRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: CheckVisasNICStatus
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckVisasNICStatusRq_MessageType'
        description: CheckVisasNICStatusRq
        required: true
basePath: /common
definitions:
  CheckVisasNICStatusRq_MessageType:
    type: object
    properties:
      CheckVisasNICStatusRq:
        $ref: '#/definitions/CheckVisasNICStatusRq_Type'
  CheckVisasNICStatusRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckVisasNICStatusRq_BodyType'
  CheckVisasNICStatusRq_BodyType:
    type: object
    properties:
      BorderNumber:
        type: integer
    required:
    - BorderNumber
  CheckVisasNICStatusRs_MessageType:
    type: object
    properties:
      CheckVisasNICStatusRs:
        $ref: '#/definitions/CheckVisasNICStatusRs_Type'
  CheckVisasNICStatusRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckVisasNICStatusRs_BodyType'
  CheckVisasNICStatusRs_BodyType:
    type: object
    properties:
      CurrentQiwaStatus:
        $ref: '#/definitions/CodeName_Type'
      CurrentNICStatus:
        $ref: '#/definitions/CodeName_Type'
      Action:
        type: string
    required:
    - CurrentQiwaStatus
    - CurrentNICStatus
    - Action
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: integer
      NameEn:
        type: integer
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-nic-nicsubmit)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
