swagger: "2.0"
info:
  title: CheckEstabMgntFlow
  x-ibm-name: checkestabmgntflow
  version: 1.0.0
  description: This service is used to check establishment activation for the requested
    CR number.
schemes:
- https
basePath: /estabmanagement
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-estabmanagement)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CheckEstabMgntFlowRq_MessageType:
    type: object
    properties:
      CheckEstabMgntFlowRq:
        $ref: '#/definitions/CheckEstabMgntFlowRq_Type'
  CheckEstabMgntFlowRs_MessageType:
    type: object
    properties:
      CheckEstabMgntFlowRs:
        $ref: '#/definitions/CheckEstabMgntFlowRs_Type'
  CheckEstabMgntFlowRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckEstabMgntFlowRq_BodyType'
  CheckEstabMgntFlowRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: string
        default: "1010479191"
    required:
    - CRNumber
  CheckEstabMgntFlowRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckEstabMgntFlowRs_BodyType'
  CheckEstabMgntFlowRs_BodyType:
    type: object
    properties:
      Message:
        $ref: '#/definitions/Message_Type'
      CRInfo:
        $ref: '#/definitions/CRInfo_Type'
      CROwnerList:
        $ref: '#/definitions/CROwnerList_Type'
      MainEstInfo:
        $ref: '#/definitions/MainEstInfo_Type'
      Nitaqat:
        type: integer
      FileType:
        type: integer
    required:
    - CRInfo
    - Message
    - CROwnerList
    - MainEstInfo
    - Nitaqat
    - FileType
  Message_Type:
    type: object
    properties:
      Code:
        type: integer
      Message:
        type: string
    required:
    - Code
    - Message
  CRInfo_Type:
    type: object
    properties:
      CRNumber:
        type: integer
      MainCRNumber:
        type: string
      CRExpiryDate:
        $ref: '#/definitions/Date_Type'
      CRIssueDate:
        $ref: '#/definitions/Date_Type'
      CRStatus:
        $ref: '#/definitions/CRStatus_Type'
      CRType:
        type: string
      CRListOfISICActivities:
        $ref: '#/definitions/CRListOfISICActivities_Type'
      NationalNumber:
        type: string
      CRCity:
        $ref: '#/definitions/CRCity_Type'
      CRNameAR:
        type: string
      CRCapital:
        type: string
      CRLegalType:
        $ref: '#/definitions/CRLegalType_Type'
      CRPhoneNo:
        type: string
      CRFaxNo:
        type: string
      CRAddress:
        type: string
    required:
    - CRNumber
    - MainCRNumber
    - CRExpiryDate
    - CRIssueDate
    - CRStatus
    - CRType
    - CRListOfISICActivities
    - NationalNumber
    - CRCity
    - CRNameAR
    - CRCapital
    - CRLegalType
    - CRPhoneNo
    - CRFaxNo
    - CRAddress
  Date_Type:
    type: object
    properties:
      Hijri:
        type: string
      Gregorian:
        type: string
  CROwnerList_Type:
    type: object
    properties:
      CROwner:
        items:
          $ref: '#/definitions/CROwner_Type'
  MainEstInfo_Type:
    type: object
    properties:
      MainUNLaborOfficeId:
        type: string
      MainUNSequenceNumber:
        type: string
      MainEstLaborOfficeId:
        type: string
      MainEstSequenceNumber:
        type: string
      MainUnifiedNationalNumber:
        type: string
      MainEstablishmentName:
        type: string
      MainEstablishmentNationality:
        type: string
      MainOwnershipType:
        type: string
      MainOwner:
        $ref: '#/definitions/Owner_Type'
      MainSevenHundredNumber:
        type: string
      MainLegalType:
        type: string
    required:
    - MainUNLaborOfficeId
    - MainUNSequenceNumber
    - MainEstLaborOfficeId
    - MainEstSequenceNumber
    - MainUnifiedNationalNumber
    - MainEstablishmentName
    - MainEstablishmentNationality
    - MainOwnershipType
  Owner_Type:
    type: object
    properties:
      ID:
        type: string
      Name:
        type: string
  CRStatus_Type:
    type: object
    properties:
      Status:
        type: string
      CRStatusDate:
        type: string
      CRStatusReason:
        type: string
  CRListOfISICActivities_Type:
    type: object
    properties:
      Activity:
        type: array
        items:
          $ref: '#/definitions/Activity_Type'
  CRCity_Type:
    type: object
    properties:
      CityAR:
        type: string
      CityEN:
        type: string
  CRLegalType_Type:
    type: object
    properties:
      TypeAR:
        type: string
      TypeEN:
        type: string
  CROwner_Type:
    type: object
    properties:
      Name:
        type: string
      ID:
        $ref: '#/definitions/ID_Type'
      PersonIdentifier:
        $ref: '#/definitions/PersonIdentifier_Type'
      PassportIdentifier:
        $ref: '#/definitions/PassportIdentifier_Type'
      PassportIssueDate:
        $ref: '#/definitions/Date_Type'
      PassportExpiryDate:
        $ref: '#/definitions/Date_Type'
      Nationality:
        $ref: '#/definitions/Nationality_Type'
      RelationType:
        type: string
  Activity_Type:
    type: object
    properties:
      isICCode:
        type: string
      isicName:
        type: string
  ID_Type:
    type: object
    properties:
      BorderNumber:
        type: string
      Code700:
        type: string
      CRNumber:
        type: string
  PersonIdentifier_Type:
    type: object
    properties:
      NationalID:
        type: string
      IqamaNumber:
        type: string
  PassportIdentifier_Type:
    type: object
    properties:
      PassportNumber:
        type: string
      PassportIssuePlaceName:
        type: string
  Nationality_Type:
    type: object
    properties:
      NationalityAR:
        type: string
      NationalityEN:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CEMF0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CEMF0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23432"
      IDNumber:
        type: integer
        default: "324324"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /chkestabmgntflow:
    post:
      operationId: CheckEstabMgntFlow
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckEstabMgntFlowRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: CheckEstabMgntFlow
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckEstabMgntFlowRq_MessageType'
        description: CheckEstabMgntFlow
        required: true
