swagger: "2.0"
info:
  title: CheckandValidateTransferredEmployee
  x-ibm-name: checkandvalidatetransferredemployee
  version: 1.0.0
  description: This service is used to check and validate the transferred employee
schemes:
- https
basePath: /changesponsor
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-emtf-chkandval)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: |
          var apim = require('apim');
          var Response = apim.getvariable('message.body');
          var statusCode = Response.CheckandValidateTransferredEmployeeRs.Header.ResponseStatus.Code ;


          if(statusCode == 'E9999998'){
              var code = 408
              apim.setvariable('message.status.code',code,'set');
          }
          else if(statusCode == '00000000'){
              var code = 200
              apim.setvariable('message.status.code',code,'set');
          }else{
                var code = 409
              apim.setvariable('message.status.code',code,'set');
          }
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  CheckandValidateTransferredEmployeeRq_MessageType:
    type: object
    properties:
      CheckandValidateTransferredEmployeeRq:
        $ref: '#/definitions/CheckandValidateTransferredEmployeeRq_Type'
  CheckandValidateTransferredEmployeeRs_MessageType:
    type: object
    properties:
      CheckandValidateTransferredEmployeeRs:
        $ref: '#/definitions/CheckandValidateTransferredEmployeeRs_Type'
  CheckandValidateTransferredEmployeeRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckandValidateTransferredEmployeeRq_BodyType'
  CheckandValidateTransferredEmployeeRq_BodyType:
    type: object
    properties:
      IdNo:
        type: string
      BirthDate:
        type: string
      DestinationLaborOfficeId:
        type: integer
      DestinationSequenceNumber:
        type: integer
    required:
    - IdNo
    - DestinationLaborOfficeId
    - DestinationSequenceNumber
  CheckandValidateTransferredEmployeeRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckandValidateTransferredEmployeeRs_BodyType'
  CheckandValidateTransferredEmployeeRs_BodyType:
    type: object
    properties:
      TransferType:
        $ref: '#/definitions/CodeName_type'
      IsEligible:
        type: integer
      NotEligibilityReasons:
        $ref: '#/definitions/NonEligibilityReasons_Type'
      DestinationDetails:
        $ref: '#/definitions/DestinationDetails_Type'
      SouceDetails:
        $ref: '#/definitions/SourceDetails_Type'
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      'SponsorDetails ':
        $ref: '#/definitions/SponsorDetails_Type'
    required:
    - TransferType
    - IsEligible
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  NonEligibilityReasons_Type:
    type: object
    properties:
      ReasonDetails:
        type: array
        items:
          $ref: '#/definitions/ReasonDetails_Type'
  SponsorDetails_Type:
    type: object
    properties:
      SponsorIdNo:
        type: string
      SponsorName:
        type: string
  LaborerDetails_Type:
    type: object
    properties:
      LaborerName:
        type: string
      LaborerIdNo:
        type: string
      LaboreNationality:
        $ref: '#/definitions/CodeName_type'
      IqamaExpiryDate:
        type: string
      'IsRegistered ':
        type: integer
      BirthDate:
        type: string
      BorderNumber:
        type: string
      Gender:
        type: string
      WorkPermitEndDate:
        type: string
      PassportNumber:
        type: string
      Occupation:
        $ref: '#/definitions/CodeName_type'
      LaborerStatusCode:
        type: integer
      ServiceEndDate:
        type: string
    required:
    - LaborerName
    - LaborerIdNo
    - LaboreNationality
  SourceDetails_Type:
    type: object
    properties:
      EstablishmentName:
        type: string
      EstablishmentId:
        type: string
      LaborOfficeId:
        type: string
      SequenceNumber:
        type: string
      EntityId:
        type: string
      NICAccountNumber:
        type: string
    required:
    - EstablishmentName
    - EstablishmentId
    - LaborOfficeId
  DestinationDetails_Type:
    type: object
    properties:
      EstablishmentName:
        type: string
      EstablishmentId:
        type: string
      EntityId:
        type: string
    required:
    - EstablishmentName
    - EstablishmentId
    - EntityId
  ReasonDetails_Type:
    type: object
    properties:
      ReasonCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - EnDescription
    - ArDescription
    - ReasonCode
  CodeName_type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
paths:
  /checkandvatransemp:
    post:
      operationId: CheckandValidateTransferredEmployee
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckandValidateTransferredEmployeeRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Check and Validate Transferred Employee
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckandValidateTransferredEmployeeRq_MessageType'
        description: Check and Validate Transferred Employee
        required: true
