swagger: "2.0"
info:
  title: CheckTransferLaborerEligibility
  x-ibm-name: checktransferlaborereligibility
  version: 1.0.0
  description: This service is used to check the eligibility of the transferred laborer
    under the same unified number.
schemes:
- https
basePath: /transferlaborer
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-emtf-etutilities)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CheckTransferLaborerEligibilityRq_MessageType:
    type: object
    properties:
      CheckTransferLaborerEligibilityRq:
        $ref: '#/definitions/CheckTransferLaborerEligibilityRq_Type'
  CheckTransferLaborerEligibilityRs_MessageType:
    type: object
    properties:
      CheckTransferLaborerEligibilityRs:
        $ref: '#/definitions/CheckTransferLaborerEligibilityRs_Type'
  CheckTransferLaborerEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckTransferLaborerEligibilityRq_BodyType'
  CheckTransferLaborerEligibilityRq_BodyType:
    type: object
    properties:
      LaborerStatusCode:
        type: integer
        default: "1"
      HasPendingRequests:
        type: boolean
        default: "False"
      CurrentEstablishmentActivity:
        type: integer
        default: "1"
      CurrentUnifiedNumber:
        type: integer
        default: "1"
      CurrentLaborOfficeId:
        type: integer
        default: "1"
      CurrentSequenceNumber:
        type: integer
        default: "1"
      DestinationLaborOfficeId:
        type: integer
        default: "1"
      DestinationSequenceNumber:
        type: integer
        default: "1"
      DestinationUnifiedNumber:
        type: integer
        default: "1"
    required:
    - LaborerStatusCode
    - HasPendingRequests
    - CurrentEstablishmentActivity
    - CurrentUnifiedNumber
    - CurrentLaborOfficeId
    - CurrentSequenceNumber
    - DestinationLaborOfficeId
    - DestinationSequenceNumber
    - DestinationUnifiedNumber
  CheckTransferLaborerEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckTransferLaborerEligibilityRs_BodyType'
  CheckTransferLaborerEligibilityRs_BodyType:
    type: object
    properties:
      ErrorsList:
        $ref: '#/definitions/ErrorsList_Type'
  ErrorsList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CTLE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CTLE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /checktransferlaborereligibility:
    post:
      operationId: CheckTransferLaborerEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckTransferLaborerEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Service Sustainability Configuration
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckTransferLaborerEligibilityRq_MessageType'
        description: CheckTransferLaborerEligibilityRq
        required: true
