swagger: "2.0"
info:
  title: CheckSaudiCertifEligibility
  x-ibm-name: checksaudicertifeligibility
  version: 1.0.0
  description: This service is used to check if the establishment is eligible to get
    Saudization certificate.
schemes:
- https
basePath: /saudicer
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-saudi-certificate)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  CheckSaudiCertifEligibilityRq_MessageType:
    type: object
    properties:
      CheckSaudiCertifEligibilityRq:
        $ref: '#/definitions/CheckSaudiCertifEligibilityRq_Type'
  CheckSaudiCertifEligibilityRs_MessageType:
    type: object
    properties:
      CheckSaudiCertifEligibilityRs:
        $ref: '#/definitions/CheckSaudiCertifEligibilityRs_Type'
  CheckSaudiCertifEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckSaudiCertifEligibilityRq_BodyType'
  CheckSaudiCertifEligibilityRq_BodyType:
    type: object
    properties:
      EstabStatus:
        type: integer
        default: "23435"
      EstabColor:
        type: integer
        default: "12"
    required:
    - EstabStatus
    - EstabColor
  CheckSaudiCertifEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckSaudiCertifEligibilityRs_BodyType'
  CheckSaudiCertifEligibilityRs_BodyType:
    type: object
    properties:
      ErrorsList:
        $ref: '#/definitions/ErrorsList_Type'
    required:
    - ErrorsList
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CSCE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CSCE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "2342423"
      IDNumber:
        type: integer
        default: "2342343"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  EstablishmentsList_Type:
    type: object
    properties:
      EstablishmentItem:
        type: string
  ErrorsList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - EnDescription
    - ArDescription
    - ErrorCode
paths:
  /checksaudicerelig:
    post:
      operationId: CheckSaudiCertifEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckSaudiCertifEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Check Saudi CertifEligibility
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckSaudiCertifEligibilityRq_MessageType'
        description: CheckSaudiCertifEligibilityRq
        required: true
