swagger: "2.0"
info:
  title: CheckUserEstablishmentsEligibility
  x-ibm-name: checkuserestablishmentseligibility
  version: 1.0.1
  description: This service is used to check user validity in many establishments.---
    PROD yaml
schemes:
- https
basePath: /usermanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-usrm-checksandgetum)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CheckUserEstablishmentsEligibilityRq_MessageType:
    type: object
    properties:
      CheckUserEstablishmentsEligibilityRq:
        $ref: '#/definitions/CheckUserEstablishmentsEligibilityRq_Type'
  CheckUserEstablishmentsEligibilityRs_MessageType:
    type: object
    properties:
      CheckUserEstablishmentsEligibilityRs:
        $ref: '#/definitions/CheckUserEstablishmentsEligibilityRs_Type'
  CheckUserEstablishmentsEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckUserEstablishmentsEligibilityRq_BodyType'
  CheckUserEstablishmentsEligibilityRq_BodyType:
    type: object
    properties:
      IdNo:
        type: string
        default: "1058873835"
      EstablishmentsList:
        $ref: '#/definitions/EstablishmentsList_Type'
      ServiceId:
        type: integer
        default: "1"
      ListAll:
        type: integer
        default: "1"
  EstablishmentsList_Type:
    type: object
    properties:
      EstablishmentsItem:
        type: array
        items:
          $ref: '#/definitions/EstablishmentsItem_Type'
  EstablishmentsItem_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "234"
      EstablishmentSequence:
        type: integer
        default: "342"
  CheckUserEstablishmentsEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckUserEstablishmentsEligibilityRs_BodyType'
  CheckUserEstablishmentsEligibilityRs_BodyType:
    type: object
    properties:
      EligibleEstablishmentsList:
        $ref: '#/definitions/EligibleEstablishments_Type'
      NonEligibleEstablishmentsList:
        $ref: '#/definitions/NonEligibleEstablishments_Type'
  EligibleEstablishments_Type:
    type: object
    properties:
      EligibleEstablishmentsItem:
        type: array
        items:
          $ref: '#/definitions/EligibleEstablishmentsItem_Type'
  NonEligibleEstablishments_Type:
    type: object
    properties:
      NonEligibleEstablishmentsItem:
        type: array
        items:
          $ref: '#/definitions/NonEligibleEstablishmentsItem_Type'
  EligibleEstablishmentsItem_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      EstablishmentName:
        type: string
      IsMainBranch:
        type: string
      UnifiedNumberId:
        type: integer
  NonEligibleEstablishmentsItem_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      EstablishmentName:
        type: string
      IsMainBranch:
        type: string
      UnifiedNumberId:
        type: integer
      EligibleForSelfSubscripition:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: CUEE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: CUEE0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /checkuserestablishmentseligibility:
    post:
      operationId: CheckUserEstablishmentsEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckUserEstablishmentsEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Check User Establishments Eligibility
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckUserEstablishmentsEligibilityRq_MessageType'
        description: CheckUserEstablishmentsEligibilityRq
        required: true
