swagger: "2.0"
info:
  title: CheckTransferredEmployeeType V2
  x-ibm-name: checktransferredemployeetype-v2
  version: 1.0.0
  description: This service is used to check and validate the transferred employee
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-contractmgmtv2)/contractmanagement/checktransferredemployeetype
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  CheckTransferredEmployeeTypeRq_MessageType:
    type: object
    properties:
      CheckTransferredEmployeeTypeRq:
        $ref: '#/definitions/CheckTransferredEmployeeTypeRq_Type'
  CheckTransferredEmployeeTypeRs_MessageType:
    type: object
    properties:
      CheckTransferredEmployeeTypeRs:
        $ref: '#/definitions/CheckTransferredEmployeeTypeRs_Type'
  CheckTransferredEmployeeTypeRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckTransferredEmployeeTypeRq_BodyType'
  CheckTransferredEmployeeTypeRq_BodyType:
    type: object
    properties:
      IdNo:
        type: string
      DestinationLaborOfficeId:
        type: integer
      DestinationSequenceNumber:
        type: integer
    required:
    - IdNo
    - DestinationLaborOfficeId
    - DestinationSequenceNumber
  CheckTransferredEmployeeTypeRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckTransferredEmployeeTypeRs_BodyType'
  CheckTransferredEmployeeTypeRs_BodyType:
    type: object
    properties:
      TransferType:
        $ref: '#/definitions/CodeName_type'
    required:
    - TransferType
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  CodeName_type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
paths:
  /checktransferredemployeetype:
    post:
      operationId: CheckTransferredEmployeeType
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckTransferredEmployeeTypeRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Check and Validate Transferred Employee
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckTransferredEmployeeTypeRq_MessageType'
        description: Check and Validate Transferred Employee
        required: true
