swagger: "2.0"
info:
  title: 'CheckAndReturnAbsherAmount '
  x-ibm-name: checkandreturnabsheramount
  version: 1.0.0
  description: 'This service is used to check if the EndorsementId has an exempted
    from visas fees or not and return Abhser Amount in case is not exempted. '
schemes:
- https
basePath: /visa/seasonalvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-sese-seasutility)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CheckAndReturnAbsherAmountRq_MessageType:
    type: object
    properties:
      CheckAndReturnAbsherAmountRq:
        $ref: '#/definitions/CheckAndReturnAbsherAmountRq_Type'
  CheckAndReturnAbsherAmountRs_MessageType:
    type: object
    properties:
      GetNitaqComplianceWeightRs:
        $ref: '#/definitions/CheckAndReturnAbsherAmountRs_Type'
  CheckAndReturnAbsherAmountRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CheckAndReturnAbsherAmountRq_BodyType'
  CheckAndReturnAbsherAmountRq_BodyType:
    type: object
    properties:
      SequenceNumber:
        type: integer
        default: "234"
      LaborOfficeId:
        type: integer
        default: "13"
      EndorsementId:
        type: integer
        default: "1653"
    required:
    - SequenceNumber
    - LaborOfficeId
    - EndorsementId
  CheckAndReturnAbsherAmountRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CheckAndReturnAbsherAmountRs_BodyType'
  CheckAndReturnAbsherAmountRs_BodyType:
    type: object
    properties:
      BalanceAmount:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /checkreturnabsheramount:
    post:
      operationId: 'CheckAndReturnAbsherAmount '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CheckAndReturnAbsherAmountRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'CheckAndReturnAbsherAmount '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CheckAndReturnAbsherAmountRq_MessageType'
        description: 'CheckAndReturnAbsherAmount '
        required: true
