swagger: "2.0"
info:
  title: CreateContractRequestDraft
  x-ibm-name: createcontractrequestdraft
  version: 1.0.0
  description: 'This service is used to create contract request draft '
schemes:
- https
basePath: /contractmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-contractmgmt)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CreateContractRequestDraftRq_MessageType:
    type: object
    properties:
      CreateContractRequestDraftRq:
        $ref: '#/definitions/CreateContractRequestDraftRq_Type'
  CreateContractRequestDraftRs_MessageType:
    type: object
    properties:
      CreateContractRequestDraftRs:
        $ref: '#/definitions/CreateContractRequestDraftRs_Type'
  CreateContractRequestDraftRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CreateContractRequestDraftRq_BodyType'
  CreateContractRequestDraftRq_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      ContractDetails:
        $ref: '#/definitions/ContractDetails_Type'
      LanguageId:
        type: integer
      DateTypeId:
        type: integer
      RelatedToId:
        type: integer
    required:
    - RequesterDetails
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      UnifiedNumberId:
        type: integer
      EntityId:
        type: string
      EstablishmentNameAr:
        type: string
      EstablishmentNameEn:
        type: string
      EstablishmentEmail:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
  LaborerDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      LaborerName:
        type: string
      LaborerTypeId:
        type: integer
      LaborerIdExpiryDate:
        type: string
      LaborerEmail:
        type: string
      LaborerMobileNumber:
        type: integer
  RequesterDetails_Type:
    type: object
    properties:
      RequesterIdNo:
        type: integer
      RequesterName:
        type: string
      RequesterUserId:
        type: integer
    required:
    - RequesterIdNo
    - RequesterName
    - RequesterUserId
  ContractDetails_Type:
    type: object
    properties:
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      LaborerJobNumber:
        type: string
      ContractTypeId:
        type: integer
      ContractDurationId:
        type: integer
      ContractPeriod:
        type: integer
      ProbationPeriod:
        type: integer
      WorkingHoursTypeId:
        type: integer
      VacationPeriod:
        type: integer
      Salary:
        type: number
      Allowances:
        $ref: '#/definitions/AllowancesItems_Type'
      StartDate:
        $ref: '#/definitions/HGDate_Type'
      ExpiryDate:
        $ref: '#/definitions/HGDate_Type'
      JoiningDate:
        type: string
      RenewalStatusId:
        type: integer
      NoticePeriod:
        type: integer
      AddedClauses:
        $ref: '#/definitions/AddedClausesItems_Type'
      SalaryFrequency:
        type: integer
      AdditionalAllowancesList:
        $ref: '#/definitions/AdditionalAllowancesList_Type'
      HoursPerWeek:
        type: integer
      DaysPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      OptionalArticles:
        $ref: '#/definitions/OptionalArticles_Type'
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
  AllowancesItems_Type:
    type: object
    properties:
      AllowancesItems:
        type: array
        items:
          $ref: '#/definitions/KeyValue_Type'
  AddedClausesItems_Type:
    type: object
    properties:
      AddedClausesItems:
        type: array
        items:
          $ref: '#/definitions/KeyValue_Type'
  KeyValue_Type:
    type: object
    properties:
      Key:
        type: string
      Value:
        type: string
  HGDate_Type:
    type: object
    properties:
      HijriDate:
        type: integer
      GregDate:
        type: string
  AdditionalAllowancesList_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/Item_Type'
  Item_Type:
    type: object
    properties:
      BenefitNameAr:
        type: string
      BenefitNameEn:
        type: string
      Frequency:
        type: integer
      AmountType:
        type: integer
      Amount:
        type: number
  OptionalArticles_Type:
    type: object
    properties:
      Period:
        type: integer
      Location:
        type: string
      WorkField:
        type: string
  CreateContractRequestDraftRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CreateContractRequestDraftRs_BodyType'
  CreateContractRequestDraftRs_BodyType:
    type: object
    properties:
      DraftId:
        type: integer
    required:
    - DraftId
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /createcontractreqdraft:
    post:
      operationId: CreateContractRequestDraft
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CreateContractRequestDraftRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Approve Change Occupation Laborer or Employer
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CreateContractRequestDraftRq_MessageType'
        description: CreateContractRequestDraftRq
        required: true
