swagger: "2.0"
info:
  title: CreateReqChangeEstActHRSD
  x-ibm-name: createreqchangeestacthrsd
  version: 1.0.0
  description: This service is used to used to change establishment activity in HRSD
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-company-management-module)/estabmanagement/createreqchangeesthrsd
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  CreateReqChangeEstActHRSDRq_MessageType:
    type: object
    properties:
      CreateReqChangeEstActHRSDRq:
        $ref: '#/definitions/CreateReqChangeEstActHRSDRq_Type'
  CreateReqChangeEstActHRSDRs_MessageType:
    type: object
    properties:
      CreateReqChangeEstActHRSDRs:
        $ref: '#/definitions/CreateReqChangeEstActHRSDRs_Type'
  CreateReqChangeEstActHRSDRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CreateReqChangeEstActHRSDRq_BodyType'
  CreateReqChangeEstActHRSDRq_BodyType:
    type: object
    properties:
      OldMainEconomicActivityId:
        type: integer
      OldSubEconomicActivityId:
        type: integer
      NewEconomicActivityId:
        type: integer
      NewMainEconomicActivityId:
        type: integer
      ReasonId:
        type: integer
      CreatedBy:
        type: integer
      UsersToAssignCount:
        type: integer
      IsElegibleForStudyByCompetentCommittee:
        type: string
      MaxSaudiPercentageMappedActivityId:
        type: integer
      IsAutoApproval:
        type: integer
      Establishment:
        $ref: '#/definitions/Establishment_Type'
  Establishment_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      PK_ID:
        type: integer
  CreateReqChangeEstActHRSDRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CreateReqChangeEstActHRSDRs_BodyType'
  CreateReqChangeEstActHRSDRs_BodyType:
    type: object
    properties:
      BusinessMessage:
        type: string
      ChangeEstablishmentActivityRequestId:
        type: integer
      Establishment:
        $ref: '#/definitions/Establishment_Type'
      Status:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /createreqchangeesthrsd:
    post:
      operationId: CreateReqChangeEstActHRSD
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CreateReqChangeEstActHRSDRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service is used to used to change establishment activity in
        HRSD
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CreateReqChangeEstActHRSDRq_MessageType'
        description: CreateReqChangeEstActHRSDRq
        required: true
