swagger: "2.0"
info:
  title: CreateContractBulk V2
  x-ibm-name: createcontractbulk-v2
  version: 1.0.0
  description: This service is used to create a bulk of contracts.
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-contractcreates)/contractmanagement/createcontractbulk
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  CreateContractBulkRq_MessageType:
    type: object
    properties:
      CreateContractBulkRq:
        $ref: '#/definitions/CreateContractBulkRq_Type'
  CreateContractBulkRs_MessageType:
    type: object
    properties:
      CreateContractBulkRs:
        $ref: '#/definitions/CreateContractBulkRs_Type'
  CreateContractBulkRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/CreateContractBulkRq_BodyType'
  CreateContractBulkRq_BodyType:
    type: object
    properties:
      ContractList:
        $ref: '#/definitions/ContractList_Type'
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
    required:
    - ContractList
    - EstablishmentDetails
    - RequesterDetails
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      UnifiedNumberId:
        type: integer
      EntityId:
        type: string
      EstablishmentNameAr:
        type: string
      EstablishmentNameEn:
        type: string
      EstablishmentEmail:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentId
    - UnifiedNumberId
    - EntityId
    - EstablishmentNameAr
    - EstablishmentNameEn
    - EstablishmentEmail
  RequesterDetails_Type:
    type: object
    properties:
      RequesterIdNo:
        type: integer
      RequesterName:
        type: string
      RequesterUserId:
        type: integer
      RequesterRole:
        type: string
    required:
    - RequesterIdNo
    - RequesterName
    - RequesterUserId
  ContractList_Type:
    type: object
    properties:
      ContractItem:
        type: array
        items:
          $ref: '#/definitions/ContractItem_Type'
  ContractItem_Type:
    type: object
    properties:
      LaborersDetails:
        $ref: '#/definitions/LaborersDetails_Type'
      ContractDetails:
        $ref: '#/definitions/ContractDetails_Type'
      LanguageId:
        type: integer
      DateTypeId:
        type: integer
      RelatedToId:
        type: integer
    required:
    - LaborersDetails
    - ContractDetails
    - LanguageId
    - DateTypeId
    - RelatedToId
  LaborersDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      BorderNumber:
        type: integer
      LaborerName:
        type: string
      LaborerTypeId:
        type: integer
      LaborerIdExpiryDate:
        type: string
      LaborerEmail:
        type: string
      LaborerMobileNumber:
        type: string
      LaborerDOB:
        type: string
      DOBType:
        type: integer
      Nationality:
        type: integer
      Gender:
        type: integer
      Religion:
        type: integer
      MaritalStatus:
        type: integer
      EducationId:
        type: integer
      SpecialtyId:
        type: integer
      WorkLocationId:
        type: integer
      IBAN:
        type: string
    required:
    - LaborerIdNo
    - LaborerName
    - LaborerTypeId
    - LaborerIdExpiryDate
    - LaborerEmail
    - LaborerMobileNumber
    - DOBType
    - SpecialtyId
    - WorkLocationId
    - IBAN
  ContractDetails_Type:
    type: object
    properties:
      OccupationId:
        type: integer
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      LaborerJobNumber:
        type: integer
      LaborerTypeId:
        type: integer
      ContractTypeId:
        type: integer
      ContractDurationId:
        type: integer
      ContractPeriod:
        type: integer
      ProbationPeriod:
        type: integer
      ProbationTerminationRight:
        type: integer
      WorkingHoursTypeId:
        type: integer
      VacationPeriod:
        type: integer
      Salary:
        type: string
      SalaryTypeId:
        type: integer
      PercentageReason:
        type: string
      CurrentStartDate:
        $ref: '#/definitions/HGDate_Type'
      CurrentExpiryDate:
        $ref: '#/definitions/HGDate_Type'
      RenewalStatusId:
        type: integer
      NoticePeriod:
        type: integer
      SalaryFrequency:
        type: integer
      Allowances:
        $ref: '#/definitions/Allowances_Type'
      CategoryId:
        type: integer
      UploadedFiles:
        $ref: '#/definitions/UploadedFiles_Type'
      IsUploadFilesSkiped:
        type: integer
      HoursPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      OptionalClauses:
        $ref: '#/definitions/OptionalClauses_Type'
      AdditionalTerms:
        $ref: '#/definitions/AdditionalTerms_Type'
      Terms:
        $ref: '#/definitions/Terms_Type'
    required:
    - OccupationId
    - JobTitle
    - LaborerJobNumber
    - ContractTypeId
    - ContractDurationId
    - WorkingHoursTypeId
    - VacationPeriod
    - Salary
    - CurrentStartDate
    - RenewalStatusId
    - NoticePeriod
    - SalaryFrequency
    - SalaryTypeId
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
    required:
    - JobTitleAr
    - JobTitleEng
  HGDate_Type:
    type: object
    properties:
      HijriDate:
        type: integer
      GregDate:
        type: string
  Allowances_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/AllowancesItem_Type'
  AllowancesItem_Type:
    type: object
    properties:
      AllowanceType:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
      Frequency:
        type: integer
      IsProvidedByEstablishment:
        type: integer
      AmountType:
        type: integer
      Amount:
        type: number
  OptionalClauses_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/OptionalClausesItem_Type'
  OptionalClausesItem_Type:
    type: object
    properties:
      OptionalClausesType:
        type: integer
      Period:
        type: integer
      Field:
        type: string
      Location:
        type: string
      FirstParty:
        type: string
      SecondParty:
        type: string
  AdditionalTerms_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/AdditionalTermsItem_Type'
  AdditionalTermsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
  Terms_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/TermsItem_Type'
  TermsItem_Type:
    type: object
    properties:
      TermId:
        type: integer
    required:
    - TermId
  UploadedFiles_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/UploadedFilesItem_Type'
  UploadedFilesItem_Type:
    type: object
    properties:
      FileId:
        type: string
      FileTypeId:
        type: integer
    required:
    - FileId
    - FileTypeId
  CreateContractBulkRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/CreateContractBulkRs_BodyType'
  CreateContractBulkRs_BodyType:
    type: object
    properties:
      BulkId:
        type: integer
      ContractList:
        $ref: '#/definitions/ContractListRs_Type'
    required:
    - BulkId
  ContractListRs_Type:
    type: object
    properties:
      ContractItem:
        type: array
        items:
          $ref: '#/definitions/ContractItemRs_Type'
  ContractItemRs_Type:
    type: object
    properties:
      ContractId:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /createcontractbulk:
    post:
      operationId: CreateContractBulk
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/CreateContractBulkRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Create Contract Bulk
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CreateContractBulkRq_MessageType'
        description: CreateContractBulkRq
        required: true
