swagger: "2.0"
info:
  title: DOROOB_GetEmployeeTrainings
  x-ibm-name: doroob-getemployeetrainings
  version: 1.0.0
  description: This service is used to get case details through Takamol Internal/External
    Integration.
schemes:
- https
basePath: /doroob/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - map:
        version: 2.0.0
        title: map
        inputs:
          personID:
            schema:
              type: string
            variable: request.parameters.personID
        outputs:
          "":
            schema:
              description: ""
              type: object
              properties:
                personID:
                  type: string
                  name: personID
              example: " {\r\n        \"personID\":\"1069400750\"\r\n    }"
            variable: message.body
            content: application/json
        actions:
        - set: .personID
          from: personID
        options:
          mapEnablePostProcessingJSON: true
          mapEmulateV4EmptyJSONObject: false
          mapEmulateV4DefaultRequiredProps: false
          mapReferenceLimit: 1
          includeEmptyXMLElements: false
          namespaceInheritance: false
          inlineNamespaces: false
          mapResolveApicVariables: false
          mapOptimizeSchemaDefinition: true
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"EXGET00001\",\n
          \   \"channelId\" : \"Integration\",\n    \"requestName\" : \"getEmployeeTrainingsRq\",\n
          \   \"responseName\": \"getEmployeeTrainingsRs\",\n    \"errorMap\" :{\n
          \       \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid Request\"}\n    }\n
          \   \n};\n\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\n\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\n\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode\r\n        },\r\n
          \       \"Body\" : apim.getvariable('message.body')\r\n            \r\n
          \       \r\n    }\r\n};\r\n\r\nif (typeof OperatorId !== 'undefined')\r\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\r\n        \"IDNumber\"
          : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        version: 2.3.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        websocket-upgrade: false
        graphql-send-type: detect
        target-url: $(ace-tip-doroob)/external/getemployeetrainings
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "var apim = require('apim');\r\napim.output('application/json');\r\nvar
          message = apim.getvariable('message.body');\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          Header = message[cfg.responseName].Header;\r\nvar TransactionId = Header.TransactionId;\r\nvar
          ChannelId = Header.ChannelId;\r\nvar RequestTime = Header.RequestTime;\r\nvar
          SessionId = Header.SessionId;\r\nvar MWRequestTime = Header.MWRequestTime;\r\nvar
          MWResponseTime = Header.MWResponseTime;\r\nvar status = Header.ResponseStatus.Status;\r\nvar
          code = Header.ResponseStatus.Code;\r\napim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\r\napim.setvariable('message.headers.Channel-Id',ChannelId,'add');\r\nif
          (RequestTime !== 'undefined')\r\napim.setvariable('message.headers.RequestTime',RequestTime,'add');\r\nif
          (SessionId !== 'undefined')\r\napim.setvariable('message.headers.X-Request-Id',SessionId,'add');\r\nif
          (MWRequestTime !== 'undefined')\r\napim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\r\nif
          (MWResponseTime !== 'undefined')\r\napim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\r\napim.setvariable('message.headers.Response-Status',status,'add');\r\napim.setvariable('message.headers.Response-Code',code,'add');"
    - switch:
        version: 2.1.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\r\nvar message = apim.getvariable('message.body');\r\nvar
                cfg = apim.getvariable('cfg');\r\nvar body = message[cfg.responseName].Body;\r\nsession.output.write(body);\r\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\r\nvar message = apim.getvariable('message.body');\r\nvar
                cfg = apim.getvariable('cfg');          \r\nvar error = {\r\n  \"errorCode\":
                message[cfg.responseName].Header.ResponseStatus.Code,\r\n  \"errorMessage\":
                {\r\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\r\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\r\n
                \ }\r\n};\r\n\r\nvar httperror=0;\r\nif(cfg.errorMap){\r\n    if(cfg.errorMap[error.errorCode]){\r\n
                \      httperror = cfg.errorMap[error.errorCode].code;\r\n       \r\n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\r\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\r\n
                \      //apim.error('ERROR',httperror,errmgs,details);\r\n    }\r\n}\r\nif(httperror
                == 0){\r\n   httperror = 409;\r\n   // apim.error('ERROR',400,'Bad
                Request','Invalid request');\r\n}\r\napim.setvariable('message.status.code',httperror,'set');\r\n\r\nsession.output.write(error);\r\napim.output('application/json');"
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  personID:
    in: path
    name: personID
    description: personID
    required: true
    type: string
definitions:
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      enrollmentList:
        $ref: '#/definitions/enrollmentListModel'
  enrollmentListModel:
    type: array
    items:
      $ref: '#/definitions/enrollmentModel'
  enrollmentModel:
    type: object
    properties:
      User:
        type: string
        example: ""
      CourseDetails:
        $ref: '#/definitions/CourseDetailsModel'
      IsActive:
        type: string
        example: ""
      Mode:
        type: string
        example: ""
      Created:
        type: string
        example: ""
  CourseDetailsModel:
    type: object
    description: 'This object will be used across the model '
    properties:
      CourseEnd:
        type: string
        example: ""
      CourseName:
        type: string
        example: ""
      CourseDisplayName:
        type: string
        example: ""
      CourseStart:
        type: string
        example: ""
      CourseModes:
        $ref: '#/definitions/CourseModesModel'
      EnrollmentStart:
        type: string
        example: ""
      EnrollmentEnd:
        type: string
        example: ""
      InviteOnly:
        type: string
        example: ""
      CourseId:
        type: string
        example: ""
  CourseModesModel:
    type: object
    description: 'This object will be used across the model '
    properties:
      Sku:
        type: string
        example: ""
      ExpirationDatetime:
        type: string
        example: ""
      Name:
        type: string
        example: ""
      Currency:
        type: string
        example: ""
      BulkSku:
        type: string
        example: ""
      MinPrice:
        type: string
        example: ""
      SuggestedPrices:
        type: string
        example: ""
      Slug:
        type: string
        example: ""
      Description:
        type: string
        example: ""
  GregorianDateModel:
    type: string
    description: This date object will be used across the model with format yyyy-MM-dd
      for gregorian dates only
    example: "2017-12-31"
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  HijriDateModel:
    type: string
    description: This date object will be used across the model with format yyyy-MM-dd
      for hijri dates only
    example: "1439-12-25"
  HijriGregorianDateModel:
    type: object
    description: This date object will be used across the model with format dd/mm/yyyy
      for hijri and gregorian
    properties:
      hijriDate:
        $ref: '#/definitions/HijriDateModel'
      gregorianDate:
        $ref: '#/definitions/GregorianDateModel'
paths:
  /enrollments/{personID}:
    parameters:
    - name: X-IBM-Client-Id
      in: header
      required: false
      description: Client id issued by security server
      type: string
    - name: X-Request-Id
      in: header
      required: false
      description: X-Request-Id returned in the response header
      type: string
    - name: X-IBM-Client-Secret
      in: header
      required: false
      description: Client secret issued by security server
      type: string
    - name: personID
      in: path
      required: true
      description: personID
      type: string
    get:
      tags:
      - Enrollments
      description: Service to get Employee Trainings
      operationId: GetEmployeeTrainings
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Response200'
        "201":
          $ref: '#/responses/Response201'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response204:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
