swagger: "2.0"
info:
  description: service extends the grace period for 120 days for absent employees
    for given laborOfficeId and sequenceNumber
  version: 1.0.0
  title: ExtendGracePeriodForEmploye
  x-ibm-name: extendgraceperiodforemployees
paths:
  /ExtendGracePeriodForEmployees:
    post:
      operationId: ExtendGracePeriodForEmployees
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ExtendGracePeriodForEmployeesRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: service extends the grace period for 120 days for absent employees
        for given laborOfficeId and sequenceNumber
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ExtendGracePeriodForEmployeesRq_MessageType'
        description: ExtendGracePeriodForEmployeesRq
        required: true
basePath: /qiwa/v2
definitions:
  ExtendGracePeriodForEmployeesRq_MessageType:
    type: object
    properties:
      ExtendGracePeriodForEmployeesRq:
        $ref: '#/definitions/ExtendGracePeriodForEmployeesRq_Type'
  ExtendGracePeriodForEmployeesRs_MessageType:
    type: object
    properties:
      ExtendGracePeriodForEmployeesRs:
        $ref: '#/definitions/ExtendGracePeriodForEmployeesRs_Type'
  ExtendGracePeriodForEmployeesRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ExtendGracePeriodForEmployeesRq_BodyType'
  ExtendGracePeriodForEmployeesRq_BodyType:
    type: object
    properties:
      requestId:
        type: integer
      laborOfficeId:
        type: integer
      sequenceNumber:
        type: integer
      laborerId:
        type: string
      reason:
        type: string
      extendedBy:
        type: string
    required:
    - requestId
    - laborOfficeId
    - sequenceNumber
    - laborerId
    - reason
    - extendedBy
  ExtendGracePeriodForEmployeesRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ExtendGracePeriodForEmployeesRs_BodyType'
  ExtendGracePeriodForEmployeesRs_BodyType:
    type: object
    properties:
      responseMessage:
        type: string
      responseMessageAr:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  cors:
    enabled: true
  properties:
    target-url:
      value: http://example.com
      description: The URL of the target service
      encoded: false
  phase: realized
  enforced: true
  gateway: datapower-api-gateway
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-ctfl-absentservices)/ExtendGracePeriodForEmployees
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: response_config
        source: |
          var apim = require('apim');


          apim.output('application/json');

          var cfg = {
              "responseName": "ExtendGracePeriodForLaborerRs"
          };

          var status = apim.getvariable("message.body."+cfg.responseName+".Header.ResponseStatus.Status");

          apim.setvariable('message.headers.Response-Status',status,'add');
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: ($header("Response-Status") = 'Error' or $header("Response-Status")
            = 'ERROR')
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\n\nvar
                cfg={\n    \"responseName\": \"ExtendGracePeriodForLaborerRs\",\n
                \   \"errorMap\" :{\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid
                Request\"},\n        \"E0001475\"  : {\"code\" :409, \"msg\":\"Grace
                period already extended for this employee\"},\n        \"E0001473\"
                \ : {\"code\" :409, \"msg\":\"Extension of grace period not allowed
                for this employee\"},\n        \"E0001478\"  : {\"code\" :400, \"msg\":\"Laborer
                ID is mandatory, please enter a valid one.\"},\n        \"E0001479\"
                \ : {\"code\" :400, \"msg\":\"Reason is mandatory, please share the
                reason for extension.\"},\n        \"E0000024\"  : {\"code\" :409,
                \"msg\":\"No Data Found\"},\n        \"E0001491\"  : {\"code\" :400,
                \"msg\":\"ExtendedBy is mandatory, please enter a valid one.\"},\n
                \       \"E0001499\"  : {\"code\" :400, \"msg\":\"Request ID is mandatory,
                please enter a valid one\"},\n        \"E0001500\"  : {\"code\" :400,
                \"msg\":\"Labor Office ID is mandatory, please enter a valid one\"},\n
                \       \"E0001501\"  : {\"code\" :400, \"msg\":\"Sequence Number
                is mandatory, please enter a valid one\"},\n        \"REST:Gateway\"
                \ : {\"code\" :500, \"msg\":\"internal server\"}\n\n    }\n    \n};\n\nvar
                error = {\n  \"errorCode\": message[cfg.responseName].Header.ResponseStatus.Code\n};\n\nvar
                httperror = 0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \   }\n}\n\nif (httperror == 0){\n    httperror = 400;\n}\n\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(message);\napim.output('application/json');\n\n\n\n"
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute: []
    finally: []
  type: rest
  testable: true
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
host: $(catalog.host)
schemes:
- https
