swagger: "2.0"
info:
  title: Foreign Investors Details
  x-ibm-name: foreign-investors-v1
  version: 1.0.0
  description: API for registering, verifing, getting details of foreign investors
    V1
schemes:
- https
basePath: /foreign-investor/v1
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    register-url:
      value: /foreign-investor/v1/register-and-verify
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        version: 2.3.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        websocket-upgrade: false
        graphql-send-type: detect
        target-url: $(ace-prow-foreign-investors)$(register-url)
    finally: []
    catch:
    - default:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: "var apim = require('apim');\nvar requestBody  = apim.getvariable('message.body');\nvar
            response  = {\n    \"KyanUserValidationReq\":{\n        \"Header\" : {\n
            \           \"TransactionId\" :requestBody.ForeignInvestorRegisterReq.Header.TransactionId,\n
            \           \"ChannelId\": \"requestBody.ForeignInvestorRegisterReq.Header.ChannelId,\",\n
            \           \"SessionId\": requestBody.ForeignInvestorRegisterReq.Header.SessionId,,\n
            \           \"RequestTime\" : requestBody.ForeignInvestorRegisterReq.Header.RequestTime,,\n\t\t\t\"MWRequestTime\"
            : requestBody.ForeignInvestorRegisterReq.Header.MWRequestTime,\n            \"ServiceCode\":
            requestBody.ForeignInvestorRegisterReq.Header.ServiceCode,\n\t\t\t\"ResponseStatus\":
            {\n\t\t\t\t\"ResponseStatus\" : 00000001,\n\t\t\t\t\"Status\": \"Failure\"\n\t\t\t\t\"EnglishMsg\":
            \"Internal Server Error\"\n\t\t\t} \n        }\n    }\n};\nsession.output.write(response);\napim.output('application/json');"
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
definitions:
  ForeignInvestorRegisterVerifyReq:
    type: object
    properties:
      Header:
        $ref: '#/definitions/RequestHeader'
      Body:
        $ref: '#/definitions/ForeignInvestorRegisterVerifyReqBody'
  ForeignInvestorRegisterVerifyRes:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ResponseHeader'
      Body:
        $ref: '#/definitions/ForeignInvestorRegisterVerifyResBody'
  RequestHeader:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        example: SSOFR001/SSOFR002
        description: SSOFR001 for Register / SSOFR002  for Verify
  ResponseHeader:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        example: SSOFR001/SSOFR002
        description: SSOFR001 for Register / SSOFR002  for Verify
      ResponseStatus:
        $ref: '#/definitions/ResponseStatus'
  ResponseStatus:
    type: object
    properties:
      Status:
        type: string
        example: Success/Failure/No Data Found
      Code:
        type: string
        example: 00000000/00000001
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  ForeignInvestorRegisterVerifyReqBody:
    type: object
    properties:
      attributes:
        $ref: '#/definitions/attributes'
  ForeignInvestorRegisterVerifyResBody:
    type: object
    properties:
      attributes:
        $ref: '#/definitions/attributesRes'
  attributes:
    type: object
    properties:
      foreignPassportNumber:
        type: string
        example: VV660207
  attributesRes:
    type: object
    properties:
      crRepresentative:
        type: object
        properties:
          birthDate:
            type: string
            example: "1980-01-01"
          email:
            type: string
            example: anna@gmail.com
          mobile:
            type: string
            example: 100678311
          name:
            type: string
            example: سعود عبدالله حمد الدليم
          partyId:
            type: string
            example: 28168200263
          partyIdType:
            type: string
            example: GCCID
          nationality:
            type: object
            properties:
              id:
                type: string
                example: QAT
              name:
                type: string
                example: قطريون
              nameEN:
                type: string
                example: QATARIS
paths:
  /register-and-verify:
    post:
      tags:
      - Foreign Investor V1
      description: Use to register foreign investor and get details
      operationId: register
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ForeignInvestorRegisterVerifyReq'
        description: Foreign Investor Register Req
        required: true
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/ForeignInvestorRegisterVerifyRes'
host: $(catalog.host)
security:
- OAuth2.0:
  - IntegrationScope
