swagger: "2.0"
info:
  title: GenerateEstaDebtCertificate
  version: 1.0.0
  description: This service is used to generate an establishment debt certificate
    to be viewed by the owner to check the active debts and violations of the establishment..
  x-ibm-name: generateestadebtcertificate
paths:
  /generateestabdebtcertificate:
    post:
      operationId: GenerateEstaDebtCertificate
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GenerateEstablishmentDebtCertificateRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service is used to generate an establishment debt certificate
        to be viewed by the owner to check the active debts and violations of the
        establishment.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GenerateEstablishmentDebtCertificateRq_MessageType'
        description: GenerateEstablishmentDebtCertificateRq
        required: true
basePath: /estabmanagement/transferownership
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
definitions:
  GenerateEstablishmentDebtCertificateRq_MessageType:
    type: object
    properties:
      GenerateEstablishmentDebtCertificateRq:
        $ref: '#/definitions/GenerateEstablishmentDebtCertificateRq_Type'
  GenerateEstablishmentDebtCertificateRs_MessageType:
    type: object
    properties:
      GenerateEstablishmentDebtCertificateRs:
        $ref: '#/definitions/GenerateEstablishmentDebtCertificateRs_Type'
  GenerateEstablishmentDebtCertificateRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GenerateEstablishmentDebtCertificateRq_BodyType'
  GenerateEstablishmentDebtCertificateRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
  GenerateEstablishmentDebtCertificateRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GenerateEstablishmentDebtCertificateRs_BodyType'
  GenerateEstablishmentDebtCertificateRs_BodyType:
    type: object
    properties:
      CertificateNumber:
        type: string
      CertificateIssueDate:
        $ref: '#/definitions/Tmstmp_Type'
      ValidUntil:
        $ref: '#/definitions/Tmstmp_Type'
      EstablishmentNumber:
        type: string
      EstablishmentName:
        type: string
      CRNumber:
        type: string
      NationalUnifiedNumber:
        type: string
      ViolationDetails:
        $ref: '#/definitions/ViolationDetails_Type'
      CaseDetails:
        $ref: '#/definitions/CaseDetails_Type'
      GeneralWPDebt:
        $ref: '#/definitions/Total_Type'
      WPFinalExitDebt:
        $ref: '#/definitions/Total_Type'
      TotalLaborerCount:
        type: integer
      TotalDebtAmount:
        type: integer
    required:
    - CertificateNumber
    - CertificateIssueDate
    - ValidUntil
    - EstablishmentNumber
    - EstablishmentName
    - ViolationDetails
    - CaseDetails
    - TotalLaborerCount
    - TotalDebtAmount
    - GeneralWPDebt
    - WPFinalExitDebt
  Total_Type:
    type: object
    properties:
      TotalLaborerCount:
        type: integer
      TotalDebtAmount:
        type: integer
    required:
    - TotalLaborerCount
    - TotalDebtAmount
  ViolationDetails_Type:
    type: object
    properties:
      ViolationsList:
        $ref: '#/definitions/Violation_Type'
      TotalActiveViolations:
        type: integer
      PenaltyAmount:
        type: integer
    required:
    - TotalActiveViolations
  Violation_Type:
    type: object
    properties:
      Iban:
        type: string
      ReasonsForViolation:
        type: string
      ViolationRegistered:
        type: string
      ViolationNotRegistered:
        type: string
      ObjectionNumber:
        type: string
      ObjectionStatus:
        type: string
      EstablishmentOwnerComments:
        type: string
      IsEmployerOnSite:
        type: string
      EstablishmentLocation:
        type: string
      ResponsiblePersonName:
        type: string
      Attachment:
        type: string
      SadadIssuedDate:
        type: string
      SadadStatus:
        type: string
      SadadDueDate:
        type: string
      SadadNumber:
        type: string
      ViolationCode:
        type: string
      PenaltyAmount:
        type: string
      ViolationUniqueId:
        type: string
      ViolationDescription:
        type: string
      ViolationApprovedDate:
        type: string
      InspectorComments:
        type: string
      Coordinates:
        type: string
    required:
    - Iban
    - ReasonsForViolation
    - ViolationRegistered
    - ViolationNotRegistered
    - ObjectionNumber
    - ObjectionStatus
    - EstablishmentOwnerComments
    - IsEmployerOnSite
    - EstablishmentLocation
    - ResponsiblePersonName
    - Attachment
    - SadadIssuedDate
    - SadadStatus
    - SadadDueDate
    - SadadNumber
    - ViolationCode
    - PenaltyAmount
    - ViolationUniqueId
    - ViolationDescription
    - ViolationApprovedDate
    - InspectorComments
    - Coordinates
  CaseDetails_Type:
    type: object
    properties:
      CasesList:
        $ref: '#/definitions/CasesList_Type'
      TotalActiveCases:
        type: integer
    required:
    - TotalActiveCases
  CasesList_Type:
    type: object
    properties:
      nationalNumber:
        type: string
      caseTopics:
        $ref: '#/definitions/caseTopics_Type'
      caseStatus:
        type: string
      fileNumber:
        type: string
      establishmentName:
        type: string
      caseNumber:
        type: string
      caseCreatedDate:
        type: string
      plaintiffType:
        type: string
      officerName:
        type: string
    required:
    - caseTopics
    - caseStatus
    - fileNumber
    - establishmentName
    - caseNumber
    - caseCreatedDate
    - plaintiffType
    - officerName
  caseTopics_Type:
    type: object
    properties:
      topicName:
        type: string
    required:
    - topicName
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-debt-certificate)/estabmanagement/transferownership/generateestabdebtcertificate
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
