swagger: "2.0"
info:
  title: GetNitaqatWrapper
  x-ibm-name: get-nitaqat-wrapper
  version: 1.0.0
  description: This API retrieves the nitaqat info Details
host: $(catalog.host)
schemes:
- https
basePath: /Indicators
security:
- OAuth2.0: []
- clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://prow-getnitaqatinfo-wrapper-http-ace.apps.stg.qiwa-nonprod.local/ext/GetNitaqatInfoWrapper
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(prow-getnitaqatinfo-wrapper)/ext/GetNitaqatInfoWrapper
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
definitions:
  NitaqatInfoRequest_MessageType:
    type: object
    properties:
      NitaqatInfoRq:
        $ref: '#/definitions/NitaqatInfoRq_Type'
  NitaqatInfoResponse_MessageType:
    type: object
    properties:
      NitaqatInfoRs:
        $ref: '#/definitions/NitaqatInfoRs_Type'
  NitaqatInfoRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/RequestHeader_Type'
      Body:
        $ref: '#/definitions/NitaqatInfoRq_Body'
  NitaqatInfoRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ResponseHeader_Type'
      Body:
        $ref: '#/definitions/NitaqatInfoRs_Body'
  RequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
      DebugFlag:
        type: string
        default: 1
  ResponseHeader_Type:
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
      DebugFlag:
        type: string
        default: 1
      ResponseStatus:
        $ref: '#/definitions/ResponseStatus'
      BackendError:
        $ref: '#/definitions/BackendError'
  ResponseStatus:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendError:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  NitaqatInfoRq_Body:
    type: object
    required:
    - LaborOfficeId
    - SequenceNumber
    properties:
      LaborOfficeId:
        type: number
      SequenceNumber:
        type: number
  NitaqatInfoRs_Body:
    type: object
    required:
    - Nitaqat
    properties:
      Nitaqat:
        $ref: '#/definitions/NitaqatDetails_Type'
  NitaqatDetails_Type:
    type: object
    required:
    - NameAr
    - NameEn
    properties:
      NameAr:
        type: string
        example: اخضر متوسط
      NameEn:
        type: number
        example: Medium Green
      Evaluations:
        type: array
        items:
          type: object
          properties:
            Id:
              type: number
              example: 100
            En:
              type: string
              example: Red
            From:
              type: number
              example: 10
            To:
              type: number
              example: 17
      Notification:
        type: object
        properties:
          Ar:
            type: string
            example: اخضر
          En:
            type: string
            example: 0
      SaudisToBeHired:
        type: number
        example: 1
      NationalizationRate:
        type: number
        example: 20
paths:
  /GetNitaqatInfoWrapper:
    post:
      tags:
      - Get Nitaqat Info
      description: Used to get Nitaqat Info
      operationId: getNitaqatInfo
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/NitaqatInfoRequest_MessageType'
        description: NitaqatinfoRq
        required: true
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/NitaqatInfoResponse_MessageType'
