swagger: "2.0"
info:
  title: GetAppointmentDetails
  x-ibm-name: getappointmentdetails
  version: 1.0.0
  description: Get a list of appointment requests with it's details
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-appointment)/qiwalo/getappointdet
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetAppointmentDetailsRq_MessageType:
    type: object
    properties:
      GetAppointmentDetailsRq:
        $ref: '#/definitions/GetAppointmentDetailsRq_Type'
  GetAppointmentDetailsRs_MessageType:
    type: object
    properties:
      GetAppointmentDetailsRs:
        $ref: '#/definitions/GetAppointmentDetailsRs_Type'
  GetAppointmentDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetAppointmentDetailsRq_BodyType'
  GetAppointmentDetailsRq_BodyType:
    type: object
    properties:
      AppointmentId:
        type: integer
      AppointmentStatusId:
        type: string
      CreationDate:
        type: string
      OfficeID:
        type: integer
      Time:
        type: integer
      Date:
        type: string
      RegionId:
        type: integer
      RequesterIdNo:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      IsElectronicOffice:
        type: boolean
      IsKiosk:
        type: integer
      OperatorId:
        type: integer
      AssignFlag:
        type: integer
      ServiceId:
        type: integer
      SortDirection:
        type: integer
      AppointmentIds:
        type: string
      DateFrom:
        type: string
      DateTo:
        type: string
      PageSize:
        type: integer
      PageIndex:
        type: integer
      RequesterTypeId:
        type: integer
    required:
    - PageSize
    - PageIndex
  GetAppointmentDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetAppointmentDetailsRs_BodyType'
  GetAppointmentDetailsRs_BodyType:
    type: object
    properties:
      AppointmentDetailsList:
        $ref: '#/definitions/AppointmentDetailsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - AppointmentDetailsList
    - TotalRecordsCount
  AppointmentDetailsList_Type:
    type: object
    properties:
      AppointmentDetailsItem:
        type: array
        items:
          $ref: '#/definitions/AppointmentDetailsItem_Type'
    required:
    - AppointmentDetailsItem
  AppointmentDetailsItem_Type:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      OfficeID:
        type: integer
      OfficeName:
        type: string
      IsElectronicOffice:
        type: boolean
      IsKiosk:
        type: integer
      ClientService:
        $ref: '#/definitions/CodeName_Type'
      SubService:
        $ref: '#/definitions/CodeName_Type'
      RequesterType:
        $ref: '#/definitions/CodeName_Type'
      Region:
        $ref: '#/definitions/CodeName_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      Time:
        type: integer
      Date:
        type: string
      AppointmentId:
        type: integer
      CreationDate:
        type: string
      AppointmentStatus:
        $ref: '#/definitions/CodeName_Type'
      UpdateReason:
        $ref: '#/definitions/CodeName_Type'
      Description:
        type: string
      CancelationReason:
        type: string
      NbAppointments:
        type: integer
      LastModifiedDate:
        type: string
      OperatorId:
        type: integer
      Status4Date:
        type: string
      Status6Date:
        type: string
      RealSessionTime:
        type: string
      VisitReason:
        $ref: '#/definitions/CodeName_Type'
      Attachment:
        $ref: '#/definitions/Attachment_Type'
      ExplanationText:
        type: string
      TicketNumber:
        type: string
      AssignFlag:
        type: integer
      AgentAssignmentDate:
        type: string
      weblink:
        type: string
      MeetingId:
        type: string
      CRNumber:
        type: string
      Attachments:
        $ref: '#/definitions/Attachment2_Type'
    required:
    - EstablishmentDetails
    - OfficeID
    - ClientService
    - SubService
    - RequesterType
    - Region
    - RequesterDetails
    - Time
    - Date
    - AppointmentId
    - CreationDate
    - AppointmentStatus
    - NbAppointments
    - VisitReason
    - Attachments
  Attachment_Type:
    type: object
    properties:
      AttachmentDetails:
        type: array
        items:
          $ref: '#/definitions/AttachmentDetails_Type'
    required:
    - AttachmentDetails
  Attachment2_Type:
    type: object
    properties:
      AttachmentItem:
        type: array
        items:
          $ref: '#/definitions/AttachmentItem_Type'
    required:
    - AttachmentItem
  AttachmentDetails_Type:
    type: object
    properties:
      AttachmentId:
        type: string
      AttachmentName:
        type: string
    required:
    - AttachmentId
    - AttachmentName
  AttachmentItem_Type:
    type: object
    properties:
      AppointmentAttachmentID:
        type: string
      AppointmentID:
        type: string
      AttachmentReference:
        type: string
      AttachmentTypeCode:
        type: string
      AttachmentNameAr:
        type: string
      AttachmentNameEn:
        type: string
    required:
    - AppointmentAttachmentID
    - AppointmentID
    - AttachmentReference
    - AttachmentTypeCode
    - AttachmentNameAr
    - AttachmentNameEn
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentName:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentName
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  RequesterDetails_Type:
    type: object
    properties:
      RequesterIdNo:
        type: string
      RequesterName:
        type: string
      RequesterUserId:
        type: integer
      RequesterMobile:
        type: string
      RequesterEmail:
        type: string
    required:
    - RequesterIdNo
    - RequesterName
    - RequesterUserId
    - RequesterMobile
    - RequesterEmail
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  DestinationDetails_Type:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
      DestinationSequenceNumber:
        type: integer
    required:
    - DestinationLaborOfficeId
    - DestinationSequenceNumber
  SourceLaborerList_Type:
    type: object
    properties:
      SourceLaborerItem:
        type: array
        items:
          $ref: '#/definitions/SourceLaborerItem_Type'
  SourceLaborerItem_Type:
    type: object
    properties:
      SourceLaborOfficeId:
        type: integer
      SourceSequenceNumber:
        type: integer
      LaborerList:
        $ref: '#/definitions/LaborerList_Type'
  LaborerList_Type:
    type: object
    properties:
      LaborerItem:
        type: array
        items:
          $ref: '#/definitions/LaborerItem_Type'
  LaborerItem_Type:
    type: object
    properties:
      LaborerName:
        type: string
      LaborerIdNo:
        type: string
    required:
    - LaborerName
    - LaborerIdNo
  LaborersNationalitiesList_Type:
    type: object
    properties:
      LaborersNationalitiesItem:
        type: array
        items:
          $ref: '#/definitions/LaborersNationalitiesItem_Type'
  LaborersNationalitiesItem_Type:
    type: object
    properties:
      Nationality:
        type: integer
      NumberOfLaborers:
        type: integer
    required:
    - Nationality
    - NumberOfLaborers
  LaborerRequestNumList_Type:
    type: object
    properties:
      LaborerRequestNumItem:
        type: array
        items:
          $ref: '#/definitions/LaborerRequestNumItem_Type'
  LaborerRequestNumItem_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      LaborerIdNo:
        type: string
      SourceLaborOfficeId:
        type: integer
      SourceSequenceNumber:
        type: integer
    required:
    - RequestNumber
    - LaborerIdNo
    - SourceLaborOfficeId
    - SourceSequenceNumber
  LaborersWithNotValidContracts_Type:
    type: object
    properties:
      LaborerIdNo:
        type: array
        items:
          type: integer
paths:
  /getappointdet:
    post:
      operationId: GetAppointmentDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetAppointmentDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Appointment Details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetAppointmentDetailsRq_MessageType'
        description: GetAppointmentDetailsRq
        required: true
