swagger: "2.0"
info:
  title: GetBulkWagesUpdateDetails V2
  version: 1.0.0
  description: GetBulkWagesUpdateDetails
  x-ibm-name: getbulkwagesupdatedetails-v2
paths:
  /getbulkwageupddetails:
    post:
      operationId: GetBulkWagesUpdateDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetBulkWagesUpdateDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Update Refunded
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetBulkWagesUpdateDetailsRq_MessageType'
        description: GetBulkWagesUpdateDetailsRq
        required: true
basePath: /contractmanagement/v2
definitions:
  GetBulkWagesUpdateDetailsRq_MessageType:
    type: object
    properties:
      GetBulkWagesUpdateDetailsRq:
        $ref: '#/definitions/GetBulkWagesUpdateDetailsRq_Type'
  GetBulkWagesUpdateDetailsRs_MessageType:
    type: object
    properties:
      GetBulkWagesUpdateDetailsRs:
        $ref: '#/definitions/GetBulkWagesUpdateDetailsRs_Type'
  GetBulkWagesUpdateDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetBulkWagesUpdateDetailsRq_BodyType'
  GetBulkWagesUpdateDetailsRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      FileId:
        type: string
      FileReferenceNumber:
        type: integer
      FileStatusId:
        type: string
      WageUpdateStatusId:
        type: string
      ContractId:
        type: integer
      EmployeeIdNo:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - PageSize
    - PageIndex
  GetBulkWagesUpdateDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetBulkWagesUpdateDetailsRs_BodyType'
  GetBulkWagesUpdateDetailsRs_BodyType:
    type: object
    properties:
      FilesList:
        type: array
        items:
          $ref: '#/definitions/FilesList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - FilesList
    - TotalRecordsCount
  FilesList_Type:
    type: object
    properties:
      File:
        type: array
        items:
          $ref: '#/definitions/File_Type'
    required:
    - File
  File_Type:
    type: object
    properties:
      FileId:
        type: string
      FileReferenceNumber:
        type: integer
      FileName:
        type: string
      FileStatus:
        $ref: '#/definitions/CodeName_Type'
      RequesterIdNo:
        type: integer
      Notes:
        type: string
      CreationDate:
        type: string
        format: date
      LastModificationDate:
        type: string
        format: date
      FileEmployeesList:
        $ref: '#/definitions/FileEmployeesList_Type'
    required:
    - FileId
    - FileReferenceNumber
    - FileName
    - FileStatus
    - RequesterIdNo
    - Notes
    - CreationDate
    - LastModificationDate
    - FileEmployeesList
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
    required:
    - Code
    - NameEn
    - NameAr
  FileEmployeesList_Type:
    type: object
    properties:
      EmployeeDetails:
        type: array
        items:
          $ref: '#/definitions/EmployeeDetails_Type'
      TotalEmployeesCount:
        type: integer
    required:
    - EmployeeDetails
    - TotalEmployeesCount
  EmployeeDetails_Type:
    type: object
    properties:
      EmployeeReferenceNumber:
        type: integer
      EmployeeIdNo:
        type: integer
      EmployeeName:
        type: string
      ContractId:
        type: integer
      GOSIBasicSalary:
        type: number
        format: decimal
      GOSITotalSalary:
        type: number
        format: decimal
      CurrentBasicSalary:
        type: number
        format: decimal
      'CurrentTotalSalary ':
        type: number
        format: decimal
      NewBasicSalary:
        type: number
        format: decimal
      NewHousingAllowance:
        type: number
        format: decimal
      NewTransportationAllowance:
        type: number
        format: decimal
      NewTotalSalary:
        type: number
        format: decimal
      WageUpdateStatus:
        $ref: '#/definitions/CodeName_Type'
      FailureReason:
        $ref: '#/definitions/CodeName_Type'
      SentToGOSI:
        type: integer
      GOSIResponseStatus:
        type: integer
      GOSIResponseDescription:
        type: integer
      Notes:
        type: string
      LastModificationDate:
        type: string
        format: date
    required:
    - EmployeeReferenceNumber
    - EmployeeIdNo
    - EmployeeName
    - ContractId
    - NewBasicSalary
    - NewHousingAllowance
    - NewTransportationAllowance
    - NewTotalSalary
    - WageUpdateStatus
    - GOSIResponseStatus
    - GOSIResponseDescription
    - Notes
    - LastModificationDate
    - SentToGOSI
    - GOSIBasicSalary
    - GOSITotalSalary
    - CurrentBasicSalary
    - 'CurrentTotalSalary '
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      TotalRecordsCount:
        type: integer
      FilesList:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-conbulkwages)/contractmanagement/getbulkwageupddetails
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
