swagger: "2.0"
info:
  title: GetChangeOccupationDraft
  x-ibm-name: getchangeoccupationdraft
  version: 1.0.0
  description: This service is used to get change occupation draft.
schemes:
- https
basePath: /chgoccupation
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-changeoccupation)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetChangeOccupationDraftRq_MessageType:
    type: object
    properties:
      GetChangeOccupationDraftRq:
        $ref: '#/definitions/GetChangeOccupationDraftRq_Type'
  GetChangeOccupationDraftRs_MessageType:
    type: object
    properties:
      GetChangeOccupationDraftRs:
        $ref: '#/definitions/GetChangeOccupationDraftRs_Type'
  GetChangeOccupationDraftRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetChangeOccupationDraftRq_BodyType'
  GetChangeOccupationDraftRq_BodyType:
    type: object
    properties:
      DraftId:
        type: integer
        default: "10010"
  GetChangeOccupationDraftRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetChangeOccupationDraftRs_BodyType'
  GetChangeOccupationDraftRs_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      RequestDetailsList:
        $ref: '#/definitions/RequestDetailsList_Type'
  RequestDetailsList_Type:
    type: object
    properties:
      LaborerOccupation:
        type: array
        items:
          $ref: '#/definitions/LaborerOccupation_Type'
  LaborerOccupation_Type:
    type: object
    properties:
      CurrentOccupationId:
        type: integer
      NewOccupationId:
        type: integer
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
  LaborerDetails_Type:
    type: object
    properties:
      LaborerName:
        type: string
      LaborerIdNo:
        type: integer
      NationalityCode:
        type: integer
      NationalityName:
        type: string
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
  RequesterDetails_Type:
    type: object
    properties:
      RequesterUserId:
        type: integer
      RequesterIdNo:
        type: integer
      RequestTypeId:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GCOD0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GCOD0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getchgoccdraft:
    post:
      operationId: GetChangeOccupationDraft
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetChangeOccupationDraftRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetChangeOccupationDraft
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetChangeOccupationDraftRq_MessageType'
        description: GetChangeOccupationDraftRq
        required: true
