swagger: "2.0"
info:
  title: GetContractDetails V2
  x-ibm-name: getcontractdetails-v2
  version: 1.0.0
  description: 'This service is used to get contract details '
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-getscontract)/contractmanagement/getcontractdetails
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  GetContractDetailsRq_MessageType:
    type: object
    properties:
      GetContractDetailsRq:
        $ref: '#/definitions/GetContractDetailsRq_Type'
  GetContractDetailsRs_MessageType:
    type: object
    properties:
      GetContractDetailsRs:
        $ref: '#/definitions/GetContractDetailsRs_Type'
  GetContractDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetContractDetailsRq_BodyType'
  GetContractDetailsRq_BodyType:
    type: object
    properties:
      ContractId:
        type: integer
  GetContractDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetContractDetailsRs_BodyType'
  GetContractDetailsRs_BodyType:
    type: object
    properties:
      TemplatesDetails:
        $ref: '#/definitions/TemplatesDetails_Type'
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      UpdateRequesterDetails:
        $ref: '#/definitions/UpdateRequesterDetails_Type'
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      ContractDetails:
        $ref: '#/definitions/ContractDetails_Type'
    required:
    - TemplatesDetails
    - EstablishmentDetails
    - RequesterDetails
    - UpdateRequesterDetails
    - LaborerDetails
    - ContractDetails
  ContractDetails_Type:
    type: object
    properties:
      ContractId:
        type: integer
      LaborerJobNumber:
        type: string
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      OccupationDetails:
        $ref: '#/definitions/OccupationDetails_Type'
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      ContractDuration:
        $ref: '#/definitions/CodeName_Type'
      ExecutionLocation:
        $ref: '#/definitions/CodeName_Type'
      ContractPeriod:
        type: integer
      ProbationPeriod:
        type: integer
      NoticePeriod:
        type: integer
      VacationPeriod:
        type: integer
      WorkingHoursType:
        $ref: '#/definitions/CodeName_Type'
      HoursPerWeek:
        type: integer
      DaysPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      RestingDays:
        type: integer
      SalaryType:
        $ref: '#/definitions/CodeName_Type'
      Salary:
        type: string
      TotalSalary:
        type: string
      SalaryDueDay:
        type: integer
      PercentageReasonEN:
        type: string
      PercentageReasonAR:
        type: string
      CurrentStartDate:
        $ref: '#/definitions/HGDate_Type'
      CurrentExpiryDate:
        $ref: '#/definitions/HGDate_Type'
      OriginalStartDate:
        $ref: '#/definitions/HGDate_Type'
      OriginalExpiryDate:
        $ref: '#/definitions/HGDate_Type'
      RenewalStatus:
        $ref: '#/definitions/CodeName_Type'
      RenewalTimes:
        type: integer
      RenewalPeriod:
        type: integer
      ContractRenewCount:
        type: integer
      CreationDate:
        type: string
        format: date-time
      LastModifiedDate:
        type: string
        format: date-time
      LaborerAppRejDate:
        type: string
        format: date-time
      RejectionDescription:
        type: string
      RejectionReason:
        $ref: '#/definitions/CodeName_Type'
      UpdateReason:
        $ref: '#/definitions/CodeName_Type'
      UpdateDate:
        type: string
        format: date-time
      ModificationReason:
        $ref: '#/definitions/CodeName_Type'
      Status:
        $ref: '#/definitions/CodeName_Type'
      LastWorkingDay:
        type: string
        format: date
      Version:
        type: integer
      Language:
        $ref: '#/definitions/CodeName_Type'
      DateType:
        $ref: '#/definitions/CodeName_Type'
      RelatedTo:
        $ref: '#/definitions/CodeName_Type'
      Allowances:
        $ref: '#/definitions/Allowances_Type'
      OptionalClauses:
        $ref: '#/definitions/OptionalClauses_Type'
      AdditionalTerms:
        $ref: '#/definitions/AdditionalTerms_Type'
      InKindBenefits:
        $ref: '#/definitions/InKindBenefits_Type'
      Commission:
        $ref: '#/definitions/Commission_Type'
      IsGosiMigrated:
        type: string
      IsGosiAdded:
        type: integer
      IsGosiUpdated:
        type: integer
      IsGosiTerminated:
        type: integer
      IsRegisteredWithGOSI:
        type: integer
      IsUnified:
        type: boolean
      ExternalContractId:
        type: integer
      MissingInfoStatus:
        $ref: '#/definitions/CodeName_Type'
      MissingInfoModificationReason:
        $ref: '#/definitions/CodeName_Type'
      MissingInfoSuggestedIBAN:
        type: string
      MissingInfoSuggestedMobileNo:
        type: string
      MissingInfoNationalAddress:
        type: string
    required:
    - ContractId
    - LaborerJobNumber
    - JobTitle
    - OccupationDetails
    - ContractType
    - ContractDuration
    - ExecutionLocation
    - ContractPeriod
    - ProbationPeriod
    - NoticePeriod
    - VacationPeriod
    - WorkingHoursType
    - HoursPerWeek
    - DaysPerWeek
    - HoursPerDay
    - RestingDays
    - SalaryType
    - Salary
    - TotalSalary
    - SalaryDueDay
    - PercentageReasonEN
    - PercentageReasonAR
    - CurrentStartDate
    - CurrentExpiryDate
    - OriginalStartDate
    - OriginalExpiryDate
    - RenewalStatus
    - RenewalTimes
    - RenewalPeriod
    - ContractRenewCount
    - CreationDate
    - LastModifiedDate
    - LaborerAppRejDate
    - RejectionDescription
    - RejectionReason
    - UpdateReason
    - UpdateDate
    - ModificationReason
    - Status
    - LastWorkingDay
    - Version
    - Language
    - DateType
    - RelatedTo
    - Allowances
    - OptionalClauses
    - AdditionalTerms
    - InKindBenefits
    - Commission
    - IsGosiMigrated
    - IsGosiAdded
    - IsGosiUpdated
    - IsGosiTerminated
    - IsRegisteredWithGOSI
    - IsUnified
  InKindBenefits_Type:
    type: object
    properties:
      InKindBenefitsItem:
        type: array
        items:
          $ref: '#/definitions/InKindBenefitsItem_Type'
  InKindBenefitsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
      DescriptionEn:
        type: string
      DescriptionAr:
        type: string
      Frequency:
        $ref: '#/definitions/CodeName_Type'
      DueDate:
        type: string
        format: date
  Commission_Type:
    type: object
    properties:
      CommissionItem:
        type: array
        items:
          $ref: '#/definitions/CommissionItem_Type'
  CommissionItem_Type:
    type: object
    properties:
      CommissionBaseEn:
        type: string
      CommissionBaseAr:
        type: string
      Percentage:
        type: string
      Frequency:
        $ref: '#/definitions/CodeName_Type'
  OptionalClauses_Type:
    type: object
    properties:
      OptionalClausesItem:
        type: array
        items:
          $ref: '#/definitions/OptionalClausesItem_Type'
  OccupationDetails_Type:
    type: object
    properties:
      OccupationId:
        type: integer
      OccupationAr:
        type: string
      OccupationEn:
        type: string
  AdditionalTerms_Type:
    type: object
    properties:
      AdditonalTermsItem:
        type: array
        items:
          $ref: '#/definitions/AdditionalTermsItem_Type'
  AdditionalTermsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
  AdditionalAllowancesList_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/Item_Type'
  Item_Type:
    type: object
    properties:
      BenefitNameAr:
        type: string
      BenefitNameEn:
        type: string
      Frequency:
        $ref: '#/definitions/CodeName_Type'
      AmountType:
        $ref: '#/definitions/CodeName_Type'
      Amount:
        type: integer
  Allowances_Type:
    type: object
    properties:
      AllowancesItem:
        type: array
        items:
          $ref: '#/definitions/AllowancesItem_Type'
  AllowancesItem_Type:
    type: object
    properties:
      AllowanceType:
        $ref: '#/definitions/CodeName_Type'
      Frequency:
        $ref: '#/definitions/CodeName_Type'
      IsProvidedByEstablishment:
        type: integer
      AmountType:
        $ref: '#/definitions/CodeName_Type'
      NameAr:
        type: string
      NameEn:
        type: string
      Amount:
        type: number
        format: double
  HGDate_Type:
    type: object
    properties:
      Hijri:
        type: integer
      Gregorian:
        type: string
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
    required:
    - JobTitleAr
    - JobTitleEng
  RequesterDetails_Type:
    type: object
    properties:
      RequesterName:
        type: string
      RequesterIdNo:
        type: string
      RequesterRoleEn:
        type: string
      RequesterRoleAr:
        type: string
      RequesterType:
        $ref: '#/definitions/CodeName_Type'
    required:
    - RequesterName
    - RequesterIdNo
    - RequesterRoleEn
    - RequesterRoleAr
    - RequesterType
  UpdateRequesterDetails_Type:
    type: object
    properties:
      UpdateRequesterName:
        type: string
      UpdateRequesterIdNo:
        type: string
      UpdateRequesterRoleEn:
        type: string
      UpdateRequesterRoleAr:
        type: string
      UpdateRequesterType:
        $ref: '#/definitions/CodeName_Type'
    required:
    - UpdateRequesterName
    - UpdateRequesterIdNo
    - UpdateRequesterRoleEn
    - UpdateRequesterRoleAr
    - UpdateRequesterType
  LaborerDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      LaborerIdType:
        $ref: '#/definitions/CodeName_Type'
      LaborerType:
        $ref: '#/definitions/CodeName_Type'
      PassportNumber:
        type: string
      BorderNumber:
        type: integer
      LaborerName:
        type: string
      LaborerEmail:
        type: string
      LaborerMobileNumber:
        type: string
      LaborerNationalAddress:
        type: string
      DOBType:
        type: integer
      LaborerDOB:
        $ref: '#/definitions/HGDate_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      IsBarmawiLaborer:
        type: integer
      Gender:
        $ref: '#/definitions/CodeName_Type'
      MaritalStatus:
        $ref: '#/definitions/CodeName_Type'
      Education:
        $ref: '#/definitions/CodeName_Type'
      Specialty:
        $ref: '#/definitions/CodeName_Type'
      WorkLocation:
        $ref: '#/definitions/CodeName_Type'
      IBAN:
        type: string
    required:
    - LaborerIdNo
    - LaborerIdType
    - LaborerType
    - PassportNumber
    - BorderNumber
    - LaborerName
    - LaborerEmail
    - LaborerMobileNumber
    - LaborerNationalAddress
    - DOBType
    - LaborerDOB
    - Nationality
    - IsBarmawiLaborer
    - Gender
    - MaritalStatus
    - Education
    - Specialty
    - WorkLocation
    - IBAN
  EstablishmentDetails_type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      UnifiedNumberId:
        type: integer
      UnifiedNationalNumber:
        type: integer
      EstablishmentType:
        $ref: '#/definitions/CodeName_Type'
      EstablishmentNameAr:
        type: string
      EstablishmentNameEn:
        type: string
      EstablishmentEmail:
        type: string
      EstablishmentNationalAddress:
        type: string
      PhoneNumber:
        type: string
      MobileNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentId
    - UnifiedNumberId
    - UnifiedNationalNumber
    - EstablishmentType
    - EstablishmentNameAr
    - EstablishmentNameEn
    - EstablishmentEmail
    - EstablishmentNationalAddress
    - PhoneNumber
    - MobileNumber
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
  TemplatesDetails_Type:
    type: object
    properties:
      TemplateId:
        type: integer
      TemplateName:
        type: string
      TemplateDescription:
        type: string
  OptionalClausesItem_Type:
    type: object
    properties:
      OptionalClausesType:
        $ref: '#/definitions/CodeName_Type'
      Period:
        type: integer
      Field:
        type: string
      Location:
        type: string
      FirstParty:
        type: string
      SecondParty:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  UploadedFilesList_Type:
    type: object
    properties:
      UploadedFilesItem:
        type: array
        items:
          $ref: '#/definitions/UploadedFilesItem_Type'
  UploadedFilesItem_Type:
    type: object
    properties:
      FileId:
        type: string
      FileTypeId:
        type: integer
      FileTypeEn:
        type: string
      FileTypeAr:
        type: string
    required:
    - FileId
    - FileTypeId
    - FileTypeEn
    - FileTypeAr
paths:
  /getcontractdetails:
    post:
      operationId: 'GetContractDetails '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetContractDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'GetContractDetails '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetContractDetailsRq_MessageType'
        description: 'The scope of this service is used to get contract details '
        required: true
