swagger: "2.0"
info:
  title: GetCustomPolicyRequestDetails
  x-ibm-name: getcustompolicyrequestdetails
  version: 1.0.0
  description: This service is used to get a list of custom policy requests with it's
    details.
schemes:
- https
basePath: /policies
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-ip)$(cat-target-url-policies)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetCustomPolicyRequestDetailsRq_MessageType:
    type: object
    properties:
      GetCustomPolicyRequestDetailsRq:
        $ref: '#/definitions/GetCustomPolicyRequestDetailsRq_Type'
  GetCustomPolicyRequestDetailsRs_MessageType:
    type: object
    properties:
      GetCustomPolicyRequestDetailsRs:
        $ref: '#/definitions/GetCustomPolicyRequestDetailsRs_Type'
  GetCustomPolicyRequestDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetCustomPolicyRequestDetailsRq_BodyType'
  GetCustomPolicyRequestDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetCustomPolicyRequestDetailsRs_BodyType'
  GetCustomPolicyRequestDetailsRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "13"
      SequenceNumber:
        type: integer
        default: "195003"
      RequestId:
        type: integer
        default: "10034"
      PageSize:
        type: integer
        default: "1"
      PageIndex:
        type: integer
        default: "100"
    required:
    - PageSize
    - PageIndex
  GetCustomPolicyRequestDetailsRs_BodyType:
    type: object
    properties:
      CustomPolicyDetailsList:
        $ref: '#/definitions/CustomPolicyDetailsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - CustomPolicyDetailsList
    - TotalRecordsCount
  CustomPolicyDetailsList_Type:
    type: object
    properties:
      CustomPolicyItem:
        type: array
        items:
          $ref: '#/definitions/CustomPolicyItem_Type'
  CustomPolicyItem_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      RequestId:
        type: integer
      RequesterName:
        type: string
      RequestDescription:
        type: string
      CreationDate:
        type: string
      LastModifiedDate:
        type: string
      StatusId:
        $ref: '#/definitions/CodeName_Type'
      LawOfficeId:
        type: string
      EstablishmentContactDetails:
        $ref: '#/definitions/EstablishmentContactDetails_Type'
      RejectionDescription:
        type: string
      LOComments:
        type: string
      PaymentReference:
        type: string
      CompCancelationReason:
        $ref: '#/definitions/CodeName_Type'
      LOCancelationReason:
        $ref: '#/definitions/CodeName_Type'
      PolicyHistory:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - RequestId
    - RequesterName
    - RequestDescription
    - CreationDate
    - LastModifiedDate
    - StatusId
    - LawOfficeId
    - EstablishmentContactDetails
    - RejectionDescription
    - LOComments
    - PaymentReference
    - CompCancelationReason
    - LOCancelationReason
    - PolicyHistory
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  EstablishmentContactDetails_Type:
    type: object
    properties:
      ContactName:
        type: string
      ContactEmail:
        type: string
      ContactPhoneNumber:
        type: string
      ContactCity:
        $ref: '#/definitions/CodeName_Type'
    required:
    - ContactName
    - ContactEmail
    - ContactPhoneNumber
    - ContactCity
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GCPRD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GCPRD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getcustpolreqdet:
    post:
      operationId: GetCustomPolicyRequestDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetCustomPolicyRequestDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'Get Custom Policy Request Details '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetCustomPolicyRequestDetailsRq_MessageType'
        description: GetCustomPolicyRequestDetailsRq
        required: true
