swagger: "2.0"
info:
  title: GetEstablishmentLicenses
  version: 1.0.0
  description: This service is used to retrieve operational, baladi & housing licenses.
  x-ibm-name: getestablishmentlicenses
basePath: /estabmanagement
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
paths:
  /getestablishmentlicenses:
    post:
      operationId: GetEstablishmentLicenses
      description: This service is used to retrieve operational, baladi & housing
        licenses.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        description: GetEstablishmentLicensesRq
        schema:
          $ref: '#/definitions/GetEstablishmentLicensesRq_MessageType'
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentLicensesRs_MessageType'
definitions:
  GetEstablishmentLicensesRq_MessageType:
    type: object
    properties:
      GetEstablishmentLicensesRq:
        $ref: '#/definitions/GetEstablishmentLicensesRq_Type'
  GetEstablishmentLicensesRs_MessageType:
    type: object
    properties:
      GetEstablishmentLicensesRs:
        $ref: '#/definitions/GetEstablishmentLicensesRs_Type'
  GetEstablishmentLicensesRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentLicensesRq_BodyType'
  GetEstablishmentLicensesRq_BodyType:
    type: object
    properties:
      NationalUnifiedNumber:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      OperationLicenseDetails:
        $ref: '#/definitions/LicenseDetails_Type'
      MunicipalLicenseDetails:
        $ref: '#/definitions/MLDetails_Type'
      HousingLicenseDetails:
        $ref: '#/definitions/LicenseDetails_Type'
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - PageSize
    - PageIndex
  LicenseDetails_Type:
    type: object
    properties:
      LicenseId:
        type: string
      LicenseStatus:
        type: string
  MLDetails_Type:
    type: object
    properties:
      LicenseId:
        type: string
      LicenseStatus:
        type: string
      LocationsStatus:
        type: string
  GetEstablishmentLicensesRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentLicensesRs_BodyType'
  GetEstablishmentLicensesRs_BodyType:
    type: object
    properties:
      MunicipalLicenseDetails:
        $ref: '#/definitions/MunicipalLicenses_List'
      OperationLicenseDetails:
        $ref: '#/definitions/OperationalLicenses_List'
      HousingLicenseDetails:
        $ref: '#/definitions/HousingLicenses_List'
  MunicipalLicenses_List:
    type: object
    properties:
      License:
        type: array
        items:
          $ref: '#/definitions/MunicipalLicenses_Type'
  OperationalLicenses_List:
    type: object
    properties:
      LicenseItem:
        type: array
        items:
          $ref: '#/definitions/OperationalLicenses_Type'
  OperationalLicenses_Type:
    type: object
    properties:
      CRNationalNumber:
        type: string
      LicenseNumber:
        type: string
      LicenseSource:
        $ref: '#/definitions/IDName_Type'
      LicenseIssueDate:
        $ref: '#/definitions/Date_Type'
      LicenseExpiryDate:
        $ref: '#/definitions/Date_Type'
      LicenseStatus:
        $ref: '#/definitions/IDName_Type'
      LicenseType:
        type: string
      LicenseName:
        type: string
      ApprovedUnit:
        type: integer
      IndustrialEstablishmentName:
        type: string
      IndustrialEstablishmentStatus:
        type: string
      CreationDate:
        type: string
      ActivitiesDetails:
        $ref: '#/definitions/ActivitiesDetails_List'
  HousingLicenses_List:
    type: object
    properties:
      LicenseItem:
        type: array
        items:
          $ref: '#/definitions/HousingLicenses_Type'
  MunicipalLicenses_Type:
    type: object
    properties:
      UnifiedNationalNumber:
        type: string
      LocationId:
        type: integer
      LocationName:
        type: string
      LocationDescription:
        type: string
      LocationStatus:
        $ref: '#/definitions/IDName_Type'
      LocationCity:
        type: string
      LicenseStatus:
        $ref: '#/definitions/IDName_Type'
      LocationCoordinates:
        $ref: '#/definitions/Coordinates_Type'
      LocationAddress:
        type: string
      MunicipalLicenseId:
        type: string
      MunicipalLicenseStartDate:
        $ref: '#/definitions/Date_Type'
      MunicipalLicenseExpiryDate:
        $ref: '#/definitions/Date_Type'
      MunicipalLicenseArea:
        type: string
      MunicipalLicenseDoorsCount:
        type: integer
      ActivityISICCode:
        type: string
      ActivityISICDescription:
        type: string
      ActivityISICDescriptionEn:
        type: string
      MunicipalLicenseStatus:
        type: string
      LocationURL:
        type: string
      BaladiaName:
        type: string
      CommercialName:
        type: string
      isMain:
        type: string
      AdditionalNo:
        type: string
      Amanah:
        $ref: '#/definitions/Amanah_Type'
      BoardsList:
        $ref: '#/definitions/Boards_Type'
      District:
        $ref: '#/definitions/Name_Type'
      MunicipalLicenseActivity:
        $ref: '#/definitions/Activity_List'
      ShortAddress:
        type: string
      CreationDate:
        type: string
      SubActivities:
        $ref: '#/definitions/Activities_List'
      TotalRecordsCount:
        type: integer
  IDName_Type:
    type: object
    properties:
      ID:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
  Name_Type:
    type: object
    properties:
      NameAr:
        type: string
      NameEn:
        type: string
  Date_Type:
    type: object
    properties:
      Hijri:
        type: string
      Gregorian:
        type: string
        format: date
    required:
    - Hijri
    - Gregorian
  Amanah_Type:
    type: object
    properties:
      AmanahCode:
        type: string
      AmanahName:
        type: string
  Board_Type:
    type: object
    properties:
      BoardType:
        type: string
      BoardArea:
        type: integer
  Boards_Type:
    type: object
    properties:
      Board:
        type: array
        items:
          $ref: '#/definitions/Board_Type'
  Coordinates_Type:
    type: object
    properties:
      Longitude:
        type: string
      Latitude:
        type: string
  Activities_List:
    type: object
    properties:
      ActivityItem:
        type: array
        items:
          $ref: '#/definitions/IDName_Type'
  Activity_List:
    type: object
    properties:
      ActivityItem:
        type: array
        items:
          $ref: '#/definitions/Activity_Type'
  Activity_Type:
    type: object
    properties:
      ActivityISICCode:
        type: string
      ActivityISICDescription:
        type: string
      ActivityAmanahDescription:
        type: string
      ActivityArea:
        type: integer
  ActivitiesDetails_List:
    type: object
    properties:
      ActivityDetailItem:
        $ref: '#/definitions/ActivityDetail_Type'
  ActivityDetail_Type:
    type: object
    properties:
      ActivityISICCode:
        type: string
      ActivityISICDescriptionAr:
        type: string
      ActivityISICDescriptionEn:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      FK_EstablishmentId:
        type: integer
  HousingLicenses_Type:
    type: object
    properties:
      LaborOfficeId:
        type: string
      SequenceNumber:
        type: string
      LicenseId:
        type: string
      LicStatusId:
        type: string
      LicStatusDesc:
        type: string
      DistrictName:
        type: string
      LocationCoordinates:
        $ref: '#/definitions/Coordinates_Type'
      Capacity:
        type: string
      StreetName:
        type: string
      CityName:
        type: string
      OwnerName:
        type: string
      Baladya:
        type: string
      Amanah:
        type: string
      LicenseType:
        type: string
      HousingType:
        type: string
      CRNationalNumber:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: http://cmpm-dashboard-profile-http-ace.apps.stg.qiwa-nonprod.local/estabmanagement/getestablishmentlicenses
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
