swagger: "2.0"
info:
  title: GetExceptionalEstablishmentBalancesDetails
  x-ibm-name: getexceptionalestablishmentbalancesdetails
  version: 1.0.0
  description: GetExceptionalEstablishmentBalancesDetails
schemes:
- https
basePath: /visa/expansion
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-expv-expansiongets)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetExceptionalEstablishmentBalancesDetailsRq_MessageType:
    type: object
    properties:
      GetExceptionalEstablishmentBalancesDetailsRq:
        $ref: '#/definitions/GetExceptionalEstablishmentBalancesDetailsRq_Type'
  GetExceptionalEstablishmentBalancesDetailsRs_MessageType:
    type: object
    properties:
      GetExceptionalEstablishmentBalancesDetailsRs:
        $ref: '#/definitions/GetExceptionalEstablishmentBalancesDetailsRs_Type'
  GetExceptionalEstablishmentBalancesDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetExceptionalEstablishmentBalancesDetailsRq_BodyType'
  GetExceptionalEstablishmentBalancesDetailsRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      ExceptionalBalanceStatusIds:
        type: string
      ExceptionRequestId:
        type: string
      RequestBalanceTypeIds:
        type: string
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - PageSize
    - PageIndex
  GetExceptionalEstablishmentBalancesDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetExceptionalEstablishmentBalancesDetailsRs_BodyType'
  GetExceptionalEstablishmentBalancesDetailsRs_BodyType:
    type: object
    properties:
      ExceptionalBalances:
        $ref: '#/definitions/ExceptionalBalances_Type'
      TotalRecordCount:
        type: integer
    required:
    - ExceptionalBalances
    - TotalRecordCount
  ExceptionalBalances_Type:
    type: object
    properties:
      BalanceDetails:
        type: array
        items:
          $ref: '#/definitions/BalanceDetails_Type'
    required:
    - BalanceDetails
  BalanceDetails_Type:
    type: object
    properties:
      ExceptionRequestId:
        type: string
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      EstablishmentID:
        type: integer
      EstablishmentName:
        type: string
      ExceptionalBalanceStartDate:
        type: string
      ExpirationDate:
        type: string
      CreationDate:
        type: string
      ExceptionalBalanceType:
        $ref: '#/definitions/CodeName_Type'
      QuotaBalance:
        type: integer
      ExceptionalBalanceStatus:
        $ref: '#/definitions/CodeName_Type'
    required:
    - ExceptionRequestId
    - LaborOfficeId
    - EstablishmentSequence
    - EstablishmentID
    - EstablishmentName
    - ExceptionalBalanceStartDate
    - ExpirationDate
    - CreationDate
    - ExceptionalBalanceType
    - QuotaBalance
    - ExceptionalBalanceStatus
  CodeName_Type:
    type: object
    properties:
      Id:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Id
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getexcepestabbalancesdetails:
    post:
      operationId: GetExceptionalEstablishmentBalancesDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetExceptionalEstablishmentBalancesDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetExceptionalEstablishmentBalancesDetails
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetExceptionalEstablishmentBalancesDetailsRq_MessageType'
        description: GetExceptionalEstablishmentBalancesDetails
        required: true
