swagger: "2.0"
info:
  title: GetEstablishmentAllData SP
  x-ibm-name: getestablishmentalldata-sp
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  properties: {}
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(dp-hrsddp-sp)/GetEstablishmentAllData
        follow-redirects: false
        inject-proxy-headers: true
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /getestablishmentalldata:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
