swagger: "2.0"
info:
  title: GetEstablishmentsUnifiedNumberMLSD
  x-ibm-name: getestablishmentsunifiednumbermlsd
  version: 1.0.0
  description: This service is used to get the unified number for the establishments.
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdget1)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetEstablishmentsUnifiedNumberMLSDRq_MessageType:
    type: object
    properties:
      GetEstablishmentsUnifiedNumberMLSDRq:
        $ref: '#/definitions/GetEstablishmentsUnifiedNumberMLSDRq_Type'
  GetEstablishmentsUnifiedNumberMLSDRs_MessageType:
    type: object
    properties:
      GetEstablishmentsUnifiedNumberMLSDRs:
        $ref: '#/definitions/GetEstablishmentsUnifiedNumberMLSDRs_Type'
  GetEstablishmentsUnifiedNumberMLSDRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentsUnifiedNumberMLSDRq_BodyType'
  GetEstablishmentsUnifiedNumberMLSDRq_BodyType:
    type: object
    properties:
      EstablishmentIdsList:
        $ref: '#/definitions/EstablishmentIds'
  EstablishmentIds:
    type: object
    properties:
      EstablishmentIds:
        type: array
        items:
          type: string
          default: "234234"
  GetEstablishmentsUnifiedNumberMLSDRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentsUnifiedNumberMLSDRs_BodyType'
  GetEstablishmentsUnifiedNumberMLSDRs_BodyType:
    type: object
    properties:
      UnifiedNumbersList:
        $ref: '#/definitions/UnifiedNumbersList_Type'
  UnifiedNumbersList_Type:
    type: object
    properties:
      UnifiedNumbers:
        type: array
        items:
          $ref: '#/definitions/UnifiedNumbers_Type'
  UnifiedNumbers_Type:
    type: object
    properties:
      EstablishmentId:
        type: string
      UnifiedNumberId:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGEUN001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGEUN001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getestablishmentsunifiednumbermlsd:
    post:
      operationId: GetEstablishmentsUnifiedNumberMLSD
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentsUnifiedNumberMLSDRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Establishment Quota Factors MLSD
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEstablishmentsUnifiedNumberMLSDRq_MessageType'
        description: GetEstablishmentsUnifiedNumberMLSDRq
        required: true
