swagger: "2.0"
info:
  title: GetEntityByCR
  x-ibm-name: getentitybycr
  version: 1.0.0
  description: GetEntityByCR
host: $(catalog.host)
schemes:
- https
basePath: /common
security:
- clientID: []
  clientSecret: []
securityDefinitions:
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://example.com
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-mci)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetEntityByCRRq_MessageType:
    type: object
    properties:
      GetEntityByCRRq:
        $ref: '#/definitions/GetEntityByCRRq_Type'
  GetEntityByCRRs_MessageType:
    type: object
    properties:
      GetEntityByCRRs:
        $ref: '#/definitions/GetEntityByCRRs_Type'
  GetEntityByCRRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEntityByCRRq_BodyType'
  GetEntityByCRRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: integer
  GetEntityByCRRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEntityByCRRs_BodyType'
  GetEntityByCRRs_BodyType:
    type: object
    properties:
      CRNumber:
        type: integer
      CRName:
        type: string
      IsMain:
        type: integer
      MainCR:
        type: integer
      CRBusiness:
        $ref: '#/definitions/CodeName_Type'
      Activities:
        type: string
      NationalNo:
        type: integer
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      CRLocation:
        $ref: '#/definitions/CodeName_Type'
      CRStatus:
        type: string
      Capital:
        type: integer
      CompanyPaidCapital:
        type: integer
      CompanyShareCount:
        type: integer
      FiscalDate:
        $ref: '#/definitions/FiscalDate_Type'
      ISICs:
        $ref: '#/definitions/ISICsList_Type'
      Parties:
        $ref: '#/definitions/PartiesList_Type'
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      TypeEn:
        type: string
      TypeAr:
        type: string
  FiscalDate_Type:
    type: object
    properties:
      Id:
        type: integer
      Name:
        type: string
      EndDay:
        type: integer
      EndMonth:
        type: integer
  ISICsList_Type:
    type: object
    properties: {}
  PartiesList_Type:
    type: object
    properties: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getentitybycr:
    post:
      operationId: GetEntityByCR
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEntityByCRRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Foreigner Information NIC
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEntityByCRRq_MessageType'
        description: ' GetEntityByCRRq'
        required: true
