swagger: "2.0"
info:
  title: GetEstAndEmpDetailsByID
  description: This service returns employee basic details after validating ID with
    DOB
  x-ibm-name: getestandempdetailsbyid
  version: 1.0.0
schemes:
- https
basePath: /nic/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /getestandempdetailsbyid/idNumber/{idNumber}/dateOfBirth/{dateOfBirth}:
    parameters:
    - $ref: '#/parameters/X-IBM-Client-Id'
    - $ref: '#/parameters/X-IBM-Client-Secret'
    - $ref: '#/parameters/idNumber'
    - $ref: '#/parameters/dateOfBirth'
    get:
      tags:
      - Get Est And Emp Details By ID
      description: This service returns details for the establishment provided and
        the given user's detail if the user is a delegate.
      operationId: getestandempdetailsfordelegate
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
definitions:
  ResponseModel:
    type: object
    description: This response object returned by the get operation
    properties:
      economicActivity:
        $ref: '#/definitions/economicActivity'
      taraineeSevenhundredNum:
        type: integer
      traineeEstName:
        type: string
      traineeName:
        type: string
      estLocation:
        type: string
      jobTitleEn:
        type: string
      jobTitleAr:
        type: string
      nationalityEn:
        type: string
      nationalityAr:
        type: string
      genderEn:
        type: string
      genderAr:
        type: string
      traineeEmail:
        type: string
      traineeMobNum:
        type: string
  economicActivity:
    type: object
    properties:
      id:
        type: string
      en:
        type: string
      ar:
        type: string
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  idNumber:
    in: path
    name: idNumber
    description: idNumber
    required: true
    type: integer
  dateOfBirth:
    in: path
    name: dateOfBirth
    description: dateOfBirth
    required: true
    type: string
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response201:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
      Location:
        type: string
        description: Id url encoded
  Response204:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - map:
        version: 2.0.0
        title: map
        inputs:
          idNumber:
            schema:
              type: integer
            variable: request.parameters.idNumber
          dateOfBirth:
            schema:
              type: string
            variable: request.parameters.dateOfBirth
        outputs:
          "":
            schema:
              description: ""
              type: object
              properties:
                idNumber:
                  type: string
                  name: idNumber
                dateOfBirth:
                  type: string
                  name: dateOfBirth
              example: "{\r\n            \"idNumber\": \"1606059952\",\r\n            \"dateOfBirth\":
                \"1411-02-05\"\r\n        }"
            variable: message.body
            content: application/json
        actions:
        - set: .idNumber
          from: idNumber
        - set: .dateOfBirth
          from: dateOfBirth
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\r\nvar cfg={\r\n    \"serviceCode\" :
          \"NDI00001\",\r\n    \"channelId\" : \"Integration\",\r\n    \"requestName\"
          : \"GetEstAndEmpDetailsByIDRq\",\r\n    \"responseName\": \"GetEstAndEmpDetailsByIDRs\",\r\n
          \   \"errorMap\" :{\r\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid
          Request\"}\r\n    }\r\n    \r\n};\r\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\nvar millisecondsvalue = \"\"+(new Date()).getTime();\nvar
          dt = new Date();\nvar cfg = apim.getvariable('cfg');\nvar OperatorId=apim.getvariable('message.headers.Operator-Id');\nvar
          appname = apim.getvariable('client.app.name');\n \nvar appcReq = {\n    [cfg.requestName]:{\n
          \       \"Header\" : {\n            \"TransactionId\" : millisecondsvalue,\n
          \           \"ChannelId\": cfg.channelId,\n            \"SessionId\": apim.getvariable('message.headers.X-Request-Id'),\n
          \           \"RequestTime\" : formatDate(dt),\n            \"ServiceCode\":
          cfg.serviceCode,\n            \"DebugFlag\": \"1\",\n            \"UserInfo\":
          {\n                \"UserId\": apim.getvariable('message.headers.UserId'),\n
          \               \"IDNumber\": apim.getvariable('message.headers.IDNumber')\t\t\t\t\n
          \           },\n            \"UDF\": {\n                \"KeyValueArr\":
          [\n                    {\n                        \"key\": \"Product\",\n
          \                       \"value\": \"Skillsportal\"\n                    },\n
          \                   {\n                        \"key\": \"Client\",\n                        \"value\":
          appname\n                    }\n                ]\n            }\t\t\t\n
          \       },\n        \"Body\" : apim.getvariable('message.body')\n    }\n};\n
          \nif (typeof OperatorId !== 'undefined')\n    appcReq[cfg.requestName].Header.UserInfo
          = {\n        \"IDNumber\" : OperatorId\n    };\nsession.output.write(appcReq);\napim.output('application/json');\n
          \n \nfunction formatDate(d)\n{\n    //get the month\n    var month = d.getMonth();\n
          \   //get the day\n    //convert day to string\n    var day = d.getDate().toString();\n
          \   //get the year\n    var year = d.getFullYear();\n    var hour = d.getHours().toString();\n
          \   var minitue = d.getMinutes().toString();\n    var second = d.getSeconds().toString();\n
          \   var millisecond = d.getMilliseconds().toString();\n    //pull the last
          two digits of the year\n    year = year.toString();\n    //increment month
          by 1 since it is 0 indexed\n    //converts month to a string\n    month
          = (month + 1).toString();\n \n    //if month is 1-9 pad right with a 0 for
          two digits\n    if (month.length === 1)\n        month = \"0\" + month;\n
          \n    //if day is between 1-9 pad right with a 0 for two digits\n    if
          (day.length === 1)\n        day = \"0\" + day;\n \n    if (hour.length ===
          1)\n        hour = \"0\" + hour;\n \n    if (minitue.length === 1)\n        minitue
          = \"0\" + minitue;\n \n    if (second.length === 1)\n        second = \"0\"
          + second;\n    if (millisecond.length == 1)\n        millisecond = \"00\"
          + millisecond;\n    if (millisecond.length == 2)\n        millisecond =
          \"0\" + millisecond;\n\n \n    //return the string \"MMddyy\"\n    return
          year+\"-\"+month+\"-\"+day+\" \"+hour + \":\" + minitue + \":\" + second+\".\"+millisecond;\n}"
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: $(ace-tip-skills-portal)/external/getestandempdetailsbyid
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "var apim = require('apim');\r\napim.output('application/json');\r\nvar
          message = apim.getvariable('message.body');\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          Header = message[cfg.responseName].Header;\r\nvar TransactionId = Header.TransactionId;\r\nvar
          ChannelId = Header.ChannelId;\r\nvar RequestTime = Header.RequestTime;\r\nvar
          SessionId = Header.SessionId;\r\nvar MWRequestTime = Header.MWRequestTime;\r\nvar
          MWResponseTime = Header.MWResponseTime;\r\nvar status = Header.ResponseStatus.Status;\r\nvar
          code = Header.ResponseStatus.Code;\r\napim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\r\napim.setvariable('message.headers.Channel-Id',ChannelId,'add');\r\nif
          (RequestTime !== 'undefined')\r\napim.setvariable('message.headers.RequestTime',RequestTime,'add');\r\nif
          (SessionId !== 'undefined')\r\napim.setvariable('message.headers.X-Request-Id',SessionId,'add');\r\nif
          (MWRequestTime !== 'undefined')\r\napim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\r\nif
          (MWResponseTime !== 'undefined')\r\napim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\r\napim.setvariable('message.headers.Response-Status',status,'add');\r\napim.setvariable('message.headers.Response-Code',code,'add');"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\r\n\r\n\r\nvar message = apim.getvariable('message.body');\r\nvar
                cfg = apim.getvariable('cfg');\r\nvar body = message[cfg.responseName].Body;\r\n\r\nsession.output.write(body);\r\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\r\n\r\nvar message = apim.getvariable('message.body');\r\nvar
                cfg = apim.getvariable('cfg');          \r\nvar error = {\r\n  \"errorCode\":
                message[cfg.responseName].Header.ResponseStatus.Code,\r\n  \"errorMessage\":
                {\r\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\r\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\r\n
                \ }\r\n};\r\n\r\nvar httperror=0;\r\nif(cfg.errorMap){\r\n    if(cfg.errorMap[error.errorCode]){\r\n
                \      httperror = cfg.errorMap[error.errorCode].code;\r\n       \r\n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\r\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\r\n
                \      //apim.error('ERROR',httperror,errmgs,details);\r\n    }\r\n}\r\nif(httperror
                == 0){\r\n   httperror = 409;\r\n   // apim.error('ERROR',400,'Bad
                Request','Invalid request');\r\n}\r\napim.setvariable('message.status.code',httperror,'set');\r\n\r\nsession.output.write(error);\r\napim.output('application/json');"
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
