swagger: "2.0"
info:
  title: GetEstablishmentLaborersMLSD
  x-ibm-name: getestablishmentlaborersmlsd
  version: 1.0.1
  description: The scope of this service is to get all laborers under the establishment.
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdget1)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetEstablishmentLaborersMLSDRq_MessageType:
    type: object
    properties:
      GetEstablishmentLaborersMLSDRq:
        $ref: '#/definitions/GetEstablishmentLaborersMLSDRq_Type'
  GetEstablishmentLaborersMLSDRs_MessageType:
    type: object
    properties:
      GetEstablishmentLaborersMLSDRs:
        $ref: '#/definitions/GetEstablishmentLaborersMLSDRs_Type'
  GetEstablishmentLaborersMLSDRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentLaborersMLSDRq_BodyType'
  GetEstablishmentLaborersMLSDRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      ForeignersOrSaudi:
        type: integer
      LaborerFirstName:
        type: string
      LaborerIdNo:
        type: string
      BorderNumber:
        type: string
      WPExpiryDateFrom:
        type: string
      WPExpiryDateTo:
        type: string
      IdExpiryDate:
        type: string
      ServiceStartDate:
        type: string
      WithoutBorders:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - PageSize
    - PageIndex
  GetEstablishmentLaborersMLSDRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetEstablishmentLaborersMLSDRs_BodyType'
  GetEstablishmentLaborersMLSDRs_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      LaborersList:
        $ref: '#/definitions/LaborersList_Type'
      TotalRecordCount:
        type: integer
  EstablishmentDetails_Type:
    type: object
    properties:
      EstablishmentId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentName:
        type: string
      UnifiedNumber:
        type: integer
      ISIC4ActivityId:
        type: integer
      EstablishmentStatusId:
        type: integer
  LaborersList_Type:
    type: object
    properties:
      Laborers:
        type: array
        items:
          $ref: '#/definitions/Laborers_Type'
  Laborers_Type:
    type: object
    properties:
      PK_LaborerId:
        type: integer
      LaborerIdNo:
        type: integer
      LaborerName:
        $ref: '#/definitions/LaborerName_Type'
      BirthYear:
        type: integer
      Gender:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      EducationalStatus:
        $ref: '#/definitions/CodeName_Type'
      Qualificaition:
        $ref: '#/definitions/CodeName_Type'
      Job:
        $ref: '#/definitions/CodeName_Type'
      LaborerStatus:
        $ref: '#/definitions/CodeName_Type'
      AccomodationStatus:
        $ref: '#/definitions/CodeName_Type'
      EntryDate:
        type: string
      Religion:
        type: string
      IdReleaseDate:
        type: string
      WorkPermitId:
        type: integer
      IdExpiryDate:
        type: string
      ServiceStartDate:
        type: string
      ServiceEndDate:
        type: string
      PassportDetails:
        $ref: '#/definitions/PassportDetails_Type'
      BorderNumber:
        type: integer
      WPDetails:
        $ref: '#/definitions/WPDetails_Type'
      ImmunizationStatus:
        $ref: '#/definitions/ImmunizationStatus_Type'
  LaborerName_Type:
    type: object
    properties:
      First:
        type: string
      Second:
        type: string
      Third:
        type: string
      Fourth:
        type: string
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      Name:
        type: string
  PassportDetails_Type:
    type: object
    properties:
      PassportNo:
        type: integer
      PassportSource:
        type: string
      PassportReleaseDate:
        type: string
  WPDetails_Type:
    type: object
    properties:
      WPStartDate:
        type: string
      WPExpirationDate:
        type: string
      WorkPermitType:
        $ref: '#/definitions/CodeName_Type'
  ImmunizationStatus_Type:
    type: object
    properties:
      Code:
        type: string
      NameAr:
        type: string
      NameEn:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getestablabmlsd:
    post:
      operationId: GetEstablishmentLaborersMLSD
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentLaborersMLSDRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: To get all laborers under the establishment
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEstablishmentLaborersMLSDRq_MessageType'
        description: GetEstablishmentLaborersMLSDRq
        required: true
