swagger: "2.0"
info:
  title: GetEstablishmentAuthorizedUserV2
  x-ibm-name: getestablishmentauthorizeduserv2
  version: 1.0.0
  description: GetEstablishmentAuthorizedUserV2
schemes:
- https
basePath: /usermanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-usrm-checksandgetum)/usermanagement/getestablishmentauthorizeduserv2
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  GetEstablishmentAuthorizedUserV2Rq_MessageType:
    type: object
    properties:
      GetEstablishmentAuthorizedUserV2Rq:
        $ref: '#/definitions/GetEstablishmentAuthorizedUserV2Rq_Type'
  GetEstablishmentAuthorizedUserV2Rs_MessageType:
    type: object
    properties:
      GetEstablishmentAuthorizedUserV2Rs:
        $ref: '#/definitions/GetEstablishmentAuthorizedUserV2Rs_Type'
  GetEstablishmentAuthorizedUserV2Rq_Type:
    type: object
    properties:
      Body:
        $ref: '#/definitions/GetEstablishmentAuthorizedUserV2Rq_BodyType'
  GetEstablishmentAuthorizedUserV2Rq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
  GetEstablishmentAuthorizedUserV2Rs_Type:
    type: object
    properties:
      Body:
        $ref: '#/definitions/GetEstablishmentAuthorizedUserV2Rs_BodyType'
  GetEstablishmentAuthorizedUserV2Rs_BodyType:
    type: object
    properties:
      TransactionID:
        type: integer
    required:
    - TransactionID
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getestablishmentauthorizeduserv2:
    post:
      operationId: GetEstablishmentAuthorizedUserV2
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetEstablishmentAuthorizedUserV2Rs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetEstablishmentAuthorizedUserV2
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetEstablishmentAuthorizedUserV2Rq_MessageType'
        description: GetEstablishmentAuthorizedUserV2
        required: true
