swagger: "2.0"
info:
  title: GetForeignerAllData
  x-ibm-name: getforeigneralldata
  version: 1.0.0
  description: This service is used to get foreigner details, border number and prison
    status.
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-nic-getforalldata)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  GetForeignerAllDataRq_MessageType:
    type: object
    properties:
      GetForeignerAllDataRq:
        $ref: '#/definitions/GetForeignerAllDataRq_Type'
  GetForeignerAllDataRs_MessageType:
    type: array
    items:
      type: object
      properties:
        GetForeignerAllDataRs:
          $ref: '#/definitions/GetForeignerAllDataRs_Type'
  GetForeignerAllDataRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetForeignerAllDataRq_BodyType'
  GetForeignerAllDataRq_BodyType:
    type: object
    properties:
      IdOrBorderNo:
        type: string
      IqamaExpiryDate:
        type: integer
      ExcludeHomeJobs:
        type: integer
      BirthDate:
        type: string
    required:
    - IdOrBorderNo
  GetForeignerAllDataRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetForeignerAllDataRs_BodyType'
  GetForeignerAllDataRs_BodyType:
    type: object
    properties:
      BirthDate:
        $ref: '#/definitions/GHDate_Type'
      Gender:
        type: string
      MartialStatus:
        $ref: '#/definitions/CodeandName_Type'
      Name:
        $ref: '#/definitions/Name_Type'
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      'Nationality ':
        $ref: '#/definitions/CodeandName_Type'
      HRSDNationality:
        $ref: '#/definitions/CodeName_Type'
      Occupation:
        $ref: '#/definitions/CodeandName_Type'
      HRSDOccupation:
        $ref: '#/definitions/CodeName_Type'
      Relationship:
        $ref: '#/definitions/CodeandName_Type'
      Religion:
        $ref: '#/definitions/CodeandName_Type'
      HRSDReligion:
        $ref: '#/definitions/CodeName_Type'
      Residency:
        $ref: '#/definitions/Residency_Type'
      Sponsor:
        $ref: '#/definitions/Sponsor_Type'
      Status:
        $ref: '#/definitions/Status_type'
      Travel:
        $ref: '#/definitions/Travel_Type'
      Visa:
        $ref: '#/definitions/Visa_Type'
      BorderNumber:
        type: string
      LaborerIdNo:
        type: string
      AlienPrisonStatus:
        type: boolean
      IsDependent:
        type: boolean
      IsHomeWroker:
        type: boolean
    required:
    - Gender
    - LaborOfficeId
    - SequenceNumber
    - BorderNumber
    - LaborerIdNo
    - AlienPrisonStatus
    - IsDependent
    - IsHomeWroker
  Name_Type:
    type: object
    properties:
      FirstName:
        type: string
      FirstNameT:
        type: string
      FullName:
        type: string
      LastName:
        type: string
      LastNameT:
        type: string
      SecondName:
        type: string
      SecondNameT:
        type: string
      ThirdName:
        type: string
      ThirdNameT:
        type: string
      TranslatedName:
        type: string
    required:
    - FirstName
    - FirstNameT
    - FullName
    - LastName
    - LastNameT
    - SecondName
    - SecondNameT
    - ThirdName
    - ThirdNameT
    - TranslatedName
  Residency_Type:
    type: object
    properties:
      ExpiryDate:
        $ref: '#/definitions/GHDate_Type'
      IdNo:
        type: integer
      IdType:
        type: string
      IssueDate:
        $ref: '#/definitions/GHDate_Type'
      IssuePlace:
        type: string
    required:
    - IdNo
    - IdType
    - IssuePlace
  Sponsor_Type:
    type: object
    properties:
      IdNo:
        type: integer
      Name:
        type: string
      Occupation:
        type: string
      Status:
        type: string
      Type:
        $ref: '#/definitions/CodeandName_Type'
    required:
    - IdNo
    - Name
    - Occupation
    - Status
  Status_type:
    type: object
    properties:
      FingerPrintStatus:
        type: boolean
      PersonStatus:
        $ref: '#/definitions/CodeandName_Type'
    required:
    - FingerPrintStatus
  Travel_Type:
    type: object
    properties:
      EntryDate:
        $ref: '#/definitions/GHDate_Type'
      LastEntryDate:
        $ref: '#/definitions/GHDate_Type'
      LastExitDate:
        $ref: '#/definitions/GHDate_Type'
      PassportExpiryDate:
        $ref: '#/definitions/GHDate_Type'
      PassportNumber:
        type: string
      TravelStatus:
        type: string
    required:
    - TravelStatus
    - PassportNumber
  Visa_Type:
    type: object
    properties:
      FinalExitVisaIssued:
        type: boolean
      VisaExpiryDate:
        $ref: '#/definitions/GHDate_Type'
      VisaType:
        type: string
    required:
    - FinalExitVisaIssued
    - VisaType
  GHDate_Type:
    type: object
    properties:
      GregorianDate:
        type: string
      HijriDate:
        type: string
    required:
    - GregorianDate
    - HijriDate
  CodeandName_Type:
    type: object
    properties:
      Code:
        type: integer
      Name:
        type: string
    required:
    - Code
    - Name
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - NameAr
    - NameEn
    - Code
paths:
  /getforeigneralldata:
    post:
      operationId: GetForeignerAllData
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetForeignerAllDataRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetForeignerAllData
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetForeignerAllDataRq_MessageType'
        description: GetForeignerAllDataRq
        required: true
