swagger: "2.0"
info:
  title: GetIndividualContractsList V2
  x-ibm-name: getindividualcontractslist-v2
  version: 1.0.0
  description: GetIndividualContractsList
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.3.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        websocket-upgrade: false
        graphql-send-type: detect
        target-url: $(ace-cntmv2-getscontract)/contractmanagement/getindividualcontractslist
        cache-key: ""
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetIndividualContractsListRq_MessageType:
    type: object
    properties:
      GetIndividualContractsListRq:
        $ref: '#/definitions/GetIndividualContractsListRq_Type'
  GetIndividualContractsListRs_MessageType:
    type: object
    properties:
      GetIndividualContractsListRs:
        $ref: '#/definitions/GetIndividualContractsListRs_Type'
  GetIndividualContractsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetIndividualContractsListRq_BodyType'
  GetIndividualContractsListRq_BodyType:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      StatusList:
        $ref: '#/definitions/StatusList_Type'
      IsUnified:
        type: integer
        enum:
        - 0
        - 1
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - LaborerIdNo
    - PageSize
    - PageIndex
  StatusList_Type:
    type: object
    properties:
      Status:
        type: array
        items:
          $ref: '#/definitions/Status_Type'
    required:
    - Status
  Status_Type:
    type: object
    properties:
      Id:
        type: integer
    required:
    - Id
  GetIndividualContractsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetIndividualContractsListRs_BodyType'
  GetIndividualContractsListRs_BodyType:
    type: object
    properties:
      ContractsList:
        $ref: '#/definitions/ContractsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  ContractsList_Type:
    type: object
    properties:
      ContractsItem:
        type: array
        items:
          $ref: '#/definitions/ContractsItem_Type'
    required:
    - ContractsItem
  ContractsItem_Type:
    type: object
    properties:
      ContractId:
        type: integer
      EstablishmentId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentNameEn:
        type: string
      EstablishmentNameAr:
        type: string
      RequesterName:
        type: string
      LaborerIdNo:
        type: integer
      LaborerName:
        type: string
      NationalityId:
        type: integer
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      ContractPeriod:
        type: integer
      ProbationPeriod:
        type: integer
      NoticePeriod:
        type: integer
      SalaryTypeId:
        type: integer
      Salary:
        type: number
        format: double
      TotalMonthlySalary:
        type: number
        format: double
      PercentageReasonEN:
        type: string
      PercentageReasonAR:
        type: string
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      Occupation:
        $ref: '#/definitions/CodeName_Type'
      WorkLocation:
        $ref: '#/definitions/CodeName_Type'
      OriginalStartDate:
        type: string
        format: datetime
      OriginalExpiryDate:
        type: string
        format: datetime
      CurrentStartDate:
        type: string
        format: datetime
      CurrentExpiryDate:
        type: string
        format: datetime
      CreationDate:
        type: string
        format: datetime
      LastModifiedDate:
        type: string
        format: datetime
      LaborerAppRejDate:
        type: string
        format: datetime
      LastWorkingDay:
        type: string
        format: date
      InActiveReason:
        $ref: '#/definitions/InActiveReason_Type'
      RejectionReason:
        $ref: '#/definitions/CodeName_Type'
      RejectionDescription:
        type: string
      UpdateReason:
        $ref: '#/definitions/CodeName_Type'
      ModificationReason:
        $ref: '#/definitions/CodeName_Type'
      Status:
        $ref: '#/definitions/CodeName_Type'
      RelatedTo:
        $ref: '#/definitions/CodeName_Type'
      RenewalStatus:
        $ref: '#/definitions/CodeName_Type'
      RenewalTimes:
        type: integer
      RenewalPeriod:
        type: integer
      ContractRenewCount:
        type: integer
      IsRegisteredwithGosi:
        type: string
      IsGosiMigrated:
        type: string
        enum:
        - 0
        - 1
        - 2
      IsUnified:
        type: string
        enum:
        - 1
        - 0
    required:
    - ContractId
    - EstablishmentId
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentNameEn
    - EstablishmentNameAr
    - RequesterName
    - LaborerIdNo
    - LaborerName
    - NationalityId
    - ContractType
    - ContractPeriod
    - ProbationPeriod
    - NoticePeriod
    - SalaryTypeId
    - Salary
    - TotalMonthlySalary
    - PercentageReasonEN
    - PercentageReasonAR
    - JobTitle
    - Occupation
    - WorkLocation
    - OriginalStartDate
    - OriginalExpiryDate
    - CurrentStartDate
    - CurrentExpiryDate
    - CreationDate
    - LastModifiedDate
    - LaborerAppRejDate
    - LastWorkingDay
    - InActiveReason
    - RejectionReason
    - RejectionDescription
    - UpdateReason
    - ModificationReason
    - Status
    - RelatedTo
    - ContractRenewCount
    - IsRegisteredwithGosi
    - IsGosiMigrated
    - IsUnified
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  InActiveReason_Type:
    type: object
    properties:
      InActiveReasonId:
        type: integer
      InActiveReasonAr:
        type: string
      InActiveReasonEn:
        type: string
      TerminationReason:
        $ref: '#/definitions/CodeName_Type'
    required:
    - InActiveReasonId
    - InActiveReasonEn
    - InActiveReasonAr
    - TerminationReason
  UpdateJoiningDateDetails_Type:
    type: object
    properties:
      ProbationEndDate:
        type: string
        format: date
      OldJoiningDate:
        type: string
        format: date
      Occupation:
        $ref: '#/definitions/CodeName_Type'
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      BasicSalary:
        type: number
        format: double
      HousingAmount:
        type: number
        format: double
      OtherAllowancesAmount:
        type: number
        format: double
    required:
    - ProbationEndDate
    - OldJoiningDate
    - Occupation
    - ContractType
    - BasicSalary
    - HousingAmount
    - OtherAllowancesAmount
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEn:
        type: string
    required:
    - JobTitleEn
    - JobTitleAr
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getindividualcontractslist:
    post:
      operationId: GetIndividualContractsList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetIndividualContractsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'GetIndividualContractsList '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetIndividualContractsListRq_MessageType'
        description: GetIndividualContractsList
        required: true
