swagger: "2.0"
info:
  title: GetIndividualContractDetails V2
  x-ibm-name: getindividualcontractdetails-v2
  version: 1.0.0
  description: 'This service is used to get individual contract details '
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-getscontract)/contractmanagement/getindividualcontractdetails
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  GetIndividualContractDetailsRq_MessageType:
    type: object
    properties:
      GetIndividualContractDetailsRq:
        $ref: '#/definitions/GetIndividualContractDetailsRq_Type'
  GetIndividualContractDetailsRs_MessageType:
    type: object
    properties:
      GetIndividualContractDetailsRs:
        $ref: '#/definitions/GetIndividualContractDetailsRs_Type'
  GetIndividualContractDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetIndividualContractDetailsRq_BodyType'
  GetIndividualContractDetailsRq_BodyType:
    type: object
    properties:
      ContractId:
        type: integer
  GetIndividualContractDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetIndividualContractDetailsRs_BodyType'
  GetIndividualContractDetailsRs_BodyType:
    type: object
    properties:
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      TemplatesDetails:
        $ref: '#/definitions/TemplatesDetails_Type'
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      ContractDetails:
        $ref: '#/definitions/ContractDetails_Type'
    required:
    - LaborerDetails
    - EstablishmentDetails
    - RequesterDetails
    - ContractDetails
  ContractDetails_Type:
    type: object
    properties:
      ContractId:
        type: integer
      LaborerJobNumber:
        type: string
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      ContractDuration:
        $ref: '#/definitions/CodeName_Type'
      ContractPeriod:
        type: integer
      ProbationPeriod:
        type: integer
      WorkingHoursType:
        $ref: '#/definitions/CodeName_Type'
      VacationPeriod:
        type: integer
      Salary:
        type: string
      SalaryType:
        $ref: '#/definitions/CodeName_Type'
      PercentageReasonEN:
        type: string
      PercentageReasonAR:
        type: string
      CurrentStartDate:
        $ref: '#/definitions/HGDate_Type'
      CurrentExpiryDate:
        $ref: '#/definitions/HGDate_Type'
      OriginalStartDate:
        $ref: '#/definitions/HGDate_Type'
      OriginalExpiryDate:
        $ref: '#/definitions/HGDate_Type'
      RenewalStatus:
        $ref: '#/definitions/CodeName_Type'
      NoticePeriod:
        type: integer
      LastModifiedDate:
        $ref: '#/definitions/HGDate_Type'
      CreationDate:
        $ref: '#/definitions/HGDate_Type'
      LaborerAppRejDate:
        $ref: '#/definitions/HGDate_Type'
      EmployerAppRejDate:
        $ref: '#/definitions/HGDate_Type'
      RejectionDescription:
        type: string
      RejectionReason:
        $ref: '#/definitions/CodeName_Type'
      UpdateReason:
        $ref: '#/definitions/CodeName_Type'
      ModificationReason:
        $ref: '#/definitions/CodeName_Type'
      Status:
        $ref: '#/definitions/CodeName_Type'
      Version:
        type: integer
      Language:
        $ref: '#/definitions/CodeName_Type'
      DateType:
        $ref: '#/definitions/CodeName_Type'
      RelatedTo:
        $ref: '#/definitions/CodeName_Type'
      SalaryFrequency:
        $ref: '#/definitions/CodeName_Type'
      Allowances:
        $ref: '#/definitions/Allowances_Type'
      HoursPerWeek:
        type: integer
      DaysPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      OptionalClauses:
        $ref: '#/definitions/OptionalClauses_Type'
      OccupationDetails:
        $ref: '#/definitions/OccupationDetails_Type'
      AddtionalTerms:
        $ref: '#/definitions/AddtionalTerms_Type'
      TerminateFlag:
        type: integer
      Category:
        $ref: '#/definitions/CodeName_Type'
      UploadedFilesList:
        $ref: '#/definitions/UploadedFiles_Type'
      IsUploadFilesSkiped:
        type: integer
      IsGosiMigrated:
        type: integer
      IsGosiAdded:
        type: integer
      IsGosiUpdated:
        type: integer
      IsGosiTerminated:
        type: integer
      IsRegisteredWithGOSI:
        type: integer
    required:
    - ContractId
    - LaborerJobNumber
    - JobTitle
    - ContractType
    - ContractDuration
    - ProbationPeriod
    - WorkingHoursType
    - VacationPeriod
    - Salary
    - SalaryType
    - CurrentStartDate
    - CurrentExpiryDate
    - OriginalStartDate
    - OriginalExpiryDate
    - RenewalStatus
    - NoticePeriod
    - LastModifiedDate
    - CreationDate
    - LaborerAppRejDate
    - EmployerAppRejDate
    - RejectionDescription
    - RejectionReason
    - Status
    - Version
    - Language
    - DateType
    - RelatedTo
    - IsGosiAdded
    - IsGosiUpdated
    - IsGosiTerminated
    - IsRegisteredWithGOSI
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  LaborerDetails_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      LaborerType:
        $ref: '#/definitions/CodeName_Type'
      LaborerName:
        type: string
      LaborerIdExpiryDate:
        type: string
      LaborerEmail:
        type: string
      LaborerMobileNumber:
        type: string
      DOBType:
        type: integer
      LaborerDOB:
        $ref: '#/definitions/HGDate_Type'
      Gender:
        $ref: '#/definitions/CodeName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      Religion:
        $ref: '#/definitions/CodeName_Type'
      MaritalStatus:
        $ref: '#/definitions/CodeName_Type'
      Education:
        $ref: '#/definitions/CodeName_Type'
      Specialty:
        $ref: '#/definitions/CodeName_Type'
      WorkLocation:
        $ref: '#/definitions/CodeName_Type'
      IBAN:
        type: string
    required:
    - LaborerIdNo
    - LaborerType
    - LaborerName
    - LaborerIdExpiryDate
    - LaborerEmail
    - LaborerMobileNumber
    - LaborerDOB
    - DOBType
    - Gender
    - Nationality
    - Religion
    - MaritalStatus
    - Education
    - Specialty
    - WorkLocation
    - IBAN
  EstablishmentDetails_type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      EntityId:
        type: string
      UnifiedNumberId:
        type: integer
      EstablishmentNameAr:
        type: string
      EstablishmentNameEn:
        type: string
      EstablishmentEmail:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentId
    - EntityId
    - UnifiedNumberId
    - EstablishmentNameAr
    - EstablishmentNameEn
    - EstablishmentEmail
  RequesterDetails_Type:
    type: object
    properties:
      RequesterUserId:
        type: integer
      RequesterName:
        type: string
      RequesterIdNo:
        type: string
      RequesterRole:
        type: string
    required:
    - RequesterUserId
    - RequesterName
    - RequesterIdNo
  HGDate_Type:
    type: object
    properties:
      Hijri:
        type: integer
      Greogrian:
        type: string
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
    required:
    - JobTitleAr
    - JobTitleEng
  TemplatesDetails_Type:
    type: object
    properties:
      TemplateId:
        type: integer
      TemplateName:
        type: string
      TemplateDescription:
        type: string
  Allowances_Type:
    type: object
    properties:
      AllowancesItem:
        type: array
        items:
          $ref: '#/definitions/AllowancesItem_Type'
  AllowancesItem_Type:
    type: object
    properties:
      AllowanceType:
        $ref: '#/definitions/CodeName_Type'
      NameAr:
        type: string
      NameEn:
        type: string
      Frequency:
        $ref: '#/definitions/CodeName_Type'
      IsProvidedByEstablishment:
        type: integer
      AmountType:
        $ref: '#/definitions/CodeName_Type'
      Amount:
        type: number
  OccupationDetails_Type:
    type: object
    properties:
      OccupationId:
        type: integer
      OccupationAr:
        type: string
      OccupationEn:
        type: string
  OptionalClauses_Type:
    type: object
    properties:
      OptionalClausesItem:
        type: array
        items:
          $ref: '#/definitions/OptionalClausesItem_Type'
  OptionalClausesItem_Type:
    type: object
    properties:
      OptionalClausesType:
        $ref: '#/definitions/CodeName_Type'
      Period:
        type: integer
      Field:
        type: string
      Location:
        type: string
      FirstParty:
        type: string
      SecondParty:
        type: string
  AddtionalTerms_Type:
    type: object
    properties:
      AdditonalTermsItem:
        $ref: '#/definitions/AddtionalTermsItem_Type'
  AddtionalTermsItem_Type:
    type: object
    properties:
      NameEn:
        type: string
      NameAr:
        type: string
  UploadedFiles_Type:
    type: object
    properties:
      UploadedFilesItem:
        type: array
        items:
          $ref: '#/definitions/UploadedFilesItem_Type'
  UploadedFilesItem_Type:
    type: object
    properties:
      FileId:
        type: string
      FileTypeId:
        type: integer
      FileTypeEn:
        type: string
      FileTypeAr:
        type: string
    required:
    - FileId
    - FileTypeId
    - FileTypeEn
    - FileTypeAr
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getindividualcontractdetails:
    post:
      operationId: GetIndividualContractDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetIndividualContractDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'GetIndividualContractDetails '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetIndividualContractDetailsRq_MessageType'
        description: 'The scope of this service is used to get contract details '
        required: true
