swagger: "2.0"
info:
  title: GetLaborVisaList
  x-ibm-name: getlaborvisalist
  version: 1.0.0
schemes:
- https
basePath: /visas
security: []
securityDefinitions: {}
x-ibm-configuration:
  properties: {}
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(dp-nic-prod)
        follow-redirects: false
        inject-proxy-headers: true
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /getvisainfo:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
      - name: GetLaborVisaList Request
        in: body
        required: false
        schema:
          type: object
