swagger: "2.0"
info:
  title: 'GetOccupationCorrectionRequest '
  x-ibm-name: getoccupationcorrectionrequest
  version: 1.0.0
  description: 'This service is used to get the details about the occupation correction
    request that is related to this establishment. '
schemes:
- https
basePath: /chgoccupation
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-chgo-choccutility)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetOccupationCorrectionRequestRq_MessageType:
    type: object
    properties:
      GetOccupationCorrectionRequestRq:
        $ref: '#/definitions/GetOccupationCorrectionRequestRq_Type'
  GetOccupationCorrectionRequestRs_MessageType:
    type: object
    properties:
      GetNitaqComplianceWeightRs:
        $ref: '#/definitions/GetOccupationCorrectionRequestRs_Type'
  GetOccupationCorrectionRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetOccupationCorrectionRequestRq_BodyType'
  GetOccupationCorrectionRequestRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "654"
      SequenceNumber:
        type: integer
        default: "10654"
      LaborerIdNo:
        type: integer
        default: "12"
      PageSize:
        type: integer
        default: "1"
      PageIndex:
        type: integer
        default: "2"
    required:
    - LaborOfficeId
    - SequenceNumber
    - PageSize
    - PageIndex
  GetOccupationCorrectionRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetOccupationCorrectionRequestRs_BodyType'
  GetOccupationCorrectionRequestRs_BodyType:
    type: object
    properties:
      OccupationCorrection:
        $ref: '#/definitions/OccupationCorrection_Type'
      TotalRecordsCount:
        type: integer
    required:
    - OccupationCorrection
    - TotalRecordsCount
  OccupationCorrection_Type:
    type: object
    properties:
      Item:
        type: array
        items:
          $ref: '#/definitions/Item_Type'
  Item_Type:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      LaborerName:
        type: string
      RequesterIdNo:
        type: integer
      CurrentOccupation:
        $ref: '#/definitions/CodeName_Type'
      NewOccupation:
        $ref: '#/definitions/CodeName_Type'
      RequestId:
        type: integer
      CreationDate:
        type: string
      Status:
        $ref: '#/definitions/CodeName_Type'
      RejectionReason:
        type: string
    required:
    - LaborerIdNo
    - LaborerName
    - RequesterIdNo
    - CurrentOccupation
    - NewOccupation
    - RequestId
    - CreationDate
    - Status
    - RejectionReason
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GOCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GOCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getoccupationcorrectionrequest:
    post:
      operationId: 'GetOccupationCorrectionRequest '
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetOccupationCorrectionRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: 'GetOccupationCorrectionRequest '
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetOccupationCorrectionRequestRq_MessageType'
        description: 'GetOccupationCorrectionRequest '
        required: true
