swagger: "2.0"
info:
  title: GetPaymentsList
  x-ibm-name: getpaymentslist
  version: 1.0.0
  description: GetPaymentsList
schemes:
- https
basePath: /payment
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-pay-getpayments)/payment/getpaymentslist
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: payload
    error-content: payload
  buffering: true
definitions:
  GetPaymentsListRq_MessageType:
    type: object
    properties:
      GetPaymentsListRq:
        $ref: '#/definitions/GetPaymentsListRq_Type'
  GetPaymentsListRs_MessageType:
    type: object
    properties:
      GetPaymentsListRs:
        $ref: '#/definitions/GetPaymentsListRs_Type'
  GetPaymentsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetPaymentsListRq_BodyType'
  GetPaymentsListRq_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetailsType'
      PaymentReference:
        type: string
      FromDate:
        type: string
      ToDate:
        type: string
      PageSize:
        type: integer
      PageIndex:
        type: integer
      ProductId:
        type: integer
      ProviderId:
        type: integer
      PaymentStatusId:
        type: integer
        minimum: 1
        maximum: 8
      OrderBy:
        type: integer
      PaymentBrand:
        type: string
    required:
    - EstablishmentDetails
    - PageSize
    - PageIndex
  GetPaymentsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetPaymentsListRs_BodyType'
  GetPaymentsListRs_BodyType:
    type: object
    properties:
      PaymentsList:
        $ref: '#/definitions/PaymentsList_Type'
      TotalRecordsCount:
        type: integer
    required:
    - TotalRecordsCount
  PaymentsList_Type:
    type: object
    properties:
      PaymentItem:
        type: array
        items:
          $ref: '#/definitions/PaymentItem_Type'
  PaymentItem_Type:
    type: object
    properties:
      PaymentID:
        type: integer
      PaymentReference:
        type: string
      Description:
        type: string
      Amount:
        type: number
      Currency:
        type: string
      Status:
        $ref: '#/definitions/Status_Type'
      Provider:
        $ref: '#/definitions/Provider_Type'
      Application:
        $ref: '#/definitions/Application_Type'
      Product:
        $ref: '#/definitions/Product_Type'
      UserId:
        type: integer
      IDNO:
        type: string
      InsertDate:
        type: string
        format: date
      LastModifyDate:
        type: string
        format: date
      PGPaymentId:
        type: string
      MWTransactionId:
        type: string
      Comments:
        type: string
      Sys_User:
        type: string
    required:
    - PaymentID
    - PaymentReference
    - Description
    - Amount
    - Currency
    - Status
    - Provider
    - Application
    - Product
    - UserId
    - IDNO
    - InsertDate
    - LastModifyDate
    - PGPaymentId
    - MWTransactionId
    - Comments
    - Sys_User
  Status_Type:
    type: object
    properties:
      StatusId:
        type: integer
        minimum: 1
        maximum: 8
      StatusEn:
        type: string
      StatusAr:
        type: string
    required:
    - StatusId
    - StatusEn
    - StatusAr
  Provider_Type:
    type: object
    properties:
      ProviderId:
        type: integer
        minimum: 1
        maximum: 3
      ProviderEn:
        type: string
      ProviderAr:
        type: string
      PaymentBrand:
        type: string
    required:
    - ProviderId
    - ProviderEn
    - ProviderAr
  Application_Type:
    type: object
    properties:
      ApplicationId:
        type: integer
        minimum: 1
        maximum: 2
      ApplicationEn:
        type: string
      ApplicationAr:
        type: string
    required:
    - ApplicationId
    - ApplicationEn
    - ApplicationAr
  Product_Type:
    type: object
    properties:
      ProductId:
        type: integer
        minimum: 1
        maximum: 13
      ProductEn:
        type: string
      ProductAr:
        type: string
    required:
    - ProductId
    - ProductEn
    - ProductAr
  EstablishmentDetailsType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getpaymentslist:
    post:
      operationId: GetPaymentsList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetPaymentsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get the details and balance of an establishment e-wallet
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetPaymentsListRq_MessageType'
        description: GetPaymentsList
        required: true
