swagger: "2.0"
info:
  title: GetSakDetails
  x-ibm-name: getsakdetails
  version: 1.0.0
  description: 'Get SAK Details '
host: $(catalog.host)
schemes:
- https
basePath: /common
security:
- clientID: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://example.com
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-awqaf)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  type: rest
  phase: realized
  enforced: true
  testable: true
  application-authentication:
    certificate: false
definitions:
  GetSakDetailsRq_MessageType:
    type: object
    properties:
      GetSakDetailsRq:
        $ref: '#/definitions/GetSakDetailsRq_Type'
  GetSakDetailsRs_MessageType:
    type: object
    properties:
      GetSakDetailsRs:
        $ref: '#/definitions/GetSakDetailsRs_Type'
  GetSakDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetSakDetailsRq_BodyType'
  GetSakDetailsRq_BodyType:
    type: object
    properties:
      LicenseNumber:
        type: integer
    required:
    - LicenseNumber
  GetSakDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetSakDetailsRs_BodyType'
  GetSakDetailsRs_BodyType:
    type: object
    properties:
      OrganizationName:
        type: string
      LicenseNumber:
        type: integer
      OrganizationStatus:
        type: string
      SupervisoryName:
        type: string
      Category:
        type: string
      Note:
        type: string
      FoundationDateH:
        type: string
      RegistrationDateH:
        type: string
      Classification:
        type: string
      LastGrantDate:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getsakdetails:
    post:
      operationId: getsakdetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetSakDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get SAK Details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetSakDetailsRq_MessageType'
        description: GetSakDetailsRq
        required: true
