swagger: "2.0"
info:
  title: GetServiceSubServiceSectorsList
  x-ibm-name: getservicesubservicesectorslist
  version: 1.0.0
  description: This service is used to get all services and subservices for governmental
    sectors.
schemes:
- https
basePath: /visa/govsector
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-gov-govsectors)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetServiceSubServiceSectorsListRq_MessageType:
    type: object
    properties:
      GetServiceSubServiceSectorsListRq:
        $ref: '#/definitions/GetServiceSubServiceSectorsListRq_Type'
  GetServiceSubServiceSectorsListRs_MessageType:
    type: object
    properties:
      GetServiceSubServiceSectorsListRs:
        $ref: '#/definitions/GetServiceSubServiceSectorsListRs_Type'
  GetServiceSubServiceSectorsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetServiceSubServiceSectorsListRq_BodyType'
  GetServiceSubServiceSectorsListRq_BodyType:
    type: object
    properties:
      ServiceId:
        type: integer
      SubServiceId:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
  GetServiceSubServiceSectorsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetServiceSubServiceSectorsListRs_BodyType'
  GetServiceSubServiceSectorsListRs_BodyType:
    type: object
    properties:
      'ServicesList ':
        $ref: '#/definitions/ServicesList_Type'
      'SubServicesList ':
        $ref: '#/definitions/SubServicesList_Type'
  ServicesList_Type:
    type: object
    properties:
      ServicesDetails:
        type: array
        items:
          $ref: '#/definitions/ServicesDetails_Type'
      TotalRecordsCount:
        type: integer
  SubServicesList_Type:
    type: object
    properties:
      ServicesDetails:
        type: array
        items:
          $ref: '#/definitions/SubServicesDetails_Type'
      TotalCount:
        type: integer
  ServicesDetails_Type:
    type: object
    properties:
      Service:
        $ref: '#/definitions/CodeName_Type'
      'Description ':
        $ref: '#/definitions/Description_Type'
      ServiceURL:
        type: string
  SubServicesDetails_Type:
    type: object
    properties:
      Service:
        $ref: '#/definitions/CodeName_Type'
      'Description ':
        $ref: '#/definitions/Description_Type'
      SubServiceURL:
        type: string
  CodeName_Type:
    type: object
    properties:
      Id:
        type: integer
      'NameAr ':
        type: string
      NameEn:
        type: string
  Description_Type:
    type: object
    properties:
      DescriptionAr:
        type: string
      'DescriptionEn ':
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getservicesubseclist:
    post:
      operationId: GetServiceSubServiceSectorsList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetServiceSubServiceSectorsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: update governmental agent privilege on the services based on governmental
        sector
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetServiceSubServiceSectorsListRq_MessageType'
        description: GetServiceSubServiceSectorsListRq
        required: true
