swagger: "2.0"
info:
  title: GetTCTStatusesList
  version: 1.0.0
  description: GetTCTStatusesList
  x-ibm-name: gettctstatuseslist
paths:
  /gettctstatuslist:
    post:
      operationId: GetTCTStatusesList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetTCTStatusesListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service will be used to return the TCT statuses lookups values
        (Main, Cancelation and Release date reduction)
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetTCTStatusesListRq_MessageType'
        description: GetTCTStatusesListRq
        required: true
basePath: /trncntr
definitions:
  GetTCTStatusesListRq_MessageType:
    type: object
    properties:
      GetTCTStatusesListRq:
        $ref: '#/definitions/GetTCTStatusesListRq_Type'
  GetTCTStatusesListRs_MessageType:
    type: object
    properties:
      GetTCTStatusesListRs:
        $ref: '#/definitions/GetTCTStatusesListRs_Type'
  GetTCTStatusesListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetTCTStatusesListRq_BodyType'
  GetTCTStatusesListRq_BodyType:
    type: object
    properties:
      StatusRequestType:
        type: integer
        description: Defines the requested status type.
        enum:
        - 1
        - 2
        - 3
        - 4
    required:
    - StatusRequestType
  GetTCTStatusesListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetTCTStatusesListRs_BodyType'
  GetTCTStatusesListRs_BodyType:
    type: object
    properties:
      TerminationStatusList:
        $ref: '#/definitions/List_Type'
        description: Mandatory if StatusRequestType is 1 or 4
      TerminationCancelationStatusList:
        $ref: '#/definitions/List_Type'
        description: Mandatory if StatusRequestType is 2 or 4
      ReleaseDateUpdateStatusList:
        $ref: '#/definitions/List_Type'
        description: Mandatory if StatusRequestType is 3 or 4
  List_Type:
    type: object
    properties:
      Status:
        type: array
        items:
          $ref: '#/definitions/Item_Type'
      TotalRecordCount:
        type: integer
    required:
    - Status
    - TotalRecordCount
  Item_Type:
    type: object
    properties:
      StatusId:
        type: integer
      StatusEn:
        type: string
      StatusAr:
        type: string
    required:
    - StatusId
    - StatusEn
    - StatusAr
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-trncntr-getterminations)$(request.path)
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
