swagger: "2.0"
info:
  title: GetVisasOccupationsList
  x-ibm-name: getvisasoccupationslist
  version: 1.0.0
  description: GetVisasOccupationsList
schemes:
- https
basePath: /common
security:
- Oauth2.0:
  - IntegrationScope
  clientId: []
  clientSecret: []
securityDefinitions:
  Oauth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmnv-commonvisautilites)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetVisasOccupationsListRq_MessageType:
    type: object
    properties:
      GetVisasOccupationsListRq:
        $ref: '#/definitions/GetVisasOccupationsListRq_Type'
  GetVisasOccupationsListRs_MessageType:
    type: object
    properties:
      GetVisasOccupationsListRs:
        $ref: '#/definitions/GetVisasOccupationsListRs_Type'
  GetVisasOccupationsListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetVisasOccupationsListRq_BodyType'
  GetVisasOccupationsListRq_BodyType:
    type: object
    properties:
      OccupationId:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
  GetVisasOccupationsListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetVisasOccupationsListRs_BodyType'
  GetVisasOccupationsListRs_BodyType:
    type: object
    properties:
      OccupationsList:
        $ref: '#/definitions/OccupationsList_Type'
      TotalRecordsCount:
        type: integer
  OccupationsList_Type:
    type: object
    properties:
      Occupation:
        type: array
        items:
          $ref: '#/definitions/Occupation_Type'
  Occupation_Type:
    type: object
    properties:
      Status:
        $ref: '#/definitions/CodeName_Type'
      NumberOfVisas:
        type: integer
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
      Classification:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getvisasocclist:
    post:
      operationId: GetVisasOccupationsList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetVisasOccupationsListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetVisasOccupationsList
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetVisasOccupationsListRq_MessageType'
        description: GetVisasOccupationsList
        required: true
