swagger: "2.0"
info:
  title: GetVisitVisaRefundablePackages
  x-ibm-name: getvisitvisarefundablepackages
  version: 1.0.0
  description: This service is used to get the Visit visa refundable packages for
    establishment .
schemes:
- https
basePath: /visa/visitvisa
produces:
- application/json
consumes:
- application/json
security:
- clientID: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-vstv-vvutilities)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetVisitVisaRefundablePackagesRq_MessageType:
    type: object
    properties:
      GetVisitVisaRefundablePackagesRq:
        $ref: '#/definitions/GetVisitVisaRefundablePackagesRq_Type'
  GetVisitVisaRefundablePackagesRs_MessageType:
    type: object
    properties:
      GetVisitVisaRefundablePackagesRs:
        $ref: '#/definitions/GetVisitVisaRefundablePackagesRs_Type'
  GetVisitVisaRefundablePackagesRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetVisitVisaRefundablePackagesRq_BodyType'
  GetVisitVisaRefundablePackagesRq_BodyType:
    type: object
    properties:
      EstablishmentID:
        type: integer
        default: "3166592"
      EstablishmentSequence:
        type: integer
        default: "1493367"
      LaborOfficeID:
        type: integer
        default: "25"
  GetVisitVisaRefundablePackagesRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetVisitVisaRefundablePackagesRs_BodyType'
  GetVisitVisaRefundablePackagesRs_BodyType:
    type: object
    properties:
      PackageList:
        $ref: '#/definitions/PackageList'
  PackageList:
    type: object
    properties:
      PackageInfo:
        type: array
        items:
          $ref: '#/definitions/Packageinfo'
  Packageinfo:
    type: object
    properties:
      ID:
        type: integer
        default: "10000"
      EstablishmentID:
        type: integer
        default: "3166592"
      EstablishmentSequence:
        type: integer
        default: "1493367"
      IDNumber:
        type: integer
        default: "1024812248"
      UserID:
        type: integer
        default: "465740"
      Status:
        type: integer
        default: "1"
      PackageID:
        type: integer
        default: "4"
      EntityID:
        type: string
        default: 25-10743-38
      LaborOfficeID:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GVVRP001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: GVVRP001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23443"
      IDNumber:
        type: integer
        default: "23432"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
        default: SUCCESS
      Code:
        type: string
        default: "00000000"
      ArabicMsg:
        type: string
        default: تمت العملية بنجاح
      EnglishMsg:
        type: string
        default: Success Call
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getvisitvisarefundablepackages:
    post:
      operationId: GetVisitVisaRefundablePackages
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetVisitVisaRefundablePackagesRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Refundable Visa Packages
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetVisitVisaRefundablePackagesRq_MessageType'
        description: GetVisitVisaRefundablePackagesRq
        required: true
