swagger: "2.0"
info:
  title: GetWorkPermitLaborerList
  x-ibm-name: getworkpermitlaborerlist
  version: 1.0.1
  description: This service is used to get all laborers that are valid for a work
    permit
schemes:
- https
basePath: /workpermit
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wp-wpget)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetWorkPermitLaborerListRq_MessageType:
    type: object
    properties:
      GetWorkPermitLaborerListRq:
        $ref: '#/definitions/GetWorkPermitLaborerListRq_Type'
  GetWorkPermitLaborerListRs_MessageType:
    type: object
    properties:
      GetWorkPermitLaborerListRs:
        $ref: '#/definitions/GetWorkPermitLaborerListRs_Type'
  GetWorkPermitLaborerListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitLaborerListRq_BodyType'
  GetWorkPermitLaborerListRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      LaborerName:
        type: string
      IqamaId:
        type: integer
      BorderNumber:
        type: string
      IsEstablishing:
        type: integer
        enum:
        - 0
        - 1
      HasExceptionalBalance:
        type: integer
        enum:
        - 0
        - 1
      IsInvestmentEstablishment:
        type: integer
        enum:
        - 0
        - 1
      IsInRedNtiqat:
        type: integer
        enum:
        - 0
        - 1
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - IsEstablishing
    - HasExceptionalBalance
    - IsInvestmentEstablishment
    - IsInRedNtiqat
    - PageSize
    - PageIndex
  GetWorkPermitLaborerListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitLaborerListRs_BodyType'
  GetWorkPermitLaborerListRs_BodyType:
    type: object
    properties:
      LaborersList:
        $ref: '#/definitions/LaborersList_Type'
      PageSize:
        type: integer
      PageIndex:
        type: integer
      TotalRecordsCount:
        type: integer
    required:
    - LaborersList
    - PageIndex
    - PageSize
    - TotalRecordsCount
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  LaborersList_Type:
    type: object
    properties:
      LaborersListDetails:
        type: array
        items:
          $ref: '#/definitions/LaborersListDetails_Type'
    required:
    - LaborersListDetails
  LaborersListDetails_Type:
    type: object
    properties:
      LaborerName:
        type: string
      LaborerIdNo:
        type: integer
      BorderNumber:
        type: integer
      IqamaExpiryDate:
        type: string
      WorkPermitExpirationDate:
        type: string
    required:
    - LaborerName
    - LaborerIdNo
    - BorderNumber
    - IqamaExpiryDate
    - WorkPermitExpirationDate
paths:
  /getwplablist:
    post:
      operationId: GetWorkPermitLaborerList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetWorkPermitLaborerListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: GetWork Permit Laborer List
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetWorkPermitLaborerListRq_MessageType'
        description: GetWorkPermitLaborerListRq
        required: true
