swagger: "2.0"
info:
  title: GetWorkPermitInvoiceDetails
  x-ibm-name: getworkpermitinvoicedetails
  version: 1.0.0
  description: The aim of this service is to retrieve basic details of the work permit
    required in the billing process.
schemes:
- https
basePath: /workpermit
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wp-wpcommon2)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetWorkPermitInvoiceDetailsRq_MessageType:
    type: object
    properties:
      GetWorkPermitInvoiceDetailsRq:
        $ref: '#/definitions/GetWorkPermitInvoiceDetailsRq_Type'
  GetWorkPermitInvoiceDetailsRs_MessageType:
    type: object
    properties:
      GetWorkPermitInvoiceDetailsRs:
        $ref: '#/definitions/GetWorkPermitInvoiceDetailsRs_Type'
  GetWorkPermitInvoiceDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitInvoiceDetailsRq_BodyType'
  GetWorkPermitInvoiceDetailsRq_BodyType:
    type: object
    properties:
      SadadNumber:
        type: integer
      WorkPermitRequestId:
        type: integer
      RequestReferenceNo:
        type: string
  GetWorkPermitInvoiceDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitInvoiceDetailsRs_BodyType'
  GetWorkPermitInvoiceDetailsRs_BodyType:
    type: object
    properties:
      InvoiceNumber:
        type: integer
      SADADNumber:
        type: integer
      InvoiceIssueDate:
        type: string
      PaymentMethod:
        type: string
      PaymentBillDate:
        type: string
      TotalWorkPermitFees:
        type: integer
      EstablishmentInforamtion:
        $ref: '#/definitions/Establishmentnforamtion_Type'
      WorkPermitLaborerList:
        $ref: '#/definitions/WorkPermitLaborerList_Type'
      PaymentStatus:
        $ref: '#/definitions/PaymentStatus_Type'
    required:
    - InvoiceNumber
    - SADADNumber
    - InvoiceIssueDate
    - PaymentMethod
    - PaymentBillDate
    - TotalWorkPermitFees
    - EstablishmentInforamtion
    - WorkPermitLaborerList
    - PaymentStatus
  Establishmentnforamtion_Type:
    type: object
    properties:
      EstablishmentName:
        type: string
      EstablishmentAddress:
        $ref: '#/definitions/EstablishmentAddress_Type'
    required:
    - EstablishmentName
    - EstablishmentAddress
  EstablishmentAddress_Type:
    type: object
    properties:
      DistrictAreaAr:
        type: string
      DistrictAreaEn:
        type: string
      StreetNameAr:
        type: string
      StreetNameEn:
        type: string
      CityAr:
        type: string
      CityEn:
        type: string
      PostalCode:
        type: string
    required:
    - DistrictAreaAr
    - DistrictAreaEn
    - StreetNameAr
    - StreetNameEn
    - CityAr
    - CityEn
    - PostalCode
  WorkPermitLaborerList_Type:
    type: object
    properties:
      WorkPermitLaborerItem:
        $ref: '#/definitions/WorkPermitLaborerItem_Type'
    required:
    - WorkPermitLaborerItem
  WorkPermitLaborerItem_Type:
    type: object
    properties:
      EmployeeName:
        type: string
      EmployeeID:
        type: integer
      WPValidityPeriod:
        type: integer
      ValidUntilDate:
        type: string
      TotalWorkPermitFee:
        type: integer
    required:
    - EmployeeName
    - EmployeeID
    - WPValidityPeriod
    - ValidUntilDate
    - TotalWorkPermitFee
  PaymentStatus_Type:
    type: object
    properties:
      StatusId:
        type: integer
      StatusDescriptionAr:
        type: string
      StatusDescriptionEn:
        type: string
    required:
    - StatusId
    - StatusDescriptionAr
    - StatusDescriptionEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getworkpermitinvoicedetails:
    post:
      operationId: GetWorkPermitInvoiceDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetWorkPermitInvoiceDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Work Permit Invoice Details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetWorkPermitInvoiceDetailsRq_MessageType'
        description: GetWorkPermitInvoiceDetailsRq
        required: true
