swagger: "2.0"
info:
  title: GetWorkPermitDetailsMlsd
  x-ibm-name: getworkpermitdetailsmlsd
  version: 1.0.0
  description: This service is used to get laborer work permit’s information.
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdwp)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  GetWorkPermitDetailsMlsdRq_MessageType:
    type: object
    properties:
      GetWorkPermitDetailsMlsdRq:
        $ref: '#/definitions/GetWorkPermitDetailsMlsdRq_Type'
  GetWorkPermitDetailsMlsdRs_MessageType:
    type: object
    properties:
      GetWorkPermitDetailsMlsdRs:
        $ref: '#/definitions/GetWorkPermitDetailsMlsdRs_Type'
  GetWorkPermitDetailsMlsdRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitDetailsMlsdRq_BodyType'
  GetWorkPermitDetailsMlsdRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "21323"
      SequenceNumber:
        type: integer
        default: "2"
      IdNo:
        type: string
        default: "2132335"
      BorderNo:
        type: string
        default: "682"
      EstablishmentId:
        type: integer
        default: "28"
      PageIndex:
        type: integer
        default: "10"
      PageSize:
        type: integer
        default: "100"
  GetWorkPermitDetailsMlsdRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetWorkPermitDetailsMlsdRs_BodyType'
  GetWorkPermitDetailsMlsdRs_BodyType:
    type: object
    properties:
      LaborerWPDetailsList:
        $ref: '#/definitions/LaborerWPDetailsList_Type'
      TotalRecordsCount:
        type: integer
  LaborerWPDetailsList_Type:
    type: object
    properties:
      LaborerWPDetails:
        $ref: '#/definitions/LaborerWPDetails_Type'
  LaborerWPDetails_Type:
    type: object
    properties:
      WPStartDate:
        type: string
      WPExpirationDate:
        type: string
      LaborerId:
        type: integer
      IdNo:
        type: string
      IdReleaseDate:
        type: string
      BorderNo:
        type: string
      PassportNo:
        type: string
      Name:
        $ref: '#/definitions/Name_Type'
      EstablishmentName:
        type: string
      JobDetails:
        $ref: '#/definitions/JobDetails_Type'
      Nationality:
        $ref: '#/definitions/Nationality_Type'
      Gender:
        $ref: '#/definitions/Gender_Type'
      WorkingDate:
        $ref: '#/definitions/WorkingDate_Type'
      KingdomEntryDate:
        type: string
      Fees:
        $ref: '#/definitions/Fees_Type'
      Transaction:
        $ref: '#/definitions/Transaction_Type'
      WPDetails:
        $ref: '#/definitions/WPDetails_Type'
      LastWPExpirationDate:
        type: string
  Name_Type:
    type: object
    properties:
      'FirstName ':
        type: string
      SecoundName:
        type: string
      ThirdName:
        type: string
      'FourthName  ':
        type: string
  JobDetails_Type:
    type: object
    properties:
      'JobId ':
        type: integer
      JobName:
        type: string
  Nationality_Type:
    type: object
    properties:
      'NationalityId ':
        type: integer
      NationalityName:
        type: string
  Gender_Type:
    type: object
    properties:
      'GenderId ':
        type: integer
      GenderName:
        type: string
  WorkingDate_Type:
    type: object
    properties:
      'ServiceStartDate ':
        type: string
      ServiceEndDate:
        type: string
  Fees_Type:
    type: object
    properties:
      'WPFees ':
        type: number
      ExtraFees:
        type: number
      TotalLaborerWPFees:
        type: number
  Transaction_Type:
    type: object
    properties:
      'TransactionStatusId ':
        type: integer
      TransactionStatus:
        type: integer
      TransactionNumber:
        type: string
      TransactionDate:
        type: string
  WPDetails_Type:
    type: object
    properties:
      'WorkPermitTypeId ':
        type: integer
      WorkPermitType:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGWPD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: MGWPD001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getworkpermitdetailsmlsd:
    post:
      operationId: GetWorkPermitDetailsMlsd
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetWorkPermitDetailsMlsdRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get Work Permit Details MLSD
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetWorkPermitDetailsMlsdRq_MessageType'
        description: GetWorkPermitDetailsMlsdRq
        required: true
