swagger: "2.0"
info:
  title: GetWPFinalExitDebts
  x-ibm-name: getwpfinalexitdebts
  version: 1.0.0
  description: GetWPFinalExitDebts
schemes:
- https
basePath: /workpermit
security:
- OAuth2.0:
  - IntegrationScope
  clientId: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wp-wpget)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  GetWPFinalExitDebtsRq_MessageType:
    type: object
    properties:
      GetWPFinalExitDebtsRq:
        $ref: '#/definitions/GetWPFinalExitDebtsRq_Type'
  GetWPFinalExitDebtsRs_MessageType:
    type: object
    properties:
      GetWPFinalExitDebtsRs:
        $ref: '#/definitions/GetWPFinalExitDebtsRs_Type'
  GetWPFinalExitDebtsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetWPFinalExitDebtsRq_BodyType'
  GetWPFinalExitDebtsRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: string
      SequenceNumber:
        type: integer
      SadadNumber:
        type: integer
      LaborerIdNo:
        type: integer
      IsPaid:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - PageSize
    - PageIndex
  GetWPFinalExitDebtsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetWPFinalExitDebtsRs_BodyType'
  GetWPFinalExitDebtsRs_BodyType:
    type: object
    properties:
      FinalExitDebtsList:
        $ref: '#/definitions/DebtsList_Type'
      TotalRecordCount:
        type: integer
    required:
    - FinalExitDebtsList
    - TotalRecordCount
  DebtsList_Type:
    type: object
    properties:
      FinalExitDebtItem:
        $ref: '#/definitions/DebtItem_Type'
    required:
    - FinalExitDebtItem
  DebtItem_Type:
    type: object
    properties:
      DebtId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      DebtAmount:
        type: integer
      SadadNumber:
        type: integer
      IsPaid:
        type: integer
      CreationDate:
        type: string
      LaborersList:
        $ref: '#/definitions/LaborersList_Type'
    required:
    - DebtId
    - LaborOfficeId
    - SequenceNumber
    - DebtAmount
    - SadadNumber
    - IsPaid
    - CreationDate
    - LaborersList
  LaborersList_Type:
    type: object
    properties:
      Laborer:
        $ref: '#/definitions/LaborerItem_Type'
    required:
    - Laborer
  LaborerItem_Type:
    type: object
    properties:
      LaborerId:
        type: integer
      LaborerName:
        type: string
      IqamaNumber:
        type: integer
      BorderNumber:
        type: integer
    required:
    - LaborerId
    - LaborerName
    - IqamaNumber
    - BorderNumber
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /getwpfinalexitdebts:
    post:
      operationId: GetWPFinalExitDebts
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetWPFinalExitDebtsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service aims to retrieve the debt details related to the final
        exit work permit requests
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetWPFinalExitDebtsRq_MessageType'
        description: GetWPFinalExitDebtsRq
        required: true
