swagger: "2.0"
info:
  version: 1.0.0
  title: HRSD_Qiwa_QueryCentre_ExecCustQuery SP
  x-ibm-name: hrsd_qiwa_querycentre_execcustquery-sp
basePath: /hrsd
x-ibm-configuration:
  properties:
    target-url:
      value: http://example.com
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(dp-qiwadp-sp)/Qiwa_QueryCentre_ExecCustQuery
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /Qiwa_QueryCentre_ExecCustQuery:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
