swagger: "2.0"
info:
  title: InternalNICMolDoMaintainEmployeeWorkLocationDetails
  description: |
    This service is used for internal
  x-ibm-name: internalnicmoldomaintainemployeeworklocationdetails
  version: 1.0.0
schemes:
- https
basePath: /external/v1
security:
- clientIdHeader: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /internalMolDoMaintainEmployeeWorkLocationDetails:
    parameters:
    - $ref: '#/parameters/X-IBM-Client-Id'
    post:
      tags:
      - NIC
      operationId: internalnicmoldomaintainemployeeworklocationdetails
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        description: Request body
        required: true
        schema:
          $ref: '#/definitions/DoMaintainEmployeeWorkLocationDetailsBody'
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "500":
          $ref: '#/responses/Response500'
definitions:
  DoMaintainEmployeeWorkLocationDetailsBody:
    type: object
    description: Request payload for DoMaintainEmployeeWorkLocationDetails
    properties:
      PersonID:
        type: string
      EmploymentType:
        type: string
      EmployerID:
        type: string
      LaborOfficeID:
        type: string
      SequenceNumber:
        type: string
      LocationIsInsideMakkah:
        type: string
      City:
        type: string
      OperatorID:
        type: string
      ClientIPAddress:
        type: string
      lang:
        type: string
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        type: string
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
responses:
  Response200:
    description: Successful  response
  Response400:
    description: Bad Request
  Response401:
    description: Unauthorized
  Response403:
    description: Forbidden
  Response404:
    description: Not Found
  Response500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/ErrorModel'
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(dp-qiwadp-nic)/NIC/Mol/api/Person/DoMaintainEmployeeWorkLocationDetails
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
