swagger: "2.0"
info:
  title: IssueWorkPermitNIC
  x-ibm-name: issueworkpermitnic
  version: 1.0.0
  description: This service is used to issue the work permit request to NIC.
schemes:
- https
basePath: /workpermit
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-nic-nicsubmit)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  IssueWorkPermitNICRq_MessageType:
    type: object
    properties:
      IssueWorkPermitNICRq:
        $ref: '#/definitions/IssueWorkPermitNICRq_Type'
  IssueWorkPermitNICRs_MessageType:
    type: object
    properties:
      IssueWorkPermitNICRs:
        $ref: '#/definitions/IssueWorkPermitNICRs_Type'
  IssueWorkPermitNICRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/IssueWorkPermitNICRq_BodyType'
  IssueWorkPermitNICRq_BodyType:
    type: object
    properties:
      LaborerIdNo:
        type: integer
        default: "2138448804"
      LaborOfficeId:
        type: integer
        default: "87687"
      SequenceNumber:
        type: integer
        default: "1978"
      JobCode:
        type: integer
        default: "18"
      EstablishmentSponsorId:
        type: integer
        default: "19898"
      StartDate:
        type: integer
        default: "20200101"
      EndDate:
        type: integer
        default: "20200106"
      WpDuration:
        type: integer
        default: "16"
      WpLabOff:
        type: integer
        default: "41"
      WpLicenceNo:
        type: integer
        default: "5541"
      WpType:
        type: integer
        default: "1565"
    required:
    - LaborerIdNo
    - LaborOfficeId
    - SequenceNumber
    - JobCode
    - EstablishmentSponsorId
    - StartDate
    - EndDate
    - WpDuration
    - WpLabOff
    - WpLicenceNo
    - WpType
  IssueWorkPermitNICRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/IssueWorkPermitNICRs_BodyType'
  IssueWorkPermitNICRs_BodyType:
    type: object
    properties:
      LaborerIdNo:
        type: integer
      Message:
        type: string
      Status:
        type: integer
      Timestamp:
        type: string
      StartDate:
        type: integer
      WpDuration:
        type: integer
      WpLabOff:
        type: integer
      WpLicenceNo:
        type: integer
      WpType:
        type: integer
    required:
    - LaborerIdNo
    - Message
    - Status
    - Timestamp
    - StartDate
    - WpDuration
    - WpLabOff
    - WpLicenceNo
    - WpType
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: NIWP0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: NIWP0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23432"
      IDNumber:
        type: integer
        default: "324324"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /issuewpnic:
    post:
      operationId: IssueWorkPermitNIC
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/IssueWorkPermitNICRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: IssueWorkPermitNIC
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/IssueWorkPermitNICRq_MessageType'
        description: IssueWorkPermitNICRq
        required: true
