swagger: "2.0"
info:
  title: MCI_SwapCR
  x-ibm-name: mci-swapcr
  version: 1.0.0
  description: This service is used to check the swap of the establishment and CR.
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-transfer-ownership)/estabmanagement/transferownership/mciswapcr
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  MCI_SwapCRRq_MessageType:
    type: object
    properties:
      MCI_SwapCRRq:
        $ref: '#/definitions/MCI_SwapCRRq_Type'
  MCI_SwapCRRs_MessageType:
    type: object
    properties:
      MCI_SwapCRRs:
        $ref: '#/definitions/MCI_SwapCRRs_Type'
  MCI_SwapCRRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/MCI_SwapCRRq_BodyType'
  MCI_SwapCRRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: string
      ReferenceNo:
        type: string
      MainCR:
        type: string
      IsMain:
        type: integer
      NationalNo:
        type: string
      CRStatus:
        $ref: '#/definitions/IDName_Type'
      CRParties:
        $ref: '#/definitions/CRParties_Type'
      SwapStatus:
        type: string
        enum:
        - "1"
        - "2"
        - "3"
    required:
    - CRNumber
    - ReferenceNo
    - MainCR
    - IsMain
  MCI_SwapCRRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/MCI_SwapCRRs_BodyType'
  MCI_SwapCRRs_BodyType:
    type: object
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  IDName_Type:
    type: object
    properties:
      Id:
        type: integer
      Name:
        type: string
  CRParties_Type:
    type: object
    properties:
      CRParty:
        type: array
        items:
          $ref: '#/definitions/CRParty_Type'
  CRParty_Type:
    type: object
    properties:
      Name:
        type: string
      RelationsType:
        $ref: '#/definitions/IDName_Type'
      Nationality:
        $ref: '#/definitions/IDName_Type'
      PartyID:
        type: string
      PartyIDType:
        type: string
      BirthDate:
        type: string
      PartyPercint:
        type: number
        format: decimal
      PartyGross:
        type: number
        format: decimal
      PartyShareCount:
        type: number
        format: decimal
      Mobile:
        type: string
      Email:
        type: string
paths:
  /transferownership/mciswapcr:
    post:
      operationId: MCI_SwapCR
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/MCI_SwapCRRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service is used to check the swap of the establishment and
        CR.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/MCI_SwapCRRq_MessageType'
        description: MCI_SwapCRRq
        required: true
