swagger: "2.0"
info:
  title: MCI_TransferOwnershipIndividual
  x-ibm-name: mci-transferownershipindividual
  version: 1.0.0
  description: This service is used to transfer the ownership of an individual establishment
    or change establishment type
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-transfer-ownership)/estabmanagement/transferownership/mcitransferownershipindividual
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  MCI_TransferOwnershipIndividualRq_MessageType:
    type: object
    properties:
      MCI_TransferOwnershipIndividualRq:
        $ref: '#/definitions/MCI_TransferOwnershipIndividualRq_Type'
  MCI_TransferOwnershipIndividualRs_MessageType:
    type: object
    properties:
      MCI_TransferOwnershipIndividualRs:
        $ref: '#/definitions/MCI_TransferOwnershipIndividualRs_Type'
  MCI_TransferOwnershipIndividualRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/MCI_TransferOwnershipIndividualRq_BodyType'
  MCI_TransferOwnershipIndividualRq_BodyType:
    type: object
    properties:
      OperationFlag:
        type: integer
      CRNumber:
        type: string
      ReferenceNo:
        type: string
      NationalNo:
        type: string
      CRParties:
        $ref: '#/definitions/CRParties_Type'
      CRRepresentative:
        $ref: '#/definitions/CRRepresentative_Type'
      BusinessType:
        $ref: '#/definitions/IDName_Type'
      CROwnership:
        $ref: '#/definitions/CROwnership_Type'
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      NationalityIso:
        $ref: '#/definitions/IDName_Type'
      Location:
        $ref: '#/definitions/Location_Type'
      CRName:
        type: string
  CRParties_Type:
    type: object
    properties:
      CRParty:
        $ref: '#/definitions/CRParty_Type'
  CRParty_Type:
    type: object
    properties:
      Name:
        type: string
      RelationsType:
        $ref: '#/definitions/IDName_Type'
      Nationality:
        $ref: '#/definitions/IDName_Type'
      PartyID:
        type: string
      PartyIDType:
        type: string
      BirthDate:
        type: string
      PartyPercint:
        type: number
      PartyGross:
        type: number
      PartyShareCount:
        type: number
  IDName_Type:
    type: object
    properties:
      Id:
        type: integer
      Name:
        type: string
  CRRepresentative_Type:
    type: object
    properties:
      Name:
        type: string
      Nationality:
        $ref: '#/definitions/IDName_Type'
      PartyID:
        type: string
      PartyIDType:
        type: string
      Mobile:
        type: string
      Email:
        type: string
      BirthDate:
        type: string
  CROwnership_Type:
    type: object
    properties:
      TransferAsMain:
        type: string
      CurrentMainCr:
        type: string
      CrToReplaceTransfered:
        type: string
      TransferWithAllBranches:
        type: string
      OldOwner:
        $ref: '#/definitions/Owner_Type'
      NewOwner:
        $ref: '#/definitions/Owner_Type'
      OwnerType:
        type: string
      Manager:
        $ref: '#/definitions/Owner_Type'
  Owner_Type:
    type: object
    properties:
      IdentifierID:
        type: integer
      Name:
        type: string
      RelationsType:
        $ref: '#/definitions/IDName_Type'
      NationalityIso:
        $ref: '#/definitions/Nationality_Type'
      IdentifierIDType:
        type: string
      BirthDate:
        type: string
      Gender:
        type: integer
      Mobile:
        type: string
      Email:
        type: string
  MCI_TransferOwnershipIndividualRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  Location_Type:
    type: object
    properties:
      Code:
        type: string
      NameAr:
        type: string
      NameEn:
        type: string
  Nationality_Type:
    type: object
    properties:
      ID:
        type: string
      Name:
        type: string
paths:
  /transferownership/mcitransferownershipindividual:
    post:
      operationId: MCI_TransferOwnershipIndividual
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/MCI_TransferOwnershipIndividualRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service is used to transfer the ownership of an individual
        establishment or change establishment type
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/MCI_TransferOwnershipIndividualRq_MessageType'
        description: MCI_TransferOwnershipIndividualRq
        required: true
