swagger: "2.0"
info:
  title: NIC_ConfirmCreateRunawayReport
  x-ibm-name: nic-confirmcreaterunawayreport
  version: 1.0.0
schemes:
- https
basePath: /nic/v1
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\n\nvar cfg={\n    \"serviceCode\" : \"EXSRR0001\",\n
          \   \"channelId\" : \"Integration\",\n    \"requestName\" : \"SubmitRunawayRequestRq\",\n
          \   \"responseName\": \"SubmitRunawayRequestRs\",\n    \"errorMap\" :{\n
          \       \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid Request\"}\n    }\n
          \   \n};\n\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\n\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\n\r\nvar appcReq
          = {\r\n    [cfg.requestName]:{\r\n        \"Header\" : {\r\n            \"TransactionId\"
          : millisecondsvalue,\r\n            \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.Reference-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode\r\n        },\r\n
          \       \"Body\" : apim.getvariable('message.body')\r\n            \r\n
          \       \r\n    }\r\n};\r\n\r\nif (typeof OperatorId !== 'undefined')\r\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\r\n        \"IDNumber\"
          : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - gatewayscript:
        version: 2.0.0
        title: Simulator
        source: "var apim = require('apim');\r\nvar testResponse = {\r\n    \"SubmitRunawayRequestRs\":
          {\r\n        \"Header\": {\r\n            \"TransactionId\": \"6222121543\",\r\n
          \           \"ChannelId\": \"Integration\",\r\n            \"SessionId\":
          \"212\",\r\n            \"RequestTime\": \"2019-10-10 00:00:00.555\",\r\n
          \           \"MWRequestTime\": \"2019-10-10 00:00:00.555\",\r\n            \"MWResponseTime\":
          \"2021-02-07 07:57:36.376\",\r\n            \"ServiceCode\": \"EXSRR0001\",\r\n
          \           \"DebugFlag\": \"1\",\r\n            \"ResponseStatus\": {\r\n
          \               \"Status\": \"SUCCESS\",\r\n                \"Code\": \"00000000\",\r\n
          \               \"ArabicMsg\": \"تمت العملية بنجاح\",\r\n                \"EnglishMsg\":
          \"Success Call\"\r\n            }\r\n        },\r\n        \"Body\":{\r\n\t\t\t\"reporterInfoName\"
          : \"test\",\r\n\t\t\t\"requesterID\" : \"1234567890\",\r\n\t\t\t\"requesterInfoName\"
          : \"test\",\r\n\t\t\t\"returnCode\" : \"12345\",\r\n\t\t\t\"returnMessage\"
          : \"test message\",\r\n\t\t\t\"runawayDate\" : \"2021-02-07\",\r\n\t\t\t\"runawayID\"
          : \"1234\",\r\n\t\t\t\"runawayInfo\" : \"test\",\r\n\t\t\t\"seqNo\" : \"123456\",\r\n\t\t\t\"totalRunawayRecords\"
          : \"1\",\r\n\t\t\t\"runawayInfo\":{\r\n\t\t\t\t\"firstEntryDate\" : \"2021-02-07\",\r\n\t\t\t\t\"nationality\"
          : \"1\",\r\n\t\t\t\t\"occupation\" : \"1\",\r\n\t\t\t\t\"passportNo\" :
          \"1\",\r\n\t\t\t\t\"personName\" : \"1\",\r\n\t\t\t\t\"resExpDate\" : \"2021-02-07\",\r\n\t\t\t\t\"sponsorId\"
          : \"1\",\r\n\t\t\t\t\"sponsorName\" : \"test\"\r\n\t\t\t}\r\n\t\t}\r\n    }\r\n};\r\napim.setvariable('message.body',testResponse,'set');"
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "\tvar apim = require('apim');\n\t\n\tapim.output('application/json');\n\n
          \   \n    \n    var cfg = apim.getvariable('cfg');\n    \n\tvar TransactionId
          = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.TransactionId\");\n\tvar
          ChannelId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ChannelId\");\n\tvar
          RequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.RequestTime\");\n\tvar
          SessionId = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.SessionId\");\n\tvar
          MWRequestTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWRequestTime\");\n\tvar
          MWResponseTime = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.MWResponseTime\");\n\tvar
          status = \"\"+apim.getvariable(\"message.body.\"+cfg.responseName+\".Header.ResponseStatus.Status\");\n\t\n\n
          \   apim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\n
          \   apim.setvariable('message.headers.Channel-Id',ChannelId,'add');\n    if
          (RequestTime !== 'undefined')\n\t    apim.setvariable('message.headers.RequestTime',RequestTime,'add');\n\tif
          (SessionId !== 'undefined')\n        apim.setvariable('message.headers.Reference-Id',SessionId,'add');\n
          \    if (MWRequestTime !== 'undefined')\n        apim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\n
          \   if (MWResponseTime !== 'undefined')\n        apim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\n\n
          \   \n    apim.setvariable('message.headers.Response-Status',status,'add');\n
          \   "
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar body = message[cfg.responseName].Body;\n\n\nsession.output.write(body);\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\nvar
                cfg = apim.getvariable('cfg');          \nvar error = {\n    \"ErrorResponse\":
                message[cfg.responseName].Header.ResponseStatus\n}\n\n\nvar httperror=0;\nif(cfg.errorMap){\n
                \   if(cfg.errorMap[error.ErrorResponse.Code]){\n       httperror
                = cfg.errorMap[error.ErrorResponse.Code].code;\n       \n       //var
                errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n       //var
                details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 400;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);\napim.output('application/json');"
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SubmitRunawayRequestRs_BodyType:
    type: object
    properties:
      reporterInfoName:
        type: string
      requesterID:
        type: integer
      requesterInfoName:
        type: string
      returnCode:
        type: integer
      returnMessage:
        type: string
      runawayDate:
        type: string
      runawayID:
        type: integer
      runawayInfo:
        $ref: '#/definitions/runawayInfo_Type'
      seqNo:
        type: integer
      totalRunawayRecords:
        type: integer
  runawayInfo_Type:
    type: object
    properties:
      firstEntryDate:
        type: string
      nationality:
        type: string
      occupation:
        type: string
      passportNo:
        type: string
      personName:
        type: string
      resExpDate:
        type: string
      CRCityEN:
        type: string
      sponsorId:
        type: integer
      sponsorName:
        type: string
  StrSubmitRunawayRequestRs_BodyType:
    type: object
    properties:
      reporterInfoName:
        type: string
      requesterID:
        type: integer
      requesterInfoName:
        type: string
      returnCode:
        type: integer
      returnMessage:
        type: string
      runawayDate:
        type: string
      runawayID:
        type: integer
      runawayInfo:
        $ref: '#/definitions/StrrunawayInfo_Type'
      seqNo:
        type: integer
      totalRunawayRecords:
        type: integer
  StrrunawayInfo_Type:
    type: object
    properties:
      firstEntryDate:
        type: string
      nationality:
        type: string
      occupation:
        type: string
      passportNo:
        type: string
      personName:
        type: string
      resExpDate:
        type: string
      CRCityEN:
        type: string
      sponsorId:
        type: integer
      sponsorName:
        type: string
paths:
  /confirm-create-runaway-report:
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
