swagger: "2.0"
info:
  title: OpenEstablishmentByGSBLicense
  x-ibm-name: openestablishmentbygsblicense
  version: 1.0.0
  description: OpenEstablishmentByGSBLicense
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-open-file-without-cr-other)/estabmanagement/openestbygsblic
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  OpenEstablishmentByGSBLicenseRq_MessageType:
    type: object
    properties:
      OpenEstablishmentByGSBLicenseRq:
        $ref: '#/definitions/OpenEstablishmentByGSBLicenseRq_Type'
  OpenEstablishmentByGSBLicenseRs_MessageType:
    type: object
    properties:
      OpenEstablishmentByGSBLicenseRs:
        $ref: '#/definitions/OpenEstablishmentByGSBLicenseRs_Type'
  OpenEstablishmentByGSBLicenseRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentByGSBLicenseRq_BodyType'
  OpenEstablishmentByGSBLicenseRq_BodyType:
    type: object
    properties:
      EntityInfo:
        $ref: '#/definitions/EntityInfo_Type'
      LicenseInfo:
        $ref: '#/definitions/LicenseInfo_Type'
      ContactInfo:
        $ref: '#/definitions/ContactInfo_Type'
      OwnerInfo:
        $ref: '#/definitions/OwnerInfo_Type'
      ApplicantInfo:
        $ref: '#/definitions/ApplicantInfo_Type'
      GSBSource:
        type: string
  OpenEstablishmentByGSBLicenseRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentByGSBLicenseRs_BodyType'
  OpenEstablishmentByGSBLicenseRs_BodyType:
    type: object
    properties:
      FileNumber:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: string
      UnifiedNationalNumber:
        type: string
  EntityInfo_Type:
    type: object
    properties:
      UnifiedNationalNumber:
        type: string
      IsMain:
        type: string
      EntityName:
        type: string
      EntityType:
        type: integer
      EntityISIC4Code:
        type: integer
      EntityNationalityCode:
        type: integer
      EntityCityCode:
        type: integer
  LicenseInfo_Type:
    type: object
    properties:
      LicenseNumber:
        type: string
      LicenseTypeCode:
        type: integer
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      GSBSourceName:
        type: string
  ContactInfo_Type:
    type: object
    properties:
      Mobile:
        type: string
      Telephone:
        type: string
      Email:
        type: string
  OwnerInfo_Type:
    type: object
    properties:
      NationalID:
        type: string
      FullName:
        $ref: '#/definitions/FullName_Type'
      BirthDate:
        type: string
      NationalityCode:
        type: integer
      Mobile:
        type: string
      EmailAddress:
        type: string
  FullName_Type:
    type: object
    properties:
      FirstName:
        type: string
      SecondName:
        type: string
      ThirdName:
        type: string
      LastName:
        type: string
  ApplicantInfo_Type:
    type: object
    properties:
      NationalID:
        type: string
      FullName:
        $ref: '#/definitions/FullName_Type'
      BirthDate:
        type: string
      NationalityCode:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /openestbygsblic:
    post:
      operationId: OpenEstablishmentByGSBLicense
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenEstablishmentByGSBLicenseRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: To get all laborers under the establishment
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/OpenEstablishmentByGSBLicenseRq_MessageType'
        description: OpenEstablishmentByGSBLicenseRq
        required: true
