swagger: "2.0"
info:
  title: OpenEstabFileOtherLic-CM
  x-ibm-name: openestabfileotherlic-cm
  version: 1.0.0
  description: OpenEstabFileOtherLic
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-open-file-without-cr-other)/estabmanagement/openestabfileotherlic
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  OpenEstabFileOtherLicRq_MessageType:
    type: object
    properties:
      OpenEstabFileOtherLicRq:
        $ref: '#/definitions/OpenEstabFileOtherLicRq_Type'
  OpenEstabFileOtherLicRs_MessageType:
    type: object
    properties:
      OpenEstabFileOtherLicRs:
        $ref: '#/definitions/OpenEstabFileOtherLicRs_Type'
  OpenEstabFileOtherLicRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstabFileOtherLicRq_BodyType'
  OpenEstabFileOtherLicRq_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      OwnerDetails:
        $ref: '#/definitions/OwnerDetails_Type'
      EstablishmentActivityLicensesDetails:
        $ref: '#/definitions/EstablishmentActivityDetails_Type'
  OpenEstabFileOtherLicRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstabFileOtherLicRs_BodyType'
  OpenEstabFileOtherLicRs_BodyType:
    type: object
    properties:
      EstablishmentId:
        type: string
  EstablishmentDetails_Type:
    type: object
    properties:
      EstablishmentName:
        type: string
      EstablishmentType:
        type: integer
      LaborOfficeId:
        type: integer
      EstablishmentNationality:
        type: integer
      EstablishmentFinancialCalendar:
        type: integer
      EstablishmentContactAddress:
        $ref: '#/definitions/Address_Type'
  Address_Type:
    type: object
    properties:
      PersonFirstName:
        type: string
      PersonLastName:
        type: string
      PersonMobileNumber:
        type: string
      City:
        $ref: '#/definitions/City_Type'
      ZipCode:
        type: string
      StreetName:
        type: string
      BuildingNo:
        type: string
      District:
        type: string
      Coordinates:
        $ref: '#/definitions/Coordinates_Type'
      Email:
        type: string
  City_Type:
    type: object
    properties:
      CityID:
        type: integer
      CityName:
        type: string
  Coordinates_Type:
    type: object
    properties:
      Longitude:
        type: string
      Latitude:
        type: string
  OwnerDetails_Type:
    type: object
    properties:
      MobileNumber:
        type: string
      City:
        type: string
      StreetName:
        type: string
      Email:
        type: string
      ZipCode:
        type: string
      BuildingNo:
        type: string
  EstablishmentActivityDetails_Type:
    type: object
    properties:
      NitaqActivity:
        type: integer
      Isic4Activity:
        type: integer
      ReqLicensesList:
        $ref: '#/definitions/ReqLicensesList_Type'
  ReqLicensesList_Type:
    type: object
    properties:
      ReqLicense:
        $ref: '#/definitions/ReqLicenses_Type'
  ReqLicenses_Type:
    type: object
    properties:
      LicenseCode:
        type: integer
      LicenseName:
        type: string
      LicenseNumber:
        type: string
      LicenseTypeId:
        type: integer
      LicenseType:
        type: string
      Source:
        type: string
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      Aria:
        type: integer
      AttachmentId:
        type: string
      IsMunicipal:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /openestabotherlic:
    post:
      operationId: OpenEstabFileOtherLic
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenEstabFileOtherLicRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: To get all laborers under the establishment
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/OpenEstabFileOtherLicRq_MessageType'
        description: OpenEstabFileOtherLicRq
        required: true
