swagger: "2.0"
info:
  title: OpenEstablishmentBySBC
  x-ibm-name: openestablishmentbysbc
  version: 1.0.0
  description: this service is used to open establishment using Saudi Business Center
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-open-file-with-cr)/estabmanagement/opnestbysbc
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  OpenEstablishmentBySBCRq_MessageType:
    type: object
    properties:
      OpenEstablishmentBySBCRq:
        $ref: '#/definitions/OpenEstablishmentBySBCRq_Type'
  OpenEstablishmentBySBCRs_MessageType:
    type: object
    properties:
      OpenEstablishmentBySBCRs:
        $ref: '#/definitions/OpenEstablishmentBySBCRs_Type'
  OpenEstablishmentBySBCRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentBySBCRq_BodyType'
  OpenEstablishmentBySBCRq_BodyType:
    type: object
    properties:
      CRNo:
        type: string
      CRStatus:
        type: string
      Activities:
        type: string
      CRCapital:
        type: integer
      CompanyPaidCapital:
        type: integer
      CompanyShareCount:
        type: integer
      FiscalDateEndDay:
        type: integer
      FiscalDateEndMonth:
        type: integer
      NationalNo:
        type: integer
      IsMain:
        type: boolean
      MainCR:
        type: integer
      BusinessType:
        $ref: '#/definitions/IDName_Type'
      Location:
        $ref: '#/definitions/IDName_Type'
      CRName:
        type: string
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      Nationality:
        $ref: '#/definitions/IDName_Type'
      ZipCode:
        type: string
      POBOX1:
        type: string
      City:
        $ref: '#/definitions/IDName_Type'
      Street:
        type: string
      LaborOfficeNo:
        type: integer
      FiscalYear:
        $ref: '#/definitions/IDName_Type'
      CRParties:
        $ref: '#/definitions/CRParties_Type'
      CRRepresentative:
        $ref: '#/definitions/CRRepresentative_Type'
      CRActivities:
        $ref: '#/definitions/CRActivities_Type'
      CRLicenses:
        $ref: '#/definitions/CRLicenses_Type'
  CRParties_Type:
    type: object
    properties:
      Party:
        type: array
        items:
          $ref: '#/definitions/Party_Type'
  CRLicenses_Type:
    type: object
    properties:
      License:
        type: array
        items:
          $ref: '#/definitions/CRLicensesItem_Type'
  Party_Type:
    type: object
    properties:
      Name:
        type: string
      RelationType:
        $ref: '#/definitions/IDName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      PartyID:
        type: integer
      BirthDate:
        type: string
      Email:
        type: string
      Mobile:
        type: string
      Gross:
        type: string
      Percint:
        type: string
      ShareCount:
        type: integer
      IDType:
        type: string
  CRLicensesItem_Type:
    type: object
    properties:
      LicenseType:
        type: integer
      LicenseNo:
        type: string
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      IssuingAuthorityName:
        type: string
      Description:
        type: string
  CRRepresentative_Type:
    type: object
    properties:
      Name:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      PartyID:
        type: integer
      BirthDate:
        type: string
      PartyIDType:
        type: string
      Mobile:
        type: integer
      Email:
        type: string
  CRActivities_Type:
    type: object
    properties:
      LookupStructure:
        type: array
        items:
          $ref: '#/definitions/IDName_Type'
  IDName_Type:
    type: object
    properties:
      ID:
        type: integer
      Name:
        type: string
  CodeName_Type:
    type: object
    properties:
      ID:
        type: string
      Name:
        type: string
  OpenEstablishmentBySBCRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentBySBCRs_BodyType'
  OpenEstablishmentBySBCRs_BodyType:
    type: object
    properties:
      EstablishmentIds:
        type: string
      RequestNumber:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /opnestbysbc:
    post:
      operationId: openestbysbc
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenEstablishmentBySBCRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: this service is used to open establishment Saudi Business Center
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/OpenEstablishmentBySBCRq_MessageType'
        description: OpenEstablishmentBySBCRq
        required: true
