swagger: "2.0"
info:
  title: OpenUnifiedEstablishmentBySBC
  version: 1.0.0
  description: |
    This service is used to open a new unified establishment by SBC.
  x-ibm-name: openunifiedestablishmentbysbc
basePath: /estabmanagement
schemes:
- https
paths:
  /OpenUniEstBySBC:
    post:
      operationId: openUnifiedEstablishmentBySBC
      summary: Open Unified Establishment by SBC
      description: Creates a new unified establishment record using CR and SBC data.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        description: OpenUnifiedEstablishmentBySBCRq
        schema:
          $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRq_MessageType'
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRs_MessageType'
definitions:
  OpenUnifiedEstablishmentBySBCRq_MessageType:
    type: object
    properties:
      OpenUnifiedEstablishmentBySBCRq:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRq_Type'
  OpenUnifiedEstablishmentBySBCRs_MessageType:
    type: object
    properties:
      OpenUnifiedEstablishmentBySBCRs:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRs_Type'
  OpenUnifiedEstablishmentBySBCRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRq_BodyType'
    required:
    - Header
    - Body
  OpenUnifiedEstablishmentBySBCRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRs_BodyType'
    required:
    - Header
    - Body
  OpenUnifiedEstablishmentBySBCRq_BodyType:
    type: object
    properties:
      CRInformation:
        $ref: '#/definitions/CRInformation_Type'
      ActivityIdList:
        $ref: '#/definitions/ActivityList_Type'
      CapitalDetails:
        $ref: '#/definitions/CapitalDetails_Type'
      EntityNationalAddress:
        $ref: '#/definitions/EntityNationalAddress_Type'
      ContactInformation:
        $ref: '#/definitions/ContactInformation_Type'
      FiscalYear:
        $ref: '#/definitions/FiscalYear_Type'
      ManagementInformation:
        $ref: '#/definitions/ManagementInformation_Type'
      PartnerList:
        $ref: '#/definitions/PartnerList_Type'
    required:
    - CRInformation
    - ActivityIdList
    - CapitalDetails
    - EntityNationalAddress
    - ContactInformation
    - FiscalYear
    - ManagementInformation
    - PartnerList
  CRInformation_Type:
    type: object
    properties:
      CrNationalNumber:
        type: string
        pattern: ^[0-9]{10}$
      EntityFullName:
        $ref: '#/definitions/Name_Type'
      Capital:
        type: integer
      IsLicenseBased:
        type: integer
      CapitalCurrencyId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      EntityTypeId:
        type: integer
      CompanyFormId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 99
      CompanyCharacterIdList:
        type: string
      HeadquarterCityId:
        type: integer
      CrIssueDate:
        $ref: '#/definitions/Date_Type'
      CRStatus:
        type: string
      LicenseList:
        $ref: '#/definitions/LicenseList_Type'
    required:
    - CrNationalNumber
    - EntityFullName
    - Capital
    - IsLicenseBased
    - CapitalCurrencyId
    - EntityTypeId
    - CompanyFormId
    - CompanyCharacterIdList
    - HeadquarterCityId
    - CrIssueDate
    - CRStatus
  Name_Type:
    type: object
    properties:
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - NameAr
    - NameEn
  Date_Type:
    type: object
    properties:
      Gregorian:
        $ref: '#/definitions/Dt_Type'
      Hijri:
        type: string
    required:
    - Gregorian
    - Hijri
  LicenseList_Type:
    type: object
    properties:
      License:
        type: array
        items:
          $ref: '#/definitions/License_Type'
    required:
    - License
  License_Type:
    type: object
    properties:
      licenseIssuerId:
        type: integer
      LicenseTypeId:
        type: integer
      LicenseNo:
        type: string
    required:
    - licenseIssuerId
    - LicenseTypeId
    - LicenseNo
  ActivityList_Type:
    type: object
    properties:
      ActivityId:
        type: array
        items:
          $ref: '#/definitions/ID_Type'
    required:
    - ActivityId
  ID_Type:
    type: object
    properties:
      ID:
        type: integer
    required:
    - ID
  CapitalDetails_Type:
    type: object
    properties:
      ContributionCapitalDetails:
        $ref: '#/definitions/ContributionCapitalDetails_Type'
      StockCapitalDetails:
        $ref: '#/definitions/StockCapitalDetails_Type'
      StockList:
        $ref: '#/definitions/StockList_Type'
    required:
    - ContributionCapitalDetails
    - StockCapitalDetails
    - StockList
  ContributionCapitalDetails_Type:
    type: object
    properties:
      CapitalTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
      CashCapital:
        type: string
      InkindCapital:
        type: string
      TotalCashContribution:
        type: string
      TotalInkindContribution:
        type: string
      ContributionValue:
        type: string
    required:
    - CapitalTypeId
    - CashCapital
    - InkindCapital
    - TotalCashContribution
  StockCapitalDetails_Type:
    type: object
    properties:
      CapitalTypeId:
        type: integer
      Capital:
        type: string
      AnnouncedCapital:
        type: string
      PaidCapital:
        type: string
      CashCapital:
        type: string
      InkindCapital:
        type: string
    required:
    - CapitalTypeId
    - Capital
    - AnnouncedCapital
    - PaidCapital
    - CashCapital
    - InkindCapital
  StockList_Type:
    type: object
    properties:
      Stock:
        type: array
        items:
          $ref: '#/definitions/Stock_Type'
    required:
    - Stock
  Stock_Type:
    type: object
    properties:
      StockCount:
        type: string
      StockValue:
        type: string
      StockTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
      StockClassId:
        type: integer
    required:
    - StockCount
    - StockValue
    - StockTypeId
    - StockClassId
  EntityNationalAddress_Type:
    type: object
    properties:
      CityId:
        type: integer
      DistrictId:
        type: string
      StreetName:
        $ref: '#/definitions/Name_Type'
      BuildingNo:
        type: string
      UnitNo:
        type: string
      PostalCode:
        type: string
      AdditionalNo:
        type: string
    required:
    - CityId
    - DistrictId
    - UnitNo
  ContactInformation_Type:
    type: object
    properties:
      PhoneNo:
        type: string
      MobileNo:
        type: string
      Email:
        type: string
      websiteURL:
        type: string
    required:
    - PhoneNo
    - MobileNo
    - Email
  FiscalYear_Type:
    type: object
    properties:
      CalendarTypeId:
        type: integer
      FiscalYearEndMonth:
        type: string
      FiscalYearEndDay:
        type: string
      FirstYearEndDate:
        type: string
    required:
    - CalendarTypeId
    - FiscalYearEndMonth
    - FiscalYearEndDay
    - FirstYearEndDate
  ManagementInformation_Type:
    type: object
    properties:
      ManagementStructureId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      ManagerList:
        type: array
        items:
          $ref: '#/definitions/ManagerList_Type'
    required:
    - ManagementStructureId
    - ManagerList
  ManagerList_Type:
    type: object
    properties:
      Manager:
        type: array
        items:
          $ref: '#/definitions/Manager_Type'
    required:
    - Manager
  Manager_Type:
    type: object
    properties:
      ManagerTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      PersonInfo:
        $ref: '#/definitions/PersonInfo_Type'
      ManagerPositionIdList:
        $ref: '#/definitions/ManagerPositionIdList_Type'
    required:
    - ManagerTypeId
    - PersonInfo
    - ManagerPositionIdList
  PersonInfo_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      IdentifierNo:
        type: string
      Title:
        $ref: '#/definitions/Name_Type'
      FirstName:
        $ref: '#/definitions/Name_Type'
      FatherName:
        $ref: '#/definitions/Name_Type'
      GrandFatherName:
        $ref: '#/definitions/Name_Type'
      FamilyName:
        $ref: '#/definitions/Name_Type'
      NationalityId:
        type: integer
    required:
    - IdentifierTypeId
    - IdentifierNo
    - FirstName
    - FatherName
    - GrandFatherName
    - FamilyName
    - NationalityId
  ManagerPositionIdList_Type:
    type: object
    properties:
      ManagerPositionId:
        type: array
        items:
          $ref: '#/definitions/ID_Type'
    required:
    - ManagerPositionId
  PartnerList_Type:
    type: object
    properties:
      Partner:
        type: array
        items:
          $ref: '#/definitions/Partner_Type'
    required:
    - Partner
  Partner_Type:
    type: object
    properties:
      PartnerTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
      PartnershipTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      IsCivilAssociation:
        type: integer
        enum:
        - 0
        - 1
      PersonInfo:
        $ref: '#/definitions/PersonInfo_Type'
      EstablishmentInfo:
        $ref: '#/definitions/EstablishmentInfo_Type'
    required:
    - PartnerTypeId
    - PartnershipTypeId
    - IdentifierTypeId
    - IsCivilAssociation
    - PersonInfo
    - EstablishmentInfo
  EstablishmentInfo_Type:
    type: object
    properties:
      ID:
        type: string
      Name:
        $ref: '#/definitions/Name_Type'
      NationalNo:
        type: string
      licenseNo:
        type: string
      DeedNo:
        type: string
      NationalityId:
        type: integer
    required:
    - ID
    - Name
    - NationalNo
    - NationalityId
  OpenUnifiedEstablishmentBySBCRs_BodyType:
    type: object
    properties:
      EstablishmentIds:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: string
      NationalUnifiedNumber:
        type: string
      RequestNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - NationalUnifiedNumber
    - RequestNumber
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  Dt_Type:
    type: string
    format: date
    description: |
      Represents a date value (Gregorian). Adjust `format` or `type` as needed.
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Status
    - Code
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-open-file-with-cr)/estabmanagement/OpenUniEstBySBC
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
securityDefinitions:
  clientId:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    x-key-type: client_id
  clientSecret:
    type: apiKey
    x-key-type: client_secret
    name: X-IBM-Client-Secret
    in: header
security:
- clientId: []
  clientSecret: []
