swagger: "2.0"
info:
  title: OpenEstabFileOtherLic
  x-ibm-name: openestabfileotherlic
  version: 1.0.0
  description: This service is used to create a new establishment file by other licenses.
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-open-file-without-cr-other)/estabmanagement/openestabfileotherlic
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  OpenEstabFileOtherLicRq_MessageType:
    type: object
    properties:
      OpenEstabFileOtherLicRq:
        $ref: '#/definitions/OpenEstabFileOtherLicRq_Type'
  OpenEstabFileOtherLicRs_MessageType:
    type: object
    properties:
      OpenEstabFileOtherLicRs:
        $ref: '#/definitions/OpenEstabFileOtherLicRs_Type'
  OpenEstabFileOtherLicRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstabFileOtherLicRq_BodyType'
  OpenEstabFileOtherLicRq_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      MainEstablishmentDetails:
        $ref: '#/definitions/MainEstablishmentDetails_Type'
      OwnerDetails:
        $ref: '#/definitions/OwnerDetails_Type'
      EstablishmentActivityDetails:
        $ref: '#/definitions/EstablishmentActivityDetails_Type'
    required:
    - EstablishmentDetails
    - MainEstablishmentDetails
    - EstablishmentActivityDetails
  OpenEstabFileOtherLicRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstabFileOtherLicRs_BodyType'
  OpenEstabFileOtherLicRs_BodyType:
    type: object
    properties:
      FileNumber:
        type: integer
  EstablishmentDetails_Type:
    type: object
    properties:
      Name:
        type: string
        default: test
      Type:
        type: integer
        default: "1"
      LegalType:
        type: string
        default: "1"
      Nationality:
        type: string
        default: "1"
      LegalStructure:
        type: string
        default: "1"
      FinancialCalendar:
        type: integer
        default: "1"
      Address:
        $ref: '#/definitions/Address_Type'
    required:
    - Name
    - Type
    - LegalType
    - Nationality
    - FinancialCalendar
    - Address
  Address_Type:
    type: object
    properties:
      FirstName:
        type: string
        default: test
      LastName:
        type: string
        default: name
      MobileNumber:
        type: string
        default: "18687887"
      CityId:
        type: integer
        default: "18"
      ZipCode:
        type: string
        default: "187887"
      StreetName:
        type: string
        default: test
      Email:
        type: string
        default: avb@c.com
    required:
    - FirstName
    - LastName
    - MobileNumber
    - CityId
    - ZipCode
    - StreetName
    - Email
  MainEstablishmentDetails_Type:
    type: object
    properties:
      UNLaborOfficeId:
        type: integer
        default: "1"
      UNSequenceNumber:
        type: integer
        default: "1"
      EstLaborOfficeId:
        type: integer
        default: "1"
      EstSequenceNumber:
        type: integer
        default: "1"
      UnifiedNationalNumber:
        type: string
        default: "1"
      EstNationality:
        type: string
        default: "1"
      EstName:
        type: string
        default: "1"
      OwnershipType:
        type: string
        default: "1"
      OwnerId:
        type: integer
        default: "1"
      OwnerName:
        type: string
        default: "1"
      SevenHundredNumber:
        type: string
        default: "1"
      LegalType:
        type: string
        default: "1"
  OwnerDetails_Type:
    type: object
    properties:
      Name:
        type: integer
        default: "1"
      NationalNumber:
        type: string
        default: "1"
      Nationality:
        type: string
        default: "1"
      Gender:
        type: integer
        default: "1"
      DateOfExpiration:
        type: string
        default: "2021-10-10"
      Origin:
        type: string
        default: "1"
      MobileNumber:
        type: string
        default: "1"
      City:
        type: string
        default: "1"
      StreetName:
        type: string
        default: "1"
      Email:
        type: string
        default: name@c.com
      ZipCode:
        type: string
        default: "5765765"
      BuildingNumber:
        type: string
        default: "1987"
    required:
    - Name
    - NationalNumber
    - Nationality
    - Gender
    - MobileNumber
    - City
    - StreetName
    - Email
    - ZipCode
    - BuildingNumber
  EstablishmentActivityDetails_Type:
    type: object
    properties:
      NitaqActivity:
        type: integer
        default: "17"
      ISIC4Activity:
        type: string
        default: "187"
      RequiredSaudizationLevel:
        type: string
        default: "176"
      ReqLicensesList:
        $ref: '#/definitions/ReqLicensesList_Type'
    required:
    - NitaqActivity
    - ISIC4Activity
    - RequiredSaudizationLevel
    - ReqLicensesList
  ReqLicensesList_Type:
    type: object
    properties:
      ReqLicenses:
        $ref: '#/definitions/ReqLicenses_Type'
    required:
    - ReqLicenses
  ReqLicenses_Type:
    type: object
    properties:
      LicenseNumber:
        type: integer
        default: "1767657657"
      Source:
        type: string
        default: "1756"
      IssueDate:
        type: string
        default: 23-06-21
      ExpiryDate:
        type: string
        default: 27-08-21
      Aria:
        type: integer
        default: "1756"
    required:
    - LicenseNumber
    - Source
    - IssueDate
    - ExpiryDate
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CEFOL001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: CEFOL001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23432"
      IDNumber:
        type: integer
        default: "324324"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /openestabfileotherlic:
    post:
      operationId: OpenEstabFileOtherLic
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenEstabFileOtherLicRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: To get all laborers under the establishment
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/OpenEstabFileOtherLicRq_MessageType'
        description: OpenEstabFileOtherLicRq
        required: true
