swagger: "2.0"
info:
  title: OpenUnifiedEstablishmentBySBCV2
  version: 1.0.0
  description: |
    This service is used to open a new unified establishment by SBC.
  x-ibm-name: openunifiedestablishmentbysbcv2
basePath: /estabmanagement
schemes:
- https
paths:
  /openuniestbysbcv2:
    post:
      operationId: openUnifiedEstablishmentBySBC
      summary: Open Unified Establishment by SBC
      description: Creates a new unified establishment record using CR and SBC data.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        description: OpenUnifiedEstablishmentBySBCRq
        schema:
          $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRq_MessageType'
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRs_MessageType'
definitions:
  OpenUnifiedEstablishmentBySBCRq_MessageType:
    type: object
    properties:
      OpenUnifiedEstablishmentBySBCRq:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRq_Type'
  OpenUnifiedEstablishmentBySBCRs_MessageType:
    type: object
    properties:
      OpenUnifiedEstablishmentBySBCRs:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRs_Type'
  OpenUnifiedEstablishmentBySBCRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRq_BodyType'
    required:
    - Header
    - Body
  OpenUnifiedEstablishmentBySBCRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenUnifiedEstablishmentBySBCRs_BodyType'
    required:
    - Header
    - Body
  OpenUnifiedEstablishmentBySBCRq_BodyType:
    type: object
    properties:
      CRInformation:
        $ref: '#/definitions/CRInformation_Type'
      ActivityIdList:
        $ref: '#/definitions/ActivityList_Type'
      CapitalDetails:
        $ref: '#/definitions/CapitalDetails_Type'
      EntityNationalAddress:
        $ref: '#/definitions/EntityNationalAddress_Type'
      ContactInformation:
        $ref: '#/definitions/ContactInformation_Type'
      FiscalYear:
        $ref: '#/definitions/FiscalYear_Type'
      ManagementInformation:
        $ref: '#/definitions/ManagementInformation_Type'
      PartnerList:
        $ref: '#/definitions/PartnerList_Type'
      Representative:
        $ref: '#/definitions/Representative_Type'
  CRInformation_Type:
    type: object
    properties:
      CrNationalNumber:
        type: string
        pattern: ^[0-9]{10}$
      EntityFullName:
        $ref: '#/definitions/Name_Type_1'
      Capital:
        type: integer
      IsLicenseBased:
        type: integer
      CapitalCurrencyId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      EntityTypeId:
        type: integer
      CompanyFormId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 99
      CompanyCharacterIdList:
        $ref: '#/definitions/CompanyCharacterIdList_Type'
      HeadquarterCityId:
        type: integer
      CrIssueDate:
        $ref: '#/definitions/Date_Type'
      CRStatus:
        type: string
      CRConfirmDate:
        $ref: '#/definitions/Date_Type'
      LicenseList:
        $ref: '#/definitions/LicenseList_Type'
    required:
    - CrNationalNumber
    - EntityFullName
    - Capital
    - IsLicenseBased
    - CapitalCurrencyId
    - EntityTypeId
    - CrIssueDate
    - CRStatus
    - CRConfirmDate
  Name_Type:
    type: object
    properties:
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - NameAr
    - NameEn
  Name_Type_1:
    type: object
    properties:
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - NameAr
  Name_Type_2:
    type: object
    properties:
      NameAr:
        type: string
      NameEn:
        type: string
  Date_Type:
    type: object
    properties:
      Gregorian:
        $ref: '#/definitions/Dt_Type'
      Hijri:
        type: string
    required:
    - Gregorian
    - Hijri
  LicenseList_Type:
    type: object
    properties:
      License:
        type: array
        items:
          $ref: '#/definitions/License_Type'
    required:
    - License
  CompanyCharacterIdList_Type:
    type: object
    properties:
      CharacterId:
        type: array
        items:
          $ref: '#/definitions/ID_Type'
    required:
    - CharacterId
  License_Type:
    type: object
    properties:
      licenseIssuerId:
        type: integer
      LicenseTypeId:
        type: integer
      LicenseNo:
        type: string
      LicenseExpiryDate:
        $ref: '#/definitions/Dt_Type'
      LicenseIssueDate:
        $ref: '#/definitions/Dt_Type'
    required:
    - licenseIssuerId
    - LicenseNo
    - LicenseExpiryDate
  ActivityList_Type:
    type: object
    properties:
      ActivityId:
        type: array
        items:
          $ref: '#/definitions/ID_Act_Type'
    required:
    - ActivityId
  ID_Act_Type:
    type: object
    properties:
      ID:
        type: integer
      IsPreLicenseIssued:
        type: integer
      IsPostLicenseIssued:
        type: integer
    required:
    - ID
  ID_Type:
    type: object
    properties:
      ID:
        type: integer
    required:
    - ID
  CapitalDetails_Type:
    type: object
    properties:
      ContributionCapitalDetails:
        $ref: '#/definitions/ContributionCapitalDetails_Type'
      StockCapitalDetails:
        $ref: '#/definitions/StockCapitalDetails_Type'
      StockList:
        $ref: '#/definitions/StockList_Type'
    required:
    - StockList
  ContributionCapitalDetails_Type:
    type: object
    properties:
      CapitalTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
      CashCapital:
        type: string
      InkindCapital:
        type: string
      TotalCashContribution:
        type: string
      TotalInkindContribution:
        type: string
      ContributionValue:
        type: string
    required:
    - CapitalTypeId
    - TotalCashContribution
  StockCapitalDetails_Type:
    type: object
    properties:
      CapitalTypeId:
        type: integer
      Capital:
        type: string
      AnnouncedCapital:
        type: string
      PaidCapital:
        type: string
      CashCapital:
        type: string
      InkindCapital:
        type: string
    required:
    - CapitalTypeId
    - Capital
    - PaidCapital
  StockList_Type:
    type: object
    properties:
      Stock:
        type: array
        items:
          $ref: '#/definitions/Stock_Type'
    required:
    - Stock
  Stock_Type:
    type: object
    properties:
      StockCount:
        type: string
      StockValue:
        type: string
      StockTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
      StockClassId:
        type: integer
    required:
    - StockCount
    - StockValue
    - StockTypeId
  EntityNationalAddress_Type:
    type: object
    properties:
      CityId:
        type: integer
      DistrictId:
        type: string
      StreetName:
        $ref: '#/definitions/Name_Type'
      BuildingNo:
        type: string
      UnitNo:
        type: string
      PostalCode:
        type: string
      AdditionalNo:
        type: string
  ContactInformation_Type:
    type: object
    properties:
      PhoneNo:
        type: string
      MobileNo:
        type: string
      Email:
        type: string
      websiteURL:
        type: string
  FiscalYear_Type:
    type: object
    properties:
      CalendarTypeId:
        type: integer
      FiscalYearEndMonth:
        type: string
      FiscalYearEndDay:
        type: string
      FirstYearEndDate:
        type: string
    required:
    - CalendarTypeId
    - FiscalYearEndMonth
    - FiscalYearEndDay
    - FirstYearEndDate
  ManagementInformation_Type:
    type: object
    properties:
      ManagementStructureId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      ManagerList:
        $ref: '#/definitions/ManagerList_Type'
    required:
    - ManagementStructureId
  ManagerList_Type:
    type: object
    properties:
      Manager:
        type: array
        items:
          $ref: '#/definitions/Manager_Type'
    required:
    - Manager
  Manager_Type:
    type: object
    properties:
      IsLicensed:
        type: integer
      ManagerTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      PersonInfo:
        $ref: '#/definitions/PersonInfo_Type_1'
      ManagerPositionIdList:
        $ref: '#/definitions/ManagerPositionIdList_Type'
    required:
    - ManagerTypeId
    - PersonInfo
  PersonInfo_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      IdentifierNo:
        type: string
      Title:
        $ref: '#/definitions/Name_Type_2'
      FirstName:
        $ref: '#/definitions/Name_Type'
      FatherName:
        $ref: '#/definitions/Name_Type_2'
      GrandFatherName:
        $ref: '#/definitions/Name_Type_2'
      FamilyName:
        $ref: '#/definitions/Name_Type'
      NationalityId:
        type: integer
      BirthDate:
        $ref: '#/definitions/Dt_Type'
      Email:
        type: string
      MobileNumber:
        type: string
    required:
    - IdentifierTypeId
    - IdentifierNo
    - FirstName
    - FamilyName
    - NationalityId
  PersonInfo_Type_1:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      IdentifierNo:
        type: string
      Title:
        $ref: '#/definitions/Name_Type_2'
      FirstName:
        $ref: '#/definitions/Name_Type'
      FatherName:
        $ref: '#/definitions/Name_Type_2'
      GrandFatherName:
        $ref: '#/definitions/Name_Type_2'
      FamilyName:
        $ref: '#/definitions/Name_Type'
      NationalityId:
        type: integer
      BirthDate:
        $ref: '#/definitions/Dt_Type'
      Email:
        type: string
      MobileNumber:
        type: string
    required:
    - IdentifierTypeId
    - IdentifierNo
    - FirstName
    - FamilyName
    - NationalityId
  Representative_Type:
    type: object
    properties:
      NationalityId:
        type: integer
      FirstName:
        $ref: '#/definitions/Name_Type'
      FatherName:
        $ref: '#/definitions/Name_Type_2'
      GrandFatherName:
        $ref: '#/definitions/Name_Type_2'
      FamilyName:
        $ref: '#/definitions/Name_Type_2'
      PartyID:
        type: string
      BirthDate:
        $ref: '#/definitions/Dt_Type'
      IdentifierTypeId:
        type: integer
      Email:
        type: string
    required:
    - NationalityId
    - FirstName
    - PartyID
    - BirthDate
  ManagerPositionIdList_Type:
    type: object
    properties:
      ManagerPositionId:
        type: array
        items:
          $ref: '#/definitions/ID_Type'
    required:
    - ManagerPositionId
  PartnerList_Type:
    type: object
    properties:
      Partner:
        type: array
        items:
          $ref: '#/definitions/Partner_Type'
    required:
    - Partner
  Partner_Type:
    type: object
    properties:
      PartnerTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
      PartnershipTypeList:
        $ref: '#/definitions/PartnershipTypeList_Type'
      PersonInfo:
        $ref: '#/definitions/PersonInfo_Type'
      GovernmentalEntity:
        $ref: '#/definitions/GovernmentalEntity_Type'
      Endowment:
        $ref: '#/definitions/Endowment_Type'
      CivilAssociation:
        $ref: '#/definitions/CivilAssociation_Type'
      SaudiCompany:
        $ref: '#/definitions/SaudiCompany_Type'
      Establishment:
        $ref: '#/definitions/Establishment_Type'
      GccCompany:
        $ref: '#/definitions/GccCompany_Type'
      ForeignCompany:
        $ref: '#/definitions/GccCompany_Type'
      PartnerShare:
        $ref: '#/definitions/PartnerShare_Type'
    required:
    - PartnerTypeId
  PartnerShare_Type:
    type: object
    properties:
      CashContributionCount:
        type: string
      InkindContributionCount:
        type: string
      TotalContributionCount:
        type: string
  GovernmentalEntity_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      GovernmentalEntityNationalNo:
        type: string
      GovernmentalEntityName:
        $ref: '#/definitions/Name_Type_1'
    required:
    - IdentifierTypeId
    - GovernmentalEntityNationalNo
    - GovernmentalEntityName
  Endowment_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      DeedNo:
        type: string
      NationalNo:
        type: string
      EndowmentName:
        $ref: '#/definitions/Name_Type_1'
    required:
    - IdentifierTypeId
    - EndowmentName
  PartnershipTypeList_Type:
    type: object
    properties:
      PartnershipType:
        type: array
        items:
          $ref: '#/definitions/ID_Type'
    required:
    - PartnershipType
  CivilAssociation_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      NationalNo:
        type: string
      LicenseNo:
        type: string
      CivilAssociationName:
        $ref: '#/definitions/Name_Type_1'
    required:
    - IdentifierTypeId
    - CivilAssociationName
  SaudiCompany_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      CrNationalNumber:
        type: string
      CrNumber:
        type: string
      CompanyName:
        $ref: '#/definitions/Name_Type_1'
    required:
    - IdentifierTypeId
    - CompanyName
  Establishment_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      CrNationalNumber:
        type: string
      CrNumber:
        type: string
      EstablishmentName:
        $ref: '#/definitions/Name_Type_1'
    required:
    - IdentifierTypeId
    - EstablishmentName
  GccCompany_Type:
    type: object
    properties:
      IdentifierTypeId:
        type: integer
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      CrNumber:
        type: string
      CompanyName:
        $ref: '#/definitions/Name_Type_1'
      NationalityId:
        type: integer
    required:
    - IdentifierTypeId
    - CrNumber
    - CompanyName
    - NationalityId
  OpenUnifiedEstablishmentBySBCRs_BodyType:
    type: object
    properties:
      EstablishmentIds:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: string
      NationalUnifiedNumber:
        type: string
      RequestNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - NationalUnifiedNumber
    - RequestNumber
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
  Dt_Type:
    type: string
    format: date
    description: |
      Represents a date value (Gregorian). Adjust `format` or `type` as needed.
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Status
    - Code
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-open-file-with-cr)/estabmanagement/openuniestbysbcv2
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
