swagger: "2.0"
info:
  title: OpenEstablishmentFileByMiras
  x-ibm-name: openestablishmentfilebymiras
  version: 1.0.0
  description: This service is used to open establishment files using Miras.
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-estabmanagement)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  OpenEstablishmentFileByMirasRq_MessageType:
    type: object
    properties:
      OpenEstablishmentFileByMirasRq:
        $ref: '#/definitions/OpenEstablishmentFileByMirasRq_Type'
  OpenEstablishmentFileByMirasRs_MessageType:
    type: object
    properties:
      OpenEstablishmentFileByMirasRs:
        $ref: '#/definitions/OpenEstablishmentFileByMirasRs_Type'
  OpenEstablishmentFileByMirasRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentFileByMirasRq_BodyType'
  OpenEstablishmentFileByMirasRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: string
        default: "100001"
      IdNo:
        type: integer
        default: "454"
  EstablishmentsList_Type:
    type: object
    properties:
      EstablishmentsItem:
        type: array
        items:
          $ref: '#/definitions/EstablishmentsItem_Type'
  EstablishmentsItem_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      EstablishmentId:
        type: integer
      ServicesList:
        $ref: '#/definitions/ServicesList_Type'
  ServicesList_Type:
    type: object
    properties:
      ServicesItem:
        type: array
        items:
          $ref: '#/definitions/ServicesItem_Type'
  ServicesItem_Type:
    type: object
    properties:
      ServiceId:
        type: integer
  OpenEstablishmentFileByMirasRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentFileByMirasRs_BodyType'
  OpenEstablishmentFileByMirasRs_BodyType:
    type: object
    properties:
      EstablishmentsInfoList:
        $ref: '#/definitions/EstablishmentsInfoList_Type'
  EstablishmentsInfoList_Type:
    type: object
    properties:
      EstablishmentsInfoItem:
        type: array
        items:
          $ref: '#/definitions/EstablishmentsInfoItem_Type'
  EstablishmentsInfoItem_Type:
    type: object
    properties:
      LaborofficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      EstablishmentId:
        type: integer
      Status:
        type: string
      StatusDescription:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: OEFBM001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: OEFBM001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23432"
      IDNumber:
        type: integer
        default: "324324"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /opnestfilebymiras:
    post:
      operationId: OpenEstablishmentFileByMiras
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenEstablishmentFileByMirasRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Add or Update User privileges
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/OpenEstablishmentFileByMirasRq_MessageType'
        description: OpenEstablishmentFileByMirasRq
        required: true
