swagger: "2.0"
info:
  title: OpenEstablishmentByMiras
  x-ibm-name: openestablishmentbymiras
  version: 1.0.0
  description: this service is used to open establishment using Miras
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: http://icp-proxy.qiwa.info:32241/estabmanagement/opnestbymiras
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  OpenEstablishmentByMirasRq_MessageType:
    type: object
    properties:
      OpenEstablishmentByMirasRq:
        $ref: '#/definitions/OpenEstablishmentByMirasRq_Type'
  OpenEstablishmentByMirasRs_MessageType:
    type: object
    properties:
      OpenEstablishmentByMirasRs:
        $ref: '#/definitions/OpenEstablishmentByMirasRs_Type'
  OpenEstablishmentByMirasRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentByMirasRq_BodyType'
  OpenEstablishmentByMirasRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: string
      NationalNumber:
        type: integer
      IsMain:
        type: boolean
      MainCR:
        type: integer
      BusinessType:
        $ref: '#/definitions/IDName_Type'
      Location:
        $ref: '#/definitions/IDName_Type'
      CRName:
        type: string
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      Nationality:
        $ref: '#/definitions/IDName_Type'
      ZipCode:
        type: string
      POBOX:
        type: string
      City:
        $ref: '#/definitions/IDName_Type'
      CRStreet:
        type: string
      CRBuilding:
        type: integer
      CROfficeNumber:
        type: integer
      FiscalYear:
        $ref: '#/definitions/IDName_Type'
      CRParties:
        $ref: '#/definitions/CRParties_Type'
      CRRepresentative:
        $ref: '#/definitions/CRRepresentative_Type'
      CRActivities:
        $ref: '#/definitions/CRActivities_Type'
  CRParties_Type:
    type: object
    properties:
      Party:
        type: array
        items:
          $ref: '#/definitions/Party_Type'
  Party_Type:
    type: object
    properties:
      Name:
        type: string
      RelationType:
        $ref: '#/definitions/IDName_Type'
      Nationality:
        $ref: '#/definitions/IDName_Type'
      PartyID:
        type: integer
      BirthDate:
        type: string
  CRRepresentative_Type:
    type: object
    properties:
      Name:
        type: string
      Nationality:
        $ref: '#/definitions/IDName_Type'
      PartyID:
        type: integer
      BirthDate:
        type: string
      PartyIDType:
        type: string
      MobileNumber:
        type: integer
      Email:
        type: string
  CRActivities_Type:
    type: object
    properties:
      Activity:
        type: array
        items:
          $ref: '#/definitions/IDName_Type'
  IDName_Type:
    type: object
    properties:
      ID:
        type: integer
      Name:
        type: string
  OpenEstablishmentByMirasRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/OpenEstablishmentByMirasRs_BodyType'
  OpenEstablishmentByMirasRs_BodyType:
    type: object
    properties:
      EstablishmentIds:
        type: string
      RequestIds:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /opnestbymiras:
    post:
      operationId: OpenEstablishmentByMiras
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OpenEstablishmentByMirasRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: this service is used to open establishment using Miras
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/OpenEstablishmentByMirasRq_MessageType'
        description: OpenEstablishmentByMirasRq
        required: true
