swagger: "2.0"
info:
  title: PushSubsequentSupervisionLicense
  version: 1.0.0
  description: PushSubsequentSupervisionLicense
  x-ibm-name: pushsubsequentsupervisionlicense
paths:
  /pushsubsequentsupervisionlicense:
    post:
      operationId: PushSubsequentSupervisionLicense
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/PushSubsequentSupervisionLicenseRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: To get all laborers under the establishment
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/PushSubsequentSupervisionLicenseRq_MessageType'
        description: PushSubsequentSupervisionLicenseRq
        required: true
basePath: /estabmanagement
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
definitions:
  PushSubsequentSupervisionLicenseRq_MessageType:
    type: object
    properties:
      PushSubsequentSupervisionLicenseRq:
        $ref: '#/definitions/PushSubsequentSupervisionLicenseRq_Type'
  PushSubsequentSupervisionLicenseRs_MessageType:
    type: object
    properties:
      PushSubsequentSupervisionLicenseRs:
        $ref: '#/definitions/PushSubsequentSupervisionLicenseRs_Type'
  PushSubsequentSupervisionLicenseRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/PushSubsequentSupervisionLicenseRq_BodyType'
  PushSubsequentSupervisionLicenseRq_BodyType:
    type: object
    properties:
      licenseInfo:
        $ref: '#/definitions/licenseInfo_Type'
      unifiedNationalNumber:
        type: string
  PushSubsequentSupervisionLicenseRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/PushSubsequentSupervisionLicenseRs_BodyType'
  PushSubsequentSupervisionLicenseRs_BodyType:
    type: object
    properties: {}
  licenseInfo_Type:
    type: object
    properties:
      LicenseInfoItem:
        type: array
        items:
          $ref: '#/definitions/LicenseInfoItem_Type'
  LicenseInfoItem_Type:
    type: object
    properties:
      LicenseName:
        type: string
      LicenseNumber:
        type: string
      LicenseStatus:
        type: integer
      Source:
        type: string
      LicenseTypeId:
        type: integer
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      activityId:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-cmpm-open-file-without-cr-other)/estabmanagement/pushsubsequentsupervisionlicense
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
