swagger: "2.0"
info:
  title: Qiwa_GetExternalContractDetails
  version: 1.0.0
  description: This service is used to get external contract details.
  x-ibm-name: qiwa_getexternalcontractdetails
schemes:
- https
basePath: /workinsaudi
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /getexternalcontractdetails:
    post:
      operationId: GetExternalContractDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetExternalContractDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This service is used to get external contract details.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetExternalContractDetailsRq_MessageType'
        description: GetExternalContractDetails
        required: true
definitions:
  GetExternalContractDetailsRq_MessageType:
    type: object
    properties:
      GetExternalContractDetailsRq:
        $ref: '#/definitions/GetExternalContractDetailsRq_Type'
  GetExternalContractDetailsRs_MessageType:
    type: object
    properties:
      GetExternalContractDetailsRs:
        $ref: '#/definitions/GetExternalContractDetailsRs_Type'
  GetExternalContractDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetExternalContractDetailsRq_BodyType'
  GetExternalContractDetailsRq_BodyType:
    type: object
    properties:
      ContractId:
        type: integer
    required:
    - ContractId
  GetExternalContractDetailsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetExternalContractDetailsRs_BodyType'
  GetExternalContractDetailsRs_BodyType:
    type: object
    properties:
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      UpdateRequesterDetails:
        $ref: '#/definitions/UpdateRequesterDetails_Type'
      CandidateId:
        type: string
      ContractDetails:
        $ref: '#/definitions/ContractDetails_Type'
      EPRO:
        $ref: '#/definitions/CodeName_Type'
      Embassy:
        $ref: '#/definitions/CodeName_Type'
    required:
    - EstablishmentDetails
    - RequesterDetails
    - UpdateRequesterDetails
    - ContractDetails
  EstablishmentDetails_type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentType:
        $ref: '#/definitions/CodeName_Type'
      EstablishmentNameAr:
        type: string
      EstablishmentNameEn:
        type: string
      EstablishmentEmail:
        type: string
      NationalAddress:
        type: string
      PhoneNumber:
        type: string
      MobileNumber:
        type: string
    required:
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentType
    - EstablishmentNameAr
    - EstablishmentNameEn
    - EstablishmentEmail
    - NationalAddress
    - PhoneNumber
    - MobileNumber
  RequesterDetails_Type:
    type: object
    properties:
      RequesterName:
        type: string
      RequesterIdNo:
        type: string
      RequesterRoleEn:
        type: string
      RequesterRoleAr:
        type: string
      RequesterType:
        $ref: '#/definitions/CodeName_Type'
    required:
    - RequesterName
    - RequesterIdNo
    - RequesterRoleEn
    - RequesterRoleAr
    - RequesterType
  UpdateRequesterDetails_Type:
    type: object
    properties:
      UpdateRequesterName:
        type: string
      UpdateRequesterIdNo:
        type: string
      UpdateRequesterRoleEn:
        type: string
      UpdateRequesterRoleAr:
        type: string
      UpdateRequesterType:
        $ref: '#/definitions/CodeName_Type'
    required:
    - UpdateRequesterName
    - UpdateRequesterIdNo
    - UpdateRequesterRoleEn
    - UpdateRequesterRoleAr
    - UpdateRequesterType
  ContractDetails_Type:
    type: object
    properties:
      ContractId:
        type: integer
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      OccupationDetails:
        $ref: '#/definitions/OccupationDetails_Type'
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      ContractDuration:
        $ref: '#/definitions/CodeName_Type'
      ExecutionLocation:
        type: string
      WorkLocation:
        $ref: '#/definitions/CodeName_Type'
      ContractPeriod:
        type: integer
      ProbationPeriod:
        type: integer
      NoticePeriod:
        type: integer
      VacationPeriod:
        type: integer
      WorkingHoursType:
        $ref: '#/definitions/CodeName_Type'
      HoursPerWeek:
        type: integer
      DaysPerWeek:
        type: integer
      HoursPerDay:
        type: integer
      RestingDays:
        type: integer
      Salary:
        type: string
      SalaryDueDay:
        type: integer
      StartDate:
        type: string
        format: date
      ExpiryDate:
        type: string
        format: date
      EndDate:
        type: string
        format: date
      RenewalStatus:
        $ref: '#/definitions/CodeName_Type'
      RenewalTimes:
        type: integer
      RenewalPeriod:
        type: integer
      CreationDate:
        type: string
        format: date-time
      LastModifiedDate:
        type: string
        format: date-time
      RejectionReason:
        type: string
      UpdateReason:
        type: string
      UpdateDate:
        type: string
        format: date-time
      ModificationReason:
        type: string
      CancellationReason:
        type: string
      Status:
        $ref: '#/definitions/CodeName_Type'
      Version:
        type: integer
      Allowances:
        type: array
        items:
          type: object
          properties:
            AllowanceType:
              $ref: '#/definitions/CodeName_Type'
            Frequency:
              $ref: '#/definitions/CodeName_Type'
            AmountType:
              $ref: '#/definitions/CodeName_Type'
            NameAr:
              type: string
            NameEn:
              type: string
            Amount:
              type: number
      OptionalClauses:
        type: array
        items:
          type: object
          properties:
            OptionalClausesType:
              $ref: '#/definitions/CodeName_Type'
            Period:
              type: integer
            Field:
              type: string
            Location:
              type: string
            FirstParty:
              type: string
            SecondParty:
              type: string
      AdditionalTerms:
        type: array
        items:
          type: object
          properties:
            NameEn:
              type: string
            NameAr:
              type: string
      InKindBenefits:
        type: array
        items:
          type: object
          properties:
            NameEn:
              type: string
            NameAr:
              type: string
            DescriptionEn:
              type: string
            DescriptionAr:
              type: string
            Frequency:
              $ref: '#/definitions/CodeName_Type'
            DueDate:
              type: string
              format: date-time
      Commission:
        type: array
        items:
          type: object
          properties:
            CommissionBaseEn:
              type: string
            CommissionBaseAr:
              type: string
            Percentage:
              type: string
            Frequency:
              $ref: '#/definitions/CodeName_Type'
    required:
    - ContractId
    - JobTitle
    - OccupationDetails
    - ContractType
    - ContractDuration
    - ExecutionLocation
    - WorkLocation
    - ContractPeriod
    - ProbationPeriod
    - NoticePeriod
    - VacationPeriod
    - WorkingHoursType
    - HoursPerWeek
    - DaysPerWeek
    - HoursPerDay
    - RestingDays
    - Salary
    - SalaryDueDay
    - StartDate
    - ExpiryDate
    - EndDate
    - RenewalStatus
    - RenewalTimes
    - RenewalPeriod
    - CreationDate
    - LastModifiedDate
    - Status
    - Version
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
    required:
    - JobTitleAr
    - JobTitleEng
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
    required:
    - Code
    - NameEn
    - NameAr
  OccupationDetails_Type:
    type: object
    properties:
      OccupationId:
        type: integer
      OccupationAr:
        type: string
      OccupationEn:
        type: string
    required:
    - OccupationId
    - OccupationAr
    - OccupationEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-ws-externalcontractget)$(request.path)
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
