swagger: "2.0"
info:
  title: Qiwa_GetExternalContractByBorderNumber
  version: 1.0.0
  description: Qiwa GetExternalContractByBorderNumber
  x-ibm-name: qiwa_getexternalcontractbybordernumber
paths:
  /getexternalcontracbyborder:
    post:
      operationId: GetExternalContractByBorderNumber
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/GetExternalContractByBorderNumberRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Create New Contract
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/GetExternalContractByBorderNumberRq_MessageType'
        description: GetExternalContractByBorderNumberRq
        required: true
basePath: /workinsaudi
definitions:
  GetExternalContractByBorderNumberRq_MessageType:
    type: object
    properties:
      GetExternalContractByBorderNumberRq:
        $ref: '#/definitions/GetExternalContractByBorderNumberRq_Type'
  GetExternalContractByBorderNumberRs_MessageType:
    type: object
    properties:
      GetExternalContractByBorderNumberRs:
        $ref: '#/definitions/GetExternalContractByBorderNumberRs_Type'
  GetExternalContractByBorderNumberRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/GetExternalContractByBorderNumberRq_BodyType'
  GetExternalContractByBorderNumberRq_BodyType:
    type: object
    properties:
      BorderNumber:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
    required:
    - BorderNumber
    - LaborOfficeId
    - SequenceNumber
  GetExternalContractByBorderNumberRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/GetExternalContractByBorderNumberRs_BodyType'
  GetExternalContractByBorderNumberRs_BodyType:
    type: object
    properties:
      ExternalContractId:
        type: integer
      CandidateName:
        type: string
      WSId:
        type: integer
      PassportNo:
        type: string
      Occupation:
        $ref: '#/definitions/CodeName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
    required:
    - ExternalContractId
    - CandidateName
    - WSId
    - PassportNo
    - Occupation
    - Nationality
  CodeName_Type:
    type: object
    properties:
      StatusId:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
    required:
    - StatusId
    - NameEn
    - NameAr
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: keep
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-ws-externalcontractget)$(request.path)
        follow-redirects: false
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
