swagger: "2.0"
info:
  title: QIWA_OccuranceIndicator
  x-ibm-name: qiwa-occuranceindicator
  version: 1.0.2
schemes:
- https
basePath: /qiwa/v2
produces:
- application/json
consumes:
- application/json
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://gw-apic.qiwa.info/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: "var apim = require('apim');\n\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\nvar dt = new Date();\n//var cfg = apim.getvariable('cfg');\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\nvar cfg={\n
          \   \"serviceCode\" : \"EXGCI001\",\n    \"channelId\" : \"Qiwa\",\n\t\"SessionId\"
          : \"1\",\n    \"requestName\" : \"OccuranceIndicatorRq\",\n    \"responseName\":
          \"OccuranceIndicatorRs\",\n    \"errorMap\" :{\n        \"ESBSCHEMA\" :
          {\"code\" :400, \"msg\":\"Invalid Request\"},\n        \"E0000028\"  : {\"code\"
          :409, \"msg\":\"Conflict\"},\n        \"E0000684\"  : {\"code\" :409, \"msg\":\"NoEstablishmentInfo\"},\n
          \       \"E0000047\"  : {\"code\" :401, \"msg\":\"NoEstablishmentInfo\"},\n
          \       \"E0000048\"  : {\"code\" :401, \"msg\":\"NoEstablishmentInfo\"},\n
          \       \"TI000011\"  : {\"code\" :409, \"msg\":\"Conflict\"},\n        \"TI000010\"
          \ : {\"code\" :409, \"msg\":\"Conflict\"},\n        \"TI000012\"  : {\"code\"
          :409, \"msg\":\"Conflict\"},\n        \"TI000013\"  : {\"code\" :409, \"msg\":\"Conflict\"},\n
          \       \"E0000034\"  : {\"code\" :401, \"msg\":\"Conflict\"}\n    }\n    \n};\n\nvar
          channel = 0;\nif (apim.getvariable('message.headers.X-Channel-Id')!= null
          && apim.getvariable('message.headers.X-Channel-Id')!=0){\n    channel= apim.getvariable('message.headers.X-Channel-Id');\n}\nelse{\n
          \   channel= cfg.channelId;\n}\n\nvar appcReq = {\n    [cfg.requestName]:{\n
          \       \"Header\" : {\n            \"TransactionId\" : millisecondsvalue,\n
          \           \"ChannelId\": channel,\n            \"SessionId\": cfg.SessionId,
          //apim.getvariable('message.headers.X-Request-Id'),\n            \"RequestTime\"
          : formatDate(dt),\n\t\t\t\"MWRequestTime\" : formatDate(dt),\n            \"ServiceCode\":
          cfg.serviceCode,\n\t\t\n        },\n        \"Body\" : apim.getvariable('message.body')\n
          \           \n        \n    }\n};\n\nif (typeof OperatorId !== 'undefined')\n
          \   appcReq[cfg.requestName].Header.UserInfo = {\n        \"IDNumber\" :
          OperatorId\n    };\nsession.output.write(appcReq);\napim.setvariable('cfg',
          cfg);\napim.output('application/json');\n\n\nfunction formatDate(d)\n{\n
          \   //get the month\n    var month = d.getMonth();\n    //get the day\n
          \   //convert day to string\n    var day = d.getDate().toString();\n    //get
          the year\n    var year = d.getFullYear();\n    var hour = d.getHours().toString();\n
          \   var minitue = d.getMinutes().toString();\n    var second = d.getSeconds().toString();\n
          \   var millisecond = d.getMilliseconds().toString();\n    //pull the last
          two digits of the year\n    year = year.toString();\n    \n    //increment
          month by 1 since it is 0 indexed\n    //converts month to a string\n    month
          = (month + 1).toString();\n\n    //if month is 1-9 pad right with a 0 for
          two digits\n    if (month.length === 1)\n        month = \"0\" + month;\n\n
          \   //if day is between 1-9 pad right with a 0 for two digits\n    if (day.length
          === 1)\n        day = \"0\" + day;\n\n    if (hour.length === 1)\n        hour
          = \"0\" + hour;\n\n    if (minitue.length === 1)\n        minitue = \"0\"
          + minitue;\n\n    if (second.length === 1)\n        second = \"0\" + second;\n
          \       \n    if (millisecond.length == 1)\n        millisecond = \"00\"
          + millisecond;\n        \n    if (millisecond.length == 2)\n        millisecond
          = \"0\" + millisecond;\n    \n    \n\n    //return the string \"MMddyy\"\n
          \   return year+\"-\"+month+\"-\"+day+\" \"+hour + \":\" + minitue + \":\"
          + second+\".\"+millisecond;\n}"
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: $(ace-trni-trainingmanagement)/external/OccuranceIndicator
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        stop-on-error:
        - OperationError
        - SOAPError
        - ConnectionError
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: Build Headers
        source: "\tvar apim = require('apim');\n\t\n\tapim.output('application/json');\n\n
          \   \n    \n   // var cfg = apim.getvariable('cfg');\n   \n   var cfg={\n
          \   \"serviceCode\" : \"EXGCI001\",\n    \"channelId\" : \"Qiwa\",\n\t\"SessionId\"
          : \"1\",\n    \"requestName\" : \"OccuranceIndicatorRq\",\n    \"responseName\":
          \"OccuranceIndicatorRs\",\n    \"errorMap\" :{\n        \"ESBSCHEMA\" :
          {\"code\" :400, \"msg\":\"Invalid Request\"},\n        \"E0000028\"  : {\"code\"
          :409, \"msg\":\"Conflict\"},\n        \"E0000684\"  : {\"code\" :409, \"msg\":\"NoEstablishmentInfo\"},\n
          \       \"E0000047\"  : {\"code\" :401, \"msg\":\"NoEstablishmentInfo\"},\n
          \       \"E0000048\"  : {\"code\" :401, \"msg\":\"NoEstablishmentInfo\"},\n
          \       \"TI000011\"  : {\"code\" :409, \"msg\":\"Conflict\"},\n        \"TI000010\"
          \ : {\"code\" :409, \"msg\":\"Conflict\"},\n        \"TI000012\"  : {\"code\"
          :409, \"msg\":\"Conflict\"},\n        \"TI000013\"  : {\"code\" :409, \"msg\":\"Conflict\"},\n
          \       \"E0000034\"  : {\"code\" :401, \"msg\":\"Conflict\"}\n    }\n    \n};\n
          \   \nvar message = apim.getvariable('message.body');\nvar cfg = apim.getvariable('cfg');\nvar
          Header = message[cfg.responseName].Header;\nvar TransactionId = Header.TransactionId;\nvar
          ChannelId = Header.ChannelId;\nvar RequestTime = Header.RequestTime;\nvar
          SessionId = Header.SessionId;\nvar MWRequestTime = Header.MWRequestTime;\nvar
          MWResponseTime = Header.MWResponseTime;\nvar status = Header.ResponseStatus.Status;\n\n\n\napim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\napim.setvariable('message.headers.Channel-Id',ChannelId,'add');\nif
          (RequestTime !== 'undefined')\n apim.setvariable('message.headers.RequestTime',RequestTime,'add');\nif
          (SessionId !== 'undefined')\n apim.setvariable('message.headers.X-Request-Id',SessionId,'add');\nif
          (MWRequestTime !== 'undefined')\napim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\nif
          (MWResponseTime !== 'undefined')\napim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\n\n
          \   \n    apim.setvariable('message.headers.Response-Status',status,'add');\n
          \   "
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\n//var
                cfg = apim.getvariable('cfg'); \nvar cfg={\n  \n    \n    \"responseName\":
                \"OccuranceIndicatorRs\",\n   \n    \n};\nvar body = message[cfg.responseName].Body;\n\n\nsession.output.write(body);\napim.output('application/json');"
        - condition: ($header("Response-Status") = 'Error' or ($header("Response-Status")
            = 'ERROR'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Error
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\n//var
                cfg = apim.getvariable('cfg');     \nvar cfg={\n  \n    \n    \"responseName\":
                \"OccuranceIndicatorRs\",\n     \"errorMap\" :{\n        \"ESBSCHEMA\"
                : {\"code\" :400, \"msg\":\"Invalid Request\"},\n        \"E0000028\"
                \ : {\"code\" :409, \"msg\":\"Conflict\"},\n        \"E0000684\"  :
                {\"code\" :409, \"msg\":\"NoEstablishmentInfo\"},\n        \"E0000047\"
                \ : {\"code\" :401, \"msg\":\"NoEstablishmentInfo\"},\n        \"E0000048\"
                \ : {\"code\" :401, \"msg\":\"NoEstablishmentInfo\"},\n        \"TI000011\"
                \ : {\"code\" :409, \"msg\":\"Conflict\"},\n        \"TI000010\"  :
                {\"code\" :409, \"msg\":\"Conflict\"},\n        \"TI000012\"  : {\"code\"
                :409, \"msg\":\"Conflict\"},\n        \"TI000013\"  : {\"code\" :409,
                \"msg\":\"Conflict\"},\n        \"E0000034\"  : {\"code\" :401, \"msg\":\"Conflict\"}\n
                \   }\n   \n    \n};\nvar error = {\n  \"errorCode\": message[cfg.responseName].Header.ResponseStatus.Code,\n
                \ \"errorMessage\": {\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\n
                \ }\n};\n\nvar httperror=0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 400;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: "var apim = require('apim');\n\nvar message = apim.getvariable('message.body');\n//var
                cfg = apim.getvariable('cfg');     \nvar cfg={\n  \n    \n    \"responseName\":
                \"Error\",\n   \n    \n};\nvar error = {\n  \"errorCode\": message['Error'].Code,\n
                \ \"errorMessage\": {\n    \"en-US\": message['Error'].Detail,\n    \"ar-SA\":
                'System Error'\n};\n\nvar httperror=0;\nif(cfg.errorMap){\n    if(cfg.errorMap[error.errorCode]){\n
                \      httperror = cfg.errorMap[error.errorCode].code;\n       \n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\n
                \      //apim.error('ERROR',httperror,errmgs,details);\n    }\n}\nif(httperror
                == 0){\n   httperror = 500;\n   // apim.error('ERROR',400,'Bad Request','Invalid
                request');\n}\napim.setvariable('message.status.code',httperror,'set');\n\nsession.output.write(error);\napim.output('application/json');"
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "200"
            type: string
          - set: message.headers.content-type
            value: application/json
            type: string
          - set: message.body
            value: '{     "errorCode": "E000500",     "errorMessage": "Internal server
              error"              }'
            type: string
    finally: []
  properties:
    target-url:
      value: http://trni-trainingmanagement-http-ace.apps.stg.qiwa-nonprod.local/external/OccuranceIndicator
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
definitions:
  OccuranceIndicatorRs:
    type: object
    additionalProperties: false
    properties:
      Header:
        $ref: '#/definitions/Header'
        properties: {}
      Body:
        $ref: '#/definitions/Body'
        properties: {}
  Body:
    type: object
    additionalProperties: false
    properties:
      OccuranceIndicator:
        type: integer
        example: "33.33"
      TotalApprovedTrainingCount:
        type: integer
      TotalEmployeeCount:
        type: integer
  Header:
    type: object
    additionalProperties: false
    properties:
      TransactionId:
        type: string
        example: "1645096893"
      ChannelId:
        type: string
        example: Qiwa
      SessionId:
        type: integer
        example: "1"
      RequestTime:
        type: string
        example: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        example: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        example: "2022-02-17 11:21:34.454"
      ServiceCode:
        type: string
        example: EXGCI001
      DebugFlag:
        type: integer
        example: "1"
      ResponseStatus:
        $ref: '#/definitions/ResponseStatus'
        properties: {}
  ResponseStatus:
    type: object
    additionalProperties: false
    properties:
      Status:
        type: string
        example: SUCCESS
      Code:
        type: string
        example: "00000000"
      ArabicMsg:
        type: string
        example: تمت العملية بنجاح
      EnglishMsg:
        type: string
        example: Success Call
  OccuranceIndicatiorReqBody:
    type: object
    additionalProperties: false
    properties:
      EstablishmentId:
        type: integer
        example: "2613438"
      UserId:
        type: integer
        example: "1071399"
      IDNumber:
        type: string
        example: "1006581878"
      LaborOfficeId:
        type: integer
        example: "9"
      SequenceNumber:
        type: integer
        example: "189630"
      Year:
        type: integer
        example: "2024"
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
  Headers:
    type: object
    properties:
      X-Request-Id:
        type: string
        example: 123e4567-e89b-12d3-a456-426614174000
  HeadersErrorModel:
    type: object
    properties:
      headers:
        $ref: '#/definitions/Headers'
paths:
  /OccuranceIndicator:
    post:
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/OccuranceIndicatorRs'
        "400":
          description: The request was rejected by the server due to malformed syntax.
            Bad Request.
        "401":
          description: The request could not be completed due to lack of valid credentials.
            Authentication.
          schema:
            $ref: '#/definitions/HeadersErrorModel'
        "403":
          description: The request could not be completed because it is not authorized.
            Authorization
          schema:
            $ref: '#/definitions/HeadersErrorModel'
        "404":
          description: The server has not found anything matching the Request-URI.
        "408":
          description: The client did not produce a request within the time that the
            server was prepared to wait.
        "409":
          description: The request could not be completed due to a conflict with the
            current state of the resource. Usually business validation errors will
            be returned in the body
          schema:
            $ref: '#/definitions/HeadersErrorModel'
        "429":
          description: The request was sent too many times in a given amount of time
          schema:
            $ref: '#/definitions/HeadersErrorModel'
        "500":
          description: The server encountered an unexpected condition which prevented
            it from fulfilling the request.
          schema:
            $ref: '#/definitions/ErrorModel'
        "501":
          description: The server does not support the functionality required and
            does not recognize the request
          schema:
            $ref: '#/definitions/ErrorModel'
        "503":
          description: The server encountered an unexpected condition which prevented
            it from fulfilling the request.
          schema:
            $ref: '#/definitions/ErrorModel'
        "510":
          description: Extensions to the request are required for the server to fulfil
            it.
          schema:
            $ref: '#/definitions/ErrorModel'
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: X-IBM-Client-Id
        in: header
        required: true
        type: string
      - name: X-Request-Id
        in: header
        required: false
        type: string
      - name: ComplianceIndicatorRq
        in: body
        required: true
        schema:
          $ref: '#/definitions/OccuranceIndicatiorReqBody'
