swagger: "2.0"
info:
  title: InterQWalletsBalanceTransfer
  x-ibm-name: qiwa-qwallet-interqwalletsbalancetransfer
  version: 1.0.0
  description: InterQWalletsBalanceTransfer
schemes:
- https
basePath: /qwallet/rb
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-qw-q-walletsubmit)/qwallet/rb/interqwalletsbalancetransfer
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  InterQWalletsBalanceTransferRq_MessageType:
    type: object
    properties:
      InterQWalletsBalanceTransferRq:
        $ref: '#/definitions/InterQWalletsBalanceTransferRq_Type'
  InterQWalletsBalanceTransferRs_MessageType:
    type: object
    properties:
      InterQWalletsBalanceTransferRs:
        $ref: '#/definitions/InterQWalletsBalanceTransferRs_Type'
  InterQWalletsBalanceTransferRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/InterQWalletsBalanceTransferRq_BodyType'
  InterQWalletsBalanceTransferRq_BodyType:
    type: object
    properties:
      SourceEstablishmentItem:
        $ref: '#/definitions/SourceEstablishmentItem_Type'
      DestinationEstablishmentItem:
        $ref: '#/definitions/DestinationEstablishmentItem_Type'
      TransferType:
        type: string
        example: F
      TransferAmount:
        type: number
        format: double
        example: 100
    required:
    - SourceEstablishmentItem
    - DestinationEstablishmentItem
    - TransferType
    - TransferAmount
  SourceEstablishmentItem_Type:
    type: object
    properties:
      QWalletId:
        type: string
        example: "55"
      LaborOfficeId:
        type: integer
        example: 1
      SequenceNumber:
        type: integer
        example: 1722644
    required:
    - LaborOfficeId
    - SequenceNumber
    - QWalletId
  DestinationEstablishmentItem_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        example: 1
      SequenceNumber:
        type: integer
        example: 1722644
    required:
    - LaborOfficeId
    - SequenceNumber
  InterQWalletsBalanceTransferRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/InterQWalletsBalanceTransferRs_BodyType'
  InterQWalletsBalanceTransferRs_BodyType:
    type: object
    properties:
      Status:
        type: string
        default: Request sent for review and approval by the Unified number owner
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /interqwalletsbalancetransfer:
    post:
      operationId: InterQWalletsBalanceTransfer
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/InterQWalletsBalanceTransferRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Get the details and balance of an establishment e-wallet
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/InterQWalletsBalanceTransferRq_MessageType'
        description: InterQWalletsBalanceTransfer
        required: true
      - name: X-IBM-Client-Id
        in: header
        description: Client id issued by security server
        required: true
        type: string
      - name: X-IBM-Client-Secret
        in: header
        description: Client secret issued by security server
        required: true
        type: string
      - name: X-Request-Id
        in: header
        description: X-Request-Id returned in the response header
        required: false
        type: string
