swagger: "2.0"
info:
  title: QiwaGetEmployeeList
  x-ibm-name: qiwagetemployeelist
  version: 1.0.0
  description: Qiwa Get Employee List
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-hrsd-hrsdutility)/common/qiwagetemployeelist
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  QiwaGetEmployeeListRq_MessageType:
    type: object
    properties:
      QiwaGetEmployeeListRq:
        $ref: '#/definitions/QiwaGetEmployeeListRq_Type'
  QiwaGetEmployeeListRs_MessageType:
    type: object
    properties:
      QiwaGetEmployeeListRs:
        $ref: '#/definitions/QiwaGetEmployeeListRs_Type'
  QiwaGetEmployeeListRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/QiwaGetEmployeeListRq_BodyType'
  QiwaGetEmployeeListRq_BodyType:
    type: object
    properties:
      EstablishmentId:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - EstablishmentId
    - PageSize
    - PageIndex
  QiwaGetEmployeeListRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/QiwaGetEmployeeListRs_BodyType'
  QiwaGetEmployeeListRs_BodyType:
    type: object
    properties:
      LaborersList:
        $ref: '#/definitions/LaborersList_Type'
      TotalRecordCount:
        type: integer
    required:
    - LaborersList
    - TotalRecordCount
  LaborersList_Type:
    type: object
    properties:
      Laborers:
        type: array
        items:
          $ref: '#/definitions/Laborers_Type'
  Laborers_Type:
    type: object
    properties:
      IdNo:
        type: integer
      BorderNumber:
        type: integer
      LaborerName:
        $ref: '#/definitions/LaborerName_Type'
      GenderId:
        type: integer
      IsSaudiFlagId:
        type: integer
      ServiceStartDate:
        type: string
      IqamaExpirationDate:
        type: string
      EntryDate:
        type: string
      WPExpirationDate:
        type: string
      LaborerStatus:
        $ref: '#/definitions/CodeName_Type'
      Job:
        $ref: '#/definitions/CodeName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      IsRegular:
        type: integer
    required:
    - IdNo
    - BorderNumber
    - LaborerName
    - GenderId
    - IsSaudiFlagId
    - ServiceStartDate
    - IqamaExpirationDate
    - EntryDate
    - WPExpirationDate
    - LaborerStatus
    - Job
    - Nationality
    - IsRegular
  LaborerName_Type:
    type: object
    properties:
      First:
        type: string
      Second:
        type: string
      Third:
        type: string
      Fourth:
        type: string
    required:
    - First
    - Second
    - Third
    - Fourth
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      Name:
        type: string
    required:
    - Code
    - Name
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /qiwagetemployeelist:
    post:
      operationId: QiwaGetEmployeeList
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/QiwaGetEmployeeListRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Qiwa Get Employee List
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/QiwaGetEmployeeListRq_MessageType'
        description: QiwaGetEmployeeListRq
        required: true
