swagger: "2.0"
info:
  title: QKS UpdateAgent
  x-ibm-name: qks-updateagent
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://apic-gw-gateway-apic.apps.stg.qiwa-nonprod.local/takamol/staging/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: POST
        target-url: $(target-url)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://kiosk-http-ace.apps.stg.qiwa-nonprod.local/qks_agent_management/v1/updateAgent
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
paths:
  /updateAgent:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
security:
- OAuth2.0:
  - IntegrationScope
  clientSecret: []
  clientID: []
- {}
consumes: []
