swagger: "2.0"
info:
  title: QKS_UnassignAgentFromProactiveAppointment
  x-ibm-name: qks_unassignagentfromproactiveappointment
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: GET
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-kiosk)/qks_proactive_management/v1/unassignAgent?$(request.querystring)
        follow-redirects: false
        inject-proxy-headers: true
    finally: []
  properties: {}
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /qiwa/v2
paths:
  /unassignAgent:
    get:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    x-key-type: client_id
  client_secret:
    type: apiKey
    x-key-type: client_secret
    name: X-IBM-Client-Secret
    in: header
  OAuth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientID: []
  client_secret: []
  OAuth2.0: []
schemes:
- https
