swagger: "2.0"
info:
  title: QKSGetEligibleAppointments
  version: 1.0.0
  description: |
    This service retrieves eligible appointments.
  x-ibm-name: qksgeteligibleappointments
basePath: /qiwalo
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
schemes:
- https
paths:
  /qksgeteligibleapp:
    post:
      operationId: QKSGetEligibleAppointments
      summary: Get Eligible Appointments
      description: Retrieves eligible appointments based on appointment date.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        description: QKSGetEligibleAppointmentsRq
        required: true
        schema:
          $ref: '#/definitions/QKSGetEligibleAppointmentsRq_MessageType'
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/QKSGetEligibleAppointmentsRs_MessageType'
definitions:
  QKSGetEligibleAppointmentsRq_MessageType:
    type: object
    properties:
      QKSGetEligibleAppointmentsRq:
        $ref: '#/definitions/QKSGetEligibleAppointmentsRq_Type'
  QKSGetEligibleAppointmentsRs_MessageType:
    type: object
    properties:
      QKSGetEligibleAppointmentsRs:
        $ref: '#/definitions/QKSGetEligibleAppointmentsRs_Type'
  QKSGetEligibleAppointmentsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/QKSGetEligibleAppointmentsRq_BodyType'
    required:
    - Header
    - Body
  QKSGetEligibleAppointmentsRq_BodyType:
    type: object
    properties:
      appointmentDate:
        type: string
        format: date
    required:
    - appointmentDate
  QKSGetEligibleAppointmentsRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/QKSGetEligibleAppointmentsRs_BodyType'
    required:
    - Header
    - Body
  QKSGetEligibleAppointmentsRs_BodyType:
    type: object
    properties:
      AgentId:
        type: integer
      Appointments:
        $ref: '#/definitions/Appointments_Type'
    required:
    - AgentId
    - Appointments
  Appointments_Type:
    type: object
    properties:
      AppointmentItem:
        type: array
        items:
          $ref: '#/definitions/AppointmentItem_Type'
    required:
    - AppointmentItem
  AppointmentItem_Type:
    type: object
    properties:
      AgentName:
        type: string
      AgentEmail:
        type: string
      AgentRole:
        type: string
      AppointmentNumber:
        type: integer
      AppointmentDate:
        type: string
      StartTime:
        type: string
      EndTime:
        type: string
      VisitorName:
        type: string
      VisitorEmail:
        type: string
      AppointmentStatus:
        type: string
      BranchService:
        type: string
    required:
    - AppointmentNumber
    - AppointmentDate
    - StartTime
    - EndTime
    - VisitorName
    - VisitorEmail
    - AppointmentStatus
    - BranchService
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-services)/qiwalo/qksgeteligibleapp
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
