swagger: "2.0"
info:
  title: QueryCenter_GetQKSQueryData
  x-ibm-name: querycenter-getqksquerydata
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
security:
- OAuth2.0:
  - IntegrationScope
  clientID: []
  clientSecret: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: ""
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        backend-type: detect
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        target-url: $(ace-qry-qry-center)/qc_querymanagement/v1/QKSQueryData
        follow-redirects: false
        inject-proxy-headers: true
    catch: []
    finally: []
  properties: {}
  application-authentication:
    certificate: false
  catalogs: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
paths:
  /QKSQueryData:
    post:
      responses:
        "200":
          description: success
          schema:
            type: string
      consumes: []
      produces: []
