swagger: "2.0"
info:
  title: RequestEstablishingVisasBalanceLO
  x-ibm-name: requestestablishingvisasbalancelo
  version: 1.0.0
  description: RequestEstablishingVisasBalanceLO
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-visas)/qiwalo/reqestabvisasbalancelo
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  RequestEstablishingVisasBalanceLORq_MessageType:
    type: object
    properties:
      RequestEstablishingVisasBalanceLORq:
        $ref: '#/definitions/RequestEstablishingVisasBalanceLORq_Type'
  RequestEstablishingVisasBalanceLORs_MessageType:
    type: object
    properties:
      RequestEstablishingVisasBalanceLORs:
        $ref: '#/definitions/RequestEstablishingVisasBalanceLORs_Type'
  RequestEstablishingVisasBalanceLORq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/RequestEstablishingVisasBalanceLORq_BodyType'
  RequestEstablishingVisasBalanceLORq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      PaymentReference:
        type: string
      EstablishmentSequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      TierId:
        type: integer
      Tier4RequestedBalance:
        type: integer
      RequesterMobileNumber:
        type: string
      RequesterName:
        type: integer
      location:
        type: integer
      email:
        type: integer
      Address:
        $ref: '#/definitions/Address_Type'
    required:
    - LaborOfficeId
    - EstablishmentSequenceNumber
    - EstablishmentId
    - TierId
  Address_Type:
    type: object
    properties:
      City:
        type: string
      District:
        type: string
      Street:
        type: string
      BuildingNumber:
        type: string
      POBox:
        type: string
      ZIPCode:
        type: string
      Latitude:
        type: integer
      Longitude:
        type: integer
      AddressDescription:
        type: string
  RequestEstablishingVisasBalanceLORs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/RequestEstablishingVisasBalanceLORs_BodyType'
  RequestEstablishingVisasBalanceLORs_BodyType:
    type: object
    properties:
      BalanceReferenceNumber:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /reqestabvisasbalancelo:
    post:
      operationId: RequestEstablishingVisasBalanceLO
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/RequestEstablishingVisasBalanceLORs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Request Establishing Balance
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/RequestEstablishingVisasBalanceLORq_MessageType'
        description: RequestEstablishingVisasBalanceLORq
        required: true
