swagger: "2.0"
info:
  title: SearchSeasonalEndorsement
  x-ibm-name: searchseasonalendorsement
  version: 1.0.0
  description: This service is used to retrieve endorsement details depending on search
    criteria provided
schemes:
- https
basePath: /visa/seasonalvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-sese-seasutility)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SearchSeasonalEndorsementRq_MessageType:
    type: object
    properties:
      SearchSeasonalEndorsementRq:
        $ref: '#/definitions/SearchSeasonalEndorsementRq_Type'
  SearchSeasonalEndorsementRs_MessageType:
    type: object
    properties:
      SearchSeasonalEndorsementRs:
        $ref: '#/definitions/SearchSeasonalEndorsementRs_Type'
  SearchSeasonalEndorsementRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchSeasonalEndorsementRq_BodyType'
  SearchSeasonalEndorsementRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      EndorsementId:
        type: integer
      EndorsementTypeId:
        type: array
        items:
          type: integer
        minItems: 1
        maxItems: 6
      EndorsementNumber:
        type: integer
      EstablishmentName:
        type: string
      SourceTypeId:
        type: integer
      EndorsementStatusId:
        type: array
        items:
          type: integer
        minItems: 1
        maxItems: 6
      GovernmentalSectorId:
        type: integer
      CreationDateGregorian:
        $ref: '#/definitions/Gregorian_Type'
      CreationDateHijri:
        $ref: '#/definitions/Hijri_Type'
      SortBy:
        type: integer
      SortDirection:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - SourceTypeId
    - PageSize
    - PageIndex
  Gregorian_Type:
    type: object
    properties:
      From:
        type: string
      To:
        type: string
  Hijri_Type:
    type: object
    properties:
      From:
        type: integer
      To:
        type: integer
  SearchSeasonalEndorsementRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchSeasonalEndorsementRs_BodyType'
  SearchSeasonalEndorsementRs_BodyType:
    type: object
    properties:
      EndorsementsList:
        $ref: '#/definitions/EndorsementsList_Type'
      TotalRecordsCount:
        type: integer
      TotalVisaCount:
        type: integer
    required:
    - EndorsementsList
    - TotalRecordsCount
    - TotalVisaCount
  EndorsementsList_Type:
    type: object
    properties:
      EndorsementsListItem:
        type: array
        items:
          $ref: '#/definitions/EndorsementsListItem_Type'
  EndorsementsListItem_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EndorsementId:
        type: integer
      EndorsementNumber:
        type: integer
      EndorsementType:
        $ref: '#/definitions/CodeName_Type'
      EstablishmentName:
        type: string
      EstablishmentId:
        type: integer
      EstablishmentLicenseNumbers:
        type: integer
      GovernmentalSector:
        $ref: '#/definitions/GovernmentalSector_Type'
      EndorsementStatus:
        $ref: '#/definitions/EndorsementStatus_Type'
      ChangeVisaCountReason:
        type: string
      CreationDate:
        type: string
      EndorsementVersion:
        type: integer
      'EstablishmentLocation ':
        $ref: '#/definitions/EstablishmentLocation_Type'
      OwnersAndRepresentativesInfosList:
        $ref: '#/definitions/OwnersAndRepresentativesInfosList_Type'
      EndorsementDetailsList:
        $ref: '#/definitions/EndorsementDetailsList_Type'
      ContactInformation:
        $ref: '#/definitions/ContactInformation_Type'
      EndorsementDecision:
        $ref: '#/definitions/EndorsementDecision_Type'
      RequiredDocuments:
        $ref: '#/definitions/RequiredDocuments_Type'
      IsExempted:
        type: boolean
      OriginalVisaCount:
        type: integer
      TotalApprovedVisaCount:
        type: integer
  GovernmentalSector_Type:
    type: object
    properties:
      GovernmentalSectorId:
        type: integer
      GovernmentalSectorAr:
        type: string
      GovernmentalSectorEn:
        type: string
  EstablishmentLocation_Type:
    type: object
    properties:
      City:
        type: string
      District:
        type: string
      Street:
        type: string
      BuildingNo:
        type: string
      ZIPCode:
        type: string
      AdditionalNumber:
        type: string
      LocationMapUrl:
        type: string
    required:
    - City
    - District
    - Street
    - BuildingNo
    - ZIPCode
    - AdditionalNumber
    - LocationMapUrl
  EndorsementStatus_Type:
    type: object
    properties:
      EndorsementStatusId:
        type: integer
      EndorsementStatusAr:
        type: string
      EndorsementStatusEn:
        type: string
    required:
    - EndorsementStatusId
    - EndorsementStatusAr
    - EndorsementStatusEn
  EndorsementDetailsList_Type:
    type: object
    properties:
      EndorsementDetailsItem:
        type: array
        items:
          $ref: '#/definitions/EndorsementDetailsItem_Type'
  EndorsementDetailsItem_Type:
    type: object
    properties:
      EndorsmentDetailsId:
        type: integer
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      Occupation:
        $ref: '#/definitions/CodeName_Type'
      Gender:
        $ref: '#/definitions/CodeName_Type'
      ReligionId:
        $ref: '#/definitions/CodeName_Type'
      TotalVisaNo:
        type: integer
      ApprovedVisaNo:
        type: integer
    required:
    - EndorsmentDetailsId
    - Nationality
    - Occupation
    - Gender
    - ReligionId
    - TotalVisaNo
  RequiredDocuments_Type:
    type: object
    properties:
      FinancialCapacityId:
        type: string
      BankWarantyDetails:
        $ref: '#/definitions/BankWarantyDetails_Type'
      ClearanceRecordsList:
        type: string
      FinalFileId:
        type: string
  BankWarantyDetails_Type:
    type: object
    properties:
      BankWarrantyId:
        type: string
      BankWarrantyNumber:
        type: string
      BankWarrantyTotalAmount:
        type: string
    required:
    - BankWarrantyId
    - BankWarrantyNumber
    - BankWarrantyTotalAmount
  CodeName_Type:
    type: object
    properties:
      Id:
        type: integer
      NameEn:
        type: string
      NameAr:
        type: string
  EndorsementDecision_Type:
    type: object
    properties:
      EndorsementDecisionId:
        type: integer
      UserId:
        type: integer
      IdNumber:
        type: integer
      Member:
        $ref: '#/definitions/CodeName_Type'
      Decision:
        $ref: '#/definitions/CodeName_Type'
      ModificationReason:
        type: string
      RejectionReason:
        type: string
      IsFinal:
        type: integer
    required:
    - EndorsementDecisionId
    - UserId
    - IdNumber
    - Member
    - Decision
  OwnersAndRepresentativesInfosList_Type:
    type: object
    properties:
      FirstName:
        type: string
      LastName:
        type: string
      PhoneNumber:
        type: string
      NationalId:
        type: integer
      Role:
        $ref: '#/definitions/CodeName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
    required:
    - Nationality
    - Role
    - NationalId
    - FirstName
    - LastName
  ContactInformation_Type:
    type: object
    properties:
      ContactPersonName:
        type: string
      ContactPersonNationalId:
        type: string
      MobileNumber:
        type: string
    required:
    - ContactPersonName
    - ContactPersonNationalId
    - MobileNumber
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchseasend:
    post:
      operationId: SearchSeasonalEndorsement
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchSeasonalEndorsementRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Update Refunded
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchSeasonalEndorsementRq_MessageType'
        description: The scope of this service is to retrieve endorsement details
          depending on search criteria provided.
        required: true
