swagger: "2.0"
info:
  title: SearchContractBulk V2
  x-ibm-name: searchcontractbulk-v2
  version: 1.0.0
  description: This service is used to search a bulk of contracts.
schemes:
- https
basePath: /contractmanagement/v2
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-contractutilities)/contractmanagement/searchcontractbulk
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SearchContractBulkRq_MessageType:
    type: object
    properties:
      SearchContractBulkRq:
        $ref: '#/definitions/SearchContractBulkRq_Type'
  SearchContractBulkRs_MessageType:
    type: object
    properties:
      SearchContractBulkRs:
        $ref: '#/definitions/SearchContractBulkRs_Type'
  SearchContractBulkRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchContractBulkRq_BodyType'
  SearchContractBulkRq_BodyType:
    type: object
    properties:
      BulkId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      PageSize:
        type: integer
      PageIndex:
        type: integer
    required:
    - BulkId
    - LaborOfficeId
    - SequenceNumber
    - PageSize
    - PageIndex
  SearchContractBulkRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchContractBulkRs_BodyType'
  SearchContractBulkRs_BodyType:
    type: object
    properties:
      BulkId:
        type: integer
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
      RequesterDetails:
        $ref: '#/definitions/RequesterDetails_Type'
      ContractList:
        $ref: '#/definitions/ContractList_Type'
      CreationDate:
        type: string
      TotalRecordCount:
        type: integer
    required:
    - ContractList
    - EstablishmentDetails
    - RequesterDetails
    - CreationDate
    - TotalRecordCount
  EstablishmentDetails_Type:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
    required:
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentId
  RequesterDetails_Type:
    type: object
    properties:
      RequesterIdNo:
        type: integer
      RequesterName:
        type: string
    required:
    - RequesterIdNo
    - RequesterName
  ContractList_Type:
    type: object
    properties:
      ContractItem:
        type: array
        items:
          $ref: '#/definitions/ContractItem_Type'
  ContractItem_Type:
    type: object
    properties:
      ContractDetails:
        $ref: '#/definitions/ContractDetails_Type'
      BulkItemDetails:
        $ref: '#/definitions/BulkItemDetails_Type'
    required:
    - ContractDetails
    - BulkItemDetails
  BulkItemDetails_Type:
    type: object
    properties:
      BulkItemStatus:
        $ref: '#/definitions/CodeName_Type'
      RejectionReason:
        type: string
    required:
    - BulkItemStatus
    - RejectionReason
  ContractDetails_Type:
    type: object
    properties:
      ContractId:
        type: integer
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      HijriStartDate:
        type: integer
      GregorianStartDate:
        type: string
      ContractPeriod:
        type: integer
      LaborerIdNo:
        type: integer
      LaborerName:
        type: string
      Occupation:
        $ref: '#/definitions/CodeName_Type'
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      Salary:
        type: number
      SalaryType:
        $ref: '#/definitions/CodeName_Type'
      SalaryFrequency:
        $ref: '#/definitions/CodeName_Type'
    required:
    - ContractId
    - ContractType
    - HijriStartDate
    - GregorianStartDate
    - ContractPeriod
    - LaborerIdNo
    - LaborerName
    - Occupation
    - JobTitle
    - Salary
    - SalaryType
    - SalaryFrequency
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
    required:
    - JobTitleAr
    - JobTitleEng
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: integer
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchcontractbulk:
    post:
      operationId: SearchContractBulk
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchContractBulkRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search Contract Bulk
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchContractBulkRq_MessageType'
        description: SearchContractBulkRq
        required: true
