swagger: "2.0"
info:
  title: SearchEstMgntRequest
  x-ibm-name: searchestmgntrequest
  version: 1.0.0
  description: This service is used to search on the establishment file request and
    get all CR, Owners, and activity information.
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-estabmanagement)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  SearchEstMgntRequestRq_MessageType:
    type: object
    properties:
      SearchEstMgntRequestRq:
        $ref: '#/definitions/SearchEstMgntRequestRq_Type'
  SearchEstMgntRequestRs_MessageType:
    type: object
    properties:
      SearchEstMgntRequestRs:
        $ref: '#/definitions/SearchEstMgntRequestRs_Type'
  SearchEstMgntRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchEstMgntRequestRq_BodyType'
  SearchEstMgntRequestRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: string
        default: "10104791918"
      LaborOfficeId:
        type: integer
        default: "345"
      SequenceNumber:
        type: integer
        default: "32434324"
      NationalNumber:
        type: string
        default: abc
      FileNumber:
        type: integer
        default: "5465"
  SearchEstMgntRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchEstMgntRequestRs_BodyType'
  SearchEstMgntRequestRs_BodyType:
    type: object
    properties:
      FileNumber:
        type: integer
      CRInformation:
        $ref: '#/definitions/CRInformation_Type'
      OwnerList:
        $ref: '#/definitions/OwnerList_Type'
      ActivityList:
        $ref: '#/definitions/ActivityList_Type'
      Status:
        $ref: '#/definitions/CodeName_Type'
      LocationList:
        $ref: '#/definitions/LocationList_Type'
      EstablishmentInformation:
        $ref: '#/definitions/EstablishmentInformation_Type'
      MainEstInfo:
        $ref: '#/definitions/MainEstInfo_Type'
      CreationDate:
        type: string
      FileType:
        $ref: '#/definitions/CodeName_Type'
    required:
    - FileNumber
    - CRInformation
    - OwnerList
    - ActivityList
    - Status
    - LocationList
    - EstablishmentInformation
    - MainEstInfo
    - CreationDate
    - FileType
  CRInformation_Type:
    type: object
    properties:
      MainCRNumber:
        type: string
      NationalNumber:
        type: string
      CRType:
        $ref: '#/definitions/CodeName_Type'
      CRIssueDate:
        $ref: '#/definitions/GregHijri_Type'
      CRExpiryDate:
        $ref: '#/definitions/GregHijri_Type'
      CRCity:
        $ref: '#/definitions/CodeName_Type'
      CRNameAR:
        type: string
      CRCapital:
        type: string
      CRLegalType:
        $ref: '#/definitions/CodeName_Type'
      CRStatus:
        $ref: '#/definitions/CodeName_Type'
      CRStatusDate:
        type: string
      CRStatusReason:
        type: string
      CRAddress:
        type: string
      CRPhoneNumber:
        type: string
      CRFaxNumber:
        type: string
      IsMain:
        type: string
      NationalityID:
        type: string
      NationalityName:
        type: string
      CRZipCode:
        type: string
      CRPOBOX:
        type: string
      CROfficeNumber:
        type: string
      CRStreet:
        type: string
      CRBuilding:
        type: integer
      CRRepresentative:
        $ref: '#/definitions/CRRepresentative_Type'
      'FiscalYearID ':
        type: integer
      FiscalYearName:
        type: string
    required:
    - MainCRNumber
    - NationalNumber
    - CRType
    - CRIssueDate
    - CRExpiryDate
    - CRNameAR
    - CRCapital
    - CRStatus
    - CRStatusDate
    - CRStatusReason
    - CRAddress
    - CRPhoneNumber
    - CRFaxNumber
    - IsMain
    - NationalityID
    - NationalityName
    - CRZipCode
    - CRPOBOX
    - CROfficeNumber
    - CRStreet
    - CRBuilding
    - CRRepresentative
    - 'FiscalYearID '
    - FiscalYearName
  CRRepresentative_Type:
    type: object
    properties:
      NationalityID:
        type: string
      NationalityName:
        type: string
      PartyID:
        type: integer
      PartyIDType:
        type: string
      MobileNumber:
        type: string
      'Email ':
        type: string
      BirthDate:
        type: string
    required:
    - NationalityID
    - NationalityName
    - PartyID
    - PartyIDType
    - MobileNumber
    - 'Email '
    - BirthDate
  OwnerList_Type:
    type: object
    properties:
      Owner:
        type: array
        items:
          $ref: '#/definitions/Owner_Type'
  Owner_Type:
    type: object
    properties:
      OwnerName:
        type: string
      OwnerId:
        $ref: '#/definitions/OwnerId_Type'
      PersonIdentifier:
        $ref: '#/definitions/PersonIdentifier_Type'
      PassportIdentifier:
        $ref: '#/definitions/PassportIdentifier_Type'
      PassportIssueDate:
        $ref: '#/definitions/GregHijri_Type'
      PassportExpiryDate:
        $ref: '#/definitions/GregHijri_Type'
      OwnerNationalityEN:
        type: string
      OwnerNationalityAr:
        type: string
      RelationType:
        type: string
      BirthDate:
        type: string
    required:
    - OwnerName
    - OwnerId
    - PersonIdentifier
    - PassportIdentifier
    - PassportIssueDate
    - PassportExpiryDate
    - OwnerNationalityEN
    - OwnerNationalityAr
    - RelationType
  OwnerId_Type:
    type: object
    properties:
      BorderNumber:
        type: string
      Code700:
        type: string
      CRNumber:
        type: string
    required:
    - BorderNumber
    - Code700
    - CRNumber
  PersonIdentifier_Type:
    type: object
    properties:
      NationalId:
        type: string
      IqamaNumber:
        type: string
    required:
    - NationalId
    - IqamaNumber
  PassportIdentifier_Type:
    type: object
    properties:
      PassportNumber:
        type: string
      PassportIssuePlaceName:
        type: string
    required:
    - PassportNumber
    - PassportIssuePlaceName
  GregHijri_Type:
    type: object
    properties:
      Hijri:
        type: integer
      Gregorian:
        type: string
    required:
    - Hijri
    - Gregorian
  ActivityList_Type:
    type: object
    properties:
      Activity:
        type: array
        items:
          $ref: '#/definitions/Activity_Type'
  Activity_Type:
    type: object
    properties:
      isICCode:
        type: string
      isICName:
        type: string
      RequiredLicence:
        $ref: '#/definitions/RequiredLicence_Type'
    required:
    - isICCode
    - isICName
  RequiredLicence_Type:
    type: object
    properties:
      Type:
        type: string
      Number:
        type: string
      Source:
        type: string
      StartDate:
        type: integer
      EndDate:
        type: integer
    required:
    - Type
    - Number
    - Source
    - StartDate
    - EndDate
  CodeName_Type:
    type: object
    properties:
      Code:
        type: string
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  LocationList_Type:
    type: object
    properties:
      Location:
        type: array
        items:
          $ref: '#/definitions/Location_Type'
  Location_Type:
    type: object
    properties:
      Address:
        $ref: '#/definitions/Address_Type'
      LocationName:
        type: string
      ActivityId:
        type: integer
      ContactInformation:
        $ref: '#/definitions/ContactInformation_Type'
    required:
    - Address
    - ActivityId
    - ContactInformation
  Address_Type:
    type: object
    properties:
      ZipCode:
        type: string
      POBOX:
        type: string
      BuildingNo:
        type: string
      StreetName:
        type: string
      City:
        $ref: '#/definitions/City_Type'
    required:
    - ZipCode
    - POBOX
    - BuildingNo
    - StreetName
    - City
  City_Type:
    type: object
    properties:
      CityID:
        type: integer
      CityName:
        type: string
    required:
    - CityID
    - CityName
  ContactInformation_Type:
    type: object
    properties:
      FirstName:
        type: string
      LastName:
        type: string
      MobileNumber:
        type: string
    required:
    - FirstName
    - LastName
    - MobileNumber
  EstablishmentInformation_Type:
    type: object
    properties:
      UnifiedNumber:
        type: string
      EstablishmentName:
        type: string
      EstablishmentNationality:
        type: string
      EstablishmentId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenenceNumber:
        type: integer
  MainEstInfo_Type:
    type: object
    properties:
      MainUNLaborOfficeId:
        type: integer
      MainUNSequenceNumber:
        type: integer
      'MainEstLaborOfficeId ':
        type: integer
      MainEstSequenceNumber:
        type: integer
      MainEstUnifiedNationalNumber:
        type: string
      MainEstablishmentName:
        type: string
      MainEstablishmentNationality:
        type: string
      MainOwnershipType:
        type: string
      MainOwner:
        $ref: '#/definitions/owner_Type'
      MainSevenHundredNumber:
        type: string
      MainLegalType:
        type: string
    required:
    - MainUNLaborOfficeId
    - MainUNSequenceNumber
    - MainEstSequenceNumber
    - MainEstUnifiedNationalNumber
    - MainEstablishmentName
    - MainEstablishmentNationality
    - MainOwnershipType
    - MainSevenHundredNumber
    - MainLegalType
  owner_Type:
    type: object
    properties:
      ID:
        type: string
      Name:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "200966842998"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SEMR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SEMR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "23432"
      IDNumber:
        type: integer
        default: "324324"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /srhestmgntreq:
    post:
      operationId: SearchEstMgntRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchEstMgntRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Check Added User  Eligibility
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchEstMgntRequestRq_MessageType'
        description: SearchEstMgntRequestRq
        required: true
