swagger: "2.0"
info:
  title: SearchRefunded
  x-ibm-name: searchrefunded
  version: 1.0.0
  description: SearchRefunded
schemes:
- https
basePath: /visa/visitvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-vstv-vvutilities2)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SearchRefundedRq_MessageType:
    type: object
    properties:
      SearchRefundedRq:
        $ref: '#/definitions/SearchRefundedRq_Type'
  SearchRefundedRs_MessageType:
    type: object
    properties:
      SearchRefundedRs:
        $ref: '#/definitions/SearchRefundedRs_Type'
  SearchRefundedRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchRefundedRq_BodyType'
  SearchRefundedRq_BodyType:
    type: object
    properties:
      StatusId:
        type: integer
        default: "0"
      PageSize:
        type: integer
        default: "1"
      PageIndex:
        type: integer
        default: "1"
  SearchRefundedRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SearchRefundedRs_BodyType'
  SearchRefundedRs_BodyType:
    type: object
    properties:
      Package_ID:
        type: integer
      LaborOfficeSequence:
        type: integer
      UserID:
        type: integer
      IDNumber:
        type: string
      PackageTypeID:
        type: integer
      StatusId:
        type: integer
      Package_Price:
        type: string
      Balance:
        type: integer
      RefundDate:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SR000001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SR000001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /searchrefunded:
    post:
      operationId: SearchRefunded
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchRefundedRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search Refunded
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchRefundedRq_MessageType'
        description: SearchRefundedRq
        required: true
