swagger: "2.0"
info:
  title: SearchEstabReqDetails
  x-ibm-name: searchestabreqdetails
  version: 1.0.0
  description: SearchEstabReqDetails
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-dashboard-profile)/estabmanagement/srhestreq
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SearchEstabReqDetailsRq_MessageType:
    type: object
    properties:
      SearchEstabReqDetailsRq:
        $ref: '#/definitions/SearchEstabReqDetailsRq_Type'
  SearchEstabReqDetailsRs_MessageType:
    type: object
    properties:
      SearchEstabReqDetailsRs:
        $ref: '#/definitions/SearchEstabReqDetailsRs_Type'
  SearchEstabReqDetailsRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SearchEstabReqDetailsRq_BodyType'
  SearchEstabReqDetailsRq_BodyType:
    type: object
    properties:
      EstablishmentId:
        type: integer
      RequestId:
        type: integer
      RequestTypeId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: string
      RequestNumber:
        type: string
  SearchEstabReqDetailsRs_Type:
    type: object
    properties:
      EstablishmentInfo:
        $ref: '#/definitions/EstablishmentInfo_Type'
      EstablishmentRequestsList:
        $ref: '#/definitions/EstablishmentRequestsList_Type'
      NitaqatInfo:
        $ref: '#/definitions/NitaqatInfo_Type'
      OwnersInfo:
        $ref: '#/definitions/OwnersInfo_Type'
      LicensesInfo:
        $ref: '#/definitions/Licenses_Type'
    required:
    - EstablishmentInfo
    - OwnersInfo
  EstablishmentRequestsList_Type:
    type: object
    properties:
      Request:
        $ref: '#/definitions/Request_Type'
  Request_Type:
    type: array
    items:
      $ref: '#/definitions/Request'
  Request:
    type: object
    properties:
      EstablishmentRequest:
        $ref: '#/definitions/EstablishmentRequest_Type'
      ChangeEstablishmentRequest:
        $ref: '#/definitions/ChangeEstablishmentRequest_Type'
      CloseEstablishmentRequest:
        $ref: '#/definitions/CloseEstablishmentRequest_Type'
      MirasEstablishmentRequest:
        $ref: '#/definitions/MirasEstablishmentRequest_Type'
  EstablishmentInfo_Type:
    type: object
    properties:
      EstablishmentId:
        type: integer
      RequestId:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      UNLaborOfficeId:
        type: integer
      UNSequenceNumber:
        type: integer
      EstablishmentName:
        type: string
      CRNumber:
        $ref: '#/definitions/Date_Type'
      CRIssueDate:
        $ref: '#/definitions/Date_Type'
      CRExpiryDate:
        type: integer
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      EstablishmentType:
        $ref: '#/definitions/CodeName_Type'
      ContactAddress:
        $ref: '#/definitions/ContactAddress_Type'
      UnifiedNumberId:
        type: integer
      NationalUnifiedNumber:
        type: string
      SevenHundredNumber:
        type: string
      Isic4Activity:
        $ref: '#/definitions/CodeName_Type'
      IsMain:
        type: integer
      Status:
        $ref: '#/definitions/CodeName_Type'
      ClosingDate:
        type: string
      CreationDate:
        type: string
    required:
    - EstablishmentId
    - RequestId
    - LaborOfficeId
    - SequenceNumber
    - UNLaborOfficeId
    - UNSequenceNumber
    - EstablishmentName
    - CRNumber
    - CRIssueDate
    - CRExpiryDate
    - Nationality
    - EstablishmentType
    - ContactAddress
    - UnifiedNumberId
    - NationalUnifiedNumber
    - SevenHundredNumber
    - Isic4Activity
    - IsMain
    - Status
    - ClosingDate
    - CreationDate
  EstablishmentRequest_Type:
    type: object
    properties:
      RequestId:
        type: integer
      RequestNumber:
        type: string
      EstablishmentId:
        type: integer
      Status:
        $ref: '#/definitions/CodeName_Type'
      RejectionReason:
        type: string
      RequestType:
        $ref: '#/definitions/CodeName_Type'
      CreationDate:
        type: string
      RequestorId:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      UNLaborOfficeId:
        type: integer
      UNSequenceNumber:
        type: integer
      EstablishmentName:
        type: string
      CRNumber:
        type: string
      CRIssuePlace:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      EstablishmentType:
        $ref: '#/definitions/CodeName_Type'
      ContactAddress:
        $ref: '#/definitions/ContactAddress_Type'
      NationalUnifiedNumber:
        type: string
      Isic4Activity:
        $ref: '#/definitions/CodeName_Type'
      EconomicActivity:
        $ref: '#/definitions/CodeName_Type'
      IsMain:
        type: integer
      MunicipalLicenseId:
        type: string
      OtherLicenseType:
        $ref: '#/definitions/CodeName_Type'
      OtherLicenseId:
        type: string
      OwnerId:
        type: string
    required:
    - RequestId
    - RequestNumber
    - EstablishmentId
    - Status
    - RejectionReason
    - RequestType
    - CreationDate
    - RequestorId
    - LaborOfficeId
    - SequenceNumber
    - UNLaborOfficeId
    - UNSequenceNumber
    - EstablishmentName
    - CRNumber
    - CRIssuePlace
    - Nationality
    - EstablishmentType
    - ContactAddress
    - NationalUnifiedNumber
    - Isic4Activity
    - EconomicActivity
    - IsMain
    - MunicipalLicenseId
    - OtherLicenseType
    - OtherLicenseId
    - OwnerId
  ChangeEstablishmentRequest_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      RequestId:
        type: integer
      EstablishmentId:
        type: integer
      Status:
        $ref: '#/definitions/CodeName_Type'
      RejectionReasonList:
        $ref: '#/definitions/RejectionReasonList_Type'
      RequestType:
        $ref: '#/definitions/CodeName_Type'
      CreationDate:
        type: string
      RequestorId:
        type: string
      RequestorName:
        type: string
      OfficeId:
        type: integer
      LOAgentId:
        type: string
      LOAgentName:
        type: string
      AgentAssignmentDate:
        type: string
      AgentApprovalDate:
        type: string
      AgentRejectionDate:
        type: string
      OldRequiedSaudLevel:
        type: string
      NewRequiredSaudLevel:
        type: string
      ChangeActivityReason:
        $ref: '#/definitions/CodeName_Type'
      ChangeActivityNote:
        type: string
      OldIsic4Activity:
        $ref: '#/definitions/CodeName_Type'
      OldEconomicActivity:
        $ref: '#/definitions/CodeName_Type'
      NewIsic4Activity:
        $ref: '#/definitions/CodeName_Type'
      NewEconomicActivity:
        $ref: '#/definitions/CodeName_Type'
      IsSaudLevelDecreased:
        type: integer
      PaymentReference:
        type: string
      IsEstablishingPeriodTerminated:
        type: integer
      IsRefundTierPaymentRefunded:
        type: integer
      TierPaymentReference:
        type: string
      RefundTierPaymentError:
        type: string
      OtherChangeActivityReasonText:
        type: string
      LicenseNumber:
        type: integer
      LicenseIssueDate:
        $ref: '#/definitions/Date_Type'
      LicenseExpiryDate:
        $ref: '#/definitions/Date_Type'
      attachment:
        $ref: '#/definitions/IDName_Type'
    required:
    - RequestNumber
    - RequestId
    - EstablishmentId
    - Status
    - RequestType
    - CreationDate
    - RequestorId
    - OldIsic4Activity
    - NewIsic4Activity
    - IsSaudLevelDecreased
    - PaymentReference
    - IsEstablishingPeriodTerminated
    - IsRefundTierPaymentRefunded
    - TierPaymentReference
    - RefundTierPaymentError
    - OtherChangeActivityReasonText
  CloseEstablishmentRequest_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      RequestId:
        type: integer
      EstablishmentId:
        type: integer
      Status:
        $ref: '#/definitions/CodeName_Type'
      RejectionReason:
        type: string
      RequestType:
        $ref: '#/definitions/CodeName_Type'
      CreationDate:
        type: string
      RequestorId:
        type: string
      ClosingDate:
        type: string
      TierPaymentReference:
        type: string
      RefundTierPaymentError:
        type: string
    required:
    - RequestNumber
    - RequestId
    - EstablishmentId
    - Status
    - RejectionReason
    - RequestType
    - CreationDate
    - RequestorId
    - ClosingDate
    - TierPaymentReference
    - RefundTierPaymentError
  MirasEstablishmentRequest_Type:
    type: object
    properties:
      RequestNumber:
        type: string
      RequestId:
        type: integer
      EstablishmentId:
        type: integer
      Status:
        $ref: '#/definitions/CodeName_Type'
      RejectionReason:
        type: string
      RequestType:
        $ref: '#/definitions/CodeName_Type'
      CreationDate:
        type: string
      RequestorId:
        type: string
      CRNumber:
        type: string
      NationalNumber:
        type: integer
      IsMain:
        type: integer
      MainCR:
        type: integer
      BusinessType:
        $ref: '#/definitions/CodeName_Type'
      Location:
        type: string
      CRName:
        type: string
      IssueDate:
        type: string
      ExpiryDate:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
      ZipCode:
        type: string
      POBOX:
        type: string
      City:
        $ref: '#/definitions/CodeName_Type'
      CRStreet:
        type: string
      CRBuilding:
        type: integer
      CROfficeNumber:
        type: integer
      FiscalYear:
        $ref: '#/definitions/IDName_Type'
      CRRepresentative:
        $ref: '#/definitions/CRRepresentative_Type'
      CRActivities:
        $ref: '#/definitions/CRActivities_Type'
    required:
    - RequestNumber
    - RequestId
    - EstablishmentId
    - Status
    - RejectionReason
    - RequestType
    - CreationDate
    - RequestorId
    - CRNumber
    - NationalNumber
    - IsMain
    - MainCR
    - BusinessType
    - Location
    - CRName
    - IssueDate
    - ExpiryDate
    - Nationality
    - ZipCode
    - POBOX
    - City
    - CRStreet
    - CRBuilding
    - CROfficeNumber
    - FiscalYear
    - CRRepresentative
    - CRActivities
  CRRepresentative_Type:
    type: object
    properties:
      Name:
        type: string
      IDNumber:
        type: integer
      IDType:
        type: string
      Birthdate:
        type: string
      Email:
        type: string
      MobileNumber:
        type: string
      Nationality:
        $ref: '#/definitions/CodeName_Type'
    required:
    - Name
    - IDNumber
    - IDType
    - Birthdate
    - Email
    - MobileNumber
    - Nationality
  CRActivities_Type:
    type: object
    properties:
      Isic4Activity:
        $ref: '#/definitions/IDName_Type'
    required:
    - Isic4Activity
  Date_Type:
    type: object
    properties:
      Hijri:
        type: integer
      Gregorian:
        type: string
    required:
    - Hijri
    - Gregorian
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
    required:
    - Code
    - NameAr
    - NameEn
  ContactAddress_Type:
    type: object
    properties:
      PersonFirstName:
        type: string
      PersonLastName:
        type: string
      PersonMobileNumber:
        type: string
      Email:
        type: string
      City:
        $ref: '#/definitions/CodeName_Type'
      ZipCode:
        type: string
      StreetName:
        type: string
      BuildingNo:
        type: integer
      District:
        type: string
      Coordinates:
        $ref: '#/definitions/Coordinates_Type'
    required:
    - PersonFirstName
    - PersonLastName
    - PersonMobileNumber
    - Email
    - City
    - ZipCode
    - StreetName
    - BuildingNo
    - District
    - Coordinates
  Coordinates_Type:
    type: object
    properties:
      Latitude:
        type: string
      Longitude:
        type: string
    required:
    - Latitude
    - Longitude
  IDName_Type:
    type: object
    properties:
      Id:
        type: integer
      Name:
        type: string
    required:
    - Id
    - Name
  NitaqatInfo_Type:
    type: object
    properties:
      Nitaq:
        $ref: '#/definitions/CodeName_Type'
      SaudizationLevel:
        type: integer
    required:
    - Nitaq
    - SaudizationLevel
  OwnersInfo_Type:
    type: object
    properties:
      Owner:
        $ref: '#/definitions/Owner_Type'
    required:
    - Owner
  Owner_Type:
    type: object
    properties:
      OwnerName:
        type: string
      IDNumber:
        type: integer
      OwnerTypeId:
        type: string
      Birthdate:
        type: string
      Email:
        type: string
      MobileNumber:
        type: string
      IsCRRepresentative:
        type: integer
      StreetName:
        type: string
      ZipCode:
        type: string
      BuildingNo:
        type: string
      Gender:
        $ref: '#/definitions/CodeName_Type'
      City:
        $ref: '#/definitions/CodeName_Type'
      RelationType:
        $ref: '#/definitions/CodeName_Type'
      Nationality:
        $ref: '#/definitions/CodeName_Type'
  Licenses_Type:
    type: object
    properties:
      LicenseType:
        $ref: '#/definitions/CodeName_Type'
      LicenseNumber:
        type: string
      LicenseName:
        type: string
      LicenseSource:
        type: string
      LicenseStatus:
        $ref: '#/definitions/CodeName_Type'
      LicenseIssueDate:
        $ref: '#/definitions/Date_Type'
      LicenseExpiryDate:
        $ref: '#/definitions/Date_Type'
      LicenseArea:
        type: integer
      LicenseAttachementId:
        type: string
    required:
    - LicenseNumber
    - LicenseName
    - LicenseSource
    - LicenseType
    - LicenseStatus
    - LicenseIssueDate
    - LicenseExpiryDate
    - LicenseArea
    - LicenseAttachementId
  RejectionReasonList_Type:
    type: object
    properties:
      RejectionReasonItem:
        type: array
        items:
          $ref: '#/definitions/RejectionReasonItem_Type'
  RejectionReasonItem_Type:
    type: object
    properties:
      RejectionReasonId:
        type: string
      RejectionReasonNameAr:
        type: string
      RejectionReasonNameEn:
        type: string
    required:
    - RejectionReasonId
    - RejectionReasonNameAr
    - RejectionReasonNameEn
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /srhestreq:
    post:
      operationId: SearchEstabReqDetails
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SearchEstabReqDetailsRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Search Estab Req Details
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SearchEstabReqDetailsRq_MessageType'
        description: SearchEstabReqDetailsRq
        required: true
