swagger: "2.0"
info:
  title: SendUNHSMS
  x-ibm-name: send-unh-sms
  version: 1.0.0
  description: This API sends the UNH sms
host: $(catalog.host)
schemes:
- https
basePath: /NotificationHubService
security:
- OAuth2.0: []
- clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: http://prow-notificationservices-smsliv-http-ace.apps.stg.qiwa-nonprod.local/external/NotificationHubService/SMSSend
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-prow-notificationservices-smsliv)/external/NotificationHubService/SMSSend
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  buffering: true
  application-authentication:
    certificate: false
  catalogs: {}
definitions:
  SmsRequest_MessageType:
    type: object
    properties:
      NotificationSmsRequest:
        $ref: '#/definitions/SmsInfoRq_Type'
  SmsResponse_MessageType:
    type: object
    properties:
      NotificationSmsResponse:
        $ref: '#/definitions/SmsInfoRs_Type'
  SmsInfoRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/RequestHeader_Type'
      Body:
        $ref: '#/definitions/SmsInfoRq_Body'
  SmsInfoRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ResponseHeader_Type'
      Body:
        $ref: '#/definitions/SmsInfoRs_Body'
  RequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
      DebugFlag:
        type: string
        default: 1
  ResponseHeader_Type:
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWRequestTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      MWResponseTime:
        type: string
        default: "2019-10-10T00:00:00.555Z"
      ServiceCode:
        type: string
        default: NPC00001
      DebugFlag:
        type: string
        default: 1
      ResponseStatus:
        $ref: '#/definitions/ResponseStatus'
      BackendError:
        $ref: '#/definitions/BackendError'
  ResponseStatus:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
  BackendError:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  SmsInfoRq_Body:
    type: object
    required:
    - SystemName
    - EventName
    - SMS
    properties:
      SystemName:
        type: number
      EventName:
        type: number
      SMS:
        type: array
        items:
          type: object
          properties:
            smsTo:
              type: string
              example: 966567876548
      Variables:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              example: ENO
            value:
              type: string
              example: 1000
  SmsInfoRs_Body:
    type: object
    properties:
      status:
        type: string
        example: Success
      Details:
        type: string
        example: SMS Sent successfully
      id:
        type: string
        example: 20
paths:
  /SMSSend:
    post:
      tags:
      - Send UNH sms
      description: Used to Send UNH sms
      operationId: sendunhsms
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SmsRequest_MessageType'
        description: smsinfoRq
        required: true
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SmsResponse_MessageType'
