swagger: "2.0"
info:
  title: SubmitSeasonalVisaRequest
  x-ibm-name: submitseasonalvisarequest
  version: 1.0.1
  description: This Service is used to submit a seasonal visa request with its details
    after the validation.
schemes:
- https
basePath: /visa/seasonalvisa
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-sese-seassubmits)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  SubmitSeasonalVisaRequestRq_MessageType:
    type: object
    properties:
      SubmitSeasonalVisaRequestRq:
        $ref: '#/definitions/SubmitSeasonalVisaRequestRq_Type'
  SubmitSeasonalVisaRequestRs_MessageType:
    type: object
    properties:
      SubmitSeasonalVisaRequestRs:
        $ref: '#/definitions/SubmitSeasonalVisaRequestRs_Type'
  SubmitSeasonalVisaRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitSeasonalVisaRequestRq_BodyType'
  SubmitSeasonalVisaRequestRq_BodyType:
    type: object
    properties:
      EstablishmentId:
        type: integer
      SequenceNumber:
        type: integer
      LaborOfficeId:
        type: integer
      EndorsementId:
        type: integer
      EstablishmentLocation:
        $ref: '#/definitions/EstablishmentLocation_Type'
      VisaDetailsList:
        $ref: '#/definitions/VisaDetailsList_Type'
      FirstName:
        type: string
      LastName:
        type: string
      Email:
        type: string
      RequesterMobileNumber:
        type: integer
    required:
    - SequenceNumber
    - LaborOfficeId
    - EndorsementId
    - FirstName
    - LastName
    - Email
    - RequesterMobileNumber
  VisaDetailsList_Type:
    type: object
    properties:
      VisaDetail:
        type: array
        items:
          $ref: '#/definitions/VisaDetail_Type'
  VisaDetail_Type:
    type: object
    properties:
      Gender:
        type: integer
      Job:
        type: integer
      Nationality:
        type: integer
      Origin:
        type: integer
      Religion:
        type: integer
      NumberOfVisas:
        type: integer
    required:
    - Gender
    - Job
    - Nationality
    - Origin
    - Religion
    - NumberOfVisas
  EstablishmentLocation_Type:
    type: object
    properties:
      Longitude:
        type: string
      Latitude:
        type: string
      City:
        type: string
      Area:
        type: string
      District:
        type: string
      Street:
        type: string
      BuildingNo:
        type: string
      AddressDescription:
        type: string
      POBox:
        type: string
      ZIPCode:
        type: string
      LocationMapUrl:
        type: string
    required:
    - City
    - Area
    - District
    - Street
    - BuildingNo
    - AddressDescription
    - POBox
    - ZIPCode
  SubmitSeasonalVisaRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitSeasonalVisaRequestRs_BodyType'
  SubmitSeasonalVisaRequestRs_BodyType:
    type: object
    properties:
      RequestNumber:
        type: string
      VisaList:
        $ref: '#/definitions/VisaList_Type'
      VisaOutGoingNumber:
        type: integer
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorsList_Type'
    required:
    - RequestNumber
    - VisaList
    - VisaOutGoingNumber
  VisaList_Type:
    type: object
    properties:
      Visa:
        $ref: '#/definitions/Visa_Type'
  Visa_Type:
    type: object
    properties:
      BorderNumber:
        type: integer
      Job:
        type: integer
      Nationality:
        type: integer
      Religion:
        type: integer
      Gender:
        type: integer
      Origin:
        type: integer
    required:
    - BorderNumber
    - Job
    - Nationality
    - Religion
    - Gender
    - Origin
  ValidationsErrorsList_Type:
    type: object
    properties:
      ValidationError:
        $ref: '#/definitions/ValidationError_Type'
  ValidationError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - ErrorCode
    - ArDescription
    - EnDescription
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /submitseasvisareq:
    post:
      operationId: SubmitSeasonalVisaRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitSeasonalVisaRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: SubmitSeasonalVisaRequest
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitSeasonalVisaRequestRq_MessageType'
        description: SubmitSeasonalVisaRequestRq
        required: true
