swagger: "2.0"
info:
  title: SubmitVisaExceptionRequest
  x-ibm-name: submitvisaexceptionrequest
  version: 1.0.0
  description: This service is used to create visa exception request with its details
    after the needed validations in exception system
schemes:
- https
basePath: /exceptions
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-exception)/exceptions/submitvisaexceptionrequest
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SubmitVisaExceptionRequestRq_MessageType:
    type: object
    properties:
      SubmitVisaExceptionRequestRq:
        $ref: '#/definitions/SubmitVisaExceptionRequestRq_Type'
  SubmitVisaExceptionRequestRs_MessageType:
    type: object
    properties:
      SubmitVisaExceptionRequestRs:
        $ref: '#/definitions/SubmitVisaExceptionRequestRs_Type'
  SubmitVisaExceptionRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitVisaExceptionRequestRq_BodyType'
  SubmitVisaExceptionRequestRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      VisaDetailsList:
        $ref: '#/definitions/VisaDetailsList_Type'
    required:
    - LaborOfficeId
    - SequenceNumber
    - VisaDetailsList
  VisaDetailsList_Type:
    type: object
    properties:
      VisaDetailsItem:
        type: array
        items:
          $ref: '#/definitions/VisaDetailsItem_Type'
    required:
    - VisaDetailsItem
  VisaDetailsItem_Type:
    type: object
    properties:
      GenderId:
        type: integer
      JobId:
        type: integer
      NationalityId:
        type: integer
      OriginId:
        type: integer
      ReligionId:
        type: integer
      NumberOfVisas:
        type: integer
    required:
    - GenderId
    - JobId
    - NationalityId
    - OriginId
    - ReligionId
    - NumberOfVisas
  SubmitVisaExceptionRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitVisaExceptionRequestRs_BodyType'
  SubmitVisaExceptionRequestRs_BodyType:
    type: object
    properties:
      VisaBordersDetailsList:
        $ref: '#/definitions/VisaBordersDetailsList_Type'
      RequestNumber:
        type: integer
      ExceptionVisaRequestId:
        type: integer
      VisaOutGoingNumber:
        type: integer
    required:
    - VisaBordersDetailsList
    - RequestNumber
    - ExceptionVisaRequestId
    - VisaOutGoingNumber
  VisaBordersDetailsList_Type:
    type: object
    properties:
      VisaBordersDetailsItem:
        type: array
        items:
          $ref: '#/definitions/VisaBordersDetailsItem_Type'
    required:
    - VisaBordersDetailsItem
  VisaBordersDetailsItem_Type:
    type: object
    properties:
      BorderNumber:
        type: integer
      JobId:
        type: integer
      NationalityId:
        type: integer
      ReligionId:
        type: integer
      GenderId:
        type: integer
      OriginId:
        type: integer
    required:
    - BorderNumber
    - JobId
    - NationalityId
    - ReligionId
    - GenderId
    - OriginId
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /submitvisaexceptionrequest:
    post:
      operationId: SubmitVisaExceptionRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitVisaExceptionRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Submit Visa Exception Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitVisaExceptionRequestRq_MessageType'
        description: SubmitVisaExceptionRequestRq
        required: true
