swagger: "2.0"
info:
  title: SubmitStandardPoliciesRequest
  x-ibm-name: submitstandardpoliciesrequest
  version: 1.0.0
  description: This service is used to create a standard policy request with its details.
schemes:
- https
basePath: /policies
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(cat-target-hostname)$(cat-target-url-policies)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SubmitStandardPoliciesRequestRq_MessageType:
    type: object
    properties:
      SubmitStandardPoliciesRequestRq:
        $ref: '#/definitions/SubmitStandardPoliciesRequestRq_Type'
  SubmitStandardPoliciesRequestRs_MessageType:
    type: object
    properties:
      SubmitStandardPoliciesRequestRs:
        $ref: '#/definitions/SubmitStandardPoliciesRequestRs_Type'
  SubmitStandardPoliciesRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitStandardPoliciesRequestRq_BodyType'
  SubmitStandardPoliciesRequestRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "1"
      SequenceNumber:
        type: integer
        default: "173744"
      StandardPolicyDetails:
        $ref: '#/definitions/StandardPolicyDetails_Type'
      RequesterName:
        type: string
        default: Manyam R
      IsAgreed:
        type: integer
        default: "0"
    required:
    - LaborOfficeId
    - IsAgreed
    - RequesterName
    - StandardPolicyDetails
    - SequenceNumber
  SubmitStandardPoliciesRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitStandardPoliciesRequestRs_BodyType'
  SubmitStandardPoliciesRequestRs_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
      RequesterName:
        type: string
      CreationDate:
        type: string
      ErrorList:
        type: string
    required:
    - RequesterName
    - RequestId
    - CreationDate
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SSPR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: SSPR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  StandardPolicyDetails_Type:
    type: object
    properties:
      WorkingHours:
        type: integer
        default: "8"
      RamadanWorkingHours:
        type: integer
        default: "6"
      OffDaysList:
        $ref: '#/definitions/OffDaysList_Type'
      AnnualVacationDays:
        type: integer
        default: "28"
      VacationAfter5Years:
        type: integer
        default: "35"
      DateType:
        type: integer
        default: "1"
    required:
    - WorkingHours
    - RamadanWorkingHours
    - AnnualVacationDays
    - VacationAfter5Years
    - DateType
  OffDaysList_Type:
    type: object
    properties:
      OffDaysItem:
        type: array
        items:
          $ref: '#/definitions/OffDaysItem_Type'
  OffDaysItem_Type:
    type: object
    properties:
      Days:
        type: integer
        default: "7"
    required:
    - Days
  ErrorList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: integer
      DescriptionAr:
        type: string
      DescriptionEn:
        type: string
    required:
    - ErrorCode
    - DescriptionAr
    - DescriptionEn
paths:
  /substandpolreq:
    post:
      operationId: SubmitStandardPoliciesRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitStandardPoliciesRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Submit Standard Policies Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitStandardPoliciesRequestRq_MessageType'
        description: SubmitStandardPoliciesRequestRq
        required: true
