swagger: "2.0"
info:
  title: SubmitWorkPermitRequest
  x-ibm-name: submitworkpermitrequest
  version: 1.0.1
  description: This service is used to submit a work permit request for several laborers
    under the same establishment.
schemes:
- https
basePath: /workpermit
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wp-subwpreq)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SubmitWorkPermitRequestRq_MessageType:
    type: object
    properties:
      SubmitWorkPermitRequestRq:
        $ref: '#/definitions/SubmitWorkPermitRequestRq_Type'
  SubmitWorkPermitRequestRs_MessageType:
    type: object
    properties:
      SubmitWorkPermitRequestRs:
        $ref: '#/definitions/SubmitWorkPermitRequestRs_Type'
  SubmitWorkPermitRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitWorkPermitRequestRq_BodyType'
  SubmitWorkPermitRequestRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
      UnifiedNumber:
        type: integer
      TotalFees:
        type: integer
      LaborersList:
        $ref: '#/definitions/LaborersList_Type'
    required:
    - LaborOfficeId
    - EstablishmentSequence
    - UnifiedNumber
    - TotalFees
    - LaborersList
  LaborersList_Type:
    type: object
    properties:
      Laborers:
        type: array
        items:
          $ref: '#/definitions/Laborers_Type'
    required:
    - Laborers
  Laborers_Type:
    type: object
    properties:
      LaborerId:
        type: integer
      LaborerIdType:
        type: integer
        enum:
        - 1
        - 2
      WPPeriod:
        type: integer
        enum:
        - 3
        - 6
        - 9
        - 12
    required:
    - LaborerId
    - LaborerIdType
    - WPPeriod
  SubmitWorkPermitRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitWorkPermitRequestRs_BodyType'
  SubmitWorkPermitRequestRs_BodyType:
    type: object
    properties:
      SadadNumber:
        type: string
      RequestRefernceNo:
        type: string
      WPRequestId:
        type: integer
      LaborerDetails:
        $ref: '#/definitions/LaborerDetails_Type'
      TotalWPFees:
        type: integer
      TotalFinancialCompensationFees:
        type: integer
      TotalCalculationFees:
        type: integer
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorsList_Type'
    required:
    - SadadNumber
    - RequestRefernceNo
    - WPRequestId
    - LaborerDetails
    - TotalWPFees
    - TotalFinancialCompensationFees
    - TotalCalculationFees
  LaborerDetails_Type:
    type: object
    properties:
      LaborerDetailsItem:
        type: array
        items:
          $ref: '#/definitions/LaborerDetailsItem_Type'
    required:
    - LaborerDetailsItem
  LaborerDetailsItem_Type:
    type: object
    properties:
      LaborerName:
        type: string
      CurrentWPStartDate:
        type: string
      CurrentWPExpiryDate:
        type: string
      WPType:
        type: integer
        enum:
        - 1
        - 2
      LaborerIdNo:
        type: integer
    required:
    - LaborerName
    - LaborerIdNo
    - CurrentWPStartDate
    - CurrentWPExpiryDate
    - WPType
  ValidationsErrorsList_Type:
    type: object
    properties:
      ValidationsError:
        type: array
        items:
          $ref: '#/definitions/ValidationsError_Type'
    required:
    - ValidationsError
  ValidationsError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - ErrorCode
    - ArDescription
    - EnDescription
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /submitwprequest:
    post:
      operationId: SubmitWorkPermitRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitWorkPermitRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Submit Work Permit Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitWorkPermitRequestRq_MessageType'
        description: SubmitWorkPermitRequestRq
        required: true
