swagger: "2.0"
info:
  title: SubmitStandardPolicyRequestLO
  x-ibm-name: submitstandardpolicyrequestlo
  version: 1.0.0
  description: This service is used to create a standard policy request with its details.
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: http://icp-proxy.qiwa.info:32287/qiwalo/substandpolreqlo
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  SubmitStandardPolicyRequestLORq_MessageType:
    type: object
    properties:
      SubmitStandardPolicyRequestLORq:
        $ref: '#/definitions/SubmitStandardPolicyRequestLORq_Type'
  SubmitStandardPolicyRequestLORs_MessageType:
    type: object
    properties:
      SubmitStandardPolicyRequestLORs:
        $ref: '#/definitions/SubmitStandardPolicyRequestLORs_Type'
  SubmitStandardPolicyRequestLORq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/SubmitStandardPolicyRequestLORq_BodyType'
  SubmitStandardPolicyRequestLORq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      StandardPolicyDetails:
        $ref: '#/definitions/StandardPolicyDetails_Type'
      EstablishmentContactDetails:
        $ref: '#/definitions/EstablishmentContactDetails_Type'
      RequesterName:
        type: string
      IsAgreed:
        type: integer
    required:
    - LaborOfficeId
    - IsAgreed
    - RequesterName
    - StandardPolicyDetails
    - EstablishmentContactDetails
    - SequenceNumber
  SubmitStandardPolicyRequestLORs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/SubmitStandardPolicyRequestLORs_BodyType'
  SubmitStandardPolicyRequestLORs_BodyType:
    type: object
    properties:
      RequestId:
        type: integer
      RequesterName:
        type: string
      CreationDate:
        type: string
      ErrorList:
        $ref: '#/definitions/ErrorItem_Type'
    required:
    - RequesterName
    - RequestId
    - CreationDate
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  EstablishmentContactDetails_Type:
    type: object
    properties:
      ContactName:
        type: string
      ContactEmail:
        type: string
      ContactPhoneNumber:
        type: string
      ContactCity:
        type: integer
  StandardPolicyDetails_Type:
    type: object
    properties:
      WorkingHours:
        type: integer
      RamadanWorkingHours:
        type: integer
      OffDaysList:
        $ref: '#/definitions/OffDaysList_Type'
      AnnualVacationDays:
        type: integer
      VacationAfter5Years:
        type: integer
      DateType:
        type: integer
    required:
    - WorkingHours
    - RamadanWorkingHours
    - AnnualVacationDays
    - VacationAfter5Years
    - DateType
  OffDaysList_Type:
    type: object
    properties:
      OffDaysItem:
        type: array
        items:
          $ref: '#/definitions/OffDaysItem_Type'
  OffDaysItem_Type:
    type: object
    properties:
      Days:
        type: integer
    required:
    - Days
  ErrorList_Type:
    type: object
    properties:
      ErrorItem:
        type: array
        items:
          $ref: '#/definitions/ErrorItem_Type'
  ErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: integer
      DescriptionAr:
        type: string
      DescriptionEn:
        type: string
    required:
    - ErrorCode
    - DescriptionAr
    - DescriptionEn
paths:
  /substandpolreqlo:
    post:
      operationId: SubmitStandardPolicyRequestLO
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/SubmitStandardPolicyRequestLORs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Submit Standard Policies Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitStandardPolicyRequestLORq_MessageType'
        description: SubmitStandardPolicyRequestLORq
        required: true
