swagger: "2.0"
info:
  title: UpdateEstLocationDetailsLO
  x-ibm-name: updateestlocationdetailslo
  version: 1.0.0
  description: UpdateEstLocationDetailsLO
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-locations)/qiwalo/updateestlocdetailslo
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  UpdateEstLocationDetailsLORq_MessageType:
    type: object
    properties:
      UpdateEstLocationDetailsLORq:
        $ref: '#/definitions/UpdateEstLocationDetailsLORq_Type'
  UpdateEstLocationDetailsLORs_MessageType:
    type: object
    properties:
      UpdateEstLocationDetailsLORs:
        $ref: '#/definitions/UpdateEstLocationDetailsLORs_Type'
  UpdateEstLocationDetailsLORq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/UpdateEstLocationDetailsLORq_BodyType'
  UpdateEstLocationDetailsLORq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      IsUpdate:
        type: integer
      LocationId:
        type: integer
      LocationName:
        type: string
      LocationDescription:
        type: string
      LocationURL:
        type: string
      MunicipalLicenseId:
        type: string
      BuildingNo:
        type: integer
      ZipCode:
        type: integer
      City:
        type: string
      StreetName:
        type: string
      LocationCoordinates:
        $ref: '#/definitions/Location_type'
      isMain:
        type: integer
      AdditionalNo:
        type: integer
      ShortAddress:
        type: string
      isRotated:
        type: integer
      LaborerId:
        type: integer
      ActivityDetails:
        $ref: '#/definitions/Activity_type'
  Location_type:
    type: object
    properties:
      Longitude:
        type: string
      Latitude:
        type: string
  Activity_type:
    type: object
    properties:
      MainActivity:
        $ref: '#/definitions/ID_type'
      SubActivities:
        type: string
  ID_type:
    type: object
    properties:
      ID:
        type: string
      NAme:
        type: string
  UpdateEstLocationDetailsLORs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/UpdateEstLocationDetailsLORs_BodyType'
  UpdateEstLocationDetailsLORs_BodyType:
    type: object
    properties: {}
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /updateestlocdetailslo:
    post:
      operationId: UpdateEstLocationDetailsLO
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/UpdateEstLocationDetailsLORs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: To get all laborers under the establishment
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/UpdateEstLocationDetailsLORq_MessageType'
        description: UpdateEstLocationDetailsLORq
        required: true
