swagger: "2.0"
info:
  title: UpdateMolBusiness
  description: This service is used to update MOL business through NIC
  x-ibm-name: updatemolbusiness
  version: 1.0.0
schemes:
- https
basePath: /external/v1
security:
- OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
paths:
  /updateMolBusiness:
    parameters:
    - $ref: '#/parameters/X-IBM-Client-Id'
    post:
      tags:
      - updateMolBusiness
      description: This service is used to update MOL business through NIC
      operationId: updateMolBusiness
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/RequestBody'
        description: Request body
        required: true
      responses:
        "200":
          $ref: '#/responses/Response200'
        "400":
          $ref: '#/responses/Response400'
        "401":
          $ref: '#/responses/Response401'
        "403":
          $ref: '#/responses/Response403'
        "404":
          $ref: '#/responses/Response404'
        "408":
          $ref: '#/responses/Response408'
        "409":
          $ref: '#/responses/Response409'
        "429":
          $ref: '#/responses/Response429'
        "500":
          $ref: '#/responses/Response500'
        "501":
          $ref: '#/responses/Response501'
        "503":
          $ref: '#/responses/Response503'
        "510":
          $ref: '#/responses/Response510'
definitions:
  RequestBody:
    type: object
    description: this is the request body
    properties:
      locationCode:
        type: integer
        example: 1
      companyNumber:
        type: integer
        example: 1589
      companyName:
        type: string
        example: company name
      ncnNumber:
        type: integer
        example: 1
      ncnLaborOffice:
        type: integer
        example: 8
      laborOfficeCompany:
        type: integer
        example: 1
      companyNationality:
        type: integer
        example: 1
      company700:
        type: number
        example: 1
      ownerID:
        type: number
        example: 1
      createDateH:
        type: integer
        example: 1
      mainBranchFlag:
        type: integer
        example: 1
      mCompanyActivity:
        type: integer
        example: 1
      sCompanyActivity:
        type: integer
        example: 1
      commercialRegistryNo:
        type: string
        example: commercialRegistryNo
      commercialRegistryIssuePlace:
        type: string
        example: commercialRegistryIssuePlace
      municipalityPermissionNo:
        type: string
        example: municipalityPermissionNo
      otherLicenseType:
        type: integer
        example: 1
      otherLicenseNo:
        type: string
        example: otherLicenseNo
      cityCode:
        type: integer
        example: 1
      telephone1:
        type: integer
        example: 1
      telephone2:
        type: integer
        example: 1
      fax:
        type: integer
        example: 1
      companyStatus:
        type: integer
        example: 1
      operatorID:
        type: number
        example: 1
      clientIPAddress:
        type: string
        example: clientIPAddress
      lang:
        type: string
        example: lang
    required:
    - operatorID
    - clientIPAddress
  ResponseModel:
    type: object
    description: This response object returned by the add or update operation
    properties:
      message:
        type: string
        example: message
      company700:
        type: number
        example: 1.2
      companyNumber:
        type: integer
        example: 1
      laborOfficeCompany:
        type: integer
        example: 1
      requestTimestamp:
        type: string
        example: requestTimestamp
      responseTimestamp:
        type: string
        example: responseTimestamp
  ErrorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    properties:
      errorCode:
        type: string
        example: EXXXX000
      errorMessage:
        $ref: '#/definitions/LocaleDataModel'
  LocaleDataModel:
    type: object
    additionalProperties:
      type: string
    example:
      en-US: English Value
      ar-SA: Arabic Value
parameters:
  X-IBM-Client-Id:
    in: header
    name: X-IBM-Client-Id
    description: Client id issued by security server
    required: true
    type: string
  X-IBM-Client-Secret:
    in: header
    name: X-IBM-Client-Secret
    description: Client secret issued by security server
    required: true
    type: string
  X-Request-Id:
    in: header
    name: X-Request-Id
    description: X-Request-Id returned in the response header
    required: false
    type: string
responses:
  Response200:
    description: Response
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ResponseModel'
  Response400:
    description: The request was rejected by the server due to malformed syntax. Bad
      Request.
  Response401:
    description: The request could not be completed due to lack of valid credentials.
      Authentication.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response403:
    description: The request could not be completed because it is not authorized.
      Authorization
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response404:
    description: The server has not found anything matching the Request-URI.
  Response408:
    description: The client did not produce a request within the time that the server
      was prepared to wait.
  Response409:
    description: The request could not be completed due to a conflict with the current
      state of the resource. Usually business validation errors will be returned in
      the body
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response429:
    description: The request was sent too many times in a given amount of time
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
  Response500:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response501:
    description: The server does not support the functionality required and does not
      recognize the request
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response503:
    description: The server encountered an unexpected condition which prevented it
      from fulfilling the request.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
  Response510:
    description: Extensions to the request are required for the server to fulfil it.
    headers:
      X-Request-Id:
        type: string
        description: Trace Id for the request.
    schema:
      $ref: '#/definitions/ErrorModel'
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: Service_Config
        source: "var apim = require('apim');\r\nvar cfg={\r\n    \"serviceCode\" :
          \"CSC00002\",\r\n    \"channelId\" : \"Qiwa\",\r\n    \"requestName\" :
          \"UpdateMolBusinessRq\",\r\n    \"responseName\": \"UpdateMolBusinessRs\",\r\n
          \   \"errorMap\" :{\r\n        \"ESBSCHEMA\" : {\"code\" :400, \"msg\":\"Invalid
          Request\"}\r\n    }\r\n    \r\n};\r\napim.setvariable('cfg',cfg);"
    - gatewayscript:
        version: 2.0.0
        title: Prepare_Request
        source: "var apim = require('apim');\r\nvar millisecondsvalue = \"\"+(new
          Date()).getTime();\r\nvar dt = new Date();\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          OperatorId=apim.getvariable('message.headers.Operator-Id');\r\nvar appname
          = apim.getvariable('client.app.name');\r\n\r\nvar appcReq = {\r\n    [cfg.requestName]:{\r\n
          \       \"Header\" : {\r\n            \"TransactionId\" : millisecondsvalue,\r\n
          \           \"ChannelId\": cfg.channelId,\r\n            \"SessionId\":
          apim.getvariable('message.headers.X-Request-Id'),\r\n            \"RequestTime\"
          : formatDate(dt),\r\n            \"ServiceCode\": cfg.serviceCode,\r\n            \"DebugFlag\":
          \"1\",\r\n            \"UserInfo\": {\r\n                \"UserId\": apim.getvariable('message.headers.UserId'),\r\n
          \               \"IDNumber\": apim.getvariable('message.headers.IDNumber')\t\t\t\t\r\n
          \           },\r\n            \"UDF\": {\r\n                \"KeyValueArr\":
          [\r\n                    {\r\n                        \"key\": \"Product\",\r\n
          \                       \"value\": \"NIC\"\r\n                    },\r\n
          \                   {\r\n                        \"key\": \"Client\",\r\n
          \                       \"value\": appname\r\n                    }\r\n
          \               ]\r\n            }\t\t\t\r\n        },\r\n        \"Body\"
          : apim.getvariable('message.body')\r\n            \r\n    }\r\n};\r\n\r\nif
          (typeof OperatorId !== 'undefined')\r\n    appcReq[cfg.requestName].Header.UserInfo
          = {\r\n        \"IDNumber\" : OperatorId\r\n    };\r\nsession.output.write(appcReq);\r\napim.output('application/json');\r\n\r\n\r\nfunction
          formatDate(d)\r\n{\r\n    //get the month\r\n    var month = d.getMonth();\r\n
          \   //get the day\r\n    //convert day to string\r\n    var day = d.getDate().toString();\r\n
          \   //get the year\r\n    var year = d.getFullYear();\r\n    var hour =
          d.getHours().toString();\r\n    var minitue = d.getMinutes().toString();\r\n
          \   var second = d.getSeconds().toString();\r\n    var millisecond = d.getMilliseconds().toString();\r\n
          \   //pull the last two digits of the year\r\n    year = year.toString();\r\n
          \   \r\n    //increment month by 1 since it is 0 indexed\r\n    //converts
          month to a string\r\n    month = (month + 1).toString();\r\n\r\n    //if
          month is 1-9 pad right with a 0 for two digits\r\n    if (month.length ===
          1)\r\n        month = \"0\" + month;\r\n\r\n    //if day is between 1-9
          pad right with a 0 for two digits\r\n    if (day.length === 1)\r\n        day
          = \"0\" + day;\r\n\r\n    if (hour.length === 1)\r\n        hour = \"0\"
          + hour;\r\n\r\n    if (minitue.length === 1)\r\n        minitue = \"0\"
          + minitue;\r\n\r\n    if (second.length === 1)\r\n        second = \"0\"
          + second;\r\n        \r\n    if (millisecond.length == 1)\r\n        millisecond
          = \"00\" + millisecond;\r\n        \r\n    if (millisecond.length == 2)\r\n
          \       millisecond = \"0\" + millisecond;\r\n    \r\n    \r\n\r\n    //return
          the string \"MMddyy\"\r\n    return year+\"-\"+month+\"-\"+day+\" \"+hour
          + \":\" + minitue + \":\" + second+\".\"+millisecond;\r\n}"
    - invoke:
        version: 2.2.0
        title: Invoke
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        timeout: 60
        verb: POST
        chunked-uploads: true
        persistent-connection: true
        http-version: HTTP/1.1
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        graphql-send-type: detect
        websocket-upgrade: false
        target-url: $(ace-tip-nic)/external/updatemolbusiness
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "var apim = require('apim');\r\napim.output('application/json');\r\nvar
          message = apim.getvariable('message.body');\r\nvar cfg = apim.getvariable('cfg');\r\nvar
          Header = message[cfg.responseName].Header;\r\nvar TransactionId = Header.TransactionId;\r\nvar
          ChannelId = Header.ChannelId;\r\nvar RequestTime = Header.RequestTime;\r\nvar
          SessionId = Header.SessionId;\r\nvar MWRequestTime = Header.MWRequestTime;\r\nvar
          MWResponseTime = Header.MWResponseTime;\r\nvar status = Header.ResponseStatus.Status;\r\nvar
          code = Header.ResponseStatus.Code;\r\napim.setvariable('message.headers.Transaction-Id',TransactionId,'add');\r\napim.setvariable('message.headers.Channel-Id',ChannelId,'add');\r\nif
          (RequestTime !== 'undefined')\r\napim.setvariable('message.headers.RequestTime',RequestTime,'add');\r\nif
          (SessionId !== 'undefined')\r\napim.setvariable('message.headers.X-Request-Id',SessionId,'add');\r\nif
          (MWRequestTime !== 'undefined')\r\napim.setvariable('message.headers.MWRequestTime',MWRequestTime,'add');\r\nif
          (MWResponseTime !== 'undefined')\r\napim.setvariable('message.headers.MWResponseTime',MWResponseTime,'add');\r\napim.setvariable('message.headers.Response-Status',status,'add');\r\napim.setvariable('message.headers.Response-Code',code,'add');"
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($header("Response-Status") = 'SUCCESS'))
          execute:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Response
              source: "var apim = require('apim');\r\nvar message = apim.getvariable('message.body');\r\nvar
                cfg = apim.getvariable('cfg');\r\nvar body = message[cfg.responseName].Body;\r\nsession.output.write(body);\r\napim.output('application/json');"
        - otherwise:
          - gatewayscript:
              version: 2.0.0
              title: Prepare_Error
              source: "var apim = require('apim');\r\nvar message = apim.getvariable('message.body');\r\nvar
                cfg = apim.getvariable('cfg');          \r\nvar error = {\r\n  \"errorCode\":
                message[cfg.responseName].Header.ResponseStatus.Code,\r\n  \"errorMessage\":
                {\r\n    \"en-US\": message[cfg.responseName].Header.ResponseStatus.EnglishMsg,\r\n
                \   \"ar-SA\": message[cfg.responseName].Header.ResponseStatus.ArabicMsg\r\n
                \ }\r\n};\r\n\r\nvar httperror=0;\r\nif(cfg.errorMap){\r\n    if(cfg.errorMap[error.errorCode]){\r\n
                \      httperror = cfg.errorMap[error.errorCode].code;\r\n       \r\n
                \      //var errmgs = cfg.errorMap[error.ErrorResponse.Code].msg;\r\n
                \      //var details = error.ErrorResponse.Code + ':' + error.ErrorResponse.EnglishMsg;\r\n
                \      //apim.error('ERROR',httperror,errmgs,details);\r\n    }\r\n}\r\nif(httperror
                == 0){\r\n   httperror = 409;\r\n   // apim.error('ERROR',400,'Bad
                Request','Invalid request');\r\n}\r\napim.setvariable('message.status.code',httperror,'set');\r\n\r\nsession.output.write(error);\r\napim.output('application/json');"
