swagger: "2.0"
info:
  title: ValidateChangeActivityEligibility
  x-ibm-name: validatechangeactivityeligibility
  version: 1.0.0
  description: ValidateChangeActivityEligibility Service
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-change-estab-activity)/estabmanagement/validateestact
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  ValidateChgActEligibilityRq_MessageType:
    type: object
    properties:
      ValidateChgActEligibilityRq:
        $ref: '#/definitions/ValidateChgActEligibilityRq_Type'
  ValidateChgActEligibilityRs_MessageType:
    type: object
    properties:
      ValidateChgActEligibilityRs:
        $ref: '#/definitions/ValidateChgActEligibilityRs_Type'
  ValidateChgActEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateChgActEligibilityRq_BodyType'
  ValidateChgActEligibilityRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      NewIsic4ActivityId:
        type: integer
      NewRequiredSaudLevel:
        type: number
      CurrentRequiredSaudLevel:
        type: number
  ValidateChgActEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateChgActEligibilityRs_BodyType'
  ValidateChgActEligibilityRs_BodyType:
    type: object
    properties:
      IsSaudLevelDecreased:
        type: integer
      CurrentConditionType:
        type: integer
      NewConditionType:
        type: integer
      OldIsic4Activity:
        $ref: '#/definitions/IDName_Type'
      OldEconomicActivity:
        $ref: '#/definitions/IDName_Type'
      NewIsic4Activity:
        $ref: '#/definitions/IDName_Type'
      NewEconomicActivity:
        $ref: '#/definitions/IDName_Type'
      CurrentRequiredSaudLevel:
        type: integer
      NewRequiredSaudLevel:
        type: integer
      IsRefundAndTerminateAllowed:
        type: integer
      EstablishmentDetails:
        $ref: '#/definitions/EstablishmentDetails_Type'
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          type: string
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
  IDName_Type:
    type: object
    properties:
      Id:
        type: integer
      Name:
        type: string
  EstablishmentDetails_Type:
    type: object
    properties:
      EstablishmentId:
        type: integer
      EstablishmentName:
        type: string
      EstablishmentType:
        type: integer
      EstablishmentNationality:
        type: integer
      IsMain:
        type: integer
      NationalUnifiedNumber:
        type: string
      EstablishmentSize:
        type: string
      NitaqatLevel:
        type: string
      UNLaborOfficeId:
        type: integer
      UNSequenceNumber:
        type: integer
      OwnerId:
        type: string
      CRIssueDateGregorian:
        type: string
      CRExpiryDateGregorian:
        type: string
paths:
  /validateestact:
    post:
      operationId: ValidateChgActEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateChgActEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Create New Contract
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateChgActEligibilityRq_MessageType'
        description: ValidateChgActEligibilityRq
        required: true
