swagger: "2.0"
info:
  title: ValidateChangeSponsorRequestLO
  x-ibm-name: validatechangesponsorrequestlo
  version: 1.0.0
  description: ValidateChangeSponsorRequestLO
schemes:
- https
basePath: /qiwalo
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-lbro-lo-employee-transfer)/qiwalo/validatecsrequestlo
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  ValidateChangeSponsorRequestLORq_MessageType:
    type: object
    properties:
      ValidateChangeSponsorRequestLORq:
        $ref: '#/definitions/ValidateChangeSponsorRequestLORq_Type'
  ValidateChangeSponsorRequestLORs_MessageType:
    type: object
    properties:
      ValidateChangeSponsorRequestLORs:
        $ref: '#/definitions/ValidateChangeSponsorRequestLORs_Type'
  ValidateChangeSponsorRequestLORq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateChangeSponsorRequestLORq_BodyType'
  ValidateChangeSponsorRequestLORq_BodyType:
    type: object
    properties:
      DestinationLaborOfficeId:
        type: integer
      DestinationSequenceNumber:
        type: integer
      LaborersNationalitiesList:
        $ref: '#/definitions/LaborersNationalitiesList_Type'
      ValidationLevel:
        type: integer
      ServiceCode:
        type: string
    required:
    - DestinationLaborOfficeId
    - DestinationSequenceNumber
  LaborersNationalitiesList_Type:
    type: object
    properties:
      LaborersNationalitiesItem:
        type: array
        items:
          $ref: '#/definitions/LaborersNationalitiesItem_Type'
  LaborersNationalitiesItem_Type:
    type: object
    properties:
      Nationality:
        type: integer
      NumberOfLaborers:
        type: integer
    required:
    - Nationality
    - NumberOfLaborers
  ValidateChangeSponsorRequestLORs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateChangeSponsorRequestLORs_BodyType'
  ValidateChangeSponsorRequestLORs_BodyType:
    type: object
    properties:
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorsList_Type'
      Balance:
        $ref: '#/definitions/Balance_Type'
      DestinationEntityId:
        type: string
      DestinationsEstablishmentId:
        type: string
      EstablishmentConditionsType:
        type: integer
      TierId:
        type: integer
      SizeId:
        type: integer
      SubEconomicActivityId:
        type: integer
  ValidationsErrorsList_Type:
    type: object
    properties:
      ValidationError:
        type: array
        items:
          $ref: '#/definitions/ValidationErrorItem_Type'
  ValidationErrorItem_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - ErrorCode
    - ArDescription
    - EnDescription
  Balance_Type:
    type: object
    properties:
      AvailableBalance:
        type: integer
      BalanceType:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /validatecsrequestlo:
    post:
      operationId: ValidateChangeSponsorRequestLO
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateChangeSponsorRequestLORs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Validate Change Sponsor Request In LO
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateChangeSponsorRequestLORq_MessageType'
        description: ValidateChangeSponsorRequestLORq
        required: true
