swagger: "2.0"
info:
  title: ValidateVisitVisaRequest
  x-ibm-name: validatevisitvisarequest
  version: 1.0.0
  description: This service is used to validate the visit visa request by calling
    several services.
schemes:
- https
basePath: /visa/visitvisa
security:
- clientIdHeader: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientIdHeader:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-vstv-vvvalidates)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  ValidateVisitVisaRequestRq_MessageType:
    type: object
    properties:
      ValidateVisitVisaRequestRq:
        $ref: '#/definitions/ValidateVisitVisaRequestRq_Type'
  ValidateVisitVisaRequestRs_MessageType:
    type: object
    properties:
      ValidateVisitVisaRequestRs:
        $ref: '#/definitions/ValidateVisitVisaRequestRs_Type'
  ValidateVisitVisaRequestRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateVisitVisaRequestRq_BodyType'
  ValidateVisitVisaRequestRq_BodyType:
    type: object
    properties:
      EstablishmentID:
        type: integer
      EstablishmentSequence:
        type: integer
      LaborOfficeID:
        type: integer
      ValidationLevel:
        type: integer
      VisaDetailsList:
        $ref: '#/definitions/VisaDetailsList_Type'
    required:
    - EstablishmentSequence
    - LaborOfficeID
    - ValidationLevel
  VisaDetailsList_Type:
    type: object
    properties:
      VisaDetail:
        type: array
        items:
          $ref: '#/definitions/VisaDetail_Type'
    required:
    - VisaDetail
  VisaDetail_Type:
    type: object
    properties:
      Gender:
        type: integer
      Job:
        type: integer
      Nationality:
        type: integer
      Origin:
        type: integer
      Religion:
        type: integer
      NumberOfVisas:
        type: integer
    required:
    - Gender
    - Job
    - Nationality
    - Origin
    - Religion
    - NumberOfVisas
  ValidateVisitVisaRequestRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateVisitVisaRequestRs_BodyType'
  ValidateVisitVisaRequestRs_BodyType:
    type: object
    properties:
      EntityID:
        type: string
      Balance:
        type: integer
      EstablishmentID:
        type: integer
      UnifiedNationalNo:
        type: integer
      OwnerId:
        type: integer
      EstablishmentTypeId:
        type: integer
      SevenHundredNo:
        type: integer
      UseUnifiedNationalNoFlag:
        type: integer
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorList_Type'
  ValidationsErrorList_Type:
    type: object
    properties:
      ValidationError:
        type: array
        items:
          $ref: '#/definitions/ValidationError_Type'
    required:
    - ValidationError
  ValidationError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - ErrorCode
    - ArDescription
    - EnDescription
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /validatevisitvisarequest:
    post:
      operationId: ValidateVisitVisaRequest
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateVisitVisaRequestRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Validate Visit Visa Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateVisitVisaRequestRq_MessageType'
        description: ValidateVisitVisaRequestRq
        required: true
