swagger: "2.0"
info:
  title: ValidateCrSwap
  x-ibm-name: validatecrswap
  version: 1.0.0
  description: To check the validity of CR Swap Transfer Ownership for Companies
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-transfer-ownership)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
        persistent-connection: true
    catch: []
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  ValidateCrSwapRq_MessageType:
    type: object
    properties:
      ValidateCrSwapRq:
        $ref: '#/definitions/ValidateCrSwapRq_Type'
  ValidateCrSwapRs_MessageType:
    type: object
    properties:
      ValidateCrSwapRs:
        $ref: '#/definitions/ValidateCrSwapRs_Type'
  ValidateCrSwapRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateCrSwapRq_BodyType'
  ValidateCrSwapRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: string
      isMain:
        type: integer
      MainCR:
        type: string
      NewOwnerID:
        type: string
      NewOwnerBirthDate:
        type: string
  ValidateCrSwapRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateCrSwapRs_BodyType'
  ValidateCrSwapRs_BodyType:
    type: object
    properties:
      NewUnifiedFlag:
        type: integer
      OpenEstabCode:
        type: integer
      lastEstablishment:
        type: integer
      MainUnifiedNumberId:
        type: integer
      UpdateValidity:
        type: integer
      CRDetails:
        $ref: '#/definitions/CRDetails_Type'
      CompanyDetails:
        $ref: '#/definitions/CompanyDetails_Type'
  CompanyDetails_Type:
    type: object
    properties:
      EstablishmentId:
        type: integer
      Company700:
        type: integer
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      CompanyName:
        type: string
      CompanyNationality:
        type: integer
      CompanyStatus:
        type: integer
      CurrentBusinessType:
        type: integer
      isMain:
        type: integer
      NewMainUNLaborOfficeId:
        type: integer
      NewMainUNSequenceNumber:
        type: integer
      OldOwnerId:
        type: integer
      OldUnifiedId:
        type: string
      OldUNSequenceNumber:
        type: integer
      OldUNLaborOfficeId:
        type: integer
      Isic4ActivityId:
        type: integer
      EstablishmentCity:
        type: integer
      OwnerCity:
        type: integer
      CurrentBusinessTypeMCI:
        type: integer
      CurrentBusinessTypeMCIAr:
        type: string
      CurrentBusinessTypeMCIEn:
        type: string
      CurrentMainCRNumber:
        type: string
  CRDetails_Type:
    type: object
    properties:
      MCIBusinessType:
        type: integer
      CRLocationCode:
        type: string
      CRLocationNameAr:
        type: string
      CRName:
        type: string
      issueDate:
        type: string
      CRExpiryDate:
        type: string
      CRNationality:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /transferownership/validatecrswap:
    post:
      operationId: validatecrswap
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateCrSwapRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: To check the validity of CR Swap Transfer Ownership for Companies
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateCrSwapRq_MessageType'
        description: ValidateCrSwapRq
        required: true
