swagger: "2.0"
info:
  title: ValidateVisasEstablishmentEligibility
  x-ibm-name: validatevisasestablishmenteligibility
  version: 1.0.0
  description: ValidateVisasEstablishmentEligibility
schemes:
- https
basePath: /common
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmnv-commonvisautilites)/common/validatevisasestablishmenteligibility
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
definitions:
  ValidateVisasEstablishmentEligibilityRq_MessageType:
    type: object
    properties:
      ValidateVisasEstablishmentEligibilityRq:
        $ref: '#/definitions/ValidateVisasEstablishmentEligibilityRq_Type'
  ValidateVisasEstablishmentEligibilityRs_MessageType:
    type: object
    properties:
      ValidateVisasEstablishmentEligibilityRs:
        $ref: '#/definitions/ValidateVisasEstablishmentEligibilityRs_Type'
  ValidateVisasEstablishmentEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateVisasEstablishmentEligibilityRq_BodyType'
  ValidateVisasEstablishmentEligibilityRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      EstablishmentSequence:
        type: integer
    required:
    - LaborOfficeId
    - EstablishmentSequence
  ValidateVisasEstablishmentEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateVisasEstablishmentEligibilityRs_BodyType'
  ValidateVisasEstablishmentEligibilityRs_BodyType:
    type: object
    properties:
      CommonVisaEligibility:
        $ref: '#/definitions/ValidationsErrorsList_Type'
      WorkVisa:
        $ref: '#/definitions/WorkVisa_Type'
      VisitVisa:
        $ref: '#/definitions/ValidationsErrorsList_Type'
      SeasonalVisa:
        $ref: '#/definitions/ValidationsErrorsList_Type'
  WorkVisa_Type:
    type: object
    properties:
      VisaType:
        type: integer
      EligibleForExceptional:
        type: integer
      ExceptionalErrorsList:
        $ref: '#/definitions/ValidationsErrorsList_Type'
      ValidationsErrorsList:
        $ref: '#/definitions/ValidationsErrorsList_Type'
  ValidationsErrorsList_Type:
    type: object
    properties:
      ValidationError:
        type: array
        items:
          $ref: '#/definitions/ValidationError_Type'
  ValidationError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ArDescription:
        type: string
      EnDescription:
        type: string
    required:
    - ErrorCode
    - ArDescription
    - EnDescription
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /validatevisasestablishmenteligibility:
    post:
      operationId: ValidateVisasEstablishmentEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateVisasEstablishmentEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Validate visas establishments eligibility Request
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateVisasEstablishmentEligibilityRq_MessageType'
        description: ValidateVisasEstablishmentEligibilityRq
        required: true
