swagger: "2.0"
info:
  title: ValidateOpenEstablishmentEligibility
  x-ibm-name: validateopenestablishmenteligibility
  version: 1.0.0
  description: Validate Open Establishment Eligibility
schemes:
- https
basePath: /estabmanagement
security:
- clientId: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-open-file-with-cr)/estabmanagement/valopenestelig
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
definitions:
  ValidateOpenEstEligibilityRq_MessageType:
    type: object
    properties:
      ValidateOpenEstEligibilityRq:
        $ref: '#/definitions/ValidateOpenEstEligibilityRq_Type'
  ValidateOpenEstEligibilityRs_MessageType:
    type: object
    properties:
      ValidateOpenEstEligibilityRs:
        $ref: '#/definitions/ValidateOpenEstEligibilityRs_Type'
  ValidateOpenEstEligibilityRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateOpenEstEligibilityRq_BodyType'
  ValidateOpenEstEligibilityRq_BodyType:
    type: object
    properties:
      CRNumber:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      AddEstablishmentFlag:
        type: integer
  ValidateOpenEstEligibilityRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateOpenEstEligibilityRs_BodyType'
  ValidateOpenEstEligibilityRs_BodyType:
    type: object
    properties:
      CRInfo:
        $ref: '#/definitions/CRInfo_Type'
      CROwnersList:
        $ref: '#/definitions/CROwnersList_type'
      MainEstDetails:
        $ref: '#/definitions/MainEstDetails_Type'
      IsSameNitaqat:
        type: integer
      Message:
        type: integer
  CRInfo_Type:
    type: object
    properties:
      CRNumber:
        type: integer
      CRName:
        type: string
      CRNationality:
        type: string
      IsMainCR:
        type: boolean
      MainCRNumber:
        type: integer
      CRBusinessType:
        $ref: '#/definitions/CodeName_Type'
      CRActivities:
        type: string
      NationalNumber:
        type: integer
      CRIssueDate:
        $ref: '#/definitions/Date_Type'
      CRExpiryDate:
        $ref: '#/definitions/Date_Type'
      CRLocation:
        $ref: '#/definitions/CodeName_Type'
      CRStatus:
        type: string
      CRCapital:
        type: integer
      CompanyPaidCapital:
        type: integer
      CompanyShareCount:
        type: integer
      FiscalDateType:
        $ref: '#/definitions/FiscalDateType_type'
      CRIsic4Activities:
        $ref: '#/definitions/CRIsic4Activities_Type'
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
  Date_Type:
    type: object
    properties:
      Hijri:
        type: string
      Gregorian:
        type: string
  FiscalDateType_type:
    type: object
    properties:
      FiscalDateTypeID:
        type: integer
      FiscalDateTypeName:
        type: string
      FiscalEndDay:
        type: integer
      FiscalEndMonth:
        type: integer
  CROwnersList_type:
    type: array
    items:
      type: object
    properties:
      CROwner:
        $ref: '#/definitions/CROwner_Type'
  CRIsic4Activities_Type:
    type: array
    items:
      type: object
    properties:
      Isic4Activity:
        $ref: '#/definitions/IDName_Type'
  CROwner_Type:
    type: object
    properties:
      PK_OwnerId:
        type: integer
      OwnerName:
        $ref: '#/definitions/Name_Type'
      OwnerRelation:
        $ref: '#/definitions/CodeName_Type'
      OwnerNationality:
        $ref: '#/definitions/CodeName_Type'
      OwnerId:
        type: integer
      OwnerIdType:
        type: string
      OwnerBirthDate:
        type: string
      OwnerPercint:
        type: integer
      OwnerGross:
        type: integer
      OwnerShareCount:
        type: integer
      OwnerEmail:
        type: string
      OwnerMobile:
        type: integer
      OwnerIdExpiryDate:
        type: string
      OwneGender:
        $ref: '#/definitions/CodeName_Type'
      OwnerOrigin:
        type: string
      OwnerStreet:
        type: string
      OwnerZipCode:
        type: string
      OwnerBuildingNo:
        type: string
      OwnerCity:
        $ref: '#/definitions/CodeName_Type'
      OwnerDistrict:
        type: string
  MainEstDetails_Type:
    type: object
    properties:
      MainUNEstablishmentId:
        type: integer
      MainUNLaborOfficeId:
        type: integer
      MainUNSequenceNumber:
        type: integer
      MainEstablishmentId:
        type: integer
      MainEstLaborOfficeId:
        type: integer
      MainEstSequenceNumber:
        type: integer
      MainUnifiedNationalNumber:
        type: string
      MainEstablishmentName:
        type: string
      MainEstablishmentNationality:
        type: string
      MainOwnershipType:
        type: string
      MainOwner:
        $ref: '#/definitions/IDName_Type'
      MainSevenHundredNumber:
        type: string
      MainLegalType:
        type: string
      MainIsic4ActivityId:
        type: string
      IsHRSD:
        type: integer
      CRNumber:
        type: string
      MainCRNumber:
        type: string
      Licenses:
        $ref: '#/definitions/Licenses_Type'
      Status:
        type: integer
      IsMain:
        type: integer
  IDName_Type:
    type: object
    properties:
      Id:
        type: integer
      Name:
        type: string
  Name_Type:
    type: object
    properties:
      FullName:
        type: string
      FirstName:
        type: string
      SecondName:
        type: string
      ThirdName:
        type: string
      LastName:
        type: string
  Licenses_Type:
    type: array
    items:
      type: object
    properties:
      License:
        $ref: '#/definitions/License_Type'
  License_Type:
    type: object
    properties:
      LicenseCode:
        type: integer
      LicenseNumber:
        type: string
      LicenseSource:
        type: string
      LicenseIssueDate:
        type: string
      LicenseExpiryDate:
        type: string
      AttachementId:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: string
      IDNumber:
        type: string
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /valopenestelig:
    post:
      operationId: ValidateOpenEstablishmentEligibility
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateOpenEstEligibilityRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: Validate Open Establishment Eligibility
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateOpenEstEligibilityRq_MessageType'
        description: ValidateOpenEstEligibilityRq
        required: true
