swagger: "2.0"
info:
  title: Validate Certificate
  x-ibm-name: validate-certificate
  version: 1.0.0
  description: This service is used to retrieve the different Certificates details
    Saudi Certificate, Debit Certificate, Salary Certificate
schemes:
- https
basePath: /estabmanagement/transferownership
security:
- clientID: []
  clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cmpm-debt-certificate)/estabmanagement/transferownership/ValidateCertificate
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  ValidateCertificateRq_MessageType:
    type: object
    properties:
      ValidateCertificateRq:
        $ref: '#/definitions/ValidateCertificateRq_Type'
  ValidateCertificateRs_MessageType:
    type: object
    properties:
      ValidateCertificateRs:
        $ref: '#/definitions/ValidateCertificateRs_Type'
  ValidateCertificateRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateCertificateRq_BodyType'
  ValidateCertificateRq_BodyType:
    type: object
    properties:
      Certificatetype:
        type: integer
      CertificateNumber:
        type: string
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentId:
        type: integer
      UserId:
        type: integer
      IDNumber:
        type: integer
      NationalUnifiedNumber:
        type: integer
      CertStatusId:
        type: integer
      RenewalStartDate:
        type: string
      PageSize:
        type: integer
      PageIndex:
        type: integer
      LaborerIdNo:
        type: integer
      RequestId:
        type: integer
      StatusId:
        type: integer
      LaborerName:
        type: string
      RequestDateFrom:
        type: string
      RequestDateTo:
        type: string
      StartDateFrom:
        type: string
      StartDateTo:
        type: string
      CertificateTypeId:
        type: integer
      SortBy:
        type: integer
    required:
    - Certificatetype
    - PageSize
    - PageIndex
  ValidateCertificateRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateCertificateRs_BodyType'
  ValidateCertificateRs_BodyType:
    type: object
    properties:
      SoudiCertDetailslist:
        $ref: '#/definitions/SoudiCertDetailslist_Type'
      DebitCertDetailslist:
        $ref: '#/definitions/DebitCertDetailslist_Type'
      SalaryCertDetailslist:
        $ref: '#/definitions/SalaryCertDetailslist_Type'
  SoudiCertDetailslist_Type:
    type: object
    properties:
      TotalRecordsCount:
        type: integer
      SCDetailsList:
        $ref: '#/definitions/SCDetailsList_Type'
    required:
    - TotalRecordsCount
    - SCDetailsList
  SCDetailsList_Type:
    type: object
    properties:
      SCDetailsItem:
        $ref: '#/definitions/SCDetailsItem_Type'
  SCDetailsItem_Type:
    type: object
    properties:
      CertificateNumber:
        type: string
      NationalUnifiedNumber:
        type: integer
      SaudiCertIssueDate:
        type: string
      SaudiCertExpiryDate:
        type: string
      SaudiCertStatus:
        $ref: '#/definitions/SaudiCertStatus_Type'
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EstablishmentName:
        type: string
      CRNumber:
        type: integer
      RequesterIdNo:
        type: integer
      RequesterUserId:
        type: integer
      RenewalStartDate:
        type: string
    required:
    - CertificateNumber
    - NationalUnifiedNumber
    - SaudiCertIssueDate
    - SaudiCertExpiryDate
    - SaudiCertStatus
    - LaborOfficeId
    - SequenceNumber
    - EstablishmentName
    - CRNumber
  SaudiCertStatus_Type:
    type: object
    properties:
      SaudiCertStatusId:
        type: integer
      SaudiCertStatusEn:
        type: string
      SaudiCertStatusAr:
        type: string
  DebitCertDetailslist_Type:
    type: object
    properties:
      CertificateIssueDate:
        type: string
      ValidUntil:
        type: string
      EstablishmentName:
        type: string
      CRNumber:
        type: string
      NationalUnifiedNumber:
        type: string
      ViolationsDetail:
        $ref: '#/definitions/ViolationDetails_Type'
      CasesDetail:
        $ref: '#/definitions/CaseDetails_Type'
      DebtCertStatusId:
        type: integer
      TotalRecordsCount:
        type: integer
    required:
    - CertificateIssueDate
    - ValidUntil
    - EstablishmentName
    - CRNumber
    - NationalUnifiedNumber
    - ViolationsDetail
    - CasesDetail
    - DebtCertStatusId
    - TotalRecordsCount
  ViolationDetails_Type:
    type: object
    properties:
      ViolationsList:
        $ref: '#/definitions/Violation_Type'
      TotalActiveViolations:
        type: integer
      PenaltyAmount:
        type: integer
    required:
    - TotalActiveViolations
  Violation_Type:
    type: object
    properties:
      iban:
        type: string
      ReasonsForViolation:
        type: string
      ViolationRegistered:
        type: string
      ViolationNotRegistered:
        type: string
      ObjectionNumber:
        type: string
      ObjectionStatus:
        type: string
      EstablishmentOwnerComments:
        type: string
      IsEmployerOnSite:
        type: string
      EstablishmentLocation:
        type: string
      ResponsiblePersonName:
        type: string
      Attachment:
        type: string
      sadadIssuedDate:
        type: string
      sadadStatus:
        type: string
      sadadDueDate:
        type: string
      sadadNumber:
        type: string
      violationCode:
        type: string
      penaltyAmount:
        type: string
      violationUniqueId:
        type: string
      violationDescription:
        type: string
      violationApprovedDate:
        type: string
      inspectorComments:
        type: string
      coordinates:
        type: string
  CaseDetails_Type:
    type: object
    properties:
      CasesList:
        type: string
      TotalActiveCases:
        type: integer
    required:
    - TotalActiveCases
  SalaryCertDetailslist_Type:
    type: object
    properties:
      TotalRecordsCount:
        type: integer
      RequestDetailsList:
        $ref: '#/definitions/RequestDetailsList_Type'
      PageSize:
        type: integer
      PageIndex:
        type: integer
  RequestDetailsList_Type:
    type: object
    properties:
      RequestDetails:
        $ref: '#/definitions/RequestDetails_Type'
  RequestDetails_Type:
    type: object
    properties:
      RequestId:
        type: integer
      EstablishmentName:
        type: string
      JobTitle:
        $ref: '#/definitions/JobTitle_Type'
      Status:
        $ref: '#/definitions/Status_Type'
      SCCreationDate:
        type: string
      RequestCreationDate:
        type: string
      SCExpiryDate:
        type: string
      CertificateType:
        $ref: '#/definitions/CertificateType_Type'
      AddressedTo:
        $ref: '#/definitions/AddressedTo_Type'
      CertificateStatus:
        $ref: '#/definitions/CertificateStatus_Type'
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      LaborerIdNo:
        type: integer
      EntityName:
        type: string
      Language:
        $ref: '#/definitions/Language_Type'
      LaborerName:
        type: string
      ServiceStartDate:
        type: string
      Nationality:
        $ref: '#/definitions/Nationality_Type'
      Bank:
        $ref: '#/definitions/Bank_Type'
      Embassy:
        $ref: '#/definitions/Embassy_Type'
      Job:
        $ref: '#/definitions/Job_Type'
      TotalSalary:
        type: number
      MainSalary:
        type: number
      Allowances:
        $ref: '#/definitions/Allowances_Type'
      ContractType:
        $ref: '#/definitions/CodeName_Type'
      ContractDuration:
        $ref: '#/definitions/CodeName_Type'
      ContractExpiryDate:
        $ref: '#/definitions/HGDate_Type'
      ContractStartDate:
        $ref: '#/definitions/HGDate_Type'
      ContractRenewalStatus:
        $ref: '#/definitions/CodeName_Type'
      ContractStatus:
        $ref: '#/definitions/CodeName_Type'
      ContractId:
        type: integer
      ExpiryReason:
        type: string
      CertificateId:
        type: string
      RejectionReason:
        type: string
      HasContract:
        type: integer
      SalaryFrequency:
        $ref: '#/definitions/CodeName_Type'
      SalaryTypeId:
        type: integer
      AdditionalAllowancesList:
        $ref: '#/definitions/AdditionalAllowancesList_Type'
      EstablishmentUser:
        type: string
  JobTitle_Type:
    type: object
    properties:
      JobTitleAr:
        type: string
      JobTitleEng:
        type: string
  Status_Type:
    type: object
    properties:
      StatusId:
        type: integer
      StatusAr:
        type: string
      StatusEng:
        type: string
  CertificateType_Type:
    type: object
    properties:
      CertificateTypeId:
        type: integer
      CertificateTypeAr:
        type: string
      CertificateTypeEn:
        type: string
  CertificateStatus_Type:
    type: object
    properties:
      CertificateStatusId:
        type: integer
      CertificateStatusAr:
        type: string
      CertificateStatusEn:
        type: string
  AddressedTo_Type:
    type: object
    properties:
      AddressedToId:
        type: integer
      AddressedToAr:
        type: string
      AddressedToEn:
        type: string
  Language_Type:
    type: object
    properties:
      LanguageId:
        type: integer
      LanguageAr:
        type: string
      LanguageEn:
        type: string
  Nationality_Type:
    type: object
    properties:
      NationalityId:
        type: integer
      NationalityAr:
        type: string
      NationalityEn:
        type: string
  Bank_Type:
    type: object
    properties:
      BankId:
        type: integer
      BankAr:
        type: string
      BankEn:
        type: string
  Embassy_Type:
    type: object
    properties:
      EmbassyId:
        type: integer
      EmbassyAr:
        type: string
      EmbassyEn:
        type: string
  Job_Type:
    type: object
    properties:
      JobId:
        type: integer
      JobAr:
        type: string
      JobEn:
        type: string
  Allowances_Type:
    type: object
    properties:
      AllowancesItem:
        $ref: '#/definitions/KeyValue_Type'
  KeyValue_Type:
    type: object
    properties:
      Key:
        type: string
      Value:
        type: string
      MonthlyAllowance:
        type: number
  CodeName_Type:
    type: object
    properties:
      Code:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
  HGDate_Type:
    type: object
    properties:
      Hijri:
        type: integer
      Greogrian:
        type: string
  AdditionalAllowancesList_Type:
    type: object
    properties:
      AdditionalAllowances:
        $ref: '#/definitions/AdditionalAllowances_Type'
  AdditionalAllowances_Type:
    type: object
    properties:
      BenefitNameAr:
        type: string
      BenefitNameEn:
        type: string
      Frequency:
        $ref: '#/definitions/CodeName_Type'
      AmountType:
        $ref: '#/definitions/CodeName_Type'
      Amount:
        type: number
      MonthlyAdditionalAmount:
        type: number
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /ValidateCertificate:
    post:
      operationId: ValidateCertificate
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateCertificateRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: ValidateCertificate
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ValidateCertificateRq_MessageType'
        description: This service is used to update CR capital details as received
          from MCI.
        required: true
