swagger: "2.0"
info:
  title: ValidateEmployeeWage V2
  version: 1.0.0
  description: This service is used to validate the occupation.
  x-ibm-name: validateemployeewage-v2
basePath: /contractmanagement/v2
consumes:
- application/json
produces:
- application/json
paths:
  /valempwage:
    post:
      operationId: ValidateEmployeeWage
      description: ValidateEmployeeWage
      parameters:
      - name: body
        in: body
        description: ValidateEmployeeWageRq
        required: true
        schema:
          $ref: '#/definitions/ValidateEmployeeWageRq_MessageType'
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ValidateEmployeeWageRs_MessageType'
definitions:
  ValidateEmployeeWageRq_MessageType:
    type: object
    properties:
      ValidateEmployeeWageRq:
        $ref: '#/definitions/ValidateEmployeeWageRq_Type'
  ValidateEmployeeWageRs_MessageType:
    type: object
    properties:
      ValidateEmployeeWageRs:
        $ref: '#/definitions/ValidateEmployeeWageRs_Type'
  ValidateEmployeeWageRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/ValidateEmployeeWageRq_BodyType'
  ValidateEmployeeWageRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
      SequenceNumber:
        type: integer
      EmployeeIdNo:
        type: integer
      ContractId:
        type: integer
      NewFinancialDetails:
        $ref: '#/definitions/FinancialDetails_Type'
    required:
    - LaborOfficeId
    - SequenceNumber
    - EmployeeIdNo
    - ContractId
    - NewFinancialDetails
  FinancialDetails_Type:
    type: object
    properties:
      BasicSalary:
        type: string
      HousingAllowance:
        type: string
      TransportationAllowance:
        type: string
    required:
    - BasicSalary
  ValidateEmployeeWageRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/ValidateEmployeeWageRs_BodyType'
  ValidateEmployeeWageRs_BodyType:
    type: object
    properties:
      CurrentBasicSalary:
        type: string
      GOSIBasicSalary:
        type: string
      CurrentTotalSalary:
        type: string
      GOSITotalSalary:
        type: string
      NewTotalSalary:
        type: string
      OtherAllowances:
        type: string
      EstablishmentId:
        type: integer
      UnifiedNationalNumber:
        type: integer
      LaborerMobileNumber:
        type: string
      LaborerEmail:
        type: string
      NationalityId:
        type: integer
      SalaryTypeId:
        type: integer
      SalaryFrequencyId:
        type: integer
      CurrentAllowancesList:
        $ref: '#/definitions/Allowances_Type'
    required:
    - NewTotalSalary
    - OtherAllowances
    - EstablishmentId
    - UnifiedNationalNumber
    - LaborerMobileNumber
    - LaborerEmail
    - NationalityId
    - SalaryTypeId
    - SalaryFrequencyId
    - CurrentAllowancesList
  Allowances_Type:
    type: object
    properties:
      AllowancesItem:
        type: array
        items:
          $ref: '#/definitions/AllowancesItem_Type'
        minItems: 1
    required:
    - AllowancesItem
  AllowancesItem_Type:
    type: object
    properties:
      AllowanceType:
        type: integer
      NameAr:
        type: string
      NameEn:
        type: string
      Frequency:
        type: integer
      IsProvidedByEstablishment:
        type: integer
      AmountType:
        type: integer
      Amount:
        type: string
    required:
    - AllowanceType
    - NameAr
    - NameEn
    - Frequency
    - IsProvidedByEstablishment
    - AmountType
    - Amount
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-cntmv2-conbulkwages)/contractmanagement/valempwage
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: allowlist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
schemes:
- https
securityDefinitions:
  clientId:
    type: apiKey
    x-key-type: client_id
    name: X-IBM-Client-Id
    in: header
  Oauth2.0:
    type: oauth2
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    flow: application
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
security:
- clientId: []
  Oauth2.0:
  - IntegrationScope
