swagger: "2.0"
info:
  title: WPSCreateComplianceCertificateBySBC
  description: This api creates the compliance certificate by sbc
  x-ibm-name: wpscreatecompliancecertificatebysbc
  version: 1.0.0
schemes:
- https
basePath: /qiwa/v2
security:
- ClientSecret: []
  OAuth2.0:
  - IntegrationScope
  clientIdHeader: []
securityDefinitions:
  ClientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientIdHeader:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
paths:
  /WPSCreateComplianceCertificateBySBC:
    post:
      operationId: WPSCreateComplianceCertificateBySBC
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/WPSCreateComplianceCertificateBySBCRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: WPSCreateComplianceCertificateBySBC
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/WPSCreateComplianceCertificateBySBCRq_MessageType'
        description: WPSCreateComplianceCertificateBySBCRq
        required: true
      - name: X-IBM-Client-Id
        in: header
        required: true
        type: string
      - name: X-IBM-Client-Secret
        in: header
        required: true
        type: string
definitions:
  WPSCreateComplianceCertificateBySBCRq_MessageType:
    type: object
    properties:
      WPSCreateComplianceCertificateBySBCRq:
        $ref: '#/definitions/WPSCreateComplianceCertificateBySBCRq_Type'
  WPSCreateComplianceCertificateBySBCRs_MessageType:
    type: object
    properties:
      WPSCreateComplianceCertificateBySBCRs:
        $ref: '#/definitions/WPSCreateComplianceCertificateBySBCRs_Type'
  WPSCreateComplianceCertificateBySBCRq_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/WPSCreateComplianceCertificateBySBCRq_BodyType'
  WPSCreateComplianceCertificateBySBCRq_BodyType:
    type: object
    properties:
      SevenHundredNumber:
        type: integer
      EstablishmentNumber:
        type: string
      EstablishmentUserID:
        type: string
    required:
    - EstablishmentUserID
  WPSCreateComplianceCertificateBySBCRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/WPSCreateComplianceCertificateBySBCRs_BodyType'
  WPSCreateComplianceCertificateBySBCRs_BodyType:
    type: object
    properties:
      CertificateID:
        type: string
      CertificateIssueDate:
        type: string
      CertificateExpiryDate:
        type: string
      CertificateStatusEn:
        type: string
      CertificateStatusAr:
        type: string
      EstablishmentName:
        type: string
      EstablishmentFileNumber:
        type: string
      EstablishmentCRNumber:
        type: integer
      EstablishmentUnifiedNumber:
        type: integer
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
      ChannelId:
        type: string
      SessionId:
        type: string
      RequestTime:
        type: string
      MWRequestTime:
        type: string
      MWResponseTime:
        type: string
      ServiceCode:
        type: string
      DebugFlag:
        type: integer
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
      IDNumber:
        type: integer
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(ace-wps-wagesprotectionsystem)/WPSCreateComplianceCertificateBySBC
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
    - gatewayscript:
        version: 2.0.0
        title: Set Header
        source: "var apim = require('apim');\nvar Response = apim.getvariable('message.body');\nvar
          statusCode = Response.WPSCreateComplianceCertificateBySBCRs.Header.ResponseStatus.Code
          ;\n\n\nif(statusCode == 'ESBSCHEMA' || statusCode == 'E0000004' || statusCode
          == 'E0001203' || statusCode == 'E0001202' \n|| statusCode == 'E0001201'
          \ || statusCode == 'E0001200' ){\n    var code = 400\n    apim.setvariable('message.status.code',code,'set');\n}\nelse
          if(statusCode == 'E0000034' || statusCode == 'E0000046' || statusCode ==
          'E0000047' || statusCode == 'E0000048' ||statusCode == 'E0001287' ){\n    var
          code = 401\n    apim.setvariable('message.status.code',code,'set');\n}\nelse
          if(statusCode == '99999999' || statusCode == 'E0001567'){\n    var code
          = 500\n    apim.setvariable('message.status.code',code,'set');\n}\nelse
          if(statusCode == '00000000'){\n    var code = 200\n    apim.setvariable('message.status.code',code,'set');\n}else{\n
          \     var code = 409\n    apim.setvariable('message.status.code',code,'set');\n}\n"
    finally: []
  properties:
    target-url:
      value: http://wps-wagesprotectionsystem-http-ace.apps.stg.qiwa-nonprod.local/WPSCreateComplianceCertificateBySBC
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
