swagger: "2.0"
info:
  title: WPSUnifiedComplianceRateValue
  x-ibm-name: wpsunifiedcomplianceratevalue
  version: 1.0.0
  description: This API calculates the Unified Compliance Rate value from the data
    sent by GOSI_ComplianceRate API and send back to user.
schemes:
- https
basePath: /qiwa/v2
security:
- OAuth2.0:
  - IntegrationScope
  clientId: []
  clientSecret: []
securityDefinitions:
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  OAuth2.0:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: takamol-native-oauth-porvider
    tokenUrl: https://$(catalog.url)/takamol-oauth/oauth2/token
    scopes:
      IntegrationScope: This scope for all integration services in Takamol
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: 2.0.0
        title: invoke
        header-control:
          type: blocklist
          values:
          - ^X-IBM-Client-Id$
        parameter-control:
          type: blocklist
          values: []
        timeout: 60
        verb: keep
        stop-on-error:
        - OperationError
        - SOAPError
        - ConnectionError
        target-url: $(ace-wps-wagesprotectionsystem)/qiwawps/WPSUnifiedComplianceRateValue
        persistent-connection: true
        inject-proxy-headers: true
    - gatewayscript:
        version: 2.0.0
        title: Set_Headers
        source: "var apim = require('apim');\nvar Response = apim.getvariable('message.body');\nvar
          statusCode = Response.WPSUnifiedComplianceRateValueRs.Header.ResponseStatus.Code
          ;\n\n\nif(statusCode == 'ESBSCHEMA' || statusCode == 'E0000004' || statusCode
          == 'E0001203' || statusCode == 'E0001202' \n|| statusCode == 'E0001201'
          \ || statusCode == 'E0001200' ){\n    var code = 400\n    apim.setvariable('message.status.code',code,'set');\n}\nelse
          if(statusCode == 'E0000034' || statusCode == 'E0000046' || statusCode ==
          'E0000047' || statusCode == 'E0000048' ||statusCode == 'E0001287' ){\n    var
          code = 401\n    apim.setvariable('message.status.code',code,'set');\n}\nelse
          if(statusCode == '99999999' || statusCode == 'E0001567'){\n    var code
          = 500\n    apim.setvariable('message.status.code',code,'set');\n}\nelse
          if(statusCode == '00000000'){\n    var code = 200\n    apim.setvariable('message.status.code',code,'set');\n}else{\n
          \     var code = 409\n    apim.setvariable('message.status.code',code,'set');\n}\n"
    catch:
    - default:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
          - set: message.status.code
            value: "500"
            type: string
          - set: message.headers.content-type
            value: application/json
            type: string
          - set: message.body
            value: '{"errorCode": "E00500", "errorMessage": "Internal Server Error"}'
            type: string
    finally: []
  properties: {}
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  application-authentication:
    certificate: false
  catalogs: {}
  buffering: true
definitions:
  WPSUnifiedComplianceRateValueRq_MessageType:
    type: object
    properties:
      WPSUnifiedComplianceRateValueRq:
        $ref: '#/definitions/WPSUnifiedComplianceRateValueRq_MessageType'
  WPSUnifiedComplianceRateValueRs_MessageType:
    type: object
    properties:
      WPSUnifiedComplianceRateValueRs:
        $ref: '#/definitions/WPSUnifiedComplianceRateValueRs_MessageType'
  WPSUnifiedComplianceRateValueRq:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLRequestHeader_Type'
      Body:
        $ref: '#/definitions/WPSUnifiedComplianceRateValueRq_BodyType'
  WPSUnifiedComplianceRateValueRq_BodyType:
    type: object
    properties:
      LaborOfficeId:
        type: integer
        default: "12"
      SequenceNumber:
        type: integer
        default: "1232"
      Year:
        type: integer
        default: "2024"
    required:
    - LaborOfficeId
    - SequenceNumber
    - Year
  WPSUnifiedComplianceRateValueRs_Type:
    type: object
    properties:
      Header:
        $ref: '#/definitions/ESBXMLResponseHeader_Type'
      Body:
        $ref: '#/definitions/WPSUnifiedComplianceRateValueRs_BodyType'
  WPSUnifiedComplianceRateValueRs_BodyType:
    type: object
    properties:
      UnifiedComplianceRate:
        type: string
  ESBXMLRequestHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: VSCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
    required:
    - ServiceCode
    - ChannelId
    - TransactionId
    - RequestTime
  ESBXMLResponseHeader_Type:
    type: object
    properties:
      TransactionId:
        type: string
        default: "6222121543"
      ChannelId:
        type: string
        default: Qiwa
      SessionId:
        type: string
        default: "212"
      RequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWRequestTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      MWResponseTime:
        type: string
        default: "2019-10-10 00:00:00.555"
      ServiceCode:
        type: string
        default: VSCR0001
      DebugFlag:
        type: integer
        default: "1"
      UserInfo:
        $ref: '#/definitions/UserInfo_Type'
      UDF:
        $ref: '#/definitions/UDF_Type'
      ResponseStatus:
        $ref: '#/definitions/MWResponseStatus_Type'
      BackendError:
        $ref: '#/definitions/BackendError_Type'
    required:
    - TransactionId
    - ChannelId
    - RequestTime
    - ServiceCode
  UDF_Type:
    type: object
    properties:
      KeyValueArr:
        type: array
        items:
          $ref: '#/definitions/KeyValueArr_Type'
  KeyValueArr_Type:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Tmstmp_Type:
    type: object
  UserInfo_Type:
    type: object
    properties:
      UserId:
        type: integer
        default: "465740"
      IDNumber:
        type: integer
        default: "1024812248"
  MWResponseStatus_Type:
    type: object
    properties:
      Status:
        type: string
      Code:
        type: string
      ArabicMsg:
        type: string
      EnglishMsg:
        type: string
    required:
    - Code
    - Status
    - ArabicMsg
    - EnglishMsg
  BackendError_Type:
    type: object
    properties:
      ErrorCode:
        type: string
      ErrorDescription:
        type: string
paths:
  /wpsUnifiedComplianceRateValue:
    post:
      operationId: WPSUnifiedComplianceRateValue
      responses:
        "200":
          description: The operation was successful.
          schema:
            $ref: '#/definitions/WPSUnifiedComplianceRateValueRs_MessageType'
      consumes:
      - application/json
      produces:
      - application/json
      description: This API calculates the Unified Compliance Rate value from the
        data sent by GOSI_ComplianceRate API and send back to user.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/WPSUnifiedComplianceRateValueRq_MessageType'
        description: WPSUnifiedComplianceRateValueRq
        required: true
